import type { ContextElement,ContextSource,ExecutionContextPackage } from '@agentforge/context-assembly';

export type PromptSectionKind='instructions'|'execution'|'objective'|'workflow'|'knowledge'|'memory'|'operational'|'supporting';
export type PromptOrdering='instruction-first'|'objective-first'|'context-first'|'policy';
export interface PromptInstruction {readonly id:string;readonly hierarchy:'system'|'platform'|'execution'|'user';readonly content:string;readonly sourceReference:string;readonly sourceVersion:string;readonly securityLabels:readonly string[];readonly priority:number;}
export interface ConsumerProfile {readonly id:string;readonly version:string;readonly category:'conversational'|'reasoning'|'coding'|'evaluation'|'simulation'|'multimodal'|'generic';readonly supportedModalities:readonly ('text'|'image-reference'|'audio-reference'|'structured-data')[];readonly preferredSections:readonly PromptSectionKind[];readonly maximumLogicalUnits:number;readonly structuredOutput:Readonly<{required:boolean;schemaReference?:string}>;readonly formatting:'canonical-text'|'canonical-structured';}
export interface PromptPolicy {readonly version:string;readonly schemaVersion:string;readonly selectedSections:readonly PromptSectionKind[];readonly sectionOrder:readonly PromptSectionKind[];readonly ordering:PromptOrdering;readonly maximumLogicalUnits:number;readonly sectionBudgets:Partial<Readonly<Record<PromptSectionKind,number>>>;readonly minimumPriority:number;}
export interface PromptBuildRequest {readonly requestId:string;readonly context:ExecutionContextPackage;readonly instructions:readonly PromptInstruction[];readonly profile:ConsumerProfile;readonly policy:PromptPolicy;readonly correlation:Readonly<{executionId:string;correlationId:string}>;readonly platformVersion:string;}
export interface PromptProvenance {readonly contextPackageId:string;readonly source:ContextSource|'instruction';readonly sourceReference:string;readonly sourceVersion:string;readonly securityLabels:readonly string[];}
export interface PromptEntry {readonly id:string;readonly value:unknown;readonly canonicalValue:string;readonly priority:number;readonly logicalUnits:number;readonly provenance:PromptProvenance;}
export interface PromptSection {readonly kind:PromptSectionKind;readonly ordinal:number;readonly entries:readonly PromptEntry[];readonly logicalUnits:number;}
export interface PromptPackage {readonly id:string;readonly requestId:string;readonly status:'complete'|'partial'|'empty';readonly execution:Readonly<{executionId:string;correlationId:string;contextPackageId:string}>;readonly sections:readonly PromptSection[];readonly canonical:string;readonly omissions:readonly string[];readonly budget:Readonly<{maximum:number;used:number}>;readonly consumer:Readonly<{profileId:string;profileVersion:string;category:ConsumerProfile['category'];modalities:ConsumerProfile['supportedModalities'];structuredOutput:ConsumerProfile['structuredOutput'];formatting:ConsumerProfile['formatting']}>;readonly security:ExecutionContextPackage['security'];readonly versions:Readonly<{schema:string;policy:string;contextSchema:string;consumer:string;platform:string}>;readonly diagnosticId:string;}
export interface PromptPolicyResult {readonly entries:readonly InternalPromptEntry[];readonly omissions:readonly string[];readonly maximum:number;readonly used:number;}
export interface PromptPolicyEvaluator {evaluate(request:PromptBuildRequest,entries:readonly InternalPromptEntry[]):PromptPolicyResult;}
export interface CanonicalPromptFormatter {format(sections:readonly PromptSection[],profile:ConsumerProfile):string;}
export type PromptErrorCode='PROMPT_INVALID_REQUEST'|'PROMPT_POLICY_FAILURE'|'PROMPT_BUDGET_FAILURE'|'PROMPT_FORMATTING_FAILURE'|'PROMPT_SERIALIZATION_FAILURE'|'PROMPT_PIPELINE_FAILURE';
export class ExternalPromptError extends Error {public constructor(public readonly kind:'policy'|'budget'|'formatting'|'serialization'|'pipeline',message:string){super(message);this.name='ExternalPromptError';}}
export class PromptBuilderError extends Error {public constructor(public readonly code:PromptErrorCode,message:string,public readonly diagnosticId:string){super(message);this.name='PromptBuilderError';}}
export interface PromptDiagnostic {readonly id:string;readonly outcome:'completed'|'failed';readonly includedSections:readonly PromptSectionKind[];readonly omittedSections:readonly PromptSectionKind[];readonly counts:Readonly<{supplied:number;included:number;omitted:number}>;readonly budget:Readonly<{maximum:number;used:number}>;readonly ordering:PromptOrdering;readonly policyVersion:string;readonly profileId:string;readonly errorCode?:PromptErrorCode;}
export interface PromptDiagnostics {record(value:PromptDiagnostic):void;list():readonly PromptDiagnostic[];}
export interface PromptFact {readonly type:'prompt.build.started'|'prompt.build.completed'|'prompt.build.failed';readonly requestId:string;readonly executionId:string;readonly diagnosticId:string;readonly policyVersion:string;readonly profileVersion:string;}
export interface PromptEvents {publish(value:PromptFact):Promise<void>;}
export interface PromptTelemetry {completed(status:PromptPackage['status'],sections:number,used:number,profileId:string):void;failed(code:PromptErrorCode):void;}
export interface InternalPromptEntry {readonly id:string;readonly section:PromptSectionKind;readonly value:unknown;readonly priority:number;readonly logicalUnits:number;readonly provenance:PromptProvenance;readonly ordinal:number;}

export class DefaultPromptPolicyEvaluator implements PromptPolicyEvaluator {
  public evaluate(request:PromptBuildRequest,entries:readonly InternalPromptEntry[]):PromptPolicyResult{
    validatePolicy(request);
    const selected=new Set(request.policy.selectedSections.filter(section=>request.profile.preferredSections.includes(section)));
    const eligible=entries.filter(entry=>selected.has(entry.section)&&entry.priority>=request.policy.minimumPriority).sort((a,b)=>b.priority-a.priority||a.ordinal-b.ordinal||a.id.localeCompare(b.id));
    const maximum=Math.min(request.policy.maximumLogicalUnits,request.profile.maximumLogicalUnits);const bySection=new Map<PromptSectionKind,number>();const included:InternalPromptEntry[]=[];let used=0;
    for(const entry of eligible){const sectionUsed=bySection.get(entry.section)??0;const sectionMaximum=request.policy.sectionBudgets[entry.section]??Number.MAX_SAFE_INTEGER;if(used+entry.logicalUnits>maximum||sectionUsed+entry.logicalUnits>sectionMaximum)continue;included.push(entry);used+=entry.logicalUnits;bySection.set(entry.section,sectionUsed+entry.logicalUnits);}
    const includedIds=new Set(included.map(entry=>`${entry.section}:${entry.id}`));const omissions=entries.filter(entry=>!includedIds.has(`${entry.section}:${entry.id}`)).map(entry=>`omitted:${entry.section}:${entry.id}`);
    return freeze({entries:orderEntries(included,request),omissions:unique(omissions),maximum,used});
  }
}

export class StableCanonicalPromptFormatter implements CanonicalPromptFormatter {
  public format(sections:readonly PromptSection[],profile:ConsumerProfile):string{try{const body=sections.map(section=>`[${section.kind}]\n${section.entries.map(entry=>entry.canonicalValue).join('\n')}`).join('\n\n');return profile.formatting==='canonical-structured'?stableStringify({sections:sections.map(section=>({kind:section.kind,values:section.entries.map(entry=>entry.value)}))}):body;}catch(error){throw new ExternalPromptError('formatting',error instanceof Error?error.message:'Canonical formatting failed');}}
}

export class PromptBuilder {
  public constructor(private readonly policies:PromptPolicyEvaluator,private readonly formatter:CanonicalPromptFormatter,private readonly diagnostics:PromptDiagnostics,private readonly events:PromptEvents,private readonly telemetry:PromptTelemetry){}
  public async build(request:PromptBuildRequest):Promise<PromptPackage>{const diagnosticId=`prompt:build:${request.requestId}`;try{validateRequest(request,diagnosticId);await this.events.publish(fact('prompt.build.started',request,diagnosticId));const collected=collect(request);const evaluated=this.policies.evaluate(request,collected);const sections=makeSections(evaluated.entries,request);const canonical=this.formatter.format(sections,request.profile);const status=sections.length===0?'empty':evaluated.omissions.length>0||request.context.status==='partial'?'partial':'complete';const result:PromptPackage=freeze({id:`prompt:${request.correlation.executionId}:${request.requestId}`,requestId:request.requestId,status,execution:{...request.correlation,contextPackageId:request.context.id},sections,canonical,omissions:[...evaluated.omissions,...request.context.omissions.map(value=>`context:${value}`)],budget:{maximum:evaluated.maximum,used:evaluated.used},consumer:{profileId:request.profile.id,profileVersion:request.profile.version,category:request.profile.category,modalities:[...request.profile.supportedModalities],structuredOutput:{...request.profile.structuredOutput},formatting:request.profile.formatting},security:clone(request.context.security),versions:{schema:request.policy.schemaVersion,policy:request.policy.version,contextSchema:request.context.versions.schema,consumer:request.profile.version,platform:request.platformVersion},diagnosticId});const includedSections=sections.map(section=>section.kind);const omittedSections=request.policy.selectedSections.filter(section=>!includedSections.includes(section));this.diagnostics.record(freeze({id:diagnosticId,outcome:'completed',includedSections,omittedSections,counts:{supplied:collected.length,included:evaluated.entries.length,omitted:collected.length-evaluated.entries.length},budget:{maximum:evaluated.maximum,used:evaluated.used},ordering:request.policy.ordering,policyVersion:request.policy.version,profileId:request.profile.id}));await this.events.publish(fact('prompt.build.completed',request,diagnosticId));this.telemetry.completed(status,sections.length,evaluated.used,request.profile.id);return result;}catch(error){const normalized=normalize(error,diagnosticId);this.diagnostics.record(freeze({id:diagnosticId,outcome:'failed',includedSections:[],omittedSections:[],counts:{supplied:0,included:0,omitted:0},budget:{maximum:Math.max(0,Math.min(request.policy.maximumLogicalUnits,request.profile.maximumLogicalUnits)),used:0},ordering:request.policy.ordering,policyVersion:request.policy.version,profileId:request.profile.id,errorCode:normalized.code}));this.telemetry.failed(normalized.code);await this.events.publish(fact('prompt.build.failed',request,diagnosticId));throw normalized;}}
}

function collect(request:PromptBuildRequest):readonly InternalPromptEntry[]{let ordinal=0;const instructions=request.instructions.map(instruction=>freeze({id:instruction.id,section:'instructions' as const,value:instruction.content,priority:instruction.priority,logicalUnits:1,provenance:{contextPackageId:request.context.id,source:'instruction' as const,sourceReference:instruction.sourceReference,sourceVersion:instruction.sourceVersion,securityLabels:[...instruction.securityLabels]},ordinal:ordinal++}));const context=request.context.elements.map(element=>fromContext(element,request.context.id,ordinal++));return Object.freeze([...instructions,...context]);}
function fromContext(element:ContextElement,contextPackageId:string,ordinal:number):InternalPromptEntry{return freeze({id:element.id,section:sectionFor(element.source),value:clone(element.content),priority:element.priority,logicalUnits:element.logicalUnits,provenance:{contextPackageId,source:element.source,sourceReference:element.sourceReference,sourceVersion:element.sourceVersion,securityLabels:[...element.securityLabels]},ordinal});}
function sectionFor(source:ContextSource):PromptSectionKind{return({execution:'execution',plan:'objective',workflow:'workflow',knowledge:'knowledge',memory:'memory',runtime:'operational'} as const)[source];}
function makeSections(entries:readonly InternalPromptEntry[],request:PromptBuildRequest):readonly PromptSection[]{const grouped=new Map<PromptSectionKind,InternalPromptEntry[]>();for(const entry of entries){const values=grouped.get(entry.section)??[];values.push(entry);grouped.set(entry.section,values);}const order=sectionOrder(request);return Object.freeze(order.filter(kind=>grouped.has(kind)).map((kind,ordinal)=>{const values=grouped.get(kind)??[];const promptEntries=values.map(value=>freeze({id:value.id,value:clone(value.value),canonicalValue:stableStringify(value.value),priority:value.priority,logicalUnits:value.logicalUnits,provenance:clone(value.provenance)}));return freeze({kind,ordinal,entries:promptEntries,logicalUnits:promptEntries.reduce((sum,item)=>sum+item.logicalUnits,0)});}));}
function orderEntries(entries:readonly InternalPromptEntry[],request:PromptBuildRequest):readonly InternalPromptEntry[]{const positions=new Map(sectionOrder(request).map((section,index)=>[section,index]));return Object.freeze([...entries].sort((a,b)=>(positions.get(a.section)??99)-(positions.get(b.section)??99)||b.priority-a.priority||a.ordinal-b.ordinal));}
function sectionOrder(request:PromptBuildRequest):readonly PromptSectionKind[]{const selected=request.policy.sectionOrder;const preferred=request.profile.preferredSections;const base:readonly PromptSectionKind[]=request.policy.ordering==='policy'?selected:request.policy.ordering==='instruction-first'?['instructions',...selected.filter(value=>value!=='instructions')]:request.policy.ordering==='objective-first'?['objective','instructions',...selected.filter(value=>value!=='objective'&&value!=='instructions')]:['knowledge','memory','workflow','objective','execution','operational','instructions','supporting'];return unique([...base,...preferred]);}
function validateRequest(request:PromptBuildRequest,id:string):void{if(request.requestId.trim()===''||request.correlation.executionId!==request.context.execution.executionId||request.correlation.correlationId!==request.context.execution.correlationId||request.platformVersion.trim()===''||request.profile.id.trim()===''||request.profile.version.trim()==='')throw new PromptBuilderError('PROMPT_INVALID_REQUEST','Invalid prompt build request',id);if(request.instructions.some(instruction=>!instruction.securityLabels.every(label=>request.context.security.labels.includes(label))))throw new PromptBuilderError('PROMPT_INVALID_REQUEST','Instruction security scope rejected',id);try{JSON.stringify(request);}catch{throw new PromptBuilderError('PROMPT_SERIALIZATION_FAILURE','Prompt request is not serializable',id);}}
function validatePolicy(request:PromptBuildRequest):void{if(request.policy.version.trim()===''||request.policy.schemaVersion.trim()===''||request.policy.maximumLogicalUnits<0||request.profile.maximumLogicalUnits<0||request.policy.minimumPriority<0)throw new ExternalPromptError('policy','Prompt policy or profile is invalid');}
function fact(type:PromptFact['type'],request:PromptBuildRequest,diagnosticId:string):PromptFact{return freeze({type,requestId:request.requestId,executionId:request.correlation.executionId,diagnosticId,policyVersion:request.policy.version,profileVersion:request.profile.version});}
function normalize(error:unknown,id:string):PromptBuilderError{if(error instanceof PromptBuilderError)return error;const kind=error instanceof ExternalPromptError?error.kind:'pipeline';const code=({policy:'PROMPT_POLICY_FAILURE',budget:'PROMPT_BUDGET_FAILURE',formatting:'PROMPT_FORMATTING_FAILURE',serialization:'PROMPT_SERIALIZATION_FAILURE',pipeline:'PROMPT_PIPELINE_FAILURE'} as const)[kind];return new PromptBuilderError(code,error instanceof Error?error.message:'Prompt build failed',id);}
function stableStringify(value:unknown):string{return JSON.stringify(sortValue(value));}
function sortValue(value:unknown):unknown{if(Array.isArray(value))return value.map(sortValue);if(typeof value==='object'&&value!==null)return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,sortValue(item)]));return value;}
function unique<T>(values:readonly T[]):readonly T[]{return Object.freeze([...new Set(values)]);}
function clone<T>(value:T):T{return JSON.parse(JSON.stringify(value)) as T;}
function freeze<T>(value:T):T{if(typeof value==='object'&&value!==null&&!Object.isFrozen(value)){for(const child of Object.values(value))freeze(child);Object.freeze(value);}return value;}

export * from './reference.js';
