/* eslint-disable @typescript-eslint/explicit-function-return-type */
import type { ExecutionContextPackage } from '@agentforge/context-assembly';
import { describe,expect,it,vi } from 'vitest';
import { DefaultPromptPolicyEvaluator,ExternalPromptError,InMemoryPromptDiagnostics,InMemoryPromptEvents,PromptBuilder,StableCanonicalPromptFormatter,type CanonicalPromptFormatter,type ConsumerProfile,type PromptBuildRequest,type PromptPolicy,type PromptPolicyEvaluator,type PromptTelemetry } from './index.js';

const contextPackage:ExecutionContextPackage={id:'context:execution-1:assembly-1',requestId:'assembly-1',status:'complete',execution:{executionId:'execution-1',correlationId:'correlation-1',tenantId:'tenant-1',workspaceId:'workspace-1',node:{workflowId:'workflow-1',nodeId:'task-1',kind:'capability',capability:'answer'}},elements:[
  {id:'execution-1',source:'execution',sourceReference:'execution:execution-1',sourceVersion:'configuration-1',content:{executionId:'execution-1'},metadata:{},securityLabels:[],priority:100,logicalUnits:1,ordinal:0},
  {id:'plan-1',source:'plan',sourceReference:'plan:plan-1',sourceVersion:'planner-1',content:{objective:'answer',constraints:['accurate']},metadata:{},securityLabels:[],priority:90,logicalUnits:1,ordinal:1},
  {id:'workflow-1',source:'workflow',sourceReference:'workflow:workflow-1',sourceVersion:'3',content:{status:'running'},metadata:{},securityLabels:[],priority:80,logicalUnits:1,ordinal:2},
  {id:'chunk-1',source:'knowledge',sourceReference:'source://one',sourceVersion:'index-1',content:'exact knowledge',metadata:{},securityLabels:['public'],priority:70,logicalUnits:1,ordinal:3},
  {id:'memory-1',source:'memory',sourceReference:'memory:memory-1',sourceVersion:'memory-1',content:{observation:'exact memory'},metadata:{},securityLabels:['public'],priority:60,logicalUnits:1,ordinal:4},
  {id:'runtime-1',source:'runtime',sourceReference:'runtime:diagnostic',sourceVersion:'runtime-1',content:{state:'running'},metadata:{},securityLabels:[],priority:50,logicalUnits:1,ordinal:5}
],sources:[],omissions:[],security:{decisionId:'decision-1',labels:['public']},budget:{maximum:10,used:6},versions:{schema:'context-1',policy:'context-policy-1',configuration:'configuration-1',platform:'0.1.0',plan:'planner-1',workflow:'3',knowledge:['index-1'],memory:['memory-1'],runtime:'runtime-1'},diagnosticId:'context-diagnostic'};
const profile:ConsumerProfile={id:'generic-text',version:'profile-1',category:'generic',supportedModalities:['text','structured-data'],preferredSections:['instructions','objective','execution','workflow','knowledge','memory','operational'],maximumLogicalUnits:10,structuredOutput:{required:false},formatting:'canonical-text'};
const policy:PromptPolicy={version:'prompt-policy-1',schemaVersion:'prompt-package-1',selectedSections:['instructions','execution','objective','workflow','knowledge','memory','operational'],sectionOrder:['instructions','objective','execution','workflow','knowledge','memory','operational'],ordering:'instruction-first',maximumLogicalUnits:10,sectionBudgets:{},minimumPriority:0};
const request=(overrides:Partial<PromptBuildRequest>={}):PromptBuildRequest=>({requestId:'build-1',context:contextPackage,instructions:[{id:'instruction-1',hierarchy:'system',content:'Preserve facts exactly.',sourceReference:'policy://system',sourceVersion:'instruction-1',securityLabels:['public'],priority:110}],profile,policy,correlation:{executionId:'execution-1',correlationId:'correlation-1'},platformVersion:'0.1.0',...overrides});
function fixture(evaluator:PromptPolicyEvaluator=new DefaultPromptPolicyEvaluator(),formatter:CanonicalPromptFormatter=new StableCanonicalPromptFormatter()){const diagnostics=new InMemoryPromptDiagnostics();const events=new InMemoryPromptEvents();const completed=vi.fn();const failed=vi.fn();const telemetry:PromptTelemetry={completed,failed};return{builder:new PromptBuilder(evaluator,formatter,diagnostics,events,telemetry),diagnostics,events,completed,failed};}

describe('Prompt Builder',()=>{
  it('deterministically composes a provider-independent Prompt Package from Context',async()=>{const first=await fixture().builder.build(request());const second=await fixture().builder.build(request());expect(first).toEqual(second);expect(first.sections.map(section=>section.kind)).toEqual(['instructions','objective','execution','workflow','knowledge','memory','operational']);expect(first).not.toHaveProperty('model');expect(first).not.toHaveProperty('messages');expect(first).not.toHaveProperty('provider');});
  it('preserves semantic values, provenance, security, and source immutability',async()=>{const input=request();const before=JSON.stringify(input);const result=await fixture().builder.build(input);const objective=result.sections.find(section=>section.kind==='objective')?.entries[0];expect(objective?.value).toEqual({objective:'answer',constraints:['accurate']});expect(objective?.provenance).toMatchObject({contextPackageId:contextPackage.id,source:'plan',sourceReference:'plan:plan-1'});expect(result.security).toEqual(contextPackage.security);expect(JSON.stringify(input)).toBe(before);});
  it('applies configurable section selection and deterministic policy ordering',async()=>{const selected={...policy,version:'prompt-policy-2',selectedSections:['instructions','knowledge'] as const,sectionOrder:['knowledge','instructions'] as const,ordering:'policy' as const};const result=await fixture().builder.build(request({policy:selected,profile:{...profile,preferredSections:['instructions','knowledge']}}));expect(result.sections.map(section=>section.kind)).toEqual(['knowledge','instructions']);expect(result.versions.policy).toBe('prompt-policy-2');expect(result.status).toBe('partial');});
  it('enforces whole-entry total and section budgets without semantic truncation',async()=>{const constrained={...policy,maximumLogicalUnits:3,sectionBudgets:{instructions:0}};const result=await fixture().builder.build(request({policy:constrained}));expect(result.budget).toEqual({maximum:3,used:3});expect(result.sections.flatMap(section=>section.entries).map(entry=>entry.id)).toEqual(['plan-1','execution-1','workflow-1']);expect(result.omissions).toContain('omitted:instructions:instruction-1');expect(result.status).toBe('partial');});
  it('applies provider-neutral consumer profiles and canonical structured formatting',async()=>{const structured={...profile,id:'evaluation-structured',version:'profile-2',category:'evaluation' as const,preferredSections:['objective','knowledge'] as const,maximumLogicalUnits:2,structuredOutput:{required:true,schemaReference:'schema://answer'},formatting:'canonical-structured' as const};const result=await fixture().builder.build(request({profile:structured}));expect(JSON.parse(result.canonical)).toEqual({sections:[{kind:'objective',values:[{constraints:['accurate'],objective:'answer'}]},{kind:'knowledge',values:['exact knowledge']}]});expect(result.consumer).toMatchObject({profileId:'evaluation-structured',profileVersion:'profile-2',structuredOutput:{required:true}});});
  it('returns a deeply immutable, serializable empty package for a zero budget',async()=>{const result=await fixture().builder.build(request({policy:{...policy,maximumLogicalUnits:0}}));expect(result).toMatchObject({status:'empty',sections:[],budget:{maximum:0,used:0}});expect(Object.isFrozen(result)).toBe(true);expect(Object.isFrozen(result.sections)).toBe(true);expect(()=>JSON.stringify(result)).not.toThrow();});
  it('publishes lifecycle facts and safe diagnostics and telemetry',async()=>{const f=fixture();const result=await f.builder.build(request());expect(f.events.facts.map(item=>item.type)).toEqual(['prompt.build.started','prompt.build.completed']);expect(f.diagnostics.list()[0]).toMatchObject({outcome:'completed',counts:{supplied:7,included:7,omitted:0},policyVersion:'prompt-policy-1',profileId:'generic-text'});expect(f.completed).toHaveBeenCalledWith(result.status,7,7,'generic-text');expect(JSON.stringify(f.diagnostics.list())).not.toMatch(/exact knowledge|exact memory/iu);});
  it('normalizes replaceable policy failures',async()=>{const evaluator:PromptPolicyEvaluator={evaluate:()=>{throw new ExternalPromptError('policy','adapter detail');}};const f=fixture(evaluator);await expect(f.builder.build(request())).rejects.toMatchObject({code:'PROMPT_POLICY_FAILURE',diagnosticId:'prompt:build:build-1'});expect(f.failed).toHaveBeenCalledWith('PROMPT_POLICY_FAILURE');expect(f.events.facts.at(-1)?.type).toBe('prompt.build.failed');});
  it('normalizes formatter failures without producing a provider request',async()=>{const formatter:CanonicalPromptFormatter={format:()=>{throw new ExternalPromptError('formatting','formatter failed');}};await expect(fixture(new DefaultPromptPolicyEvaluator(),formatter).builder.build(request())).rejects.toMatchObject({code:'PROMPT_FORMATTING_FAILURE'});});
  it('rejects invalid correlation and instruction security scope',async()=>{await expect(fixture().builder.build(request({correlation:{executionId:'other',correlationId:'correlation-1'}}))).rejects.toMatchObject({code:'PROMPT_INVALID_REQUEST'});const instruction=request().instructions[0];if(instruction===undefined)throw new Error('Instruction fixture is missing');await expect(fixture().builder.build(request({instructions:[{...instruction,securityLabels:['secret']}]}))).rejects.toMatchObject({code:'PROMPT_INVALID_REQUEST'});});
});
