/* eslint-disable @typescript-eslint/explicit-function-return-type, @typescript-eslint/no-unsafe-assignment, require-yield */
import type { CapabilityBinding } from '@agentprodready/capability-resolution';
import type { ExecutionContext } from '@agentprodready/foundation';
import { describe,expect,it,vi } from 'vitest';
import { AiProviderFramework,FactoryAiAdapterResolver,InMemoryAiDiagnostics,InMemoryAiEvents,NormalizedAiError,ProviderAdapterError,ReferenceAiProviderAdapter,type AiExecutionRequest,type AiProviderAdapter } from '../index.js';

const binding:CapabilityBinding=Object.freeze({bindingId:'b',requestId:'resolution',capability:'chat',capabilityContractVersion:'1',implementationId:'reference',implementationVersion:'1',provider:Object.freeze({id:'p',pluginId:'plugin',contributionId:'c'}),source:'default',diagnosticId:'resolution:r'});
const context:ExecutionContext=Object.freeze({executionId:'e',correlationId:'c',startedAt:'x',configurationVersion:'v',securityContextId:'s',attributes:Object.freeze({})});
const request:AiExecutionRequest=Object.freeze({requestId:'r',binding,context,messages:Object.freeze([{role:'user' as const,content:Object.freeze([{type:'text' as const,text:'hello'}])}]),generation:Object.freeze({maximumOutputTokens:10}),structuredOutput:Object.freeze({name:'answer',schema:Object.freeze({type:'object'}),strict:true}),tools:Object.freeze([{name:'lookup',description:'Lookup',inputSchema:Object.freeze({type:'object'})}]),streaming:Object.freeze({enabled:true,includeUsage:true}),metadata:Object.freeze({trace:'t'}),constraints:Object.freeze({locality:'us'})});
function fixture(adapter:AiProviderAdapter=new ReferenceAiProviderAdapter()){const resolver=new FactoryAiAdapterResolver();const factory=vi.fn(async()=>adapter);resolver.bind('reference',factory);const diagnostics=new InMemoryAiDiagnostics();const events=new InMemoryAiEvents();const telemetry={completed:vi.fn(),failed:vi.fn(),streamed:vi.fn()};return{framework:new AiProviderFramework(resolver,diagnostics,events,telemetry),factory,diagnostics,events,telemetry};}

describe('AiProviderFramework',()=>{
 it('runs the complete selected binding to normalized immutable result pipeline',async()=>{const f=fixture();const result=await f.framework.execute(request);expect(result.content).toEqual([{type:'text',text:'hello'}]);expect(result.structuredOutput).toEqual({echo:'hello'});expect(result.toolCalls).toEqual([]);expect(result.finishReason).toBe('completed');expect(Object.isFrozen(result)).toBe(true);expect(f.factory).toHaveBeenCalledOnce();expect(f.events.facts[0]?.type).toBe('ai.completed');expect(f.telemetry.completed).toHaveBeenCalledOnce();});
 it('normalizes streaming content, usage, and completion',async()=>{const f=fixture();const events=[];for await(const event of f.framework.stream(request))events.push(event);expect(events.map(item=>item.type)).toEqual(['content','usage','completed']);expect(events.map(item=>item.sequence)).toEqual([0,1,2]);expect(f.telemetry.streamed).toHaveBeenCalledWith('reference-ai',3);});
 it('supports replaceable coexisting provider adapters without consumer changes',async()=>{const second:AiProviderAdapter={id:'second',execute:async value=>({...await new ReferenceAiProviderAdapter().execute(value),content:[{type:'text',text:'second'}]}),stream:value=>new ReferenceAiProviderAdapter().stream(value),health:async()=>({name:'second',status:'healthy'})};const result=await fixture(second).framework.execute(request);expect(result.content).toEqual([{type:'text',text:'second'}]);});
 it.each([['authentication','AI_AUTHENTICATION'],['rate-limit','AI_RATE_LIMITED'],['context-limit','AI_CONTEXT_LIMIT'],['invalid-request','AI_INVALID_REQUEST'],['unavailable','AI_UNAVAILABLE'],['timeout','AI_PROVIDER_TIMEOUT']] as const)('normalizes %s failures without leaking provider errors',async(kind,code)=>{const adapter:AiProviderAdapter={id:'failure',execute:async()=>{throw new ProviderAdapterError(kind,'normalized message',kind==='rate-limit'||kind==='unavailable');},stream:async function*(){throw new ProviderAdapterError(kind,'normalized message',false);},health:async()=>({name:'failure',status:'unhealthy'})};const f=fixture(adapter);await expect(f.framework.execute(request)).rejects.toMatchObject({code,retryable:expect.any(Boolean)});expect(f.diagnostics.get('ai:r')).toMatchObject({outcome:'failed',errorCode:code});expect(f.telemetry.failed).toHaveBeenCalledOnce();});
 it('rejects provider-specific request fields and malformed normalized results',async()=>{await expect(fixture().framework.execute({...request,constraints:{deploymentName:'secret'}})).rejects.toBeInstanceOf(NormalizedAiError);const bad:AiProviderAdapter={id:'bad',execute:async()=>({...await new ReferenceAiProviderAdapter().execute(request),requestId:'wrong'}),stream:value=>new ReferenceAiProviderAdapter().stream(value),health:async()=>({name:'bad',status:'healthy'})};await expect(fixture(bad).framework.execute(request)).rejects.toMatchObject({code:'AI_INVALID_REQUEST'});});
 it('reports normalized provider health without exposing an SDK',async()=>{expect(await fixture().framework.health(binding)).toEqual({name:'reference-ai',status:'healthy'});expect(JSON.stringify(await fixture().framework.execute(request))).not.toMatch(/apiKey|deploymentName|sdkResponse/iu);});
});


