import {describe,expect,it} from 'vitest';
import type {AuthorizationDecision} from '@agentforge/security';
import {AllApproversPolicy,buildHumanInteractionRequest,DeterministicResponseValidator,FirstValidResponsePolicy,HumanInteractionError,HumanInteractionFramework,InMemoryHumanInteractionAudit,InMemoryHumanInteractionDiagnostics,InMemoryHumanInteractionEvents,InMemoryInteractionStore,RecordingRuntimeInteractionPort,RecordingWorkflowInteractionPort,redactedView,ReferenceDeliveryAdapter,StaticParticipantResolver,type HumanInteractionRequest,type HumanResponse,type ResolvedParticipant} from './index.js';

const created='2026-08-06T00:00:00.000Z',expires='2026-08-07T00:00:00.000Z',scope={tenantId:'tenant-1',workspaceId:'workspace-1',classification:'restricted' as const};
function authorization(principalId:string,action:'read'|'approve'='approve',tenantId='tenant-1'):AuthorizationDecision{return{id:`decision:${principalId}:${action}`,requestId:`request:${principalId}`,outcome:'permit',authorized:true,principalId,effectivePrincipalId:principalId,action,resource:{id:'interaction-1',type:'workflow',version:'1'},effectiveScope:{tenantId,workspaceId:'workspace-1'},appliedPolicies:['human-policy'],conditions:[],restrictions:[],obligations:[],reason:'permit',policyVersions:['1'],evidenceReferences:[],issuedAt:created,expiresAt:expires,correlation:{executionId:'execution-1',correlationId:'correlation-1'},schemaVersion:'1',cacheKey:'key'};}
function participant(id:string):ResolvedParticipant{return{principalId:id,tenantId:'tenant-1',roles:['approver'],authorizationDecision:authorization(id),authorityState:'active'};}
function request(overrides:Partial<HumanInteractionRequest>={}):HumanInteractionRequest{return{id:'interaction-1',version:'1',type:'approval',purpose:'Approve governed operation',participantRequirement:{type:'role',values:['approver'],minimumParticipants:1,delegationAllowed:false,requesterMayRespond:false},executionReference:'execution-1',workflowReference:'workflow-1',agentReference:'agent:1',collaborationReference:'collaboration:1',subjectArtifactReferences:['artifact:1'],responseContract:{types:['approve','reject','conditional-approval'],requiredFields:[],optionIds:[],schemaReference:'schema:approval:1',commentsAllowed:true,evidenceRequired:false},scope,interactionPolicy:{version:'1',responsePolicy:'first-valid',conflictingResponse:'escalate',requiredApprovals:1},expirationPolicy:{version:'1',expiresAt:expires,outcome:'escalate'},escalationPolicy:{version:'1',enabled:true,reasonCodes:['timeout','conflict']},correlationId:'correlation-1',causationId:null,requestedBy:'requester',createdAt:created,provenance:{sourceReference:'workflow:node:1',builderVersion:'1'},...overrides};}
function response(id='response-1',principalId='approver-1',type:HumanResponse['type']='approve'):HumanResponse{return{id,interactionId:'interaction-1',principalId,type,structuredInput:type==='conditional-approval'?{conditions:['restricted-use']}:{},evidenceReferences:[],respondedAt:'2026-08-06T01:00:00.000Z',authorizationDecisionId:`decision:${principalId}:approve`,correlationId:'correlation-1',causationId:'interaction-1'};}
function fixture(participants:readonly ResolvedParticipant[]=[participant('approver-1')],delivery=new ReferenceDeliveryAdapter()):Readonly<{framework:HumanInteractionFramework;store:InMemoryInteractionStore;events:InMemoryHumanInteractionEvents;audit:InMemoryHumanInteractionAudit;diagnostics:InMemoryHumanInteractionDiagnostics;runtime:RecordingRuntimeInteractionPort;workflow:RecordingWorkflowInteractionPort;delivery:ReferenceDeliveryAdapter}>{const store=new InMemoryInteractionStore(),events=new InMemoryHumanInteractionEvents(),audit=new InMemoryHumanInteractionAudit(),diagnostics=new InMemoryHumanInteractionDiagnostics(),runtime=new RecordingRuntimeInteractionPort(),workflow=new RecordingWorkflowInteractionPort();return{framework:new HumanInteractionFramework(new StaticParticipantResolver(participants),delivery,store,new DeterministicResponseValidator(),events,audit,diagnostics,runtime,workflow),store,events,audit,diagnostics,runtime,workflow,delivery};}

describe('request, resolution, delivery, and immutable boundaries',()=>{
 it('builds deeply immutable normalized requests without execution state or secrets',()=>{const value=buildHumanInteractionRequest(request());expect(Object.isFrozen(value)).toBe(true);expect(Object.isFrozen(value.responseContract)).toBe(true);expect(JSON.stringify(value)).not.toMatch(/retryState|currentWorkflowNode|secretValue/);});
 it('rejects invalid requests and raw secret-like fields',()=>{expect(()=>buildHumanInteractionRequest(request({purpose:''}))).toThrowError(HumanInteractionError);expect(()=>buildHumanInteractionRequest({...request(),provenance:{sourceReference:'apiKey:value',builderVersion:'1'}})).toThrowError(/secret/i);});
 it('resolves only authorized tenant-scoped participants',async()=>{const value=fixture([participant('approver-1'),{...participant('other'),tenantId:'other'}]);const record=await value.framework.issue(request(),created);expect(record.deliveries.map(item=>item.participantId)).toEqual(['approver-1']);});
 it('keeps delivery replaceable and retry identity distinct from interaction identity',async()=>{const value=fixture();await value.framework.issue(request(),created);const retry=await value.framework.retryDelivery('interaction-1',participant('approver-1'),'2026-08-06T00:05:00.000Z');expect(retry.id).not.toBe(value.delivery.values[0]?.id);expect(retry.interactionId).toBe('interaction-1');expect(retry.attempt).toBe(2);});
 it('records delivery failure without converting it to approval',async()=>{const value=fixture([participant('approver-1')],new ReferenceDeliveryAdapter(new Set(['approver-1'])));const record=await value.framework.issue(request(),created);expect(record.state).toBe('delivery-failed');expect(record.result).toBeUndefined();});
 it('produces authorized redacted views without exposing artifact references',()=>{const view=redactedView(request(),participant('approver-1'));expect(view).toMatchObject({redacted:true,artifactReferences:['redacted']});});
});

describe('response validation and explicit approval semantics',()=>{
 it('rejects unauthorized, cross-tenant, and revoked responders',async()=>{const value=fixture();await value.framework.issue(request(),created);await expect(value.framework.respond('interaction-1',response(),{...participant('approver-1'),authorityState:'revoked'},new FirstValidResponsePolicy(),'2026-08-06T01:00:00.000Z')).rejects.toThrowError(/RESPONSE UNAUTHORIZED/);});
 it('enforces separation of duties and forbidden delegation',async()=>{const requesterRequest=request({requestedBy:'approver-1'}),value=fixture();await value.framework.issue(requesterRequest,created);await expect(value.framework.respond('interaction-1',response(),participant('approver-1'),new FirstValidResponsePolicy(),'2026-08-06T01:00:00.000Z')).rejects.toMatchObject({code:'SEPARATION_OF_DUTIES_VIOLATION'});});
 it('represents approval, rejection, and conditional approval explicitly',()=>{const policy=new FirstValidResponsePolicy();expect(policy.decide(request(),[response()],[]).approval).toMatchObject({outcome:'approved',explicit:true});expect(policy.decide(request(),[response('r','approver-1','reject')],[]).status).toBe('rejected');expect(policy.decide(request(),[response('r','approver-1','conditional-approval')],[]).approval).toMatchObject({outcome:'approved-with-conditions',conditions:['restricted-use']});});
 it('never treats silence or defer as approval',()=>{const policy=new FirstValidResponsePolicy();expect(policy.decide(request(),[],[])).toMatchObject({complete:false,status:'inconclusive'});expect(policy.decide(request(),[response('r','approver-1','defer')],[]).approval).toMatchObject({outcome:'deferred'});});
 it('deduplicates identical response IDs deterministically',async()=>{const value=fixture([participant('approver-1'),participant('approver-2')]),pending=request({participantRequirement:{type:'role',values:['approver'],minimumParticipants:2,delegationAllowed:false,requesterMayRespond:false},interactionPolicy:{version:'1',responsePolicy:'all-approvers',conflictingResponse:'escalate',requiredApprovals:2}});await value.framework.issue(pending,created);expect(await value.framework.respond('interaction-1',response(),participant('approver-1'),new AllApproversPolicy(),'2026-08-06T01:00:00.000Z')).toBeUndefined();expect(await value.framework.respond('interaction-1',response(),participant('approver-1'),new AllApproversPolicy(),'2026-08-06T01:01:00.000Z')).toBeUndefined();expect(value.store.get('interaction-1')?.responses).toHaveLength(1);});
 it('handles conflicting responders with explicit escalation',()=>{const policy=new AllApproversPolicy(),people=[participant('approver-1'),participant('approver-2')];expect(policy.decide(request({interactionPolicy:{version:'1',responsePolicy:'all-approvers',conflictingResponse:'escalate',requiredApprovals:2}}),[response(),response('r2','approver-2','reject')],people)).toMatchObject({complete:true,status:'escalated',conflict:true});});
 it('rejects responses after expiration',async()=>{const value=fixture();await value.framework.issue(request(),created);await expect(value.framework.respond('interaction-1',response(),participant('approver-1'),new FirstValidResponsePolicy(),expires)).rejects.toMatchObject({code:'INTERACTION_EXPIRED'});});
});

describe('lifecycle, integration, and accountability',()=>{
 it('keeps Runtime waiting/resumption and Workflow continuation in their owning ports',async()=>{const value=fixture();await value.framework.issue(request(),created);const result=await value.framework.respond('interaction-1',response(),participant('approver-1'),new FirstValidResponsePolicy(),'2026-08-06T01:00:00.000Z');expect(value.runtime.awaitingIds).toEqual(['interaction-1']);expect(value.runtime.completedIds).toEqual(['interaction-1']);expect(value.workflow.resultIds).toEqual([result?.id]);expect(result).not.toHaveProperty('workflowContinuation');});
 it('makes expiration and escalation explicit without implicit approval',async()=>{const value=fixture();await value.framework.issue(request(),created);const result=await value.framework.expire('interaction-1',expires);expect(result).toMatchObject({completionStatus:'escalated',expirationStatus:'expired',escalationStatus:'required'});expect(result.approvalDecision).toBeUndefined();});
 it('supports explicit cancellation and rejects later responses',async()=>{const value=fixture();await value.framework.issue(request(),created);const cancelled=await value.framework.cancel('interaction-1','decision:cancel','2026-08-06T02:00:00.000Z');expect(cancelled.completionStatus).toBe('cancelled');await expect(value.framework.respond('interaction-1',response(),participant('approver-1'),new FirstValidResponsePolicy(),'2026-08-06T03:00:00.000Z')).rejects.toMatchObject({code:'INTERACTION_ALREADY_COMPLETED'});});
 it('marks human input descriptive and unverified by default',async()=>{const value=fixture();await value.framework.issue(request(),created);const result=await value.framework.respond('interaction-1',response(),participant('approver-1'),new FirstValidResponsePolicy(),'2026-08-06T01:00:00.000Z');expect(result).toMatchObject({descriptive:true,humanInputVerified:false});});
 it('carries human evaluation references without owning scoring or aggregation',async()=>{const value=fixture(),evaluationRequest=request({type:'evaluation',responseContract:{types:['evaluation'],requiredFields:['evaluationResultReference'],optionIds:[],schemaReference:'evaluation:human:1',commentsAllowed:true,evidenceRequired:false}});await value.framework.issue(evaluationRequest,created);const evaluationResponse={...response('evaluation-response','approver-1','evaluation'),structuredInput:{evaluationResultReference:'evaluation-result:1'}};const result=await value.framework.respond('interaction-1',evaluationResponse,participant('approver-1'),new FirstValidResponsePolicy(),'2026-08-06T01:00:00.000Z');expect(result).toMatchObject({completionStatus:'information-provided',humanInputVerified:false});expect(result).not.toHaveProperty('score');});
 it('publishes correlated events, diagnostics, and accountable audit facts',async()=>{const value=fixture();await value.framework.issue(request(),created);await value.framework.respond('interaction-1',response(),participant('approver-1'),new FirstValidResponsePolicy(),'2026-08-06T01:00:00.000Z');expect(value.events.values.some(item=>item.type==='approval.granted')).toBe(true);expect(value.audit.values).toHaveLength(1);expect(value.diagnostics.list()).not.toHaveLength(0);});
});
