/* eslint-disable @typescript-eslint/restrict-template-expressions */
import type {EvaluationResult} from '@agentprodready/evaluation';
import type {AuthorizationDecision,AuthorityState} from '@agentprodready/security';

export type InteractionType='approval'|'review'|'clarification'|'decision'|'correction'|'confirmation'|'escalation'|'evaluation';
export type ResponseType='approve'|'reject'|'conditional-approval'|'defer'|'input'|'correction'|'confirm'|'evaluation'|'escalate';
export type CompletionStatus='approved'|'rejected'|'conditionally-approved'|'information-provided'|'correction-provided'|'confirmed'|'escalated'|'expired'|'cancelled'|'invalid-response'|'inconclusive';
export type InteractionState='created'|'authorized'|'issued'|'delivered'|'awaiting-response'|'responded'|'validated'|'completed'|'delivery-failed'|'expired'|'cancelled'|'escalated'|'rejected'|'invalidated'|'revoked';
export interface InteractionScope{readonly tenantId:string;readonly workspaceId?:string;readonly projectId?:string;readonly classification:'public'|'internal'|'confidential'|'restricted';}
export interface ParticipantRequirement{readonly type:'principal'|'role'|'group'|'tenant-administrator'|'resource-owner'|'compliance-reviewer'|'security-reviewer'|'subject-matter-expert'|'authorized-approver'|'any-eligible';readonly values:readonly string[];readonly minimumParticipants:number;readonly delegationAllowed:boolean;readonly requesterMayRespond:boolean;}
export interface AllowedResponseContract{readonly types:readonly ResponseType[];readonly requiredFields:readonly string[];readonly optionIds:readonly string[];readonly schemaReference:string;readonly commentsAllowed:boolean;readonly evidenceRequired:boolean;}
export interface InteractionPolicy{readonly version:string;readonly responsePolicy:'first-valid'|'all-approvers';readonly conflictingResponse:'escalate'|'reject'|'inconclusive';readonly requiredApprovals:number;}
export interface ExpirationPolicy{readonly version:string;readonly expiresAt:string;readonly outcome:'reject'|'escalate'|'restricted'|'cancel'|'inconclusive'|'request-another'|'administrative-intervention';}
export interface EscalationPolicy{readonly version:string;readonly enabled:boolean;readonly participantRequirement?:ParticipantRequirement;readonly reasonCodes:readonly string[];}
export interface HumanInteractionRequest{readonly id:string;readonly version:string;readonly type:InteractionType;readonly purpose:string;readonly participantRequirement:ParticipantRequirement;readonly executionReference:string;readonly workflowReference?:string;readonly agentReference?:string;readonly collaborationReference?:string;readonly subjectArtifactReferences:readonly string[];readonly responseContract:AllowedResponseContract;readonly scope:InteractionScope;readonly interactionPolicy:InteractionPolicy;readonly expirationPolicy:ExpirationPolicy;readonly escalationPolicy:EscalationPolicy;readonly correlationId:string;readonly causationId:string|null;readonly requestedBy:string;readonly createdAt:string;readonly provenance:Readonly<{sourceReference:string;builderVersion:string}>;}
export interface HumanResponse{readonly id:string;readonly interactionId:string;readonly principalId:string;readonly type:ResponseType;readonly decision?:string;readonly structuredInput:Readonly<Record<string,unknown>>;readonly comments?:string;readonly evidenceReferences:readonly string[];readonly respondedAt:string;readonly authorizationDecisionId:string;readonly delegationReference?:string;readonly correlationId:string;readonly causationId:string|null;}
export interface ApprovalDecision{readonly outcome:'approved'|'rejected'|'approved-with-conditions'|'deferred'|'expired'|'cancelled'|'invalid';readonly conditions:readonly string[];readonly obligations:readonly string[];readonly explicit:true;}
export interface HumanInteractionResult{readonly id:string;readonly interactionId:string;readonly requestVersion:string;readonly completionStatus:CompletionStatus;readonly validatedResponses:readonly HumanResponse[];readonly respondingPrincipalIds:readonly string[];readonly approvalDecision?:ApprovalDecision;readonly appliedPolicy:Readonly<{type:InteractionPolicy['responsePolicy'];version:string}>;readonly expirationStatus:'active'|'expired';readonly escalationStatus:'none'|'required'|'created'|'failed';readonly evidenceReferences:readonly string[];readonly evaluationResultReference?:string;readonly humanInputVerified:false;readonly verificationReference?:string;readonly diagnosticsReference:string;readonly correlationId:string;readonly completedAt:string;readonly descriptive:true;}
export interface ResolvedParticipant{readonly principalId:string;readonly tenantId:string;readonly roles:readonly string[];readonly authorizationDecision:AuthorizationDecision;readonly authorityState:AuthorityState;}
export interface ParticipantResolver{resolve(request:HumanInteractionRequest):Promise<readonly ResolvedParticipant[]>;}
export interface InteractionDelivery{readonly id:string;readonly interactionId:string;readonly attempt:number;readonly channel:string;readonly participantId:string;readonly status:'delivered'|'failed';readonly authorizationDecisionId:string;readonly occurredAt:string;}
export interface DeliveryAdapter{deliver(request:HumanInteractionRequest,participant:ResolvedParticipant,deliveryId:string,attempt:number):Promise<InteractionDelivery>;}
export interface InteractionLifecycleFact{readonly id:string;readonly interactionId:string;readonly from:InteractionState;readonly to:InteractionState;readonly reason:string;readonly authorizationDecisionId?:string;readonly occurredAt:string;readonly correlationId:string;readonly version:number;}
export interface InteractionRecord{readonly request:HumanInteractionRequest;readonly state:InteractionState;readonly responses:readonly HumanResponse[];readonly deliveries:readonly InteractionDelivery[];readonly lifecycle:readonly InteractionLifecycleFact[];readonly result?:HumanInteractionResult;readonly version:number;}
export interface InteractionStore{create(request:HumanInteractionRequest):void;get(id:string):InteractionRecord|undefined;append(id:string,fact:InteractionLifecycleFact,change:Readonly<{state:InteractionState;response?:HumanResponse;delivery?:InteractionDelivery;result?:HumanInteractionResult}>):InteractionRecord;}
export interface ResponseValidation{readonly valid:boolean;readonly duplicate:boolean;readonly errors:readonly HumanInteractionErrorCode[];readonly response:HumanResponse;readonly diagnosticId:string;}
export interface ResponseValidator{validate(request:HumanInteractionRequest,record:InteractionRecord,response:HumanResponse,participant:ResolvedParticipant,now:string):ResponseValidation;}
export interface ResponsePolicy{readonly type:InteractionPolicy['responsePolicy'];decide(request:HumanInteractionRequest,responses:readonly HumanResponse[],eligible:readonly ResolvedParticipant[]):Readonly<{complete:boolean;status:CompletionStatus;conflict:boolean;approval?:ApprovalDecision}>;}
export interface RuntimeInteractionPort{awaiting(interactionId:string,executionReference:string):Promise<Readonly<{accepted:boolean}>>;completed(result:HumanInteractionResult,executionReference:string):Promise<Readonly<{accepted:boolean;resumedByRuntime:boolean}>>;}
export interface WorkflowInteractionPort{consume(result:HumanInteractionResult,workflowReference:string):Promise<Readonly<{accepted:boolean;continuationOwnedByWorkflow:true}>>;}
export interface HumanEvaluationReference{readonly requestReference:string;readonly result:EvaluationResult;}
export interface RedactedInteractionView{readonly interactionId:string;readonly type:InteractionType;readonly purpose:string;readonly artifactReferences:readonly string[];readonly redacted:true;readonly principalId:string;readonly authorizationDecisionId:string;}
export interface HumanInteractionFact{readonly type:'interaction.created'|'interaction.issued'|'interaction.delivered'|'interaction.delivery-failed'|'response.submitted'|'response.validated'|'approval.granted'|'approval.rejected'|'interaction.expired'|'interaction.escalated'|'interaction.cancelled'|'interaction.completed';readonly interactionId:string;readonly operationId:string;readonly tenantId:string;readonly principalId?:string;readonly correlationId:string;readonly diagnosticsReference:string;}
export interface HumanInteractionEvents{publish(value:HumanInteractionFact):Promise<void>;}
export interface HumanInteractionAudit{record(value:Readonly<{type:string;interactionId:string;principalIds:readonly string[];authorizationDecisionIds:readonly string[];evidenceReferences:readonly string[];correlationId:string}>):Promise<void>;}
export interface HumanInteractionDiagnostics{record(value:Readonly<{id:string;interactionId:string;phase:string;outcome:'completed'|'failed';policyVersions:readonly string[];errorCode?:HumanInteractionErrorCode}>):void;list():readonly unknown[];}
export type HumanInteractionErrorCode='INTERACTION_REQUEST_INVALID'|'PARTICIPANT_RESOLUTION_FAILED'|'PARTICIPANT_UNAUTHORIZED'|'INTERACTION_DELIVERY_FAILED'|'RESPONSE_INVALID'|'RESPONSE_UNAUTHORIZED'|'INTERACTION_EXPIRED'|'INTERACTION_CANCELLED'|'DUPLICATE_RESPONSE'|'CONFLICTING_RESPONSES'|'SEPARATION_OF_DUTIES_VIOLATION'|'ESCALATION_FAILED'|'INTERACTION_NOT_FOUND'|'INTERACTION_ALREADY_COMPLETED';
export class HumanInteractionError extends Error{public constructor(public readonly code:HumanInteractionErrorCode,message:string,public readonly diagnosticId:string){super(message);this.name='HumanInteractionError';}}

export function buildHumanInteractionRequest(value:HumanInteractionRequest):HumanInteractionRequest{validateRequest(value);return freeze(clone(value));}
export function redactedView(request:HumanInteractionRequest,participant:ResolvedParticipant):RedactedInteractionView{enforceParticipant(request,participant,'read');return freeze({interactionId:request.id,type:request.type,purpose:request.purpose,artifactReferences:request.subjectArtifactReferences.map(()=> 'redacted'),redacted:true,principalId:participant.principalId,authorizationDecisionId:participant.authorizationDecision.id});}

export class HumanInteractionFramework{
 public constructor(private readonly resolver:ParticipantResolver,private readonly delivery:DeliveryAdapter,private readonly store:InteractionStore,private readonly validator:ResponseValidator,private readonly events:HumanInteractionEvents,private readonly audit:HumanInteractionAudit,private readonly diagnostics:HumanInteractionDiagnostics,private readonly runtime:RuntimeInteractionPort,private readonly workflow:WorkflowInteractionPort){}
 public async issue(request:HumanInteractionRequest,now:string):Promise<InteractionRecord>{const normalized=buildHumanInteractionRequest(request);this.store.create(normalized);const participants=await this.resolver.resolve(normalized);if(participants.length<normalized.participantRequirement.minimumParticipants)throw this.error(normalized,'PARTICIPANT_RESOLUTION_FAILED','resolve');for(const participant of participants)enforceParticipant(normalized,participant,'read');let record=this.transition(normalized.id,'created','authorized','participants-authorized',now,participants[0]?.authorizationDecision.id);record=this.transition(normalized.id,'authorized','issued','request-issued',now,participants[0]?.authorizationDecision.id);await this.events.publish(this.fact(normalized,'interaction.issued','issue'));for(let index=0;index<participants.length;index+=1){const participant=participants[index];if(participant===undefined)continue;const delivery=await this.delivery.deliver(normalized,participant,`delivery:${normalized.id}:${index+1}`,1);record=this.store.append(normalized.id,this.lifecycle(normalized,record.state,delivery.status==='delivered'?'delivered':'delivery-failed','delivery-recorded',now,participant.authorizationDecision.id,record.version+1),{state:delivery.status==='delivered'?'delivered':'delivery-failed',delivery});await this.events.publish(this.fact(normalized,delivery.status==='delivered'?'interaction.delivered':'interaction.delivery-failed',delivery.id,participant.principalId));}if(record.deliveries.some(value=>value.status==='delivered'))record=this.transition(normalized.id,record.state,'awaiting-response','delivery-available',now);await this.runtime.awaiting(normalized.id,normalized.executionReference);return record;}
 public async retryDelivery(id:string,participant:ResolvedParticipant,now:string):Promise<InteractionDelivery>{const record=this.required(id);enforceParticipant(record.request,participant,'read');const attempt=record.deliveries.filter(value=>value.participantId===participant.principalId).length+1;const delivery=await this.delivery.deliver(record.request,participant,`delivery:${id}:${participant.principalId}:${attempt}`,attempt);this.store.append(id,this.lifecycle(record.request,record.state,record.state,'delivery-retry',now,participant.authorizationDecision.id,record.version+1),{state:record.state,delivery});return delivery;}
 public async respond(id:string,response:HumanResponse,participant:ResolvedParticipant,policy:ResponsePolicy,now:string):Promise<HumanInteractionResult|undefined>{const record=this.required(id);if(record.result!==undefined)throw this.error(record.request,'INTERACTION_ALREADY_COMPLETED','response');const validation=this.validator.validate(record.request,record,response,participant,now);if(validation.duplicate)return undefined;if(!validation.valid)throw this.error(record.request,validation.errors[0]??'RESPONSE_INVALID','response');let changed=this.store.append(id,this.lifecycle(record.request,record.state,'responded','response-submitted',now,response.authorizationDecisionId,record.version+1),{state:'responded',response:validation.response});changed=this.transition(id,'responded','validated','response-validated',now,response.authorizationDecisionId);const eligible=await this.resolver.resolve(record.request);const decision=policy.decide(record.request,changed.responses,eligible);if(!decision.complete)return undefined;const result=this.result(record.request,changed.responses,decision.status,decision.approval,now,decision.conflict?'required':'none');this.store.append(id,this.lifecycle(record.request,'validated','completed','policy-complete',now,response.authorizationDecisionId,changed.version+1),{state:'completed',result});await this.publishCompletion(record.request,result);await this.runtime.completed(result,record.request.executionReference);if(record.request.workflowReference!==undefined)await this.workflow.consume(result,record.request.workflowReference);return result;}
 public async expire(id:string,now:string):Promise<HumanInteractionResult>{const record=this.required(id);if(record.result!==undefined)throw this.error(record.request,'INTERACTION_ALREADY_COMPLETED','expiration');const escalation=record.request.expirationPolicy.outcome==='escalate';const status:CompletionStatus=escalation?'escalated':record.request.expirationPolicy.outcome==='reject'?'rejected':record.request.expirationPolicy.outcome==='cancel'?'cancelled':'inconclusive';const result=this.result(record.request,record.responses,status,undefined,now,escalation?'required':'none','expired');this.store.append(id,this.lifecycle(record.request,record.state,escalation?'escalated':'expired','expiration-policy',now,undefined,record.version+1),{state:escalation?'escalated':'expired',result});await this.events.publish(this.fact(record.request,escalation?'interaction.escalated':'interaction.expired','expiration'));await this.auditResult(record.request,result);return result;}
 public async cancel(id:string,authorizationDecisionId:string,now:string):Promise<HumanInteractionResult>{const record=this.required(id);const result=this.result(record.request,record.responses,'cancelled',undefined,now);this.store.append(id,this.lifecycle(record.request,record.state,'cancelled','cancelled',now,authorizationDecisionId,record.version+1),{state:'cancelled',result});await this.events.publish(this.fact(record.request,'interaction.cancelled','cancel'));await this.auditResult(record.request,result);return result;}
 private result(request:HumanInteractionRequest,responses:readonly HumanResponse[],status:CompletionStatus,approval:ApprovalDecision|undefined,now:string,escalation:HumanInteractionResult['escalationStatus']='none',expiration:HumanInteractionResult['expirationStatus']='active'):HumanInteractionResult{return freeze({id:`result:${request.id}:${responses.length}`,interactionId:request.id,requestVersion:request.version,completionStatus:status,validatedResponses:[...responses],respondingPrincipalIds:unique(responses.map(value=>value.principalId)),...(approval===undefined?{}:{approvalDecision:approval}),appliedPolicy:{type:request.interactionPolicy.responsePolicy,version:request.interactionPolicy.version},expirationStatus:expiration,escalationStatus:escalation,evidenceReferences:unique(responses.flatMap(value=>value.evidenceReferences)),humanInputVerified:false,diagnosticsReference:`human:${request.id}`,correlationId:request.correlationId,completedAt:now,descriptive:true});}
 private transition(id:string,from:InteractionState,to:InteractionState,reason:string,now:string,decision?:string):InteractionRecord{const record=this.required(id);return this.store.append(id,this.lifecycle(record.request,from,to,reason,now,decision,record.version+1),{state:to});}
 private lifecycle(request:HumanInteractionRequest,from:InteractionState,to:InteractionState,reason:string,now:string,decision:string|undefined,version:number):InteractionLifecycleFact{return freeze({id:`lifecycle:${request.id}:${version}`,interactionId:request.id,from,to,reason,...(decision===undefined?{}:{authorizationDecisionId:decision}),occurredAt:now,correlationId:request.correlationId,version});}
 private required(id:string):InteractionRecord{const record=this.store.get(id);if(record===undefined)throw new HumanInteractionError('INTERACTION_NOT_FOUND','Interaction not found',`human:${id}`);return record;}
 private error(request:HumanInteractionRequest,code:HumanInteractionErrorCode,phase:string):HumanInteractionError{this.diagnostics.record({id:`human:${request.id}:${phase}`,interactionId:request.id,phase,outcome:'failed',policyVersions:[request.interactionPolicy.version,request.expirationPolicy.version],errorCode:code});return new HumanInteractionError(code,code.replaceAll('_',' '),`human:${request.id}:${phase}`);}
 private fact(request:HumanInteractionRequest,type:HumanInteractionFact['type'],operationId:string,principalId?:string):HumanInteractionFact{return freeze({type,interactionId:request.id,operationId,tenantId:request.scope.tenantId,...(principalId===undefined?{}:{principalId}),correlationId:request.correlationId,diagnosticsReference:`human:${request.id}`});}
 private async publishCompletion(request:HumanInteractionRequest,result:HumanInteractionResult):Promise<void>{const event=result.completionStatus==='approved'||result.completionStatus==='conditionally-approved'?'approval.granted':result.completionStatus==='rejected'?'approval.rejected':'interaction.completed';await this.events.publish(this.fact(request,event,result.id));await this.auditResult(request,result);this.diagnostics.record({id:result.diagnosticsReference,interactionId:request.id,phase:'complete',outcome:'completed',policyVersions:[request.interactionPolicy.version,request.expirationPolicy.version]});}
 private async auditResult(request:HumanInteractionRequest,result:HumanInteractionResult):Promise<void>{await this.audit.record({type:result.completionStatus,interactionId:request.id,principalIds:result.respondingPrincipalIds,authorizationDecisionIds:result.validatedResponses.map(value=>value.authorizationDecisionId),evidenceReferences:result.evidenceReferences,correlationId:request.correlationId});}
}

function validateRequest(value:HumanInteractionRequest):void{if(value.id.trim()===''||value.purpose.trim()===''||value.executionReference.trim()===''||value.scope.tenantId.trim()===''||value.participantRequirement.minimumParticipants<1||value.responseContract.types.length===0||Date.parse(value.expirationPolicy.expiresAt)<=Date.parse(value.createdAt)||value.type==='approval'&&!value.responseContract.types.some(type=>type==='approve'||type==='conditional-approval'||type==='reject'))throw new HumanInteractionError('INTERACTION_REQUEST_INVALID','Invalid human interaction request',`human:${value.id||'unknown'}:request`);const serialized=JSON.stringify(value);if(/password|secretValue|apiKey/i.test(serialized))throw new HumanInteractionError('INTERACTION_REQUEST_INVALID','Raw secret-like content is forbidden',`human:${value.id}:request`);}
function enforceParticipant(request:HumanInteractionRequest,participant:ResolvedParticipant,action:'read'|'approve'):void{const decision=participant.authorizationDecision;if(participant.authorityState!=='active'||!decision.authorized||decision.principalId!==participant.principalId||decision.effectiveScope.tenantId!==request.scope.tenantId||decision.action!==action&&!(action==='read'&&decision.action==='approve'))throw new HumanInteractionError('PARTICIPANT_UNAUTHORIZED','Participant is not authorized',`human:${request.id}:security`);}
function clone<T>(value:T):T{return JSON.parse(JSON.stringify(value)) as T;}function freeze<T>(value:T):T{if(typeof value==='object'&&value!==null&&!Object.isFrozen(value)){for(const child of Object.values(value))freeze(child);Object.freeze(value);}return value;}function unique<T>(values:readonly T[]):readonly T[]{return freeze([...new Set(values)]);}

export * from './reference.js';
