import {describe,expect,it,vi} from 'vitest';
import type {EventDelivery,PlatformEvent} from '@agentforge/event-bus';
import {AuditError,AuditPlatform,type AuditAuthorizationOutcome,type AuditIngestionRequest,type AuditQueryRequest,freeze} from './index.js';
import {DeterministicHashChainIntegrityProvider,DeterministicRetentionResolver,InMemoryAuditArchive,InMemoryAuditDiagnostics,InMemoryAuditEvents,InMemoryAuditEvidenceStore,InMemoryAuditIndex,InMemoryAuditRecordStore,InMemoryAuditTelemetry,InMemoryAuditTombstones,InMemoryLegalHoldStore,JsonReferenceAuditExportProvider} from './reference.js';

const now=():Date=>new Date('2026-08-06T00:00:00.000Z');
function authorization(operation:AuditAuthorizationOutcome['operation'],overrides:Partial<AuditAuthorizationOutcome>={}):AuditAuthorizationOutcome{return freeze({decisionId:`decision:${operation}`,authorized:true,state:'active',operation,principalId:'auditor-1',scope:{tenantId:'tenant-1',workspaceId:'workspace-1',projectId:'project-1'},maximumClassification:'restricted',redactedFields:[],restrictions:[],obligations:[],policyVersion:'security-1',...overrides});}
function request(overrides:Partial<AuditIngestionRequest>={}):AuditIngestionRequest{return freeze({requestId:'ingest-1',source:{sourceType:'platform-event',sourceId:'event-1',sourceSchemaVersion:'1',eventId:'event-1',deliveryId:'delivery-1',producer:'workflow',derivationKey:'security-audit',derivationPolicyVersion:'1'},truthStatus:'observed',occurredAt:'2026-08-05T23:59:00.000Z',principalId:'principal-1',effectivePrincipalId:'principal-1',action:'workflow.completed',resource:{id:'workflow-1',type:'workflow',version:'1'},outcome:'succeeded',scope:{tenantId:'tenant-1',workspaceId:'workspace-1',projectId:'project-1'},authorizationDecisionId:'decision:source',policyReferences:['policy-1'],evidenceReferences:['event:event-1'],categories:['security'],classification:'confidential',retentionRequirements:[{policyId:'retention-1',category:'security',minimumDays:0,maximumDays:365,mandatory:true,archivalEligible:true,deletionRestrictions:[],policyVersion:'1'}],attributes:{summary:'workflow completed'},executionReference:'execution-1',correlationId:'execution-1',causationId:null,siblingSourceIds:[],schemaVersion:'1',ingestionPolicyVersion:'1',lifecycleOrigin:'source-fact',derivationDepth:0,...overrides});}
interface Fixture{readonly platform:AuditPlatform;readonly records:InMemoryAuditRecordStore;readonly index:InMemoryAuditIndex;readonly archive:InMemoryAuditArchive;readonly evidence:InMemoryAuditEvidenceStore;readonly holds:InMemoryLegalHoldStore;readonly tombstones:InMemoryAuditTombstones;readonly events:InMemoryAuditEvents;readonly diagnostics:InMemoryAuditDiagnostics;readonly telemetry:InMemoryAuditTelemetry;readonly integrity:DeterministicHashChainIntegrityProvider;}
function fixture():Fixture{const records=new InMemoryAuditRecordStore(),index=new InMemoryAuditIndex(),archive=new InMemoryAuditArchive(),evidence=new InMemoryAuditEvidenceStore(),holds=new InMemoryLegalHoldStore(),tombstones=new InMemoryAuditTombstones(),events=new InMemoryAuditEvents(),diagnostics=new InMemoryAuditDiagnostics(),telemetry=new InMemoryAuditTelemetry(),integrity=new DeterministicHashChainIntegrityProvider();return{platform:new AuditPlatform({records,index,archive,evidence,integrity,retention:new DeterministicRetentionResolver(),holds,tombstones,events,diagnostics,telemetry,now}),records,index,archive,evidence,holds,tombstones,events,diagnostics,telemetry,integrity};}
function query(auth:AuditAuthorizationOutcome=authorization('query'),overrides:Partial<AuditQueryRequest>={}):AuditQueryRequest{return freeze({id:'query-1',authorization:auth,scope:{tenantId:'tenant-1',workspaceId:'workspace-1',projectId:'project-1'},from:'2026-01-01T00:00:00.000Z',to:'2026-12-31T00:00:00.000Z',principalIds:[],actions:[],resourceIds:[],outcomes:[],correlations:[],causations:[],categories:[],truthStatuses:[],limit:100,snapshotAt:'2026-08-07T00:00:00.000Z',policyVersion:'query-1',...overrides});}

describe('audit ingestion and immutable accountability',()=>{
 it('normalizes an authoritative fact into an immutable record with distinct times and provenance',async()=>{const{platform}=fixture();const record=await platform.ingest(request());expect(record.occurredAt).toBe('2026-08-05T23:59:00.000Z');expect(record.recordedAt).toBe('2026-08-06T00:00:00.000Z');expect(record.source.eventId).toBe('event-1');expect(Object.isFrozen(record)).toBe(true);expect(Object.isFrozen(record.integrity)).toBe(true);expect(()=>{(record.resource as{id:string}).id='changed';}).toThrow();});
 it('rejects invalid, secret-bearing, and recursive lifecycle sources',async()=>{const{platform}=fixture();await expect(platform.ingest(request({principalId:''}))).rejects.toMatchObject({code:'AUDIT_INGESTION_INVALID'});await expect(platform.ingest(request({attributes:{accessToken:'secret'}}))).rejects.toMatchObject({code:'AUDIT_SOURCE_INVALID'});await expect(platform.ingest(request({lifecycleOrigin:'audit-lifecycle'}))).rejects.toMatchObject({code:'AUDIT_RECURSION_SUPPRESSED'});});
 it('deduplicates Event Bus redelivery by source identity rather than Delivery ID',async()=>{const{platform,records}=fixture();const event={eventId:'event-1'} as PlatformEvent;const make=(deliveryId:string):EventDelivery=>({deliveryId,event,subscriptionId:'audit',subscriberId:'audit',attempt:1,deliveredAt:'2026-08-06T00:00:00.000Z',mode:'live'});const first=await platform.ingestDelivery(make('delivery-1'),()=>request());const second=await platform.ingestDelivery(make('delivery-2'),()=>request({requestId:'ingest-2'}));expect(second).toBe(first);expect(await records.list()).toHaveLength(1);});
 it('creates deterministic sibling records for explicit derivations',async()=>{const{platform}=fixture();const first=await platform.ingest(request());const sibling=await platform.ingest(request({requestId:'ingest-2',source:{...request().source,derivationKey:'compliance-audit'},categories:['compliance'],siblingSourceIds:[first.id]}));expect(sibling.id).not.toBe(first.id);expect(sibling.siblingSourceIds).toEqual([first.id]);});
 it('assigns explicit classification, retention precedence, and integrity metadata',async()=>{const{platform}=fixture();const record=await platform.ingest(request({retentionRequirements:[...request().retentionRequirements,{policyId:'mandatory-long',category:'compliance-controlled',minimumDays:1000,mandatory:true,archivalEligible:true,deletionRestrictions:['approval'],policyVersion:'2'}]}));expect(record.retention.effectivePolicyIds).toContain('mandatory-long');expect(record.retention.minimumRetainUntil).toBe('2029-05-02T00:00:00.000Z');expect(record.retention.deletionRestrictions).toEqual(['approval']);expect(record.integrity.guarantee).toBe('reference-tamper-evidence');});
 it('separates source operation outcome from persistence failure',async()=>{const value=fixture();vi.spyOn(value.records,'save').mockRejectedValueOnce(new Error('store down'));await expect(value.platform.ingest(request({outcome:'succeeded'}))).rejects.toMatchObject({code:'AUDIT_STORE_UNAVAILABLE'});expect(value.diagnostics.list().at(-1)?.outcome).toBe('failed');});
});

describe('authorized queries, redaction, and reconstruction',()=>{
 it('enforces Security outcomes and denies cross-tenant access without existence leakage',async()=>{const{platform}=fixture();await platform.ingest(request());await expect(platform.query(query(authorization('query',{authorized:false})))).rejects.toMatchObject({code:'AUDIT_ACCESS_DENIED'});await expect(platform.query(query(authorization('query',{scope:{tenantId:'other'}})))).rejects.toMatchObject({code:'AUDIT_CROSS_TENANT_DENIED'});});
 it('requires separately scoped administrative operations',async()=>{const{platform}=fixture();await expect(platform.query(query(authorization('administrative-access')))).rejects.toBeInstanceOf(AuditError);});
 it('returns deterministic paginated redacted views without mutating records',async()=>{const{platform,records}=fixture();const original=await platform.ingest(request());await platform.ingest(request({requestId:'ingest-2',source:{...request().source,sourceId:'event-2',eventId:'event-2'},occurredAt:original.occurredAt}));const auth=authorization('query',{redactedFields:['attributes']});const first=await platform.query(query(auth,{limit:1}));const second=await platform.query(query(auth,{limit:1,...(first.nextCursor===undefined?{}:{cursor:first.nextCursor})}));expect(first.views[0]?.record.attributes).toBeUndefined();expect(first.views[0]?.redaction.fields).toEqual(['attributes']);expect(second.views[0]?.recordId).not.toBe(first.views[0]?.recordId);expect((await records.find(original.id))?.attributes).toEqual({summary:'workflow completed'});});
 it('filters normalized dimensions and includes integrity metadata',async()=>{const{platform}=fixture();await platform.ingest(request());expect((await platform.query(query(undefined,{actions:['other']}))).views).toHaveLength(0);const result=await platform.query(query(undefined,{actions:['workflow.completed'],truthStatuses:['observed'],causations:[null]}));expect(result.views[0]?.integrity.status).toBe('verified');});
 it('reconstructs observed, derived, and inferred relationships without execution replay',async()=>{const{platform}=fixture();await platform.ingest(request({truthStatus:'inferred'}));const result=await platform.query(query());const reconstruction=platform.reconstruct('reconstruction-1',result,'2026-08-06T01:00:00.000Z');expect(reconstruction.elements[0]?.relationship).toBe('inferred');expect(reconstruction.noExecutionReplay).toBe(true);});
});

describe('integrity, holds, archive, evidence, export, and deletion',()=>{
 it('reports verified, tampered, missing, and chain-break outcomes without mutation',async()=>{const{platform,records}=fixture();const first=await platform.ingest(request());const second=await platform.ingest(request({requestId:'ingest-2',source:{...request().source,sourceId:'event-2',eventId:'event-2'}}));let result=await platform.verify({id:'verify-1',recordIds:[first.id,second.id],policyVersion:'1',authorization:authorization('verify'),correlationId:'execution-1'});expect(result.status).toBe('verified');records.unsafeReplaceForVerification(freeze({...second,action:'tampered'}));result=await platform.verify({id:'verify-2',recordIds:[first.id,second.id,'missing'],policyVersion:'1',authorization:authorization('verify'),correlationId:'execution-1'});expect(result.failedRecordIds).toContain(second.id);expect(result.missingRecordIds).toEqual(['missing']);expect((await records.find(first.id))?.integrity).toBe(first.integrity);});
 it('applies and releases authorized versioned Legal Holds idempotently',()=>{const{platform}=fixture();const hold=platform.applyHold({id:'hold-1',scope:{tenantId:'tenant-1',recordIds:[],correlationIds:['execution-1']},reason:'investigation',policyVersion:'1',authorization:authorization('legal-hold-apply'),requestedAt:'2026-08-06T00:00:00.000Z'});expect(platform.applyHold({id:'hold-1',scope:hold.scope,reason:'investigation',policyVersion:'1',authorization:authorization('legal-hold-apply'),requestedAt:hold.appliedAt})).toBe(hold);const released=platform.releaseHold('hold-1','closed','2026-08-07T00:00:00.000Z',authorization('legal-hold-release'));expect(released.status).toBe('released');expect(hold.status).toBe('active');});
 it('archives without changing logical identity, provenance, integrity, or security',async()=>{const{platform,records,archive}=fixture();const record=await platform.ingest(request());const result=await platform.archive(record.id,authorization('archive'));expect(result.recordId).toBe(record.id);expect(archive.records.get(record.id)).toBe(record);expect(await records.find(record.id)).toBe(record);});
 it('finalizes immutable evidence preserving source, redaction, integrity, and policy versions',async()=>{const{platform}=fixture();await platform.ingest(request());const result=await platform.query(query(authorization('query',{redactedFields:['attributes']})));const evidence=await platform.evidencePackage('evidence-1','investigation',result,authorization('evidence'),'2026-08-06T01:00:00.000Z');expect(Object.isFrozen(evidence)).toBe(true);expect(evidence.sourceRecordReferences[0]?.integrityDigest).toBeTruthy();expect(evidence.redactions[0]?.fields).toEqual(['attributes']);expect(evidence.policyVersions).toContain('security-1');});
 it('requires separate export authority and governed destination/format',async()=>{const{platform}=fixture();await platform.ingest(request());const result=await platform.query(query());const evidence=await platform.evidencePackage('evidence-1','review',result,authorization('evidence'),'2026-08-06T01:00:00.000Z');await expect(platform.export({id:'export-1',requestingPrincipalId:'auditor-1',evidencePackageId:evidence.id,format:'json',destination:{reference:'approved:archive',classification:'restricted',encrypted:true,recipientRestrictions:['compliance']},purpose:'review',authorization:authorization('query'),policyVersion:'1',requestedAt:'2026-08-06T02:00:00.000Z'},evidence,new JsonReferenceAuditExportProvider())).rejects.toMatchObject({code:'AUDIT_EXPORT_DENIED'});const exported=await platform.export({id:'export-2',requestingPrincipalId:'auditor-1',evidencePackageId:evidence.id,format:'evidence-bundle',destination:{reference:'approved:archive',classification:'restricted',encrypted:true,recipientRestrictions:['compliance']},purpose:'review',authorization:authorization('export'),policyVersion:'1',requestedAt:'2026-08-06T02:00:00.000Z'},evidence,new JsonReferenceAuditExportProvider());expect(Object.isFrozen(exported)).toBe(true);expect(exported.sourceRecordIds).toEqual(evidence.sourceRecordReferences.map(value=>value.id));});
 it('blocks deletion for retention, hold, investigation, dependency, or authorization',async()=>{const{platform}=fixture();const record=await platform.ingest(request({retentionRequirements:[{policyId:'retention-1',category:'security',minimumDays:10,maximumDays:365,mandatory:true,archivalEligible:true,deletionRestrictions:[],policyVersion:'1'}]}));const base={id:'delete-1',recordId:record.id,method:'physical' as const,authorization:authorization('delete'),requestedAt:'2026-08-07T00:00:00.000Z',activeInvestigation:false,dependencyClearance:true,policyVersion:'1'};await expect(platform.delete(base)).rejects.toMatchObject({code:'AUDIT_DELETION_PROHIBITED'});await expect(platform.delete({...base,authorization:authorization('query')})).rejects.toMatchObject({code:'AUDIT_ACCESS_DENIED'});});
 it('propagates eligible governed deletion and creates content-free accountable evidence',async()=>{const{platform,records,index,archive,evidence,tombstones}=fixture();const record=await platform.ingest(request());await platform.archive(record.id,authorization('archive'));const result=await platform.query(query());await platform.evidencePackage('evidence-1','review',result,authorization('evidence'),'2026-08-06T01:00:00.000Z');const tombstone=await platform.delete({id:'delete-1',recordId:record.id,method:'physical',authorization:authorization('delete'),requestedAt:'2026-08-07T00:00:00.000Z',activeInvestigation:false,dependencyClearance:true,policyVersion:'1'});expect(await records.find(record.id)).toBeUndefined();expect(index.ids.has(record.id)).toBe(false);expect(archive.records.has(record.id)).toBe(false);expect(evidence.packages.size).toBe(0);expect(tombstones.list()).toEqual([tombstone]);expect(JSON.stringify(tombstone)).not.toContain('workflow completed');});
 it('Legal Hold overrides otherwise eligible deletion and release only resumes evaluation',async()=>{const{platform}=fixture();const record=await platform.ingest(request());platform.applyHold({id:'hold-1',scope:{tenantId:'tenant-1',recordIds:[record.id],correlationIds:[]},reason:'case',policyVersion:'1',authorization:authorization('legal-hold-apply'),requestedAt:'2026-08-06T00:00:00.000Z'});const deletion={id:'delete-1',recordId:record.id,method:'logical' as const,authorization:authorization('delete'),requestedAt:'2026-08-07T00:00:00.000Z',activeInvestigation:false,dependencyClearance:true,policyVersion:'1'};await expect(platform.delete(deletion)).rejects.toMatchObject({code:'AUDIT_DELETION_PROHIBITED'});platform.releaseHold('hold-1','released','2026-08-07T00:00:00.000Z',authorization('legal-hold-release'));expect((await platform.delete({...deletion,id:'delete-2'})).deletedRecordId).toBe(record.id);});
 it('exposes minimized lifecycle events, diagnostics, telemetry, and normalized health',async()=>{const{platform,events,diagnostics,telemetry}=fixture();await platform.ingest(request());expect(events.facts[0]).toMatchObject({type:'audit.record.created',origin:'audit-lifecycle',derivationDepth:0});expect(JSON.stringify(events.facts[0])).not.toContain('workflow completed');expect(diagnostics.list()[0]?.outcome).toBe('completed');expect(telemetry.counters.get('ingestion:created')).toBe(1);expect(await platform.health()).toMatchObject({name:'audit',status:'healthy',records:1});});
});


