import type {PlatformEvent,EventDelivery} from '@agentforge/event-bus';
import type {AuthorityState} from '@agentforge/security';

export type AuditOutcome='succeeded'|'failed'|'denied'|'cancelled'|'partial'|'inconclusive'|'pending'|'revoked'|'expired';
export type TruthStatus='observed'|'derived'|'inferred'|'unknown';
export type AuditCategory='security'|'administrative'|'access'|'data-usage'|'agent'|'tool-side-effect'|'plugin'|'configuration'|'compliance'|'operational'|'evaluation'|'human-approval';
export type AuditClassification='public'|'internal'|'confidential'|'restricted';
export interface AuditScope{readonly tenantId:string;readonly workspaceId?:string;readonly projectId?:string;}
export interface AuditSourceIdentity{readonly sourceType:string;readonly sourceId:string;readonly sourceSchemaVersion:string;readonly eventId?:string;readonly deliveryId?:string;readonly producer:string;readonly derivationKey:string;readonly derivationPolicyVersion:string;}
export interface AuditRetentionRequirement{readonly policyId:string;readonly category:'operational'|'security'|'administrative'|'compliance-controlled'|'legal-hold-eligible'|'permanent';readonly minimumDays:number;readonly maximumDays?:number;readonly mandatory:boolean;readonly archivalEligible:boolean;readonly deletionRestrictions:readonly string[];readonly policyVersion:string;}
export interface AuditRetentionMetadata{readonly effectivePolicyIds:readonly string[];readonly category:AuditRetentionRequirement['category'];readonly startsAt:string;readonly minimumRetainUntil:string;readonly expiresAt?:string;readonly archivalEligible:boolean;readonly deletionRestrictions:readonly string[];readonly policyVersions:readonly string[];readonly resolutionVersion:string;}
export interface AuditIntegrityMetadata{readonly contentDigest:string;readonly previousRecordDigest?:string;readonly algorithmReference:string;readonly algorithmVersion:string;readonly keyReference?:string;readonly checkpointReference?:string;readonly generatedAt:string;readonly guarantee:'reference-tamper-evidence'|'provider-declared';}
export interface AuditIngestionRequest{readonly requestId:string;readonly source:AuditSourceIdentity;readonly truthStatus:TruthStatus;readonly occurredAt:string;readonly principalId:string;readonly effectivePrincipalId:string;readonly action:string;readonly resource:Readonly<{id:string;type:string;version:string}>;readonly outcome:AuditOutcome;readonly scope:AuditScope;readonly authorizationDecisionId:string;readonly policyReferences:readonly string[];readonly evidenceReferences:readonly string[];readonly categories:readonly AuditCategory[];readonly classification:AuditClassification;readonly retentionRequirements:readonly AuditRetentionRequirement[];readonly attributes:Readonly<Record<string,string>>;readonly executionReference?:string;readonly correlationId:string;readonly causationId:string|null;readonly siblingSourceIds:readonly string[];readonly schemaVersion:string;readonly ingestionPolicyVersion:string;readonly lifecycleOrigin?:'source-fact'|'audit-lifecycle';readonly derivationDepth?:number;}
export interface AuditRecord{readonly id:string;readonly type:string;readonly schemaVersion:string;readonly occurredAt:string;readonly recordedAt:string;readonly principalId:string;readonly effectivePrincipalId:string;readonly action:string;readonly resource:Readonly<{id:string;type:string;version:string}>;readonly outcome:AuditOutcome;readonly scope:AuditScope;readonly authorizationDecisionId:string;readonly policyReferences:readonly string[];readonly evidenceReferences:readonly string[];readonly categories:readonly AuditCategory[];readonly classification:AuditClassification;readonly attributes:Readonly<Record<string,string>>;readonly executionReference?:string;readonly correlationId:string;readonly causationId:string|null;readonly source:AuditSourceIdentity;readonly truthStatus:TruthStatus;readonly siblingSourceIds:readonly string[];readonly retention:AuditRetentionMetadata;readonly integrity:AuditIntegrityMetadata;readonly ingestionPolicyVersion:string;}
export interface AuditAuthorizationOutcome{readonly decisionId:string;readonly authorized:boolean;readonly state:AuthorityState;readonly operation:'query'|'export'|'legal-hold-apply'|'legal-hold-release'|'archive'|'verify'|'delete'|'evidence'|'administrative-access';readonly principalId:string;readonly scope:AuditScope;readonly maximumClassification:AuditClassification;readonly redactedFields:readonly string[];readonly restrictions:readonly string[];readonly obligations:readonly string[];readonly policyVersion:string;}
export interface AuditRecordStore{save(record:AuditRecord):Promise<void>;find(id:string):Promise<AuditRecord|undefined>;findBySource(key:string):Promise<AuditRecord|undefined>;list():Promise<readonly AuditRecord[]>;removeGoverned(id:string,method:DeletionMethod):Promise<readonly string[]>;}
export interface AuditIndexProvider{index(record:AuditRecord):Promise<void>;removeGoverned(id:string):Promise<void>;}
export interface AuditArchiveProvider{archive(record:AuditRecord):Promise<Readonly<{locationReference:string;archivedAt:string}>>;removeGoverned(id:string):Promise<void>;}
export interface AuditEvidenceStore{save(value:AuditEvidencePackage):Promise<void>;removeRecordReference(id:string):Promise<void>;}
export interface AuditIntegrityProvider{generate(record:Omit<AuditRecord,'integrity'>,previous?:AuditRecord):Promise<AuditIntegrityMetadata>;verify(records:readonly AuditRecord[],request:IntegrityVerificationRequest):Promise<IntegrityVerificationResult>;health():Promise<'healthy'|'degraded'|'unhealthy'>;}
export interface RetentionPolicyResolver{resolve(requirements:readonly AuditRetentionRequirement[],startsAt:string):AuditRetentionMetadata;}
export interface LegalHoldStore{save(value:LegalHoldRecord):void;activeFor(record:AuditRecord,at:string):readonly LegalHoldRecord[];get(id:string):LegalHoldRecord|undefined;}
export interface AuditEvents{publish(value:AuditLifecycleFact):Promise<void>;}
export interface AuditLifecycleFact{readonly type:'audit.record.created'|'audit.hold.applied'|'audit.hold.released'|'audit.verified'|'audit.archived'|'audit.evidence.finalized'|'audit.exported'|'audit.deleted'|'audit.accessed';readonly recordReference?:string;readonly operationId:string;readonly outcome:'completed'|'failed';readonly tenantId:string;readonly correlationId:string;readonly classification:AuditClassification;readonly origin:'audit-lifecycle';readonly derivationDepth:0;}
export interface AuditDiagnostics{record(value:AuditDiagnostic):void;list():readonly AuditDiagnostic[];}
export interface AuditDiagnostic{readonly id:string;readonly phase:'ingestion'|'query'|'integrity'|'hold'|'archive'|'evidence'|'export'|'deletion';readonly outcome:'completed'|'failed'|'duplicate'|'denied';readonly recordId?:string;readonly sourceId?:string;readonly policyVersions:readonly string[];readonly errorCode?:AuditErrorCode;}
export interface AuditTelemetry{ingested(duplicate:boolean):void;queried(count:number):void;verified(status:VerificationStatus):void;governance(operation:string):void;failed(code:AuditErrorCode):void;}
export interface AuditHealth{health():Promise<Readonly<{name:'audit';status:'healthy'|'degraded'|'unhealthy';records:number;activeHolds:number;integrityProvider:'healthy'|'degraded'|'unhealthy'}>>;}
export type AuditErrorCode='AUDIT_INGESTION_INVALID'|'AUDIT_SOURCE_INVALID'|'AUDIT_STORE_UNAVAILABLE'|'AUDIT_QUERY_INVALID'|'AUDIT_ACCESS_DENIED'|'AUDIT_CROSS_TENANT_DENIED'|'AUDIT_INTEGRITY_FAILED'|'AUDIT_RETENTION_INVALID'|'AUDIT_HOLD_CONFLICT'|'AUDIT_HOLD_NOT_FOUND'|'AUDIT_ARCHIVE_FAILED'|'AUDIT_EXPORT_DENIED'|'AUDIT_EXPORT_FAILED'|'AUDIT_REDACTION_FAILED'|'AUDIT_EVIDENCE_FAILED'|'AUDIT_DELETION_PROHIBITED'|'AUDIT_DELETION_FAILED'|'AUDIT_VERSION_INCOMPATIBLE'|'AUDIT_SERIALIZATION_FAILED'|'AUDIT_RECURSION_SUPPRESSED'|'AUDIT_UNKNOWN';
export class AuditError extends Error{public constructor(public readonly code:AuditErrorCode,message:string,public readonly diagnosticId:string,options?:ErrorOptions){super(message,options);this.name='AuditError';}}
export interface IntegrityVerificationRequest{readonly id:string;readonly recordIds:readonly string[];readonly policyVersion:string;readonly authorization:AuditAuthorizationOutcome;readonly correlationId:string;}
export type VerificationStatus='verified'|'failed'|'partial'|'unavailable'|'unsupported'|'indeterminate';
export interface IntegrityVerificationResult{readonly id:string;readonly status:VerificationStatus;readonly verifiedRecordIds:readonly string[];readonly failedRecordIds:readonly string[];readonly missingRecordIds:readonly string[];readonly chainBreakRecordIds:readonly string[];readonly algorithmReferences:readonly string[];readonly policyVersion:string;readonly diagnosticsReference:string;readonly verifiedAt:string;}
export interface LegalHoldRequest{readonly id:string;readonly scope:Readonly<{tenantId:string;recordIds:readonly string[];correlationIds:readonly string[]}>;readonly reason:string;readonly incidentReference?:string;readonly policyVersion:string;readonly authorization:AuditAuthorizationOutcome;readonly requestedAt:string;}
export interface LegalHoldRecord{readonly id:string;readonly scope:LegalHoldRequest['scope'];readonly reason:string;readonly appliedBy:string;readonly appliedAt:string;readonly authorizationDecisionId:string;readonly policyVersion:string;readonly status:'active'|'released';readonly release?:Readonly<{releasedBy:string;releasedAt:string;reason:string;authorizationDecisionId:string}>;}
export interface AuditQueryRequest{readonly id:string;readonly authorization:AuditAuthorizationOutcome;readonly scope:AuditScope;readonly from:string;readonly to:string;readonly principalIds:readonly string[];readonly actions:readonly string[];readonly resourceIds:readonly string[];readonly outcomes:readonly AuditOutcome[];readonly correlations:readonly string[];readonly causations:readonly (string|null)[];readonly categories:readonly AuditCategory[];readonly truthStatuses:readonly TruthStatus[];readonly limit:number;readonly cursor?:string;readonly snapshotAt:string;readonly policyVersion:string;}
export interface RedactionMetadata{readonly policyVersion:string;readonly fields:readonly string[];readonly reason:'authorization-restriction'|'data-minimization';readonly authorizationDecisionId:string;readonly generatedAt:string;}
export interface AuditRecordView{readonly recordId:string;readonly record:Readonly<Partial<AuditRecord>>;readonly redaction:RedactionMetadata;readonly integrity:Readonly<{status:VerificationStatus;contentDigest:string}>;}
export interface AuditQueryResult{readonly queryId:string;readonly views:readonly AuditRecordView[];readonly appliedScope:AuditScope;readonly nextCursor?:string;readonly snapshotAt:string;readonly completion:'complete'|'partial';readonly diagnosticsReference:string;}
export interface ReconstructionElement{readonly recordId:string;readonly relationship:TruthStatus;readonly correlationId:string;readonly causationId:string|null;readonly occurredAt:string;}
export interface AuditReconstruction{readonly id:string;readonly elements:readonly ReconstructionElement[];readonly generatedAt:string;readonly querySnapshotAt:string;readonly noExecutionReplay:true;}
export interface AuditEvidencePackage{readonly id:string;readonly purpose:string;readonly requestingPrincipalId:string;readonly scope:AuditScope;readonly sourceRecordReferences:readonly Readonly<{id:string;schemaVersion:string;integrityDigest:string}>[];readonly redactions:readonly RedactionMetadata[];readonly integrityResults:readonly IntegrityVerificationResult[];readonly policyVersions:readonly string[];readonly selectionCriteria:Readonly<Record<string,string>>;readonly packageSchemaVersion:string;readonly finalizedAt:string;readonly manifestDigest:string;readonly diagnosticsReference:string;}
export interface AuditExportRequest{readonly id:string;readonly requestingPrincipalId:string;readonly evidencePackageId:string;readonly format:'json'|'csv'|'signed-archive'|'pdf'|'evidence-bundle';readonly destination:Readonly<{reference:string;classification:AuditClassification;region?:string;encrypted:boolean;recipientRestrictions:readonly string[]}>;readonly purpose:string;readonly authorization:AuditAuthorizationOutcome;readonly policyVersion:string;readonly requestedAt:string;}
export interface AuditExportPackage{readonly id:string;readonly evidencePackageId:string;readonly sourceRecordIds:readonly string[];readonly format:AuditExportRequest['format'];readonly destinationReference:string;readonly classification:AuditClassification;readonly exportedBy:string;readonly exportedAt:string;readonly policyVersion:string;readonly representationDigest:string;readonly providerReference:string;}
export interface AuditExportProvider{export(request:AuditExportRequest,evidence:AuditEvidencePackage):Promise<Readonly<{providerReference:string;representationDigest:string}>>;}
export type DeletionMethod='logical'|'physical'|'cryptographic-erasure';
export interface GovernedDeletionRequest{readonly id:string;readonly recordId:string;readonly method:DeletionMethod;readonly authorization:AuditAuthorizationOutcome;readonly requestedAt:string;readonly activeInvestigation:boolean;readonly dependencyClearance:boolean;readonly policyVersion:string;}
export interface AuditTombstone{readonly id:string;readonly deletedRecordId:string;readonly method:DeletionMethod;readonly authorizedBy:string;readonly authorizationDecisionId:string;readonly retentionPolicyIds:readonly string[];readonly legalHoldVerifiedAbsent:true;readonly deletedAt:string;readonly affectedRepresentations:readonly string[];readonly propagationComplete:boolean;readonly policyVersion:string;}
export interface AuditTombstoneStore{save(value:AuditTombstone):void;list():readonly AuditTombstone[];}

export interface AuditPlatformDependencies{readonly records:AuditRecordStore;readonly index:AuditIndexProvider;readonly archive:AuditArchiveProvider;readonly evidence:AuditEvidenceStore;readonly integrity:AuditIntegrityProvider;readonly retention:RetentionPolicyResolver;readonly holds:LegalHoldStore;readonly tombstones:AuditTombstoneStore;readonly events:AuditEvents;readonly diagnostics:AuditDiagnostics;readonly telemetry:AuditTelemetry;readonly now?:()=>Date;}

export class AuditPlatform implements AuditHealth{
 public constructor(private readonly dependencies:AuditPlatformDependencies){}
 public async ingest(request:AuditIngestionRequest):Promise<AuditRecord>{const diagnosticId=`audit:ingest:${request.requestId}`;try{validateIngestion(request,diagnosticId);if(request.lifecycleOrigin==='audit-lifecycle'||(request.derivationDepth??0)>8)throw new AuditError('AUDIT_RECURSION_SUPPRESSED','Audit lifecycle recursion suppressed',diagnosticId);const key=sourceKey(request);const existing=await this.dependencies.records.findBySource(key);if(existing!==undefined){this.dependencies.diagnostics.record({id:diagnosticId,phase:'ingestion',outcome:'duplicate',recordId:existing.id,sourceId:request.source.sourceId,policyVersions:[request.ingestionPolicyVersion]});this.dependencies.telemetry.ingested(true);return existing;}const recordedAt=(this.dependencies.now?.()??new Date()).toISOString();const retention=this.dependencies.retention.resolve(request.retentionRequirements,recordedAt);const base:Omit<AuditRecord,'integrity'>=freeze({id:`audit:${digest(key)}`,type:`audit.${request.action}`,schemaVersion:request.schemaVersion,occurredAt:request.occurredAt,recordedAt,principalId:request.principalId,effectivePrincipalId:request.effectivePrincipalId,action:request.action,resource:copy(request.resource),outcome:request.outcome,scope:copy(request.scope),authorizationDecisionId:request.authorizationDecisionId,policyReferences:[...request.policyReferences],evidenceReferences:[...request.evidenceReferences],categories:[...request.categories],classification:request.classification,attributes:minimize(request.attributes),...optional('executionReference',request.executionReference),correlationId:request.correlationId,causationId:request.causationId,source:copy(request.source),truthStatus:request.truthStatus,siblingSourceIds:[...request.siblingSourceIds],retention,ingestionPolicyVersion:request.ingestionPolicyVersion});const previous=(await this.dependencies.records.list()).at(-1);const integrity=await this.dependencies.integrity.generate(base,previous);const record:AuditRecord=freeze({...base,integrity});await this.dependencies.records.save(record);await this.dependencies.index.index(record);await this.dependencies.events.publish(lifecycle('audit.record.created',request.requestId,record));this.dependencies.diagnostics.record({id:diagnosticId,phase:'ingestion',outcome:'completed',recordId:record.id,sourceId:request.source.sourceId,policyVersions:[request.ingestionPolicyVersion,...retention.policyVersions]});this.dependencies.telemetry.ingested(false);return record;}catch(error){const normalized=normalize(error,diagnosticId);this.dependencies.telemetry.failed(normalized.code);this.dependencies.diagnostics.record({id:diagnosticId,phase:'ingestion',outcome:'failed',sourceId:request.source.sourceId,policyVersions:[request.ingestionPolicyVersion],errorCode:normalized.code});throw normalized;}}
 public async ingestDelivery(delivery:EventDelivery,request:(event:PlatformEvent)=>AuditIngestionRequest):Promise<AuditRecord>{const normalized=request(delivery.event);return this.ingest(freeze({...normalized,source:{...normalized.source,eventId:delivery.event.eventId,deliveryId:delivery.deliveryId}}));}
 public async query(request:AuditQueryRequest):Promise<AuditQueryResult>{enforce(request.authorization,'query',request.scope,`audit:query:${request.id}`);if(request.limit<1||request.limit>1000||Date.parse(request.from)>Date.parse(request.to))throw new AuditError('AUDIT_QUERY_INVALID','Audit query is invalid',`audit:query:${request.id}`);const all=(await this.dependencies.records.list()).filter(record=>authorizedRecord(record,request.authorization)&&record.recordedAt<=request.snapshotAt&&matches(record,request)).sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt)||a.id.localeCompare(b.id));const offset=request.cursor===undefined?0:Number.parseInt(request.cursor,10);const selected=all.slice(offset,offset+request.limit);const views=selected.map(record=>view(record,request.authorization,this.dependencies.now?.()??new Date()));const next=offset+selected.length<all.length?String(offset+selected.length):undefined;this.dependencies.telemetry.queried(views.length);this.dependencies.diagnostics.record({id:`audit:query:${request.id}`,phase:'query',outcome:'completed',policyVersions:[request.policyVersion,request.authorization.policyVersion]});return freeze({queryId:request.id,views,appliedScope:copy(request.scope),...optional('nextCursor',next),snapshotAt:request.snapshotAt,completion:'complete',diagnosticsReference:`audit:query:${request.id}`});}
 public async verify(request:IntegrityVerificationRequest):Promise<IntegrityVerificationResult>{enforce(request.authorization,'verify',request.authorization.scope,`audit:verify:${request.id}`);const records=(await Promise.all(request.recordIds.map(id=>this.dependencies.records.find(id)))).filter((value):value is AuditRecord=>value!==undefined);const result=await this.dependencies.integrity.verify(records,request);this.dependencies.telemetry.verified(result.status);await this.dependencies.events.publish({type:'audit.verified',operationId:request.id,outcome:'completed',tenantId:request.authorization.scope.tenantId,correlationId:request.correlationId,classification:'restricted',origin:'audit-lifecycle',derivationDepth:0});return result;}
 public applyHold(request:LegalHoldRequest):LegalHoldRecord{enforce(request.authorization,'legal-hold-apply',{tenantId:request.scope.tenantId},`audit:hold:${request.id}`);const existing=this.dependencies.holds.get(request.id);if(existing!==undefined)return existing;const value:LegalHoldRecord=freeze({id:request.id,scope:copy(request.scope),reason:request.reason,appliedBy:request.authorization.principalId,appliedAt:request.requestedAt,authorizationDecisionId:request.authorization.decisionId,policyVersion:request.policyVersion,status:'active'});this.dependencies.holds.save(value);void this.dependencies.events.publish({type:'audit.hold.applied',operationId:request.id,outcome:'completed',tenantId:request.scope.tenantId,correlationId:request.id,classification:'restricted',origin:'audit-lifecycle',derivationDepth:0});this.dependencies.telemetry.governance('hold-applied');return value;}
 public releaseHold(id:string,reason:string,at:string,authorization:AuditAuthorizationOutcome):LegalHoldRecord{enforce(authorization,'legal-hold-release',authorization.scope,`audit:hold-release:${id}`);const existing=this.dependencies.holds.get(id);if(existing===undefined)throw new AuditError('AUDIT_HOLD_NOT_FOUND','Legal Hold does not exist',`audit:hold-release:${id}`);if(existing.status==='released')return existing;const released:LegalHoldRecord=freeze({...existing,status:'released',release:{releasedBy:authorization.principalId,releasedAt:at,reason,authorizationDecisionId:authorization.decisionId}});this.dependencies.holds.save(released);void this.dependencies.events.publish({type:'audit.hold.released',operationId:id,outcome:'completed',tenantId:existing.scope.tenantId,correlationId:id,classification:'restricted',origin:'audit-lifecycle',derivationDepth:0});return released;}
 public async archive(recordId:string,authorization:AuditAuthorizationOutcome):Promise<Readonly<{recordId:string;locationReference:string;archivedAt:string}>>{const record=await this.requiredRecord(recordId);enforce(authorization,'archive',record.scope,`audit:archive:${recordId}`);const result=await this.dependencies.archive.archive(record);return freeze({recordId,...result});}
 public reconstruct(id:string,result:AuditQueryResult,at:string):AuditReconstruction{return freeze({id,elements:result.views.map(value=>({recordId:value.recordId,relationship:value.record.truthStatus??'unknown',correlationId:value.record.correlationId??'',causationId:value.record.causationId??null,occurredAt:value.record.occurredAt??''})),generatedAt:at,querySnapshotAt:result.snapshotAt,noExecutionReplay:true});}
 public async evidencePackage(id:string,purpose:string,result:AuditQueryResult,authorization:AuditAuthorizationOutcome,at:string):Promise<AuditEvidencePackage>{enforce(authorization,'evidence',result.appliedScope,`audit:evidence:${id}`);const records=(await Promise.all(result.views.map(value=>this.requiredRecord(value.recordId))));const value:AuditEvidencePackage=freeze({id,purpose,requestingPrincipalId:authorization.principalId,scope:copy(result.appliedScope),sourceRecordReferences:records.map(record=>({id:record.id,schemaVersion:record.schemaVersion,integrityDigest:record.integrity.contentDigest})),redactions:result.views.map(value=>value.redaction),integrityResults:[],policyVersions:unique([authorization.policyVersion,...records.flatMap(record=>record.retention.policyVersions)]),selectionCriteria:{queryId:result.queryId,snapshotAt:result.snapshotAt},packageSchemaVersion:'1',finalizedAt:at,manifestDigest:digest(stable(records.map(record=>({id:record.id,digest:record.integrity.contentDigest})))),diagnosticsReference:`audit:evidence:${id}`});await this.dependencies.evidence.save(value);return value;}
 public async export(request:AuditExportRequest,evidence:AuditEvidencePackage,provider:AuditExportProvider):Promise<AuditExportPackage>{enforce(request.authorization,'export',evidence.scope,`audit:export:${request.id}`);if(!request.destination.encrypted||request.destination.reference.trim()==='')throw new AuditError('AUDIT_EXPORT_DENIED','Export destination is not governed',`audit:export:${request.id}`);try{const result=await provider.export(request,evidence);const value:AuditExportPackage=freeze({id:`export:${request.id}`,evidencePackageId:evidence.id,sourceRecordIds:evidence.sourceRecordReferences.map(record=>record.id),format:request.format,destinationReference:request.destination.reference,classification:request.destination.classification,exportedBy:request.requestingPrincipalId,exportedAt:request.requestedAt,policyVersion:request.policyVersion,...result});await this.dependencies.events.publish({type:'audit.exported',operationId:request.id,outcome:'completed',tenantId:evidence.scope.tenantId,correlationId:request.id,classification:value.classification,origin:'audit-lifecycle',derivationDepth:0});return value;}catch(error){if(error instanceof AuditError)throw error;throw new AuditError('AUDIT_EXPORT_FAILED','Audit export failed',`audit:export:${request.id}`,{cause:error});}}
 public async delete(request:GovernedDeletionRequest):Promise<AuditTombstone>{const record=await this.requiredRecord(request.recordId);enforce(request.authorization,'delete',record.scope,`audit:delete:${request.id}`);const now=Date.parse(request.requestedAt);if(now<Date.parse(record.retention.minimumRetainUntil)||this.dependencies.holds.activeFor(record,request.requestedAt).length>0||request.activeInvestigation||!request.dependencyClearance||record.retention.deletionRestrictions.length>0)throw new AuditError('AUDIT_DELETION_PROHIBITED','Governance prohibits Audit Record deletion',`audit:delete:${request.id}`);const affected=[...await this.dependencies.records.removeGoverned(record.id,request.method),'index','archive','evidence'];await this.dependencies.index.removeGoverned(record.id);await this.dependencies.archive.removeGoverned(record.id);await this.dependencies.evidence.removeRecordReference(record.id);const tombstone:AuditTombstone=freeze({id:`tombstone:${request.id}`,deletedRecordId:record.id,method:request.method,authorizedBy:request.authorization.principalId,authorizationDecisionId:request.authorization.decisionId,retentionPolicyIds:record.retention.effectivePolicyIds,legalHoldVerifiedAbsent:true,deletedAt:request.requestedAt,affectedRepresentations:unique(affected),propagationComplete:true,policyVersion:request.policyVersion});this.dependencies.tombstones.save(tombstone);await this.dependencies.events.publish({type:'audit.deleted',recordReference:record.id,operationId:request.id,outcome:'completed',tenantId:record.scope.tenantId,correlationId:request.id,classification:record.classification,origin:'audit-lifecycle',derivationDepth:0});return tombstone;}
 public async health():Promise<Readonly<{name:'audit';status:'healthy'|'degraded'|'unhealthy';records:number;activeHolds:number;integrityProvider:'healthy'|'degraded'|'unhealthy'}>>{const integrityProvider=await this.dependencies.integrity.health();return freeze({name:'audit',status:integrityProvider==='unhealthy'?'unhealthy':integrityProvider==='degraded'?'degraded':'healthy',records:(await this.dependencies.records.list()).length,activeHolds:0,integrityProvider});}
 private async requiredRecord(id:string):Promise<AuditRecord>{const record=await this.dependencies.records.find(id);if(record===undefined)throw new AuditError('AUDIT_QUERY_INVALID','Audit Record is unavailable',`audit:record:${id}`);return record;}
}

function validateIngestion(request:AuditIngestionRequest,id:string):void{if(request.requestId.trim()===''||request.source.sourceId.trim()===''||request.source.producer.trim()===''||request.principalId.trim()===''||request.action.trim()===''||request.scope.tenantId.trim()===''||request.categories.length===0||!Number.isFinite(Date.parse(request.occurredAt))||request.causationId===request.source.eventId)throw new AuditError('AUDIT_INGESTION_INVALID','Audit ingestion request is invalid',id);if(Object.keys(request.attributes).some(key=>/password|secret|token|credential|private.?key/i.test(key))||Object.values(request.attributes).some(value=>value.length>2048))throw new AuditError('AUDIT_SOURCE_INVALID','Sensitive or unbounded source attributes are prohibited',id);try{JSON.stringify(request);}catch(error){throw new AuditError('AUDIT_SERIALIZATION_FAILED','Audit source is not serializable',id,{cause:error});}}
function sourceKey(request:AuditIngestionRequest):string{return stable({sourceType:request.source.sourceType,sourceId:request.source.sourceId,eventId:request.source.eventId,tenantId:request.scope.tenantId,categories:request.categories,schemaVersion:request.schemaVersion,derivationKey:request.source.derivationKey,derivationPolicyVersion:request.source.derivationPolicyVersion});}
function enforce(value:AuditAuthorizationOutcome,operation:AuditAuthorizationOutcome['operation'],scope:AuditScope,id:string):void{if(!value.authorized||value.state!=='active'||value.operation!==operation)throw new AuditError(operation==='export'?'AUDIT_EXPORT_DENIED':'AUDIT_ACCESS_DENIED','Audit operation is not authorized',id);if(value.scope.tenantId!==scope.tenantId)throw new AuditError('AUDIT_CROSS_TENANT_DENIED','Cross-tenant Audit access denied',id);if(scope.workspaceId!==undefined&&value.scope.workspaceId!==scope.workspaceId||scope.projectId!==undefined&&value.scope.projectId!==scope.projectId)throw new AuditError('AUDIT_ACCESS_DENIED','Audit scope is not authorized',id);}
function authorizedRecord(record:AuditRecord,outcome:AuditAuthorizationOutcome):boolean{const rank=(value:AuditClassification):number=>['public','internal','confidential','restricted'].indexOf(value);return record.scope.tenantId===outcome.scope.tenantId&&(outcome.scope.workspaceId===undefined||record.scope.workspaceId===outcome.scope.workspaceId)&&(outcome.scope.projectId===undefined||record.scope.projectId===outcome.scope.projectId)&&rank(record.classification)<=rank(outcome.maximumClassification);}
function matches(record:AuditRecord,query:AuditQueryRequest):boolean{return Date.parse(record.occurredAt)>=Date.parse(query.from)&&Date.parse(record.occurredAt)<=Date.parse(query.to)&&(query.principalIds.length===0||query.principalIds.includes(record.principalId))&&(query.actions.length===0||query.actions.includes(record.action))&&(query.resourceIds.length===0||query.resourceIds.includes(record.resource.id))&&(query.outcomes.length===0||query.outcomes.includes(record.outcome))&&(query.correlations.length===0||query.correlations.includes(record.correlationId))&&(query.causations.length===0||query.causations.includes(record.causationId))&&(query.categories.length===0||query.categories.some(value=>record.categories.includes(value)))&&(query.truthStatuses.length===0||query.truthStatuses.includes(record.truthStatus));}
function view(record:AuditRecord,outcome:AuditAuthorizationOutcome,at:Date):AuditRecordView{const redacted=new Set(outcome.redactedFields);const value=Object.fromEntries(Object.entries(copy(record)).filter(([key])=>!redacted.has(key)));return freeze({recordId:record.id,record:value,redaction:{policyVersion:outcome.policyVersion,fields:[...redacted],reason:'authorization-restriction',authorizationDecisionId:outcome.decisionId,generatedAt:at.toISOString()},integrity:{status:'verified',contentDigest:record.integrity.contentDigest}});}
function lifecycle(type:AuditLifecycleFact['type'],operationId:string,record:AuditRecord):AuditLifecycleFact{return freeze({type,recordReference:record.id,operationId,outcome:'completed',tenantId:record.scope.tenantId,correlationId:record.correlationId,classification:record.classification,origin:'audit-lifecycle',derivationDepth:0});}
function minimize(value:Readonly<Record<string,string>>):Readonly<Record<string,string>>{return Object.freeze(Object.fromEntries(Object.entries(value).filter(([key])=>!/password|secret|token|credential|private.?key/i.test(key)).map(([key,item])=>[key,item.slice(0,2048)])));}
function normalize(error:unknown,id:string):AuditError{return error instanceof AuditError?error:new AuditError('AUDIT_STORE_UNAVAILABLE',error instanceof Error?error.message:'Audit operation failed',id,{cause:error});}
export function stable(value:unknown):string{return JSON.stringify(sort(value));}
function sort(value:unknown):unknown{if(Array.isArray(value))return value.map(sort);if(typeof value==='object'&&value!==null)return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,sort(item)]));return value;}
export function digest(value:string):string{let result=2166136261;for(const character of value){result^=character.codePointAt(0)??0;result=Math.imul(result,16777619);}return(result>>>0).toString(16).padStart(8,'0');}
function unique<T>(values:readonly T[]):readonly T[]{return freeze([...new Set(values)]);}
function optional<K extends string,V>(key:K,value:V|undefined):Partial<Record<K,V>>{return value===undefined?{}:{[key]:value} as Record<K,V>;}
function copy<T>(value:T):T{return JSON.parse(JSON.stringify(value)) as T;}
export function freeze<T>(value:T):T{if(typeof value==='object'&&value!==null&&!Object.isFrozen(value)){for(const child of Object.values(value))freeze(child);Object.freeze(value);}return value;}

export * from './reference.js';
