import type {AuditArchiveProvider,AuditDiagnostic,AuditDiagnostics,AuditEvidencePackage,AuditEvidenceStore,AuditErrorCode,AuditEvents,AuditExportProvider,AuditExportRequest,AuditIndexProvider,AuditIntegrityMetadata,AuditIntegrityProvider,AuditLifecycleFact,AuditRecord,AuditRecordStore,AuditRetentionMetadata,AuditRetentionRequirement,AuditTelemetry,AuditTombstone,AuditTombstoneStore,DeletionMethod,IntegrityVerificationRequest,IntegrityVerificationResult,LegalHoldRecord,LegalHoldStore,RetentionPolicyResolver,VerificationStatus} from './index.js';
import {digest,freeze,stable} from './index.js';

export class InMemoryAuditRecordStore implements AuditRecordStore{readonly #records=new Map<string,AuditRecord>();readonly #source=new Map<string,string>();public async save(record:AuditRecord):Promise<void>{this.#records.set(record.id,record);this.#source.set(recordSourceKey(record),record.id);}public async find(id:string):Promise<AuditRecord|undefined>{return this.#records.get(id);}public async findBySource(key:string):Promise<AuditRecord|undefined>{const id=this.#source.get(key);return id===undefined?undefined:this.#records.get(id);}public async list():Promise<readonly AuditRecord[]>{return freeze([...this.#records.values()]);}public async removeGoverned(id:string,_method:DeletionMethod):Promise<readonly string[]>{this.#records.delete(id);for(const[key,value]of this.#source)if(value===id)this.#source.delete(key);return['record-store'];}public unsafeReplaceForVerification(record:AuditRecord):void{this.#records.set(record.id,record);}}
export class InMemoryAuditIndex implements AuditIndexProvider{readonly ids=new Set<string>();public async index(record:AuditRecord):Promise<void>{this.ids.add(record.id);}public async removeGoverned(id:string):Promise<void>{this.ids.delete(id);}}
export class InMemoryAuditArchive implements AuditArchiveProvider{readonly records=new Map<string,AuditRecord>();public async archive(record:AuditRecord):Promise<Readonly<{locationReference:string;archivedAt:string}>>{this.records.set(record.id,record);return freeze({locationReference:`archive:${record.id}`,archivedAt:'2026-08-06T00:00:00.000Z'});}public async removeGoverned(id:string):Promise<void>{this.records.delete(id);}}
export class InMemoryAuditEvidenceStore implements AuditEvidenceStore{readonly packages=new Map<string,AuditEvidencePackage>();public async save(value:AuditEvidencePackage):Promise<void>{this.packages.set(value.id,value);}public async removeRecordReference(id:string):Promise<void>{for(const[key,value]of this.packages)if(value.sourceRecordReferences.some(record=>record.id===id))this.packages.delete(key);}}
export class InMemoryLegalHoldStore implements LegalHoldStore{readonly #values=new Map<string,LegalHoldRecord>();public save(value:LegalHoldRecord):void{this.#values.set(value.id,value);}public activeFor(record:AuditRecord,_at:string):readonly LegalHoldRecord[]{return freeze([...this.#values.values()].filter(value=>value.status==='active'&&value.scope.tenantId===record.scope.tenantId&&(value.scope.recordIds.length===0||value.scope.recordIds.includes(record.id))&&(value.scope.correlationIds.length===0||value.scope.correlationIds.includes(record.correlationId))));}public get(id:string):LegalHoldRecord|undefined{return this.#values.get(id);}}
export class InMemoryAuditTombstones implements AuditTombstoneStore{readonly values:AuditTombstone[]=[];public save(value:AuditTombstone):void{this.values.push(value);}public list():readonly AuditTombstone[]{return freeze([...this.values]);}}
export class DeterministicRetentionResolver implements RetentionPolicyResolver{public resolve(requirements:readonly AuditRetentionRequirement[],startsAt:string):AuditRetentionMetadata{if(requirements.length===0)throw new Error('Retention policy is required');const mandatory=requirements.filter(value=>value.mandatory);const effective=mandatory.length>0?mandatory:requirements;const longest=[...effective].sort((a,b)=>b.minimumDays-a.minimumDays||a.policyId.localeCompare(b.policyId))[0];if(longest===undefined)throw new Error('Retention policy is unavailable');const categories:readonly AuditRetentionRequirement['category'][]=['operational','security','administrative','compliance-controlled','legal-hold-eligible','permanent'];const category=[...effective].sort((a,b)=>categories.indexOf(b.category)-categories.indexOf(a.category))[0]?.category??longest.category;const minimumRetainUntil=addDays(startsAt,longest.minimumDays);const maximums=effective.map(value=>value.maximumDays).filter((value):value is number=>value!==undefined);const expiresAt=category==='permanent'||maximums.length===0?undefined:addDays(startsAt,Math.max(...maximums));return freeze({effectivePolicyIds:effective.map(value=>value.policyId).sort(),category,startsAt,minimumRetainUntil,...(expiresAt===undefined?{}:{expiresAt}),archivalEligible:effective.every(value=>value.archivalEligible),deletionRestrictions:[...new Set(effective.flatMap(value=>value.deletionRestrictions))].sort(),policyVersions:[...new Set(effective.map(value=>value.policyVersion))].sort(),resolutionVersion:'retention-resolution-1'});}}
export class DeterministicHashChainIntegrityProvider implements AuditIntegrityProvider{public async generate(record:Omit<AuditRecord,'integrity'>,previous?:AuditRecord):Promise<AuditIntegrityMetadata>{return freeze({contentDigest:digest(stable(record)),...(previous===undefined?{}:{previousRecordDigest:previous.integrity.contentDigest}),algorithmReference:'agentforge-reference-digest',algorithmVersion:'1',generatedAt:record.recordedAt,guarantee:'reference-tamper-evidence'});}public async verify(records:readonly AuditRecord[],request:IntegrityVerificationRequest):Promise<IntegrityVerificationResult>{const found=new Map(records.map(value=>[value.id,value]));const missing=request.recordIds.filter(id=>!found.has(id));const failed:string[]=[];const chain:string[]=[];for(let index=0;index<records.length;index++){const record=records[index];if(record===undefined)continue;const{integrity,...base}=record;if(digest(stable(base))!==integrity.contentDigest)failed.push(record.id);const previous=records[index-1];if(previous!==undefined&&integrity.previousRecordDigest!==previous.integrity.contentDigest)chain.push(record.id);}const status:VerificationStatus=missing.length>0||failed.length>0||chain.length>0?(records.length===0?'unavailable':failed.length+chain.length===records.length?'failed':'partial'):'verified';return freeze({id:request.id,status,verifiedRecordIds:records.filter(value=>!failed.includes(value.id)&&!chain.includes(value.id)).map(value=>value.id),failedRecordIds:failed,missingRecordIds:missing,chainBreakRecordIds:chain,algorithmReferences:[...new Set(records.map(value=>value.integrity.algorithmReference))],policyVersion:request.policyVersion,diagnosticsReference:`audit:verify:${request.id}`,verifiedAt:'2026-08-06T00:00:00.000Z'});}public async health():Promise<'healthy'>{return'healthy';}}
export class JsonReferenceAuditExportProvider implements AuditExportProvider{public async export(request:AuditExportRequest,evidence:AuditEvidencePackage):Promise<Readonly<{providerReference:string;representationDigest:string}>>{return freeze({providerReference:`export-provider:${request.id}`,representationDigest:digest(stable({format:request.format,destination:request.destination.reference,evidenceId:evidence.id,records:evidence.sourceRecordReferences}))});}}
export class InMemoryAuditEvents implements AuditEvents{readonly facts:AuditLifecycleFact[]=[];public async publish(value:AuditLifecycleFact):Promise<void>{this.facts.push(freeze({...value}));}}
export class InMemoryAuditDiagnostics implements AuditDiagnostics{readonly values:AuditDiagnostic[]=[];public record(value:AuditDiagnostic):void{this.values.push(freeze({...value}));}public list():readonly AuditDiagnostic[]{return freeze([...this.values]);}}
export class InMemoryAuditTelemetry implements AuditTelemetry{readonly counters=new Map<string,number>();public ingested(duplicate:boolean):void{this.#add(duplicate?'ingestion:duplicate':'ingestion:created');}public queried(count:number):void{this.#add('query:records',count);}public verified(status:VerificationStatus):void{this.#add(`verification:${status}`);}public governance(operation:string):void{this.#add(`governance:${operation}`);}public failed(code:AuditErrorCode):void{this.#add(`failure:${code}`);}#add(key:string,value=1):void{this.counters.set(key,(this.counters.get(key)??0)+value);}}

function recordSourceKey(record:AuditRecord):string{return stable({sourceType:record.source.sourceType,sourceId:record.source.sourceId,eventId:record.source.eventId,tenantId:record.scope.tenantId,categories:record.categories,schemaVersion:record.schemaVersion,derivationKey:record.source.derivationKey,derivationPolicyVersion:record.source.derivationPolicyVersion});}
function addDays(value:string,days:number):string{return new Date(Date.parse(value)+days*86_400_000).toISOString();}
