import type { ExecutionContext } from '@agentforge/foundation';
import type { ExecutionPlan } from '@agentforge/planning';
import type { WorkflowPort } from '@agentforge/runtime';

export type WorkflowStatus='created'|'initialized'|'running'|'waiting'|'resumed'|'completing'|'completed'|'failed'|'cancelled';
export type NodeStatus='pending'|'ready'|'executing'|'waiting'|'completed'|'failed'|'cancelled';
export type WorkflowNodeKind='capability'|'decision'|'approval'|'loop'|'merge'|'completion';
export interface WorkflowNode {readonly id:string;readonly kind:WorkflowNodeKind;readonly capability?:string;readonly dependencies:readonly string[];readonly branch?:Readonly<Record<string,readonly string[]>>;readonly maxIterations?:number;}
export interface WorkflowGraph {readonly id:string;readonly entryNodeId:string;readonly exitNodeIds:readonly string[];readonly nodes:readonly WorkflowNode[];}
export interface NodeExecutionContract {readonly workflowId:string;readonly nodeId:string;readonly kind:WorkflowNodeKind;readonly capability?:string;}
export interface WorkflowSnapshot {readonly workflowId:string;readonly status:WorkflowStatus;readonly nodeStates:Readonly<Record<string,NodeStatus>>;readonly branchOutcomes:Readonly<Record<string,string>>;readonly loopIterations:Readonly<Record<string,number>>;readonly history:readonly WorkflowStatus[];}
export interface WorkflowFact {readonly type:string;readonly workflowId:string;readonly executionId:string;readonly occurredAt:string;}
export interface WorkflowEventPublisher {publish(fact:WorkflowFact):Promise<void>;}
export interface WorkflowTelemetry {transition(workflowId:string,status:WorkflowStatus):void;node(workflowId:string,nodeId:string,status:NodeStatus):void;}
export interface WorkflowSnapshotStore {store(snapshot:WorkflowSnapshot):Promise<void>;}
export type WorkflowErrorCode='WORKFLOW_INVALID_GRAPH'|'WORKFLOW_INVALID_TRANSITION'|'WORKFLOW_NODE_NOT_ELIGIBLE'|'WORKFLOW_APPROVAL_REQUIRED'|'WORKFLOW_ABORTED';
export class WorkflowError extends Error {public constructor(public readonly code:WorkflowErrorCode,message:string){super(message);this.name='WorkflowError';}}

const allowed:Readonly<Record<WorkflowStatus,readonly WorkflowStatus[]>>={created:['initialized'],initialized:['running'],running:['waiting','completing','failed','cancelled'],waiting:['resumed','cancelled'],resumed:['running'],completing:['completed'],completed:[],failed:[],cancelled:[]};
export class WorkflowEngine {
  readonly #nodeStates=new Map<string,NodeStatus>();readonly #branches=new Map<string,string>();readonly #loops=new Map<string,number>();readonly #history:WorkflowStatus[]=['created'];#status:WorkflowStatus='created';
  public constructor(public readonly graph:WorkflowGraph,private readonly context:ExecutionContext,private readonly events:WorkflowEventPublisher,private readonly telemetry:WorkflowTelemetry,private readonly snapshots:WorkflowSnapshotStore,private readonly now:()=>Date=()=>new Date()){validateGraph(graph);deepFreeze(graph);for(const node of graph.nodes)this.#nodeStates.set(node.id,'pending');}
  public async initialize():Promise<void>{await this.#transition('initialized');await this.#transition('running');this.#refresh();}
  public eligible():readonly NodeExecutionContract[]{if(this.#status!=='running')return Object.freeze([]);this.#refresh();return Object.freeze(this.graph.nodes.filter(node=>this.#nodeStates.get(node.id)==='ready').map(node=>deepFreeze({workflowId:this.graph.id,nodeId:node.id,kind:node.kind,...(node.capability===undefined?{}:{capability:node.capability})})));}
  public async start(nodeId:string):Promise<void>{const node=this.#required(nodeId);if(this.#nodeStates.get(nodeId)!=='ready')throw new WorkflowError('WORKFLOW_NODE_NOT_ELIGIBLE',nodeId);if(node.kind==='approval'){this.#nodeStates.set(nodeId,'waiting');await this.#transition('waiting');}else{this.#nodeStates.set(nodeId,'executing');await this.#recordNode(nodeId,'executing');}}
  public async complete(nodeId:string,outcome?:string):Promise<void>{const node=this.#required(nodeId);if(this.#nodeStates.get(nodeId)!=='executing')throw new WorkflowError('WORKFLOW_NODE_NOT_ELIGIBLE',nodeId);if(node.kind==='decision'&&outcome!==undefined)this.#branches.set(nodeId,outcome);if(node.kind==='loop'){const next=(this.#loops.get(nodeId)??0)+1;if(next>(node.maxIterations??1))throw new WorkflowError('WORKFLOW_INVALID_TRANSITION','Loop bound exceeded');this.#loops.set(nodeId,next);}this.#nodeStates.set(nodeId,'completed');await this.#recordNode(nodeId,'completed');this.#refresh();if(this.graph.exitNodeIds.every(id=>this.#nodeStates.get(id)==='completed')){await this.#transition('completing');await this.#transition('completed');}}
  public async resumeApproval(nodeId:string,approved:boolean):Promise<void>{const node=this.#required(nodeId);if(node.kind!=='approval'||this.#nodeStates.get(nodeId)!=='waiting'||this.#status!=='waiting')throw new WorkflowError('WORKFLOW_APPROVAL_REQUIRED',nodeId);this.#branches.set(nodeId,approved?'approved':'rejected');this.#nodeStates.set(nodeId,'completed');await this.#transition('resumed');await this.#transition('running');this.#refresh();}
  public snapshot():WorkflowSnapshot{return deepFreeze({workflowId:this.graph.id,status:this.#status,nodeStates:Object.fromEntries(this.#nodeStates),branchOutcomes:Object.fromEntries(this.#branches),loopIterations:Object.fromEntries(this.#loops),history:[...this.#history]});}
  #refresh():void{for(const node of this.graph.nodes)if(this.#nodeStates.get(node.id)==='pending'&&node.dependencies.every(id=>this.#nodeStates.get(id)==='completed'))this.#nodeStates.set(node.id,'ready');}
  async #transition(next:WorkflowStatus):Promise<void>{if(!allowed[this.#status].includes(next))throw new WorkflowError('WORKFLOW_INVALID_TRANSITION',`${this.#status} -> ${next}`);this.#status=next;this.#history.push(next);this.telemetry.transition(this.graph.id,next);await this.events.publish(Object.freeze({type:`workflow.${next}`,workflowId:this.graph.id,executionId:this.context.executionId,occurredAt:this.now().toISOString()}));await this.snapshots.store(this.snapshot());}
  async #recordNode(id:string,status:NodeStatus):Promise<void>{this.telemetry.node(this.graph.id,id,status);await this.events.publish(Object.freeze({type:`workflow.node.${status}`,workflowId:this.graph.id,executionId:this.context.executionId,occurredAt:this.now().toISOString()}));await this.snapshots.store(this.snapshot());}
  #required(id:string):WorkflowNode{const node=this.graph.nodes.find(item=>item.id===id);if(node===undefined)throw new WorkflowError('WORKFLOW_INVALID_GRAPH',`Unknown node ${id}`);return node;}
}

export class ExecutionPlanWorkflowAdapter {public fromPlan(plan:ExecutionPlan):WorkflowGraph{const nodes=plan.tasks.map(task=>deepFreeze({id:task.id,kind:'capability' as const,capability:task.capability,dependencies:Object.freeze([...task.dependencies])}));return deepFreeze({id:plan.workflow.id,entryNodeId:nodes.find(node=>node.dependencies.length===0)?.id??'',exitNodeIds:Object.freeze(nodes.filter(node=>!nodes.some(other=>other.dependencies.includes(node.id))).map(node=>node.id)),nodes:Object.freeze(nodes)});}}
export class RuntimeWorkflowAdapter implements WorkflowPort {public constructor(private readonly factory:(graph:WorkflowGraph,context:ExecutionContext)=>WorkflowEngine,private readonly plans=new ExecutionPlanWorkflowAdapter()){}public async execute(plan:unknown,context:ExecutionContext,signal:AbortSignal):Promise<{readonly snapshot:WorkflowSnapshot;readonly eligible:readonly NodeExecutionContract[]}>{if(signal.aborted)throw new WorkflowError('WORKFLOW_ABORTED','Workflow aborted');if(!isPlan(plan))throw new WorkflowError('WORKFLOW_INVALID_GRAPH','Runtime input is not an ExecutionPlan');const engine=this.factory(this.plans.fromPlan(plan),context);await engine.initialize();return deepFreeze({snapshot:engine.snapshot(),eligible:engine.eligible()});}}
export class InMemoryWorkflowFacts implements WorkflowEventPublisher {readonly facts:WorkflowFact[]=[];public async publish(fact:WorkflowFact):Promise<void>{this.facts.push(fact);}}
export class InMemoryWorkflowSnapshots implements WorkflowSnapshotStore {readonly items:WorkflowSnapshot[]=[];public async store(snapshot:WorkflowSnapshot):Promise<void>{this.items.push(snapshot);}}
export class NoopWorkflowTelemetry implements WorkflowTelemetry {public transition(_id:string,_status:WorkflowStatus):void{}public node(_id:string,_node:string,_status:NodeStatus):void{}}

function validateGraph(graph:WorkflowGraph):void{const ids=new Set(graph.nodes.map(node=>node.id));if(graph.nodes.length===0||!ids.has(graph.entryNodeId)||graph.exitNodeIds.length===0||graph.exitNodeIds.some(id=>!ids.has(id))||graph.nodes.filter(node=>node.dependencies.length===0).length!==1)throw new WorkflowError('WORKFLOW_INVALID_GRAPH','Entry or exit is invalid');const visiting=new Set<string>();const visited=new Set<string>();const visit=(id:string):void=>{if(visiting.has(id))throw new WorkflowError('WORKFLOW_INVALID_GRAPH','Cycle detected');if(visited.has(id))return;visiting.add(id);const node=graph.nodes.find(item=>item.id===id);if(node===undefined)throw new WorkflowError('WORKFLOW_INVALID_GRAPH',`Missing ${id}`);for(const dependency of node.dependencies)visit(dependency);visiting.delete(id);visited.add(id);};for(const id of ids)visit(id);const reachable=new Set<string>([graph.entryNodeId]);let changed=true;while(changed){changed=false;for(const node of graph.nodes)if(node.dependencies.some(id=>reachable.has(id))&&!reachable.has(node.id)){reachable.add(node.id);changed=true;}}if(reachable.size!==ids.size)throw new WorkflowError('WORKFLOW_INVALID_GRAPH','Unreachable node');}
function isPlan(value:unknown):value is ExecutionPlan{return typeof value==='object'&&value!==null&&'validation'in value&&'tasks'in value&&'workflow'in value;}
function deepFreeze<T>(value:T):T{if(typeof value==='object'&&value!==null&&!Object.isFrozen(value)){for(const child of Object.values(value))deepFreeze(child);Object.freeze(value);}return value;}

