/* eslint-disable @typescript-eslint/explicit-function-return-type */
import type { ExecutionContext } from '@agentprodready/foundation';
import { describe,expect,it,vi } from 'vitest';
import { ExecutionPlanWorkflowAdapter,InMemoryWorkflowFacts,InMemoryWorkflowSnapshots,NoopWorkflowTelemetry,RuntimeWorkflowAdapter,WorkflowEngine,WorkflowError,type WorkflowGraph } from './index.js';

const context:ExecutionContext=Object.freeze({executionId:'e1',correlationId:'c1',startedAt:'x',configurationVersion:'v',securityContextId:'s',attributes:Object.freeze({})});
const graph:WorkflowGraph={id:'w',entryNodeId:'a',exitNodeIds:['d'],nodes:[{id:'a',kind:'capability',capability:'start',dependencies:[]},{id:'b',kind:'capability',capability:'left',dependencies:['a']},{id:'c',kind:'capability',capability:'right',dependencies:['a']},{id:'d',kind:'merge',dependencies:['b','c']}]};
function fixture(value:WorkflowGraph=structuredClone(graph)){const events=new InMemoryWorkflowFacts();const snapshots=new InMemoryWorkflowSnapshots();const telemetry={transition:vi.fn(),node:vi.fn()};return{engine:new WorkflowEngine(value,context,events,telemetry,snapshots,()=>new Date('2026-08-06')),events,snapshots,telemetry};}

describe('WorkflowEngine',()=>{
 it('interprets an immutable graph using explicit dependencies and parallel eligibility',async()=>{const f=fixture();await f.engine.initialize();expect(f.engine.eligible().map(x=>x.nodeId)).toEqual(['a']);await f.engine.start('a');await f.engine.complete('a');expect(f.engine.eligible().map(x=>x.nodeId)).toEqual(['b','c']);expect(Object.isFrozen(f.engine.graph)).toBe(true);expect(Object.isFrozen(f.engine.snapshot())).toBe(true);});
 it('centrally completes workflow state and emits facts and telemetry',async()=>{const f=fixture();await f.engine.initialize();for(const id of ['a','b','c','d']){await f.engine.start(id);await f.engine.complete(id);}expect(f.engine.snapshot().status).toBe('completed');expect(f.engine.snapshot().history).toEqual(['created','initialized','running','completing','completed']);expect(f.events.facts.at(-1)?.type).toBe('workflow.completed');expect(f.telemetry.transition).toHaveBeenCalled();expect(f.snapshots.items.length).toBeGreaterThan(1);});
 it('pauses and resumes approval without changing graph',async()=>{const approval:WorkflowGraph={id:'approval',entryNodeId:'approve',exitNodeIds:['done'],nodes:[{id:'approve',kind:'approval',dependencies:[]},{id:'done',kind:'completion',dependencies:['approve']}]};const f=fixture(approval);await f.engine.initialize();await f.engine.start('approve');expect(f.engine.snapshot().status).toBe('waiting');await f.engine.resumeApproval('approve',true);expect(f.engine.eligible().map(x=>x.nodeId)).toEqual(['done']);expect(f.engine.snapshot().branchOutcomes.approve).toBe('approved');});
 it('supports branches and bounded loop semantics structurally',async()=>{const special:WorkflowGraph={id:'special',entryNodeId:'decision',exitNodeIds:['loop'],nodes:[{id:'decision',kind:'decision',dependencies:[],branch:{yes:['loop']}},{id:'loop',kind:'loop',dependencies:['decision'],maxIterations:1}]};const f=fixture(special);await f.engine.initialize();await f.engine.start('decision');await f.engine.complete('decision','yes');await f.engine.start('loop');await f.engine.complete('loop');expect(f.engine.snapshot().branchOutcomes.decision).toBe('yes');expect(f.engine.snapshot().loopIterations.loop).toBe(1);});
 it('rejects cyclic and unreachable definitions',()=>{const invalid:WorkflowGraph={id:'bad',entryNodeId:'a',exitNodeIds:['b'],nodes:[{id:'a',kind:'capability',dependencies:['b']},{id:'b',kind:'completion',dependencies:['a']}]};expect(()=>fixture(invalid)).toThrowError(WorkflowError);});
 it('adapts validated plans to Runtime without executing business work',async()=>{const plan={planId:'p',objective:'x',goal:{statement:'x'},intent:{name:'x',outcome:'x'},strategy:'single-step' as const,requiredCapabilities:[{capability:'x',constraints:{}}],tasks:[{id:'t',description:'x',capability:'x',dependencies:[],optional:false}],workflow:{id:'w',source:'generated' as const,taskIds:['t']},decisionPoints:[],validation:{valid:true as const,checkedAt:'x'},optimization:{removedTaskIds:[],originalTaskCount:1,optimizedTaskCount:1},metadata:{plannerVersion:'x',createdAt:'x',executionId:'e1',correlationId:'c1'}};const factory=vi.fn((definition:WorkflowGraph,ctx:ExecutionContext)=>new WorkflowEngine(definition,ctx,new InMemoryWorkflowFacts(),new NoopWorkflowTelemetry(),new InMemoryWorkflowSnapshots()));const adapter=new RuntimeWorkflowAdapter(factory,new ExecutionPlanWorkflowAdapter());const result=await adapter.execute(plan,context,new AbortController().signal);expect(result.eligible).toEqual([{workflowId:'w',nodeId:'t',kind:'capability',capability:'x'}]);expect(factory).toHaveBeenCalledOnce();});
});
