import type { HealthResult } from '@agentforge/foundation';
import type { NormalizedToolResult,ToolAdapter,ToolAdapterResolver,ToolDiagnostic,ToolDiagnostics,ToolEventPublisher,ToolFact,ToolTelemetry } from '../contracts/tool.js';
interface PrivateExternalRequest {readonly operation:string;readonly payload:string;}
interface PrivateExternalResponse {readonly body:string;readonly statusCode:200;}
export class ReferenceToolAdapter implements ToolAdapter {public readonly id='reference-tool';public async invoke(request:Parameters<ToolAdapter['invoke']>[0]):Promise<NormalizedToolResult>{const external:PrivateExternalRequest={operation:request.binding.capability,payload:JSON.stringify(request.parameters)};const response:PrivateExternalResponse={body:external.payload,statusCode:200};return{requestId:request.requestId,status:'completed',data:JSON.parse(response.body) as unknown,tool:{id:request.binding.implementationId,version:request.binding.implementationVersion,sideEffect:'read-only',idempotency:'idempotent'},execution:{executionId:request.context.executionId,correlationId:request.context.correlationId,...(request.idempotencyKey===undefined?{}:{idempotencyKey:request.idempotencyKey})},validation:{valid:true,contractId:request.binding.implementationId,contractVersion:request.binding.implementationVersion,checkedFields:[]},diagnosticId:`tool:${request.requestId}`,metadata:{transportStatus:String(response.statusCode)}};}public async health():Promise<HealthResult>{return{name:this.id,status:'healthy'};}}
export class FactoryToolAdapterResolver implements ToolAdapterResolver {readonly #items=new Map<string,()=>Promise<ToolAdapter>>();public bind(id:string,factory:()=>Promise<ToolAdapter>):void{this.#items.set(id,factory);}public async resolve(binding:Parameters<ToolAdapterResolver['resolve']>[0]):Promise<ToolAdapter>{const factory=this.#items.get(binding.implementationId);if(factory===undefined)throw new TypeError(`No Composition tool binding: ${binding.implementationId}`);return await factory();}}
export class InMemoryToolDiagnostics implements ToolDiagnostics {readonly #items=new Map<string,ToolDiagnostic>();public record(value:ToolDiagnostic):void{this.#items.set(value.id,value);}public get(id:string):ToolDiagnostic|undefined{return this.#items.get(id);}public list():readonly ToolDiagnostic[]{return Object.freeze([...this.#items.values()]);}}
export class InMemoryToolEvents implements ToolEventPublisher {readonly facts:ToolFact[]=[];public async publish(value:ToolFact):Promise<void>{this.facts.push(value);}}
export class NoopToolTelemetry implements ToolTelemetry {public completed(_id:string,_duration:number):void{}public failed(_id:string,_code:Parameters<ToolTelemetry['failed']>[1],_duration:number):void{}}
