/* eslint-disable @typescript-eslint/explicit-function-return-type */
import type { ExecutionContext } from '@agentprodready/foundation';
import { describe,expect,it,vi } from 'vitest';
import { CatalogOrGeneratedWorkflowPlanner,DeduplicatingPlanOptimizer,InMemoryPlanningEventPublisher,InMemoryWorkflowCatalog,ObjectiveGoalAnalyzer,ObjectiveIntentAnalyzer,PlanningEngine,PlanningError,RuntimePlanningAdapter,SequentialTaskDecomposer,StrictPlanValidator,TaskCapabilityPlanner,TaskStrategySelector } from '../index.js';

const context:ExecutionContext=Object.freeze({executionId:'e1',correlationId:'c1',startedAt:'2026-08-06T00:00:00.000Z',configurationVersion:'v1',securityContextId:'s1',attributes:Object.freeze({})});
function fixture(overrides:Record<string,unknown>={}){const events=new InMemoryPlanningEventPublisher();const telemetry={started:vi.fn(),completed:vi.fn(),failed:vi.fn()};const dependencies={goals:new ObjectiveGoalAnalyzer(),intents:new ObjectiveIntentAnalyzer(),tasks:new SequentialTaskDecomposer(),capabilities:new TaskCapabilityPlanner(),strategies:new TaskStrategySelector(),workflows:new CatalogOrGeneratedWorkflowPlanner(),catalog:new InMemoryWorkflowCatalog(),optimizer:new DeduplicatingPlanOptimizer(),validator:new StrictPlanValidator(),events,telemetry,now:()=>new Date('2026-08-06T00:00:00.000Z'),...overrides};return{engine:new PlanningEngine(dependencies),events,telemetry};}

describe('PlanningEngine',()=>{
  it('transforms objectives into deeply immutable provider-neutral plans',async()=>{const f=fixture();const plan=await f.engine.createPlan({objective:'retrieve documents then summarize',context});expect(plan.tasks).toHaveLength(2);expect(plan.requiredCapabilities.map(x=>x.capability)).toEqual(['retrieve.documents','summarize']);expect(JSON.stringify(plan)).not.toMatch(/providerId|timeout|retry/iu);expect(Object.isFrozen(plan)).toBe(true);expect(Object.isFrozen(plan.tasks)).toBe(true);expect(()=>{(plan.tasks as unknown as PlannedTaskHack[]).push({});}).toThrow();expect(f.events.facts().map(x=>x.type)).toEqual(['planning.started','planning.completed']);expect(f.telemetry.completed).toHaveBeenCalledWith('e1',expect.any(Number),2);});
  it('selects an existing workflow when the catalog matches',async()=>{const workflow=Object.freeze({id:'known',source:'catalog' as const,taskIds:Object.freeze(['task-1'])});const f=fixture({catalog:new InMemoryWorkflowCatalog([{objective:'summarize',workflow}])});expect((await f.engine.createPlan({objective:'summarize',context})).workflow).toBe(workflow);});
  it('generates a deterministic workflow when none exists',async()=>{const f=fixture();const first=await f.engine.createPlan({objective:'translate',context});const second=await f.engine.createPlan({objective:'translate',context});expect(first.workflow).toEqual(second.workflow);expect(first.workflow.source).toBe('generated');});
  it('optimizes duplicate tasks without changing objective or intent',async()=>{const duplicate=Object.freeze({id:'task-2',description:'summarize',capability:'summarize',dependencies:Object.freeze([]),optional:false});const f=fixture({tasks:{decompose:()=>Object.freeze([{...duplicate,id:'task-1'},duplicate])}});const plan=await f.engine.createPlan({objective:'summarize',context});expect(plan.tasks).toHaveLength(1);expect(plan.objective).toBe('summarize');expect(plan.intent.outcome).toBe('summarize');expect(plan.optimization.removedTaskIds).toEqual(['task-2']);});
  it('rejects invalid graphs before a plan reaches Runtime',async()=>{const cyclic=Object.freeze([{id:'a',description:'a',capability:'a',dependencies:Object.freeze(['b']),optional:false},{id:'b',description:'b',capability:'b',dependencies:Object.freeze(['a']),optional:false}]);const f=fixture({tasks:{decompose:()=>cyclic}});await expect(f.engine.createPlan({objective:'cycle',context})).rejects.toMatchObject({code:'PLANNING_DEPENDENCY_CYCLE'});expect(f.telemetry.failed).toHaveBeenCalledOnce();expect(f.events.facts().at(-1)?.type).toBe('planning.failed');});
  it('implements Runtime PlanningPort and honors cancellation',async()=>{const adapter=new RuntimePlanningAdapter(fixture().engine);const signal=new AbortController().signal;const plan=await adapter.plan({objective:'review code'},context,signal);expect(plan.validation.valid).toBe(true);const controller=new AbortController();controller.abort();await expect(adapter.plan('never plan',context,controller.signal)).rejects.toMatchObject({code:'PLANNING_ABORTED'});});
  it('rejects blank objectives',async()=>{await expect(fixture().engine.createPlan({objective:' ',context})).rejects.toBeInstanceOf(PlanningError);});
});
type PlannedTaskHack=Record<string,unknown>;


