import type { ExecutionContext,SecurityContextReference } from '@agentforge/foundation';
import type { PluginPermissionAuthorizer } from '@agentforge/plugin-framework';
import type { SecurityAuthorizationPort } from '@agentforge/runtime';

export type PrincipalType='human'|'agent'|'service'|'workload'|'plugin'|'tool'|'external-system'|'administrator'|'anonymous';
export type AuthenticationStrength='anonymous'|'single-factor'|'multi-factor'|'hardware-backed';
export type SecurityAction='read'|'create'|'update'|'delete'|'execute'|'invoke'|'approve'|'publish'|'configure'|'delegate'|'administer'|'export'|'retrieve'|'consolidate'|'evaluate'|'install'|'activate'|'disable';
export type ResourceType='tenant'|'workspace'|'project'|'workflow'|'agent'|'tool'|'knowledge-source'|'knowledge-record'|'memory-record'|'prompt-package'|'evaluation-result'|'plugin'|'provider'|'configuration'|'secret-reference'|'api-operation'|'administrative-operation'|'capability';
export type AuthorizationOutcome='permit'|'deny'|'conditional-permit'|'not-applicable'|'indeterminate';
export interface AuthenticationEvidence {readonly evidenceId:string;readonly subject:string;readonly issuerReference:string;readonly method:string;readonly strength:AuthenticationStrength;readonly authenticatedAt:string;readonly expiresAt:string;readonly sessionReference:string;readonly claims:Readonly<Record<string,string|readonly string[]>>;readonly version:string;}
export interface AgentAuthority {readonly initiatingPrincipalId:string;readonly allowedCapabilities:readonly string[];readonly allowedTools:readonly string[];readonly executionRestrictions:readonly string[];readonly delegationIds:readonly string[];}
export interface Principal {readonly id:string;readonly type:PrincipalType;readonly identitySource:string;readonly tenantId:string;readonly workspaceIds:readonly string[];readonly projectIds:readonly string[];readonly roles:readonly string[];readonly claims:Readonly<Record<string,string|readonly string[]>>;readonly permissions:readonly string[];readonly securityLabels:readonly string[];readonly authenticationStrength:AuthenticationStrength;readonly sessionReference:string;readonly evidenceId:string;readonly modelVersion:string;readonly agentAuthority?:AgentAuthority;}
export interface IdentityNormalizationPolicy {readonly version:string;readonly principalTypeClaim:string;readonly tenantClaim:string;readonly workspaceClaim:string;readonly projectClaim:string;readonly rolesClaim:string;readonly permissionsClaim:string;readonly labelsClaim:string;}
export interface PrincipalNormalizer {normalize(evidence:AuthenticationEvidence,policy:IdentityNormalizationPolicy):Principal;}
export interface ResourceReference {readonly id:string;readonly type:ResourceType;readonly tenantId:string;readonly workspaceId?:string;readonly projectId?:string;readonly classification:'public'|'internal'|'confidential'|'restricted'|'regulated'|'tenant-private'|'user-private'|'agent-private';readonly securityLabels:readonly string[];readonly parentReference?:string;readonly version:string;readonly metadata:Readonly<Record<string,string>>;}
export interface DelegationGrant {readonly id:string;readonly delegatingPrincipalId:string;readonly receivingPrincipalId:string;readonly actions:readonly SecurityAction[];readonly resourceTypes:readonly ResourceType[];readonly resourceIds:readonly string[];readonly tenantId:string;readonly workspaceIds:readonly string[];readonly projectIds:readonly string[];readonly conditions:readonly SecurityCondition[];readonly restrictions:readonly string[];readonly parentDelegationId?:string;readonly depth:number;readonly maximumDepth:number;readonly allowRedelegation:boolean;readonly issuedAt:string;readonly expiresAt:string;readonly policyReferences:readonly string[];readonly version:string;}
export interface ImpersonationContext {readonly authorizationDecisionId:string;readonly originalPrincipalId:string;readonly impersonatedPrincipalId:string;readonly reason:string;readonly issuedAt:string;readonly expiresAt:string;readonly auditReference:string;}
export interface SecurityCondition {readonly type:'step-up-authentication'|'consent'|'human-approval'|'result-limit'|'field-mask'|'allowed-tools'|'network-destination'|'no-persistence'|'no-export'|'time-limit'|'resource-limit'|'additional-audit';readonly key:string;readonly value:string;}
export interface AuthorizationRequest {readonly requestId:string;readonly requestVersion:string;readonly principal:Principal;readonly action:SecurityAction;readonly resource:ResourceReference;readonly scope:Readonly<{tenantId:string;workspaceId?:string;projectId?:string}>;readonly execution:Readonly<{executionId:string;correlationId:string}>;readonly delegationIds:readonly string[];readonly impersonation?:ImpersonationContext;readonly capabilityRequirements:readonly string[];readonly toolPermissions:readonly string[];readonly pluginPermissions:readonly string[];readonly environmental:Readonly<Record<string,string>>;readonly policyContext:Readonly<{activePolicySet:string;configurationVersion:string}>;readonly occurredAt:string;}
export interface SecurityPolicy {readonly id:string;readonly version:string;readonly schemaVersion:string;readonly source:'platform'|'organization'|'tenant'|'workspace'|'project'|'resource'|'agent'|'tool'|'plugin'|'compliance'|'execution';readonly priority:number;readonly mandatory:boolean;readonly active:boolean;readonly effect:'permit'|'deny'|'conditional-permit'|'not-applicable';readonly principalTypes:readonly PrincipalType[];readonly requiredRoles:readonly string[];readonly actions:readonly SecurityAction[];readonly resourceTypes:readonly ResourceType[];readonly tenantIds:readonly string[];readonly workspaceIds:readonly string[];readonly projectIds:readonly string[];readonly requiredLabels:readonly string[];readonly requiredAuthenticationStrength?:AuthenticationStrength;readonly conditions:readonly SecurityCondition[];readonly restrictions:readonly string[];readonly obligations:readonly string[];}
export interface PolicyResolver {resolve(request:AuthorizationRequest):Promise<readonly SecurityPolicy[]>;}
export interface PolicyEvaluation {readonly policyId:string;readonly policyVersion:string;readonly applicable:boolean;readonly outcome:AuthorizationOutcome;readonly conditions:readonly SecurityCondition[];readonly restrictions:readonly string[];readonly obligations:readonly string[];readonly evidenceReferences:readonly string[];readonly reason:string;}
export interface PolicyEvaluator {evaluate(policy:SecurityPolicy,request:AuthorizationRequest,delegations:readonly DelegationGrant[]):PolicyEvaluation;}
export interface PolicyConflictResolver {resolve(evaluations:readonly PolicyEvaluation[]):Readonly<{outcome:AuthorizationOutcome;applied:readonly PolicyEvaluation[];reason:string}>;}
export interface AuthorizationDecision {readonly id:string;readonly requestId:string;readonly outcome:AuthorizationOutcome;readonly authorized:boolean;readonly principalId:string;readonly effectivePrincipalId:string;readonly action:SecurityAction;readonly resource:Readonly<{id:string;type:ResourceType;version:string}>;readonly effectiveScope:AuthorizationRequest['scope'];readonly appliedPolicies:readonly string[];readonly conditions:readonly SecurityCondition[];readonly restrictions:readonly string[];readonly obligations:readonly string[];readonly reason:string;readonly policyVersions:readonly string[];readonly evidenceReferences:readonly string[];readonly issuedAt:string;readonly expiresAt:string;readonly correlation:AuthorizationRequest['execution'];readonly schemaVersion:string;readonly cacheKey:string;}
export type AuthorityState='active'|'expired'|'revoked'|'superseded';
export interface AuthorityValidity {readonly decisionId:string;readonly state:AuthorityState;readonly checkedAt:string;readonly reason:string;}
export interface SecurityContext extends SecurityContextReference {readonly effectivePrincipalId:string;readonly originalPrincipalId:string;readonly impersonatedPrincipalId?:string;readonly tenantId:string;readonly workspaceId?:string;readonly projectId?:string;readonly effectivePermissions:readonly string[];readonly delegatedPermissions:readonly string[];readonly restrictions:readonly string[];readonly securityLabels:readonly string[];readonly authenticationStrength:AuthenticationStrength;readonly authorizationReferences:readonly string[];readonly policyVersions:readonly string[];readonly issuedAt:string;readonly metadata:Readonly<Record<string,string>>;}
export interface AuthorizedSecretReference {readonly id:string;readonly providerReference:string;readonly purpose:string;readonly tenantId:string;readonly workspaceId?:string;readonly expiresAt:string;readonly authorizationDecisionId:string;}
export interface Revocation {readonly id:string;readonly subjectType:'decision'|'security-context'|'delegation'|'principal'|'session'|'plugin-permission'|'tool-permission'|'secret-access';readonly subjectId:string;readonly scope:string;readonly effectiveAt:string;readonly reason:string;readonly version:string;}
export interface DelegationStore {get(id:string):DelegationGrant|undefined;save(grant:DelegationGrant):void;}
export interface RevocationStore {revoke(value:Revocation):void;find(subjectType:Revocation['subjectType'],subjectId:string,at:string):Revocation|undefined;version():number;}
export interface AuthorizationDecisionCache {get(key:string):AuthorizationDecision|undefined;set(key:string,decision:AuthorizationDecision):void;deleteBySubject(subjectId:string):void;clear():void;}
export interface SecurityDiagnostic {readonly id:string;readonly outcome:AuthorizationOutcome|'failed';readonly principalType:PrincipalType;readonly resourceType:ResourceType;readonly appliedPolicies:readonly string[];readonly policyVersions:readonly string[];readonly conflictResolution:'explicit-deny-precedence';readonly conditions:readonly string[];readonly scopeResult:'accepted'|'rejected';readonly errorCode?:SecurityErrorCode;}
export interface SecurityDiagnostics {record(value:SecurityDiagnostic):void;list():readonly SecurityDiagnostic[];}
export interface SecurityFact {readonly type:'principal.normalized'|'authorization.requested'|'authorization.permitted'|'authorization.denied'|'authorization.conditional'|'authorization.indeterminate'|'security-context.created'|'authority.revoked'|'impersonation.used';readonly requestId:string;readonly tenantId:string;readonly decisionId?:string;readonly principalId:string;readonly correlationId:string;readonly version:string;}
export interface SecurityEvents {publish(value:SecurityFact):Promise<void>;}
export interface SecurityTelemetry {decided(outcome:AuthorizationOutcome,principalType:PrincipalType,resourceType:ResourceType):void;cache(hit:boolean):void;failed(code:SecurityErrorCode):void;}
export interface SecurityAudit {record(value:Readonly<{type:string;principalId:string;effectivePrincipalId:string;resourceId:string;action:string;decisionId:string;outcome:AuthorizationOutcome;impersonationReference?:string;diagnosticId:string}>):Promise<void>;}
export interface SecurityHealth {health():Promise<Readonly<{name:string;status:'healthy'|'degraded'|'unhealthy';policyVersion:string;revocationVersion:number}>>;}
export type SecurityErrorCode='SECURITY_AUTHENTICATION_EVIDENCE_INVALID'|'SECURITY_PRINCIPAL_RESOLUTION_FAILED'|'SECURITY_AUTHORIZATION_REQUEST_INVALID'|'SECURITY_POLICY_UNAVAILABLE'|'SECURITY_POLICY_EVALUATION_FAILED'|'SECURITY_POLICY_CONFLICT'|'SECURITY_UNSUPPORTED_PRINCIPAL'|'SECURITY_UNSUPPORTED_RESOURCE'|'SECURITY_DELEGATION_INVALID'|'SECURITY_CONTEXT_EXPIRED'|'SECURITY_AUTHENTICATION_STRENGTH_INSUFFICIENT'|'SECURITY_AUTHORIZATION_INDETERMINATE'|'SECURITY_AUTHORIZATION_DENIED'|'SECURITY_REVOKED'|'SECURITY_SCOPE_VIOLATION'|'SECURITY_UNKNOWN';
export class ExternalSecurityError extends Error {public constructor(public readonly kind:'evidence'|'principal'|'request'|'policy-unavailable'|'policy-evaluation'|'policy-conflict'|'principal-unsupported'|'resource-unsupported'|'delegation'|'expired'|'strength'|'indeterminate'|'denied'|'revoked'|'scope'|'unknown',message:string){super(message);this.name='ExternalSecurityError';}}
export class SecurityError extends Error {public constructor(public readonly code:SecurityErrorCode,message:string,public readonly diagnosticId:string){super(message);this.name='SecurityError';}}

export class SecurityPlatform implements SecurityHealth {
  public constructor(private readonly policies:PolicyResolver,private readonly evaluator:PolicyEvaluator,private readonly conflicts:PolicyConflictResolver,private readonly delegations:DelegationStore,private readonly revocations:RevocationStore,private readonly cache:AuthorizationDecisionCache,private readonly diagnostics:SecurityDiagnostics,private readonly events:SecurityEvents,private readonly telemetry:SecurityTelemetry,private readonly audit:SecurityAudit,private readonly now:()=>Date=()=>new Date()){}
  public async authorize(request:AuthorizationRequest):Promise<AuthorizationDecision>{const diagnosticId=`security:${request.requestId}`;try{validateRequest(request,diagnosticId);await this.events.publish(fact('authorization.requested',request));const grants=this.#grants(request,diagnosticId);const key=cacheKey(request,grants,this.revocations.version());const cached=this.cache.get(key);if(cached!==undefined&&this.validity(cached).state==='active'){this.telemetry.cache(true);return cached;}this.telemetry.cache(false);let resolved:readonly SecurityPolicy[];try{resolved=await this.policies.resolve(request);}catch(error){return await this.#indeterminate(request,key,diagnosticId,error);}let evaluations:readonly PolicyEvaluation[];try{evaluations=resolved.filter(value=>value.active).map(value=>this.evaluator.evaluate(value,request,grants));}catch(error){return await this.#indeterminate(request,key,diagnosticId,error);}const conflict=this.conflicts.resolve(evaluations);const issuedAt=this.now().toISOString();const expirationCandidates=grants.map(value=>value.expiresAt);const expiresAt=expirationCandidates.sort()[0]??new Date(this.now().getTime()+300000).toISOString();const outcome=evaluations.length===0?'deny':conflict.outcome;const authorized=outcome==='permit'||outcome==='conditional-permit';const applied=conflict.applied;const decision:AuthorizationDecision=freeze({id:`decision:${request.requestId}:${hash(key)}`,requestId:request.requestId,outcome,authorized,principalId:request.principal.id,effectivePrincipalId:request.impersonation?.impersonatedPrincipalId??request.principal.id,action:request.action,resource:{id:request.resource.id,type:request.resource.type,version:request.resource.version},effectiveScope:{...request.scope},appliedPolicies:applied.map(value=>value.policyId),conditions:applied.flatMap(value=>value.conditions).map(clone),restrictions:unique([...applied.flatMap(value=>value.restrictions),...grants.flatMap(value=>value.restrictions)]),obligations:unique(applied.flatMap(value=>value.obligations)),reason:evaluations.length===0?'deny-by-default':conflict.reason,policyVersions:unique(applied.map(value=>value.policyVersion)),evidenceReferences:unique(applied.flatMap(value=>value.evidenceReferences)),issuedAt,expiresAt,correlation:{...request.execution},schemaVersion:'authorization-decision-1',cacheKey:key});this.cache.set(key,decision);await this.#record(request,decision,diagnosticId);return decision;}catch(error){const normalized=normalize(error,diagnosticId);this.diagnostics.record(freeze({id:diagnosticId,outcome:'failed',principalType:request.principal.type,resourceType:request.resource.type,appliedPolicies:[],policyVersions:[],conflictResolution:'explicit-deny-precedence',conditions:[],scopeResult:'rejected',errorCode:normalized.code}));this.telemetry.failed(normalized.code);throw normalized;}}
  public createSecurityContext(request:AuthorizationRequest,decision:AuthorizationDecision,version:string):SecurityContext{const validity=this.validity(decision);if(!decision.authorized||validity.state!=='active')throw new SecurityError(validity.state==='expired'?'SECURITY_CONTEXT_EXPIRED':validity.state==='revoked'?'SECURITY_REVOKED':'SECURITY_AUTHORIZATION_DENIED','Authority is not currently valid',`security-context:${decision.id}`);const context:SecurityContext=freeze({id:`security-context:${decision.id}`,version,principalId:decision.principalId,decisionId:decision.id,expiresAt:decision.expiresAt,effectivePrincipalId:decision.effectivePrincipalId,originalPrincipalId:decision.principalId,...optional('impersonatedPrincipalId',request.impersonation?.impersonatedPrincipalId),tenantId:request.scope.tenantId,...optional('workspaceId',request.scope.workspaceId),...optional('projectId',request.scope.projectId),effectivePermissions:effectivePermissions(request),delegatedPermissions:request.delegationIds.flatMap(id=>this.delegations.get(id)?.actions??[]),restrictions:[...decision.restrictions],securityLabels:[...request.resource.securityLabels],authenticationStrength:request.principal.authenticationStrength,authorizationReferences:[decision.id],policyVersions:[...decision.policyVersions],issuedAt:this.now().toISOString(),metadata:{classification:request.resource.classification}});void this.events.publish({...fact('security-context.created',request),decisionId:decision.id});return context;}
  public validity(decision:AuthorizationDecision):AuthorityValidity{const checkedAt=this.now().toISOString();if(this.revocations.find('decision',decision.id,checkedAt)!==undefined)return freeze({decisionId:decision.id,state:'revoked',checkedAt,reason:'decision-revoked'});if(Date.parse(decision.expiresAt)<=this.now().getTime())return freeze({decisionId:decision.id,state:'expired',checkedAt,reason:'decision-expired'});return freeze({decisionId:decision.id,state:'active',checkedAt,reason:'authority-active'});}
  public revoke(value:Revocation):void{this.revocations.revoke(freeze(clone(value)));this.cache.deleteBySubject(value.subjectId);void this.events.publish({type:'authority.revoked',requestId:value.id,tenantId:'security',principalId:value.subjectId,correlationId:value.id,version:value.version});}
  public async health():Promise<Readonly<{name:string;status:'healthy';policyVersion:string;revocationVersion:number}>>{return freeze({name:'security-platform',status:'healthy',policyVersion:'resolved-per-request',revocationVersion:this.revocations.version()});}
  #grants(request:AuthorizationRequest,id:string):readonly DelegationGrant[]{const values=request.delegationIds.map(value=>this.delegations.get(value));if(values.some(value=>value===undefined))throw new SecurityError('SECURITY_DELEGATION_INVALID','Delegation is unavailable',id);const grants=values.filter((value):value is DelegationGrant=>value!==undefined);for(const grant of grants)if(!validGrant(grant,request,this.now(),this.revocations))throw new SecurityError('SECURITY_DELEGATION_INVALID','Delegation is invalid',id);return grants;}
  async #indeterminate(request:AuthorizationRequest,key:string,id:string,error:unknown):Promise<AuthorizationDecision>{const issuedAt=this.now().toISOString();const decision:AuthorizationDecision=freeze({id:`decision:${request.requestId}:indeterminate`,requestId:request.requestId,outcome:'indeterminate',authorized:false,principalId:request.principal.id,effectivePrincipalId:request.principal.id,action:request.action,resource:{id:request.resource.id,type:request.resource.type,version:request.resource.version},effectiveScope:{...request.scope},appliedPolicies:[],conditions:[],restrictions:[],obligations:[],reason:'policy-evaluation-indeterminate',policyVersions:[],evidenceReferences:[],issuedAt,expiresAt:issuedAt,correlation:{...request.execution},schemaVersion:'authorization-decision-1',cacheKey:key});this.telemetry.failed('SECURITY_AUTHORIZATION_INDETERMINATE');await this.#record(request,decision,id);void error;return decision;}
  async #record(request:AuthorizationRequest,decision:AuthorizationDecision,id:string):Promise<void>{const eventType=decision.outcome==='permit'?'authorization.permitted':decision.outcome==='conditional-permit'?'authorization.conditional':decision.outcome==='indeterminate'?'authorization.indeterminate':'authorization.denied';this.diagnostics.record(freeze({id,outcome:decision.outcome,principalType:request.principal.type,resourceType:request.resource.type,appliedPolicies:[...decision.appliedPolicies],policyVersions:[...decision.policyVersions],conflictResolution:'explicit-deny-precedence',conditions:decision.conditions.map(value=>value.type),scopeResult:decision.outcome==='deny'&&decision.reason.includes('scope')?'rejected':'accepted'}));this.telemetry.decided(decision.outcome,request.principal.type,request.resource.type);await this.events.publish({...fact(eventType,request),decisionId:decision.id});await this.audit.record({type:'authorization-decision',principalId:decision.principalId,effectivePrincipalId:decision.effectivePrincipalId,resourceId:decision.resource.id,action:decision.action,decisionId:decision.id,outcome:decision.outcome,...optional('impersonationReference',request.impersonation?.auditReference),diagnosticId:id});}
}

export class SecurityRuntimeAdapter implements SecurityAuthorizationPort {public constructor(private readonly contexts:ReadonlyMap<string,SecurityContext>,private readonly validity:(decisionId:string)=>AuthorityState){}public async authorize(context:ExecutionContext):Promise<{readonly authorized:boolean;readonly decisionId:string}>{const security=this.contexts.get(context.securityContextId);if(security===undefined||context.securityContext?.id!==security.id||this.validity(security.decisionId)!=='active')return{authorized:false,decisionId:security?.decisionId??'missing-security-context'};return{authorized:true,decisionId:security.decisionId};}}
export class SecurityPluginPermissionAdapter implements PluginPermissionAuthorizer {public constructor(private readonly authorizePermissions:(pluginId:string,permissions:readonly string[])=>Promise<AuthorizationDecision>){}public async authorize(pluginId:string,permissions:readonly string[]):Promise<{readonly authorized:boolean;readonly decisionId:string;readonly reason?:string}>{const decision=await this.authorizePermissions(pluginId,permissions);return{authorized:decision.authorized,decisionId:decision.id,...(decision.authorized?{}:{reason:'Plugin permissions denied'})};}}
export function enforce(decision:AuthorizationDecision,validity:AuthorityValidity):void{if(!decision.authorized||validity.state!=='active')throw new SecurityError(validity.state==='revoked'?'SECURITY_REVOKED':validity.state==='expired'?'SECURITY_CONTEXT_EXPIRED':'SECURITY_AUTHORIZATION_DENIED','Protected operation is not authorized',`security:enforce:${decision.id}`);}

function validateRequest(request:AuthorizationRequest,id:string):void{if(request.requestId.trim()===''||request.principal.id.trim()===''||request.scope.tenantId.trim()===''||request.resource.id.trim()===''||request.resource.tenantId!==request.scope.tenantId||request.principal.tenantId!==request.scope.tenantId||request.scope.workspaceId!==undefined&&(!request.principal.workspaceIds.includes(request.scope.workspaceId)||request.resource.workspaceId!==request.scope.workspaceId)||request.scope.projectId!==undefined&&(!request.principal.projectIds.includes(request.scope.projectId)||request.resource.projectId!==request.scope.projectId))throw new SecurityError('SECURITY_SCOPE_VIOLATION','Authorization request scope rejected',id);if(request.impersonation!==undefined&&(request.impersonation.originalPrincipalId!==request.principal.id||request.impersonation.reason.trim()===''||Date.parse(request.impersonation.expiresAt)<=Date.parse(request.occurredAt)))throw new SecurityError('SECURITY_AUTHORIZATION_REQUEST_INVALID','Invalid impersonation context',id);try{JSON.stringify(request);}catch{throw new SecurityError('SECURITY_AUTHORIZATION_REQUEST_INVALID','Authorization request is not serializable',id);}}
function validGrant(grant:DelegationGrant,request:AuthorizationRequest,now:Date,revocations:RevocationStore):boolean{return grant.receivingPrincipalId===request.principal.id&&grant.tenantId===request.scope.tenantId&&grant.actions.includes(request.action)&&grant.resourceTypes.includes(request.resource.type)&&(grant.resourceIds.length===0||grant.resourceIds.includes(request.resource.id))&&(request.scope.workspaceId===undefined||grant.workspaceIds.includes(request.scope.workspaceId))&&(request.scope.projectId===undefined||grant.projectIds.includes(request.scope.projectId))&&grant.depth<=grant.maximumDepth&&Date.parse(grant.expiresAt)>now.getTime()&&revocations.find('delegation',grant.id,now.toISOString())===undefined&&(grant.parentDelegationId===undefined||grant.allowRedelegation);}
function effectivePermissions(request:AuthorizationRequest):readonly string[]{const authority=request.principal.agentAuthority;const base=new Set(request.principal.permissions);if(authority===undefined)return freeze([...base]);const constrained=[...base].filter(permission=>authority.allowedCapabilities.includes(permission)||authority.allowedTools.includes(permission));return freeze(constrained);}
function cacheKey(request:AuthorizationRequest,grants:readonly DelegationGrant[],revocationVersion:number):string{return stable({principal:request.principal.id,effective:request.impersonation?.impersonatedPrincipalId??request.principal.id,principalModel:request.principal.modelVersion,session:request.principal.sessionReference,strength:request.principal.authenticationStrength,roles:request.principal.roles,claims:request.principal.claims,permissions:request.principal.permissions,action:request.action,resource:request.resource.id,resourceType:request.resource.type,resourceVersion:request.resource.version,classification:request.resource.classification,labels:request.resource.securityLabels,scope:request.scope,delegations:grants.map(value=>({id:value.id,version:value.version,expiresAt:value.expiresAt})),impersonation:request.impersonation,capabilities:request.capabilityRequirements,tools:request.toolPermissions,plugins:request.pluginPermissions,environmental:request.environmental,policyContext:request.policyContext,revocationVersion});}
function fact(type:SecurityFact['type'],request:AuthorizationRequest):SecurityFact{return freeze({type,requestId:request.requestId,tenantId:request.scope.tenantId,principalId:request.principal.id,correlationId:request.execution.correlationId,version:request.requestVersion});}
function normalize(error:unknown,id:string):SecurityError{if(error instanceof SecurityError)return error;const kind=error instanceof ExternalSecurityError?error.kind:'unknown';const code=({evidence:'SECURITY_AUTHENTICATION_EVIDENCE_INVALID',principal:'SECURITY_PRINCIPAL_RESOLUTION_FAILED',request:'SECURITY_AUTHORIZATION_REQUEST_INVALID','policy-unavailable':'SECURITY_POLICY_UNAVAILABLE','policy-evaluation':'SECURITY_POLICY_EVALUATION_FAILED','policy-conflict':'SECURITY_POLICY_CONFLICT','principal-unsupported':'SECURITY_UNSUPPORTED_PRINCIPAL','resource-unsupported':'SECURITY_UNSUPPORTED_RESOURCE',delegation:'SECURITY_DELEGATION_INVALID',expired:'SECURITY_CONTEXT_EXPIRED',strength:'SECURITY_AUTHENTICATION_STRENGTH_INSUFFICIENT',indeterminate:'SECURITY_AUTHORIZATION_INDETERMINATE',denied:'SECURITY_AUTHORIZATION_DENIED',revoked:'SECURITY_REVOKED',scope:'SECURITY_SCOPE_VIOLATION',unknown:'SECURITY_UNKNOWN'} as const)[kind];return new SecurityError(code,error instanceof Error?error.message:'Security operation failed',id);}
function stable(value:unknown):string{return JSON.stringify(sort(value));}
function sort(value:unknown):unknown{if(Array.isArray(value))return value.map(sort);if(typeof value==='object'&&value!==null)return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,sort(item)]));return value;}
function hash(value:string):string{let result=2166136261;for(const character of value){result^=character.codePointAt(0)??0;result=Math.imul(result,16777619);}return(result>>>0).toString(16);}
function optional<K extends string,V>(key:K,value:V|undefined):Partial<Record<K,V>>{return value===undefined?{}:{[key]:value} as Record<K,V>;}
function unique<T>(values:readonly T[]):readonly T[]{return freeze([...new Set(values)]);}
function clone<T>(value:T):T{return JSON.parse(JSON.stringify(value)) as T;}
function freeze<T>(value:T):T{if(typeof value==='object'&&value!==null&&!Object.isFrozen(value)){for(const child of Object.values(value))freeze(child);Object.freeze(value);}return value;}

export * from './reference.js';


