import { ExternalSecurityError,type AuthenticationEvidence,type AuthorizationDecision,type AuthorizationDecisionCache,type AuthorizationOutcome,type AuthorizationRequest,type DelegationGrant,type DelegationStore,type IdentityNormalizationPolicy,type PolicyConflictResolver,type PolicyEvaluation,type PolicyEvaluator,type Principal,type PrincipalNormalizer,type Revocation,type RevocationStore,type SecurityAudit,type SecurityDiagnostic,type SecurityDiagnostics,type SecurityEvents,type SecurityFact,type SecurityPolicy,type SecurityTelemetry,type PolicyResolver } from './index.js';

export class StaticPrincipalNormalizer implements PrincipalNormalizer {public normalize(evidence:AuthenticationEvidence,policy:IdentityNormalizationPolicy):Principal{if(evidence.subject.trim()===''||evidence.issuerReference.trim()===''||Date.parse(evidence.expiresAt)<=Date.parse(evidence.authenticatedAt))throw new ExternalSecurityError('evidence','Authentication evidence is invalid');const claim=(key:string):readonly string[]=>{const value=evidence.claims[key];return value===undefined?[]:typeof value==='string'?[value]:[...value];};const type=claim(policy.principalTypeClaim)[0]??'anonymous';if(!['human','agent','service','workload','plugin','tool','external-system','administrator','anonymous'].includes(type))throw new ExternalSecurityError('principal-unsupported','Principal type is unsupported');const tenantId=claim(policy.tenantClaim)[0];if(tenantId===undefined)throw new ExternalSecurityError('principal','Tenant claim is required');return deepFreeze({id:evidence.subject,type:type as Principal['type'],identitySource:evidence.issuerReference,tenantId,workspaceIds:claim(policy.workspaceClaim),projectIds:claim(policy.projectClaim),roles:claim(policy.rolesClaim),claims:{...evidence.claims},permissions:claim(policy.permissionsClaim),securityLabels:claim(policy.labelsClaim),authenticationStrength:evidence.strength,sessionReference:evidence.sessionReference,evidenceId:evidence.evidenceId,modelVersion:policy.version});}}
export class StaticPolicyResolver implements PolicyResolver {public constructor(private readonly policies:readonly SecurityPolicy[]){}public async resolve(_request:AuthorizationRequest):Promise<readonly SecurityPolicy[]>{return Object.freeze([...this.policies]);}}
export class BasicSecurityPolicyEvaluator implements PolicyEvaluator {public evaluate(policy:SecurityPolicy,request:AuthorizationRequest,delegations:readonly DelegationGrant[]):PolicyEvaluation{const applicable=(policy.principalTypes.length===0||policy.principalTypes.includes(request.principal.type))&&(policy.requiredRoles.length===0||policy.requiredRoles.every(value=>request.principal.roles.includes(value)))&&(policy.actions.length===0||policy.actions.includes(request.action))&&(policy.resourceTypes.length===0||policy.resourceTypes.includes(request.resource.type))&&(policy.tenantIds.length===0||policy.tenantIds.includes(request.scope.tenantId))&&(request.scope.workspaceId===undefined||policy.workspaceIds.length===0||policy.workspaceIds.includes(request.scope.workspaceId))&&(request.scope.projectId===undefined||policy.projectIds.length===0||policy.projectIds.includes(request.scope.projectId))&&policy.requiredLabels.every(value=>request.resource.securityLabels.includes(value))&&strengthAtLeast(request.principal.authenticationStrength,policy.requiredAuthenticationStrength??'anonymous')&&agentWithinAuthority(request)&&delegations.every(value=>value.receivingPrincipalId===request.principal.id);return deepFreeze({policyId:policy.id,policyVersion:policy.version,applicable,outcome:applicable?policy.effect:'not-applicable',conditions:applicable?[...policy.conditions]:[],restrictions:applicable?[...policy.restrictions]:[],obligations:applicable?[...policy.obligations]:[],evidenceReferences:applicable?[`policy:${policy.id}:${policy.version}`]:[],reason:applicable?`policy-${policy.effect}`:'policy-not-applicable'});}}
export class ExplicitDenyConflictResolver implements PolicyConflictResolver {public resolve(evaluations:readonly PolicyEvaluation[]):Readonly<{outcome:AuthorizationOutcome;applied:readonly PolicyEvaluation[];reason:string}>{const applicable=evaluations.filter(value=>value.applicable);const denies=applicable.filter(value=>value.outcome==='deny');if(denies.length>0)return deepFreeze({outcome:'deny',applied:denies,reason:'explicit-deny-precedence'});const indeterminate=applicable.filter(value=>value.outcome==='indeterminate');if(indeterminate.length>0)return deepFreeze({outcome:'indeterminate',applied:indeterminate,reason:'indeterminate-fails-closed'});const conditional=applicable.filter(value=>value.outcome==='conditional-permit');const permits=applicable.filter(value=>value.outcome==='permit');if(conditional.length>0)return deepFreeze({outcome:'conditional-permit',applied:[...conditional,...permits],reason:'conditional-permit'});if(permits.length>0)return deepFreeze({outcome:'permit',applied:permits,reason:'explicit-permit'});if(applicable.some(value=>value.outcome==='not-applicable'))return deepFreeze({outcome:'not-applicable',applied:applicable,reason:'not-applicable'});return deepFreeze({outcome:'deny',applied:[],reason:'deny-by-default'});}}
export class InMemoryDelegationStore implements DelegationStore {readonly #items=new Map<string,DelegationGrant>();public get(id:string):DelegationGrant|undefined{return this.#items.get(id);}public save(value:DelegationGrant):void{this.#items.set(value.id,deepFreeze(clone(value)));}}
export class InMemoryRevocationStore implements RevocationStore {readonly #items:Revocation[]=[];#version=0;public revoke(value:Revocation):void{this.#items.push(deepFreeze(clone(value)));this.#version++;}public find(type:Revocation['subjectType'],id:string,at:string):Revocation|undefined{return this.#items.find(value=>value.subjectType===type&&value.subjectId===id&&value.effectiveAt<=at);}public version():number{return this.#version;}}
export class InMemoryAuthorizationDecisionCache implements AuthorizationDecisionCache {readonly #items=new Map<string,AuthorizationDecision>();public get(key:string):AuthorizationDecision|undefined{return this.#items.get(key);}public set(key:string,value:AuthorizationDecision):void{this.#items.set(key,value);}public deleteBySubject(subjectId:string):void{for(const [key,value] of this.#items)if(value.principalId===subjectId||value.effectivePrincipalId===subjectId||value.id===subjectId)this.#items.delete(key);}public clear():void{this.#items.clear();}public size():number{return this.#items.size;}}
export class InMemorySecurityDiagnostics implements SecurityDiagnostics {readonly #items:SecurityDiagnostic[]=[];public record(value:SecurityDiagnostic):void{this.#items.push(value);}public list():readonly SecurityDiagnostic[]{return Object.freeze([...this.#items]);}}
export class InMemorySecurityEvents implements SecurityEvents {readonly facts:SecurityFact[]=[];public async publish(value:SecurityFact):Promise<void>{this.facts.push(value);}}
export class InMemorySecurityAudit implements SecurityAudit {readonly records:Readonly<{type:string;principalId:string;effectivePrincipalId:string;resourceId:string;action:string;decisionId:string;outcome:AuthorizationOutcome;impersonationReference?:string;diagnosticId:string}>[]=[];public async record(value:Readonly<{type:string;principalId:string;effectivePrincipalId:string;resourceId:string;action:string;decisionId:string;outcome:AuthorizationOutcome;impersonationReference?:string;diagnosticId:string}>):Promise<void>{this.records.push(value);}}
export class NoopSecurityTelemetry implements SecurityTelemetry {public decided(_outcome:AuthorizationOutcome,_principalType:Principal['type'],_resourceType:AuthorizationRequest['resource']['type']):void{}public cache(_hit:boolean):void{}public failed(_code:string):void{}}

export class DeterministicSecurityPolicySimulator {public constructor(private readonly evaluator:PolicyEvaluator,private readonly conflicts:PolicyConflictResolver){}public simulate(request:AuthorizationRequest,policies:readonly SecurityPolicy[],delegations:readonly DelegationGrant[]):Readonly<{authoritative:false;outcome:AuthorizationOutcome;policyVersions:readonly string[]}>{const evaluations=policies.map(value=>this.evaluator.evaluate(value,request,delegations));const result=this.conflicts.resolve(evaluations);return deepFreeze({authoritative:false,outcome:result.outcome,policyVersions:result.applied.map(value=>value.policyVersion)});}}

function strengthAtLeast(actual:Principal['authenticationStrength'],required:Principal['authenticationStrength']):boolean{const levels={anonymous:0,'single-factor':1,'multi-factor':2,'hardware-backed':3};return levels[actual]>=levels[required];}
function agentWithinAuthority(request:AuthorizationRequest):boolean{const authority=request.principal.agentAuthority;if(request.principal.type!=='agent')return true;if(authority===undefined)return false;return request.capabilityRequirements.every(value=>authority.allowedCapabilities.includes(value))&&request.toolPermissions.every(value=>authority.allowedTools.includes(value))&&!request.environmental.selfEscalation;}
function clone<T>(value:T):T{return JSON.parse(JSON.stringify(value)) as T;}
function deepFreeze<T>(value:T):T{if(typeof value==='object'&&value!==null&&!Object.isFrozen(value)){for(const child of Object.values(value))deepFreeze(child);Object.freeze(value);}return value;}

