/* eslint-disable @typescript-eslint/explicit-function-return-type */
import { ExecutionContextFactory,type CreateExecutionContextRequest } from '@agentprodready/foundation';
import { describe,expect,it,vi } from 'vitest';
import { SecurityPlatform,SecurityPluginPermissionAdapter,SecurityRuntimeAdapter,enforce,type AuthorizationRequest,type DelegationGrant,type IdentityNormalizationPolicy,type Principal,type SecurityPolicy,type SecurityTelemetry } from './index.js';
import { BasicSecurityPolicyEvaluator,DeterministicSecurityPolicySimulator,ExplicitDenyConflictResolver,InMemoryAuthorizationDecisionCache,InMemoryDelegationStore,InMemoryRevocationStore,InMemorySecurityAudit,InMemorySecurityDiagnostics,InMemorySecurityEvents,StaticPolicyResolver,StaticPrincipalNormalizer } from './reference.js';

const identityPolicy:IdentityNormalizationPolicy={version:'principal-1',principalTypeClaim:'type',tenantClaim:'tenant',workspaceClaim:'workspaces',projectClaim:'projects',rolesClaim:'roles',permissionsClaim:'permissions',labelsClaim:'labels'};
const principal:Principal={id:'user-1',type:'human',identitySource:'identity-source:enterprise',tenantId:'tenant-1',workspaceIds:['workspace-1'],projectIds:['project-1'],roles:['member'],claims:{department:'engineering'},permissions:['capability.answer','tool.lookup'],securityLabels:['public'],authenticationStrength:'multi-factor',sessionReference:'session:1',evidenceId:'evidence:1',modelVersion:'principal-1'};
const policy=(effect:SecurityPolicy['effect']='permit',overrides:Partial<SecurityPolicy>={}):SecurityPolicy=>({id:`policy-${effect}`,version:'policy-1',schemaVersion:'security-policy-1',source:'tenant',priority:10,mandatory:true,active:true,effect,principalTypes:['human','agent'],requiredRoles:['member'],actions:['execute'],resourceTypes:['capability'],tenantIds:['tenant-1'],workspaceIds:['workspace-1'],projectIds:['project-1'],requiredLabels:['public'],conditions:[],restrictions:[],obligations:[],...overrides});
const request=(overrides:Partial<AuthorizationRequest>={}):AuthorizationRequest=>({requestId:'authorization-1',requestVersion:'authorization-request-1',principal,action:'execute',resource:{id:'capability:answer',type:'capability',tenantId:'tenant-1',workspaceId:'workspace-1',projectId:'project-1',classification:'internal',securityLabels:['public'],version:'resource-1',metadata:{}},scope:{tenantId:'tenant-1',workspaceId:'workspace-1',projectId:'project-1'},execution:{executionId:'execution-1',correlationId:'correlation-1'},delegationIds:[],capabilityRequirements:['capability.answer'],toolPermissions:[],pluginPermissions:[],environmental:{network:'internal'},policyContext:{activePolicySet:'active-1',configurationVersion:'configuration-1'},occurredAt:'2026-08-06T00:00:00.000Z',...overrides});
function fixture(policies:readonly SecurityPolicy[]=[policy()],start='2026-08-06T00:00:00.000Z'){let current=new Date(start);const delegations=new InMemoryDelegationStore();const revocations=new InMemoryRevocationStore();const cache=new InMemoryAuthorizationDecisionCache();const diagnostics=new InMemorySecurityDiagnostics();const events=new InMemorySecurityEvents();const audit=new InMemorySecurityAudit();const decided=vi.fn();const cacheMetric=vi.fn();const failed=vi.fn();const telemetry:SecurityTelemetry={decided,cache:cacheMetric,failed};const platform=new SecurityPlatform(new StaticPolicyResolver(policies),new BasicSecurityPolicyEvaluator(),new ExplicitDenyConflictResolver(),delegations,revocations,cache,diagnostics,events,telemetry,audit,()=>new Date(current));return{platform,delegations,revocations,cache,diagnostics,events,audit,decided,cacheMetric,failed,advance:(milliseconds:number)=>{current=new Date(current.getTime()+milliseconds);}};}

describe('Security & Authorization Platform',()=>{
  it('normalizes trusted authentication evidence into a provider-independent immutable Principal',()=>{const evidence={evidenceId:'evidence-1',subject:'user-1',issuerReference:'identity-source:enterprise',method:'federated',strength:'multi-factor' as const,authenticatedAt:'2026-08-06T00:00:00.000Z',expiresAt:'2026-08-06T01:00:00.000Z',sessionReference:'session:1',claims:{type:'human',tenant:'tenant-1',workspaces:['workspace-1'],projects:['project-1'],roles:['member'],permissions:['capability.answer'],labels:['public']},version:'evidence-1'};const result=new StaticPrincipalNormalizer().normalize(evidence,identityPolicy);expect(result).toMatchObject({id:'user-1',type:'human',tenantId:'tenant-1',roles:['member']});expect(Object.isFrozen(result)).toBe(true);expect(result).not.toHaveProperty('accessToken');});
  it('uses immutable Authorization Requests and denies by default',async()=>{const input=request();const before=JSON.stringify(input);const decision=await fixture([]).platform.authorize(input);expect(decision).toMatchObject({outcome:'deny',authorized:false,reason:'deny-by-default'});expect(Object.isFrozen(decision)).toBe(true);expect(JSON.stringify(input)).toBe(before);expect(()=>{enforce(decision,{decisionId:decision.id,state:'active',checkedAt:decision.issuedAt,reason:'active'});}).toThrow();});
  it('explicitly represents permit, deny, conditional, not-applicable, and indeterminate outcomes',async()=>{expect((await fixture([policy('permit')]).platform.authorize(request())).outcome).toBe('permit');expect((await fixture([policy('permit'),policy('deny')]).platform.authorize(request())).outcome).toBe('deny');const conditional=policy('conditional-permit',{conditions:[{type:'step-up-authentication',key:'strength',value:'hardware-backed'},{type:'no-export',key:'export',value:'forbidden'}],restrictions:['minimum-fields'],obligations:['enhanced-audit']});expect(await fixture([conditional]).platform.authorize(request())).toMatchObject({outcome:'conditional-permit',authorized:true});expect((await fixture([policy('not-applicable')]).platform.authorize(request())).outcome).toBe('not-applicable');const unavailable={resolve:async()=>{throw new Error('policy engine unavailable');}};const f=fixture();const platform=new SecurityPlatform(unavailable,new BasicSecurityPolicyEvaluator(),new ExplicitDenyConflictResolver(),f.delegations,f.revocations,f.cache,f.diagnostics,f.events,{decided:vi.fn(),cache:vi.fn(),failed:vi.fn()},f.audit,()=>new Date('2026-08-06T00:00:00.000Z'));expect(await platform.authorize(request())).toMatchObject({outcome:'indeterminate',authorized:false});});
  it('creates Security Contexts and the sole Foundation factory incorporates their authority unchanged',async()=>{const f=fixture();const decision=await f.platform.authorize(request());const security=f.platform.createSecurityContext(request(),decision,'security-context-1');const create:CreateExecutionContextRequest={executionId:'execution-1',correlationId:'correlation-1',tenantId:'tenant-1',workspaceId:'workspace-1',startedAt:'2026-08-06T00:00:00.000Z',configurationVersion:'configuration-1',securityContextId:security.id,securityContext:security};const context=new ExecutionContextFactory().create(create);expect(context.securityContext).toEqual(security);expect(Object.isFrozen(context.securityContext)).toBe(true);});
  it('enforces tenant, workspace, and project isolation and fails closed',async()=>{for(const altered of [{scope:{tenantId:'other'}},{scope:{tenantId:'tenant-1',workspaceId:'other'}},{scope:{tenantId:'tenant-1',workspaceId:'workspace-1',projectId:'other'}}])await expect(fixture().platform.authorize(request(altered))).rejects.toMatchObject({code:'SECURITY_SCOPE_VIOLATION'});});
  it('keeps delegation bounded, expiring, depth-limited, and revocable while constraining agents',async()=>{const agent:Principal={...principal,id:'agent-1',type:'agent',permissions:['capability.answer','capability.admin'],agentAuthority:{initiatingPrincipalId:'user-1',allowedCapabilities:['capability.answer'],allowedTools:[],executionRestrictions:['no-export'],delegationIds:['delegation-1']}};const grant:DelegationGrant={id:'delegation-1',delegatingPrincipalId:'user-1',receivingPrincipalId:'agent-1',actions:['execute'],resourceTypes:['capability'],resourceIds:['capability:answer'],tenantId:'tenant-1',workspaceIds:['workspace-1'],projectIds:['project-1'],conditions:[],restrictions:['no-export'],depth:1,maximumDepth:1,allowRedelegation:false,issuedAt:'2026-08-05T00:00:00.000Z',expiresAt:'2026-08-07T00:00:00.000Z',policyReferences:['policy-permit'],version:'delegation-1'};const f=fixture([policy('permit',{principalTypes:['agent'],requiredRoles:[]})]);f.delegations.save(grant);const decision=await f.platform.authorize(request({principal:agent,delegationIds:['delegation-1']}));expect(decision).toMatchObject({outcome:'permit',restrictions:['no-export']});const context=f.platform.createSecurityContext(request({principal:agent,delegationIds:['delegation-1']}),decision,'1');expect(context.effectivePermissions).toEqual(['capability.answer']);await expect(f.platform.authorize(request({principal:agent,delegationIds:['delegation-1'],capabilityRequirements:['capability.admin'],requestId:'self-escalation'}))).resolves.toMatchObject({authorized:false});f.platform.revoke({id:'revoke-delegation',subjectType:'delegation',subjectId:'delegation-1',scope:'all',effectiveAt:'2026-08-06T00:00:00.000Z',reason:'withdrawn',version:'1'});await expect(f.platform.authorize(request({principal:agent,delegationIds:['delegation-1'],requestId:'after-revoke'}))).rejects.toMatchObject({code:'SECURITY_DELEGATION_INVALID'});});
  it('keeps impersonation explicit, time-bounded, and fully audited',async()=>{const impersonation={authorizationDecisionId:'admin-decision',originalPrincipalId:'user-1',impersonatedPrincipalId:'user-2',reason:'incident investigation',issuedAt:'2026-08-05T23:00:00.000Z',expiresAt:'2026-08-06T01:00:00.000Z',auditReference:'impersonation-audit-1'};const f=fixture();const decision=await f.platform.authorize(request({impersonation}));expect(decision.effectivePrincipalId).toBe('user-2');expect(f.audit.records[0]).toMatchObject({principalId:'user-1',effectivePrincipalId:'user-2',impersonationReference:'impersonation-audit-1'});});
  it('does not treat capabilities, tool credentials, or plugin declarations as authorization',async()=>{const denied=await fixture([]).platform.authorize(request({environmental:{credentialReference:'credential:tool'},toolPermissions:['payment.charge'],capabilityRequirements:['capability.answer']}));expect(denied.authorized).toBe(false);const adapter=new SecurityPluginPermissionAdapter(async()=>denied);await expect(adapter.authorize('plugin-1',['network'])).resolves.toMatchObject({authorized:false,reason:'Plugin permissions denied'});});
  it('preserves labels, policy versions, cache dimensions, expiration, and reauthorization',async()=>{const f=fixture();const first=await f.platform.authorize(request());const cached=await f.platform.authorize(request());expect(cached).toBe(first);const changed=await f.platform.authorize(request({environmental:{network:'external'}}));expect(changed.cacheKey).not.toBe(first.cacheKey);expect(first.policyVersions).toEqual(['policy-1']);const context=f.platform.createSecurityContext(request(),first,'context-1');expect(context.securityLabels).toEqual(['public']);f.advance(300001);expect(f.platform.validity(first).state).toBe('expired');expect(()=>f.platform.createSecurityContext(request(),first,'context-2')).toThrow();const refreshed=await fixture().platform.authorize(request({requestId:'reauthorized'}));expect(refreshed.id).not.toBe(first.id);});
  it('revokes current authority and cache validity without mutating historical decisions',async()=>{const f=fixture();const decision=await f.platform.authorize(request());const snapshot=JSON.stringify(decision);f.platform.revoke({id:'revocation-1',subjectType:'decision',subjectId:decision.id,scope:'all',effectiveAt:'2026-08-06T00:00:00.000Z',reason:'policy-change',version:'1'});expect(f.platform.validity(decision).state).toBe('revoked');expect(JSON.stringify(decision)).toBe(snapshot);expect(()=>{enforce(decision,f.platform.validity(decision));}).toThrow();});
  it('uses secret references and conditional obligations without exposing secret values',async()=>{const reference={id:'secret-reference-1',providerReference:'secret-store:key-1',purpose:'tool-authentication',tenantId:'tenant-1',expiresAt:'2026-08-06T01:00:00.000Z',authorizationDecisionId:'decision-1'};expect(reference).not.toHaveProperty('value');expect(JSON.stringify(reference)).not.toMatch(/password|apiKey|token/iu);const conditional=await fixture([policy('conditional-permit',{conditions:[{type:'consent',key:'consent-version',value:'2'},{type:'field-mask',key:'fields',value:'email'}]})]).platform.authorize(request());expect(conditional.conditions.map(value=>value.type)).toEqual(['consent','field-mask']);});
  it('provides events, protected diagnostics, telemetry, audit, health, and non-authoritative simulation',async()=>{const f=fixture();const decision=await f.platform.authorize(request());expect(f.events.facts.map(value=>value.type)).toEqual(['authorization.requested','authorization.permitted']);expect(f.diagnostics.list()[0]).toMatchObject({outcome:'permit',conflictResolution:'explicit-deny-precedence'});expect(f.decided).toHaveBeenCalledWith('permit','human','capability');expect(f.audit.records).toHaveLength(1);expect(await f.platform.health()).toEqual({name:'security-platform',status:'healthy',policyVersion:'resolved-per-request',revocationVersion:0});expect(JSON.stringify(f.diagnostics.list())).not.toMatch(/engineering|credential|secret/iu);const simulation=new DeterministicSecurityPolicySimulator(new BasicSecurityPolicyEvaluator(),new ExplicitDenyConflictResolver()).simulate(request(),[policy()],[]);expect(simulation).toMatchObject({authoritative:false,outcome:'permit'});expect(decision.authorized).toBe(true);});
  it('adapts current Security Context validity into Runtime authorization without redefining authority',async()=>{const f=fixture();const decision=await f.platform.authorize(request());const security=f.platform.createSecurityContext(request(),decision,'1');const contexts=new Map([[security.id,security]]);const adapter=new SecurityRuntimeAdapter(contexts,id=>id===decision.id?f.platform.validity(decision).state:'revoked');const context=new ExecutionContextFactory().create({executionId:'execution-1',correlationId:'correlation-1',configurationVersion:'configuration-1',securityContextId:security.id,securityContext:security});expect(await adapter.authorize(context)).toEqual({authorized:true,decisionId:decision.id});f.platform.revoke({id:'revoke',subjectType:'decision',subjectId:decision.id,scope:'all',effectiveAt:'2026-08-06T00:00:00.000Z',reason:'revoked',version:'1'});expect(await adapter.authorize(context)).toEqual({authorized:false,decisionId:decision.id});});
});



