import {describe,expect,it,vi} from 'vitest';
import {createPlatformEvent,createSubscription,EventBus,EventBusError,ExternalMessagingError,FoundationEventPublisherAdapter,OutboxPublisher,type EventDelivery,type EventSubscriber,type EventSubscription,type EventVisibilityDecision,type PlatformEvent} from './index.js';
import {DeterministicEventRouter,IdempotentSubscriber,InMemoryDeadLetterStore,InMemoryDeliveryJournal,InMemoryEventBusDiagnostics,InMemoryEventBusTelemetry,InMemoryPublicationIntentStore,InMemoryReplayAudit,InMemoryReplayStore,InMemorySubscriberInbox,InMemorySubscriptionRegistry,StaticVisibilityAuthorizer} from './reference.js';

const now=():Date=>new Date('2026-08-06T00:00:00.000Z');
const decision:EventVisibilityDecision={decisionId:'decision:observe',authorized:true,state:'active',tenantId:'tenant-1',workspaceIds:['workspace-1'],projectIds:['project-1'],maximumClassification:'restricted',allowedLabels:['operations'],policyVersion:'security-1'};
function event(overrides:Record<string,unknown>={}):PlatformEvent{return createPlatformEvent({eventId:'event-1',type:'workflow.completed',contractVersion:'1',occurredAt:'2026-08-06T00:00:00.000Z',producer:'workflow',correlationId:'execution-1',causationId:null,orderingKey:{value:'workflow-1',scope:'workflow'},executionReference:'execution-1',scope:{tenantId:'tenant-1',workspaceId:'workspace-1',projectId:'project-1'},security:{classification:'confidential',labels:['operations'],authorizationReference:'source-decision'},payload:{workflowId:'workflow-1'},source:{component:'workflow'},provenance:['workflow-engine'],retention:{category:'replayable',expiresAt:'2027-08-06T00:00:00.000Z',policyVersion:'retention-1'},...overrides});}
function subscription(overrides:Partial<EventSubscription>={}):EventSubscription{return createSubscription({id:'subscription-1',subscriberId:'subscriber-1',principalId:'principal-1',eventTypes:['workflow.*'],contractVersions:['1'],scope:{tenantId:'tenant-1',workspaceId:'workspace-1',projectId:'project-1'},filter:{classifications:['confidential']},authorizationReference:'decision:observe',deliveryGuarantee:'at-least-once',ordering:'ordering-key',replayCapability:'replay-safe',retry:{maximumAttempts:2,retryableCategories:['transport','timeout','unknown'],policyVersion:'retry-1'},flow:{maximumConcurrency:1,queueCapacity:10,batchSize:1,overflow:'persist-backlog',policyVersion:'flow-1'},compatibleSchemaVersions:['1'],enabled:true,metadata:{owner:'test'},...overrides});}
interface Fixture{readonly bus:EventBus;readonly registry:InMemorySubscriptionRegistry;readonly replay:InMemoryReplayStore;readonly deadLetters:InMemoryDeadLetterStore;readonly journal:InMemoryDeliveryJournal;readonly diagnostics:InMemoryEventBusDiagnostics;readonly telemetry:InMemoryEventBusTelemetry;readonly audit:InMemoryReplayAudit;readonly subscriber:EventSubscriber;}
function fixture(subscriber:EventSubscriber=new IdempotentSubscriber('subscriber-1',new InMemorySubscriberInbox()),visibility:EventVisibilityDecision=decision):Fixture{let id=0;const registry=new InMemorySubscriptionRegistry(),replay=new InMemoryReplayStore(),deadLetters=new InMemoryDeadLetterStore(),journal=new InMemoryDeliveryJournal(),diagnostics=new InMemoryEventBusDiagnostics(),telemetry=new InMemoryEventBusTelemetry(),audit=new InMemoryReplayAudit();const bus=new EventBus({registry,router:new DeterministicEventRouter(),visibility:new StaticVisibilityAuthorizer(new Map([[visibility.decisionId,visibility]])),replay,deadLetters,journal,diagnostics,telemetry,replayAudit:audit,now,id:():string=>`delivery-${String(++id)}`,maximumChainDepth:8});bus.register(subscription(),subscriber);return{bus,registry,replay,deadLetters,journal,diagnostics,telemetry,audit,subscriber};}

describe('Blueprint 16 event contracts',()=>{
 it('creates a deeply immutable, provider-independent logical fact',()=>{const value=event();expect(Object.isFrozen(value)).toBe(true);expect(Object.isFrozen(value.payload)).toBe(true);expect(value.causationId).toBeNull();expect(()=>{(value.scope as{tenantId:string}).tenantId='other';}).toThrow();expect(JSON.stringify(value)).not.toMatch(/kafka|rabbit|redis/i);});
 it('rejects commands, unbounded payloads, cycles, and mutable publication',async()=>{expect(()=>event({type:'invoke.tool'})).toThrowError(EventBusError);expect(()=>event({payload:{value:'x'.repeat(100)},maximumPayloadBytes:4})).toThrowError(/bounded/);expect(()=>event({causationId:'event-1'})).toThrowError(/cause itself/);const{bus}=fixture();await expect(bus.publish({...event()})).rejects.toMatchObject({code:'EVENT_INVALID'});});
 it('supports secure external references and explicit retention without secret values',()=>{const value=event({payload:undefined,payloadReference:{referenceId:'artifact-1',storageProviderReference:'store-ref',version:'1',classification:'restricted',authorizationReference:'decision:artifact'}});expect(value.payloadReference?.referenceId).toBe('artifact-1');expect(JSON.stringify(value)).not.toContain('secretValue');});
 it('requires explicit normalized subscription delivery, ordering, retry, flow, and compatibility policies',()=>{const value=subscription();expect(value.deliveryGuarantee).toBe('at-least-once');expect(value.ordering).toBe('ordering-key');expect(value.flow.overflow).toBe('persist-backlog');expect(()=>subscription({flow:{...value.flow,queueCapacity:0}})).toThrowError(/invalid/);});
});

describe('publication, routing, security, and isolation',()=>{
 it('routes deterministically and keeps publishers unaware of subscribers',async()=>{const{bus,registry}=fixture();const second=new IdempotentSubscriber('subscriber-2',new InMemorySubscriberInbox());bus.register(subscription({id:'subscription-0',subscriberId:'subscriber-2'}),second);expect(registry.list().map(value=>value.id)).toEqual(['subscription-0','subscription-1']);const result=await bus.publish(event());expect(result).toMatchObject({routed:2,delivered:2,failed:0});});
 it('filters by version, metadata, tenant, and workspace before delivery',async()=>{const{bus,subscriber}=fixture();expect((await bus.publish(event({contractVersion:'2'}))).routed).toBe(0);expect((await bus.publish(event({scope:{tenantId:'other',workspaceId:'workspace-1'}}))).routed).toBe(0);expect((subscriber as IdempotentSubscriber).deliveries).toHaveLength(0);});
 it('enforces Blueprint 15 outcome and never infers permission from registration',async()=>{const denied={...decision,authorized:false};const{bus}=fixture(undefined,denied);const result=await bus.publish(event());expect(result.records[0]).toMatchObject({status:'filtered'});expect(result.delivered).toBe(0);});
 it('enforces classification, labels, and current authority fail closed',async()=>{const restricted={...decision,maximumClassification:'internal' as const};const{bus}=fixture(undefined,restricted);expect((await bus.publish(event())).filtered).toBe(1);const revoked={...decision,state:'revoked' as const};expect((await fixture(undefined,revoked).bus.publish(event())).filtered).toBe(1);});
 it('isolates slow and failing subscribers',async()=>{let release!:()=>void;const slow:EventSubscriber={id:'subscriber-1',handle:():Promise<'acknowledged'>=>new Promise(resolve=>{release=():void=>{resolve('acknowledged');};})};const{bus}=fixture(slow);const fast=vi.fn(async():Promise<'acknowledged'>=>'acknowledged');bus.register(subscription({id:'subscription-fast',subscriberId:'subscriber-fast'}),{id:'subscriber-fast',handle:fast});const pending=bus.publish(event());await vi.waitFor(()=>{expect(fast).toHaveBeenCalled();});release();expect((await pending).delivered).toBe(2);});
});

describe('delivery reliability and governance',()=>{
 it('uses stable event identity and unique delivery identity for retry without business retry',async()=>{let calls=0;const subscriber:EventSubscriber={id:'subscriber-1',handle:async delivery=>{calls++;expect(delivery.event.eventId).toBe('event-1');if(calls===1)throw new ExternalMessagingError('transport','temporary');return'acknowledged';}};const{bus}=fixture(subscriber);const result=await bus.publish(event());expect(result.records.map(value=>value.deliveryId)).toEqual(['delivery-1','delivery-2']);expect(result.records.map(value=>value.eventId)).toEqual(['event-1','event-1']);expect(calls).toBe(2);});
 it('supports subscriber idempotency under duplicate at-least-once delivery',async()=>{const handler=vi.fn(async()=>{}),subscriber=new IdempotentSubscriber('subscriber-1',new InMemorySubscriberInbox(),handler);const{bus}=fixture(subscriber);await bus.publish(event());await bus.publish(event());expect(handler).toHaveBeenCalledTimes(1);});
 it('isolates poison events and preserves immutable events in dead letters',async()=>{const poison:EventSubscriber={id:'subscriber-1',handle:async()=>{throw new ExternalMessagingError('poison','bad event');}};const{bus,deadLetters}=fixture(poison);const value=event();const result=await bus.publish(value);expect(result.failed).toBe(1);expect(deadLetters.list()[0]?.event).toBe(value);expect(Object.isFrozen(deadLetters.list()[0])).toBe(true);});
 it('enforces explicit ordering keys where declared',async()=>{const{bus}=fixture();const result=await bus.publish(event({orderingKey:undefined}));expect(result.records[0]).toMatchObject({status:'failed'});});
 it('normalizes unknown messaging failures and exposes diagnostics, telemetry, and health',async()=>{const broken:EventSubscriber={id:'subscriber-1',handle:async()=>{throw new Error('provider detail');}};const{bus,diagnostics,telemetry}=fixture(broken);await bus.publish(event());expect(diagnostics.list().some(value=>value.errorCode==='DELIVERY_FAILED')).toBe(true);expect(telemetry.counters.get('dead-lettered')).toBe(1);expect(await bus.health()).toMatchObject({name:'event-bus',status:'degraded',deadLetters:1});});
});

describe('replay, retention, recursion, and transactional publication',()=>{
 it('replays the original fact with new delivery identity and audited metadata',async()=>{const handle=async(delivery:EventDelivery):Promise<'acknowledged'>=>{if(delivery.mode==='replay'){expect(delivery.event.eventId).toBe('event-1');expect(delivery.replay?.originalPublishedAt).toBe(delivery.event.occurredAt);}return'acknowledged';};const subscriber:EventSubscriber={id:'subscriber-1',handle:vi.fn(handle)};const{bus,audit}=fixture(subscriber);await bus.publish(event());const result=await bus.replay({replayId:'replay-1',requestingPrincipalId:'admin',subscriptionId:'subscription-1',eventTypes:['workflow.completed'],scope:{tenantId:'tenant-1',workspaceId:'workspace-1',projectId:'project-1'},from:'2026-08-05T00:00:00.000Z',to:'2026-08-07T00:00:00.000Z',correlationIds:['execution-1'],purpose:'diagnostics',authorizationReference:'decision:observe',allowExternalSideEffects:false});expect(result.records[0]).toMatchObject({eventId:'event-1',mode:'replay',replayId:'replay-1'});expect(audit.records).toHaveLength(1);});
 it('rejects replay-unsafe subscribers and invalid replay authority',async()=>{const{bus}=fixture();bus.register(subscription({id:'no-replay',subscriberId:'no-replay',replayCapability:'prohibited'}),{id:'no-replay',handle:async()=> 'acknowledged'});await expect(bus.replay({replayId:'r',requestingPrincipalId:'p',subscriptionId:'no-replay',eventTypes:[],scope:{tenantId:'tenant-1'},from:'2026-01-01T00:00:00.000Z',to:'2027-01-01T00:00:00.000Z',correlationIds:[],purpose:'unsafe',authorizationReference:'decision:observe',allowExternalSideEffects:false})).rejects.toMatchObject({code:'REPLAY_UNSAFE'});});
 it('expires replay availability by retention policy without mutating history',()=>{const store=new InMemoryReplayStore(),value=event({retention:{category:'operational',expiresAt:'2026-08-07T00:00:00.000Z',policyVersion:'1'}});store.append(value);expect(store.expire('2026-08-08T00:00:00.000Z')).toBe(1);expect(value.retention.expiresAt).toBe('2026-08-07T00:00:00.000Z');});
 it('prevents excessive event chains and self-causation',async()=>{expect(()=>event({chainDepth:65})).toThrowError(/depth/);const{bus}=fixture();await expect(bus.publish(event({chainDepth:9}))).rejects.toMatchObject({code:'EVENT_CHAIN_LIMIT'});});
 it('recovers committed outbox intent while ignoring rolled-back intent and preserving identity',async()=>{const store=new InMemoryPublicationIntentStore(),telemetry=new InMemoryEventBusTelemetry(),value=event();store.add({id:'intent-1',event:value,committed:true,createdAt:value.occurredAt,attempts:0});store.add({id:'intent-2',event:event({eventId:'event-2'}),committed:false,createdAt:value.occurredAt,attempts:0});const publish=vi.fn().mockRejectedValueOnce(new Error('down')).mockResolvedValue(undefined);const outbox=new OutboxPublisher(store,publish,telemetry,now);expect(await outbox.flush()).toEqual({published:0,pending:1});expect(await outbox.flush()).toEqual({published:1,pending:0});expect(publish.mock.calls.map(call=>(call[0] as typeof value).eventId)).toEqual(['event-1','event-1']);expect(store.get('intent-2')?.publishedAt).toBeUndefined();});
 it('adapts the Foundation bootstrap publisher into the final Event Bus contract',async()=>{const{bus}=fixture();const adapter=new FoundationEventPublisherAdapter(bus,{producer:'foundation',scope:{tenantId:'tenant-1',workspaceId:'workspace-1',projectId:'project-1'},security:{classification:'confidential',labels:['operations'],authorizationReference:'source'},retention:{category:'operational',policyVersion:'1'}});await adapter.publish({eventId:'foundation-1',type:'workflow.completed',version:1,occurredAt:'2026-08-06T00:00:00.000Z',correlationId:'execution-1',payload:{ok:true}});expect((await bus.health()).status).toBe('healthy');});
});
