import type { EventPublisher as FoundationEventPublisher, PlatformEvent as FoundationPlatformEvent } from '@agentprodready/foundation';

import type { AuthorityState } from '@agentprodready/security';

export type DeliveryGuarantee='best-effort'|'at-most-once'|'at-least-once'|'exactly-once-capable';
export type OrderingMode='unordered'|'ordering-key';
export type ReplayCapability='replay-safe'|'diagnostic-only'|'read-model-rebuild'|'administrative-only'|'prohibited';
export type OverflowAction='reject'|'delay'|'persist-backlog'|'throttle'|'isolate-subscriber'|'dead-letter'|'drop-disposable';
export type RetentionCategory='ephemeral'|'operational'|'replayable'|'audit-relevant'|'compliance-controlled'|'permanent';
export type Classification='public'|'internal'|'confidential'|'restricted';
export interface EventScope{readonly tenantId:string;readonly workspaceId?:string;readonly projectId?:string;}
export interface CauseReference{readonly type:'runtime-step'|'user-request'|'workflow-transition'|'external-callback'|'scheduled-operation'|'other';readonly id:string;readonly executionId?:string;readonly producer?:string;}
export interface OrderingKey{readonly value:string;readonly scope:'execution'|'workflow'|'aggregate'|'resource'|'tenant'|'subscription';}
export interface RetentionPolicy{readonly category:RetentionCategory;readonly expiresAt?:string;readonly policyVersion:string;}
export interface SecurePayloadReference{readonly referenceId:string;readonly storageProviderReference:string;readonly version:string;readonly classification:Classification;readonly expiresAt?:string;readonly authorizationReference:string;}
export interface EventSecurity{readonly classification:Classification;readonly labels:readonly string[];readonly authorizationReference:string;}
export interface PlatformEvent<T=unknown>{readonly eventId:string;readonly type:string;readonly contractVersion:string;readonly schemaVersion:string;readonly occurredAt:string;readonly producer:string;readonly correlationId:string;readonly causationId:string|null;readonly causeReference?:CauseReference;readonly orderingKey?:OrderingKey;readonly executionReference?:string;readonly scope:EventScope;readonly security:EventSecurity;readonly payload?:T;readonly payloadReference?:SecurePayloadReference;readonly source:Readonly<Record<string,string>>;readonly provenance:readonly string[];readonly retention:RetentionPolicy;readonly chainDepth:number;}
export interface CreatePlatformEvent<T>{readonly eventId:string;readonly type:string;readonly contractVersion:string;readonly schemaVersion?:string;readonly occurredAt:string;readonly producer:string;readonly correlationId:string;readonly causationId?:string|null;readonly causeReference?:CauseReference;readonly orderingKey?:OrderingKey;readonly executionReference?:string;readonly scope:EventScope;readonly security:EventSecurity;readonly payload?:T;readonly payloadReference?:SecurePayloadReference;readonly source?:Readonly<Record<string,string>>;readonly provenance?:readonly string[];readonly retention:RetentionPolicy;readonly chainDepth?:number;readonly maximumPayloadBytes?:number;}
export interface EventFilter{readonly producers?:readonly string[];readonly correlationIds?:readonly string[];readonly classifications?:readonly Classification[];readonly labels?:readonly string[];}
export interface MessagingRetryPolicy{readonly maximumAttempts:number;readonly retryableCategories:readonly DeliveryFailureCategory[];readonly policyVersion:string;}
export interface FlowControlPolicy{readonly maximumConcurrency:number;readonly queueCapacity:number;readonly batchSize:number;readonly overflow:OverflowAction;readonly policyVersion:string;}
export interface EventVisibilityDecision{readonly decisionId:string;readonly authorized:boolean;readonly state:AuthorityState;readonly tenantId:string;readonly workspaceIds:readonly string[];readonly projectIds:readonly string[];readonly maximumClassification:Classification;readonly allowedLabels:readonly string[];readonly policyVersion:string;}
export interface EventVisibilityAuthorizer{authorize(event:PlatformEvent,subscription:EventSubscription,operation:'live'|'replay'):Promise<EventVisibilityDecision>;}
export interface EventSubscription{readonly id:string;readonly subscriberId:string;readonly principalId:string;readonly eventTypes:readonly string[];readonly contractVersions:readonly string[];readonly scope:EventScope;readonly filter:EventFilter;readonly authorizationReference:string;readonly deliveryGuarantee:DeliveryGuarantee;readonly ordering:OrderingMode;readonly replayCapability:ReplayCapability;readonly retry:MessagingRetryPolicy;readonly flow:FlowControlPolicy;readonly compatibleSchemaVersions:readonly string[];readonly enabled:boolean;readonly metadata:Readonly<Record<string,string>>;}
export interface EventSubscriber{readonly id:string;handle(delivery:EventDelivery):Promise<'acknowledged'|'rejected'>;}
export interface SubscriptionRegistry{register(subscription:EventSubscription,subscriber:EventSubscriber):void;unregister(id:string):void;get(id:string):EventSubscription|undefined;subscriber(id:string):EventSubscriber|undefined;list():readonly EventSubscription[];}
export interface EventRouter{route(event:PlatformEvent,subscriptions:readonly EventSubscription[]):readonly EventSubscription[];}
export type DeliveryFailureCategory='subscriber-rejected'|'subscriber-unavailable'|'timeout'|'transport'|'overflow'|'security'|'replay-unsafe'|'version-incompatible'|'poison'|'unknown';
export type DeliveryMode='live'|'retry'|'replay';
export interface ReplayMetadata{readonly replayId:string;readonly replayedAt:string;readonly initiatorPrincipalId:string;readonly reason:string;readonly originalPublishedAt:string;}
export interface EventDelivery{readonly deliveryId:string;readonly event:PlatformEvent;readonly subscriptionId:string;readonly subscriberId:string;readonly attempt:number;readonly deliveredAt:string;readonly mode:DeliveryMode;readonly replay?:ReplayMetadata;}
export interface DeliveryRecord{readonly deliveryId:string;readonly eventId:string;readonly subscriptionId:string;readonly subscriberId:string;readonly attempt:number;readonly deliveredAt:string;readonly mode:DeliveryMode;readonly replayId?:string;readonly status:'acknowledged'|'rejected'|'failed'|'dead-lettered'|'filtered';readonly failureCategory?:DeliveryFailureCategory;readonly diagnosticId:string;}
export interface DeadLetterRecord{readonly id:string;readonly event:PlatformEvent;readonly subscriptionId:string;readonly failure:DeliveryFailure;readonly recordedAt:string;readonly deliveryIds:readonly string[];}
export interface DeliveryFailure{readonly category:DeliveryFailureCategory;readonly code:EventBusErrorCode;readonly message:string;readonly retryable:boolean;}
export interface ReplayRequest{readonly replayId:string;readonly requestingPrincipalId:string;readonly subscriptionId:string;readonly eventTypes:readonly string[];readonly scope:EventScope;readonly from:string;readonly to:string;readonly correlationIds:readonly string[];readonly purpose:string;readonly authorizationReference:string;readonly allowExternalSideEffects:boolean;}
export interface ReplayAudit{record(request:ReplayRequest,result:Readonly<{delivered:number;filtered:number;rejected:number}>):Promise<void>;}
export interface ReplayStore{append(event:PlatformEvent):void;query(request:ReplayRequest):readonly PlatformEvent[];expire(at:string):number;}
export interface DeadLetterStore{record(value:DeadLetterRecord):void;list(subscriptionId?:string):readonly DeadLetterRecord[];}
export interface DeliveryJournal{record(value:DeliveryRecord):void;list(eventId?:string):readonly DeliveryRecord[];}
export interface SubscriberInbox{has(eventId:string):boolean;mark(eventId:string):void;}
export interface EventBusDiagnostic{readonly id:string;readonly eventId:string;readonly phase:'publication'|'routing'|'delivery'|'replay'|'dead-letter'|'outbox';readonly outcome:'completed'|'failed'|'filtered'|'pending';readonly subscriptionId?:string;readonly deliveryId?:string;readonly errorCode?:EventBusErrorCode;readonly correlationId:string;}
export interface EventBusDiagnostics{record(value:EventBusDiagnostic):void;list():readonly EventBusDiagnostic[];}
export interface EventBusTelemetry{published(eventType:string):void;delivery(status:DeliveryRecord['status'],durationMs:number):void;replayed(count:number):void;deadLettered():void;backpressure(subscriptionId:string):void;outbox(status:'published'|'pending'):void;}
export interface EventBusHealth{health():Promise<Readonly<{name:'event-bus';status:'healthy'|'degraded'|'unhealthy';subscriptions:number;deadLetters:number;replayAvailable:boolean}>>;}
export type EventBusErrorCode='EVENT_INVALID'|'EVENT_NOT_FACT'|'EVENT_PAYLOAD_TOO_LARGE'|'EVENT_VERSION_INCOMPATIBLE'|'SUBSCRIPTION_INVALID'|'SUBSCRIPTION_DUPLICATE'|'SUBSCRIBER_UNAVAILABLE'|'DELIVERY_FAILED'|'DELIVERY_OVERFLOW'|'EVENT_UNAUTHORIZED'|'REPLAY_UNAUTHORIZED'|'REPLAY_UNSAFE'|'EVENT_CHAIN_LIMIT'|'EVENT_CYCLE'|'OUTBOX_NOT_COMMITTED'|'OUTBOX_PUBLICATION_FAILED'|'EVENT_UNKNOWN';
export class EventBusError extends Error{public constructor(public readonly code:EventBusErrorCode,message:string,public readonly diagnosticId:string,options?:ErrorOptions){super(message,options);this.name='EventBusError';}}
export class ExternalMessagingError extends Error{public constructor(public readonly category:DeliveryFailureCategory,message:string){super(message);this.name='ExternalMessagingError';}}
export interface PublicationResult{readonly eventId:string;readonly routed:number;readonly delivered:number;readonly failed:number;readonly filtered:number;readonly records:readonly DeliveryRecord[];}
export interface EventTransport{publish(event:PlatformEvent):Promise<void>;}
export interface PublicationIntent{readonly id:string;readonly event:PlatformEvent;readonly committed:boolean;readonly createdAt:string;readonly publishedAt?:string;readonly attempts:number;readonly errorCode?:EventBusErrorCode;}
/** Future owner: Blueprint 24 / originating domain persistence boundary. */
export interface PublicationIntentStore{pending():readonly PublicationIntent[];markPublished(id:string,at:string):void;markFailed(id:string,code:EventBusErrorCode):void;}

export interface EventBusDependencies{readonly registry:SubscriptionRegistry;readonly router:EventRouter;readonly visibility:EventVisibilityAuthorizer;readonly replay:ReplayStore;readonly deadLetters:DeadLetterStore;readonly journal:DeliveryJournal;readonly diagnostics:EventBusDiagnostics;readonly telemetry:EventBusTelemetry;readonly replayAudit:ReplayAudit;readonly now?:()=>Date;readonly id?:()=>string;readonly maximumChainDepth?:number;}

const classifications:readonly Classification[]=['public','internal','confidential','restricted'];
export function createPlatformEvent<T>(input:CreatePlatformEvent<T>):PlatformEvent<T>{const id=`event:${input.eventId}`;if(blank(input.eventId)||blank(input.type)||blank(input.producer)||blank(input.correlationId)||blank(input.scope.tenantId)||blank(input.contractVersion)||!Number.isFinite(Date.parse(input.occurredAt)))throw new EventBusError('EVENT_INVALID','Required event metadata is invalid',id);if(/^(execute|invoke|build|start|retry|schedule|cancel)[._-]/i.test(input.type))throw new EventBusError('EVENT_NOT_FACT','The Event Bus accepts facts, not commands',id);if((input.payload===undefined)===(input.payloadReference===undefined))throw new EventBusError('EVENT_INVALID','Exactly one payload form is required',id);const bytes=input.payload===undefined?0:new TextEncoder().encode(serialized(input.payload,id)).byteLength;if(bytes>(input.maximumPayloadBytes??65536))throw new EventBusError('EVENT_PAYLOAD_TOO_LARGE','Inline payload exceeds its bounded contract',id);const depth=input.chainDepth??0;if(depth<0||depth>64)throw new EventBusError('EVENT_CHAIN_LIMIT','Event chain depth is outside the contract',id);if(input.causationId===input.eventId)throw new EventBusError('EVENT_CYCLE','An event cannot cause itself',id);return freeze({eventId:input.eventId,type:input.type,contractVersion:input.contractVersion,schemaVersion:input.schemaVersion??'1',occurredAt:input.occurredAt,producer:input.producer,correlationId:input.correlationId,causationId:input.causationId??null,...optional('causeReference',copy(input.causeReference)),...optional('orderingKey',copy(input.orderingKey)),...optional('executionReference',input.executionReference),scope:copy(input.scope),security:copy(input.security),...optional('payload',copy(input.payload)),...optional('payloadReference',copy(input.payloadReference)),source:copy(input.source??{}),provenance:[...(input.provenance??[])],retention:copy(input.retention),chainDepth:depth});}

export function createSubscription(input:EventSubscription):EventSubscription{if(blank(input.id)||blank(input.subscriberId)||blank(input.principalId)||input.eventTypes.length===0||blank(input.scope.tenantId)||input.retry.maximumAttempts<1||input.flow.maximumConcurrency<1||input.flow.queueCapacity<1||input.flow.batchSize<1)throw new EventBusError('SUBSCRIPTION_INVALID','Subscription contract is invalid',`subscription:${input.id}`);return freeze(copy(input));}

export class EventBus implements EventBusHealth{
 public constructor(private readonly dependencies:EventBusDependencies){}
 public register(subscription:EventSubscription,subscriber:EventSubscriber):void{if(subscription.subscriberId!==subscriber.id)throw new EventBusError('SUBSCRIPTION_INVALID','Subscriber identity mismatch',`subscription:${subscription.id}`);this.dependencies.registry.register(createSubscription(subscription),subscriber);}
 public async publish(event:PlatformEvent):Promise<PublicationResult>{const started=Date.now();validateFrozenEvent(event,this.dependencies.maximumChainDepth??32);this.dependencies.replay.append(event);this.dependencies.telemetry.published(event.type);this.dependencies.diagnostics.record(diag(event,'publication','completed'));const eligible=this.dependencies.router.route(event,this.dependencies.registry.list());const records=(await Promise.all(eligible.map(subscription=>this.#deliver(event,subscription,'live')))).flat();this.dependencies.telemetry.delivery(records.some(value=>value.status==='failed'||value.status==='dead-lettered')?'failed':'acknowledged',Date.now()-started);return freeze({eventId:event.eventId,routed:eligible.length,delivered:records.filter(value=>value.status==='acknowledged').length,failed:records.filter(value=>value.status==='failed'||value.status==='dead-lettered').length,filtered:records.filter(value=>value.status==='filtered').length,records});}
 public async replay(request:ReplayRequest):Promise<PublicationResult>{const subscription=this.dependencies.registry.get(request.subscriptionId);if(subscription===undefined)throw new EventBusError('SUBSCRIBER_UNAVAILABLE','Replay subscription is unavailable',`replay:${request.replayId}`);if(subscription.replayCapability==='prohibited'||(!request.allowExternalSideEffects&&subscription.replayCapability==='administrative-only'))throw new EventBusError('REPLAY_UNSAFE','Subscriber does not support the requested replay',`replay:${request.replayId}`);const records:DeliveryRecord[]=[];let filtered=0;for(const event of this.dependencies.replay.query(request)){const delivered=await this.#deliver(event,subscription,'replay',request);records.push(...delivered);filtered+=delivered.filter(value=>value.status==='filtered').length;}const result=freeze({eventId:`replay:${request.replayId}`,routed:1,delivered:records.filter(value=>value.status==='acknowledged').length,failed:records.filter(value=>value.status==='failed'||value.status==='dead-lettered').length,filtered,records});await this.dependencies.replayAudit.record(request,{delivered:result.delivered,filtered:result.filtered,rejected:result.failed});this.dependencies.telemetry.replayed(result.delivered);return result;}
 public async health():Promise<Readonly<{name:'event-bus';status:'healthy'|'degraded'|'unhealthy';subscriptions:number;deadLetters:number;replayAvailable:boolean}>>{return freeze({name:'event-bus',status:this.dependencies.deadLetters.list().length>0?'degraded':'healthy',subscriptions:this.dependencies.registry.list().length,deadLetters:this.dependencies.deadLetters.list().length,replayAvailable:true});}
 async #deliver(event:PlatformEvent,subscription:EventSubscription,mode:DeliveryMode,replayRequest?:ReplayRequest):Promise<DeliveryRecord[]>{const decision=await this.dependencies.visibility.authorize(event,subscription,mode==='replay'?'replay':'live');if(!visible(event,subscription,decision,replayRequest)){const record=this.#record(event,subscription,1,mode,'filtered',undefined,replayRequest);return[record];}if(subscription.ordering==='ordering-key'&&event.orderingKey===undefined){const record=this.#record(event,subscription,1,mode,'failed','unknown',replayRequest);return[record];}const subscriber=this.dependencies.registry.subscriber(subscription.id);if(subscriber===undefined)throw new EventBusError('SUBSCRIBER_UNAVAILABLE','Subscriber is unavailable',`delivery:${event.eventId}:${subscription.id}`);const records:DeliveryRecord[]=[];for(let attempt=1;attempt<=subscription.retry.maximumAttempts;attempt++){const deliveryId=this.dependencies.id?.()??`delivery:${event.eventId}:${subscription.id}:${String(attempt)}:${mode}`;const deliveredAt=(this.dependencies.now?.()??new Date()).toISOString();const delivery:EventDelivery=freeze({deliveryId,event,subscriptionId:subscription.id,subscriberId:subscription.subscriberId,attempt,deliveredAt,mode,...optional('replay',replayRequest===undefined?undefined:{replayId:replayRequest.replayId,replayedAt:deliveredAt,initiatorPrincipalId:replayRequest.requestingPrincipalId,reason:replayRequest.purpose,originalPublishedAt:event.occurredAt})});try{const outcome=await subscriber.handle(delivery);if(outcome==='acknowledged'){records.push(this.#record(event,subscription,attempt,mode,'acknowledged',undefined,replayRequest,deliveryId));break;}throw new ExternalMessagingError('subscriber-rejected','Subscriber rejected delivery');}catch(error){const failure=normalizeFailure(error);const final=attempt===subscription.retry.maximumAttempts||!failure.retryable||!subscription.retry.retryableCategories.includes(failure.category);const record=this.#record(event,subscription,attempt,mode,final?'dead-lettered':'failed',failure.category,replayRequest,deliveryId);records.push(record);if(final){this.dependencies.deadLetters.record(freeze({id:`dead-letter:${record.deliveryId}`,event,subscriptionId:subscription.id,failure,recordedAt:deliveredAt,deliveryIds:records.map(value=>value.deliveryId)}));this.dependencies.telemetry.deadLettered();break;}}}return records;}
 #record(event:PlatformEvent,subscription:EventSubscription,attempt:number,mode:DeliveryMode,status:DeliveryRecord['status'],failure?:DeliveryFailureCategory,replay?:ReplayRequest,deliveryId?:string):DeliveryRecord{const id=deliveryId??(this.dependencies.id?.()??`delivery:${event.eventId}:${subscription.id}:${String(attempt)}:${mode}`);const record:DeliveryRecord=freeze({deliveryId:id,eventId:event.eventId,subscriptionId:subscription.id,subscriberId:subscription.subscriberId,attempt,deliveredAt:(this.dependencies.now?.()??new Date()).toISOString(),mode,...optional('replayId',replay?.replayId),status,...optional('failureCategory',failure),diagnosticId:`event-bus:${id}`});this.dependencies.journal.record(record);this.dependencies.diagnostics.record({...diag(event,status==='filtered'?'routing':'delivery',status==='failed'||status==='dead-lettered'||status==='rejected'?'failed':status==='acknowledged'?'completed':status),subscriptionId:subscription.id,deliveryId:id,...optional('errorCode',status==='failed'||status==='dead-lettered'?'DELIVERY_FAILED' as const:undefined)});return record;}
}

export class OutboxPublisher{public constructor(private readonly store:PublicationIntentStore,private readonly publish:(event:PlatformEvent)=>Promise<unknown>,private readonly telemetry:EventBusTelemetry,private readonly now:()=>Date=()=>new Date()){}public async flush():Promise<Readonly<{published:number;pending:number}>>{let published=0;for(const intent of this.store.pending()){if(!intent.committed)continue;try{await this.publish(intent.event);this.store.markPublished(intent.id,this.now().toISOString());this.telemetry.outbox('published');published++;}catch(error){this.store.markFailed(intent.id,'OUTBOX_PUBLICATION_FAILED');this.telemetry.outbox('pending');void error;}}return freeze({published,pending:this.store.pending().length});}}
export class FoundationEventPublisherAdapter implements FoundationEventPublisher{public constructor(private readonly bus:EventBus,private readonly defaults:Readonly<{producer:string;scope:EventScope;security:EventSecurity;retention:RetentionPolicy;classification?:Classification}>){ }public async publish<T>(event:FoundationPlatformEvent<T>):Promise<void>{await this.bus.publish(createPlatformEvent({eventId:event.eventId,type:event.type,contractVersion:String(event.version),occurredAt:event.occurredAt,producer:this.defaults.producer,correlationId:event.correlationId,scope:this.defaults.scope,security:this.defaults.security,payload:event.payload,retention:this.defaults.retention}));}}

function validateFrozenEvent(event:PlatformEvent,maximumDepth:number):void{if(!Object.isFrozen(event)||!Object.isFrozen(event.scope)||!Object.isFrozen(event.security)||!Object.isFrozen(event.retention))throw new EventBusError('EVENT_INVALID','Events must be created as immutable logical facts',`event:${event.eventId}`);if(event.chainDepth>maximumDepth)throw new EventBusError('EVENT_CHAIN_LIMIT','Configured event-chain depth exceeded',`event:${event.eventId}`);}
function visible(event:PlatformEvent,subscription:EventSubscription,decision:EventVisibilityDecision,replay?:ReplayRequest):boolean{const rank=(value:Classification):number=>classifications.indexOf(value);return decision.authorized&&decision.state==='active'&&decision.decisionId===subscription.authorizationReference&&decision.tenantId===event.scope.tenantId&&subscription.scope.tenantId===event.scope.tenantId&&(event.scope.workspaceId===undefined||decision.workspaceIds.includes(event.scope.workspaceId))&&(event.scope.projectId===undefined||decision.projectIds.includes(event.scope.projectId))&&rank(decision.maximumClassification)>=rank(event.security.classification)&&event.security.labels.every(value=>decision.allowedLabels.includes(value))&&(replay===undefined||replay.authorizationReference===decision.decisionId);}
function normalizeFailure(error:unknown):DeliveryFailure{const category=error instanceof ExternalMessagingError?error.category:'unknown';return freeze({category,code:'DELIVERY_FAILED',message:error instanceof Error?error.message:'Delivery failed',retryable:['subscriber-unavailable','timeout','transport','unknown'].includes(category)});}
function diag(event:PlatformEvent,phase:EventBusDiagnostic['phase'],outcome:EventBusDiagnostic['outcome']):EventBusDiagnostic{return freeze({id:`event-bus:${phase}:${event.eventId}`,eventId:event.eventId,phase,outcome,correlationId:event.correlationId});}
function serialized(value:unknown,id:string):string{try{return JSON.stringify(value);}catch(error){throw new EventBusError('EVENT_INVALID','Event payload must be serializable',id,{cause:error});}}
function blank(value:string):boolean{return value.trim()==='';}
function optional<K extends string,V>(key:K,value:V|undefined):Partial<Record<K,V>>{return value===undefined?{}:{[key]:value} as Record<K,V>;}
function copy<T>(value:T):T{return value===undefined?value:JSON.parse(JSON.stringify(value)) as T;}
export function freeze<T>(value:T):T{if(typeof value==='object'&&value!==null&&!Object.isFrozen(value)){for(const child of Object.values(value))freeze(child);Object.freeze(value);}return value;}

export * from './reference.js';


