import type {DeadLetterRecord,DeadLetterStore,DeliveryJournal,DeliveryRecord,EventBusDiagnostic,EventBusDiagnostics,EventBusTelemetry,EventDelivery,EventFilter,EventRouter,EventSubscriber,EventSubscription,EventVisibilityAuthorizer,EventVisibilityDecision,PlatformEvent,PublicationIntent,PublicationIntentStore,ReplayAudit,ReplayRequest,ReplayStore,SubscriberInbox,SubscriptionRegistry,EventBusErrorCode} from './index.js';
import {EventBusError,freeze} from './index.js';

export class InMemorySubscriptionRegistry implements SubscriptionRegistry{
 readonly #subscriptions=new Map<string,EventSubscription>();readonly #subscribers=new Map<string,EventSubscriber>();
 public register(subscription:EventSubscription,subscriber:EventSubscriber):void{if(this.#subscriptions.has(subscription.id))throw new EventBusError('SUBSCRIPTION_DUPLICATE','Subscription already exists',`subscription:${subscription.id}`);this.#subscriptions.set(subscription.id,subscription);this.#subscribers.set(subscription.id,subscriber);}
 public unregister(id:string):void{this.#subscriptions.delete(id);this.#subscribers.delete(id);}
 public get(id:string):EventSubscription|undefined{return this.#subscriptions.get(id);}
 public subscriber(id:string):EventSubscriber|undefined{return this.#subscribers.get(id);}
 public list():readonly EventSubscription[]{return freeze([...this.#subscriptions.values()].sort((a,b)=>a.id.localeCompare(b.id)));}
}
export class DeterministicEventRouter implements EventRouter{public route(event:PlatformEvent,subscriptions:readonly EventSubscription[]):readonly EventSubscription[]{return freeze(subscriptions.filter(value=>value.enabled&&matchesType(event.type,value.eventTypes)&&value.contractVersions.includes(event.contractVersion)&&value.compatibleSchemaVersions.includes(event.schemaVersion)&&matchesFilter(event,value.filter)&&scopeMatches(event,value)).sort((a,b)=>a.id.localeCompare(b.id)));}}
export class StaticVisibilityAuthorizer implements EventVisibilityAuthorizer{public constructor(private readonly decisions:ReadonlyMap<string,EventVisibilityDecision>){}public async authorize(_event:PlatformEvent,subscription:EventSubscription,_operation:'live'|'replay'):Promise<EventVisibilityDecision>{return this.decisions.get(subscription.authorizationReference)??freeze({decisionId:'missing',authorized:false,state:'expired',tenantId:subscription.scope.tenantId,workspaceIds:[],projectIds:[],maximumClassification:'public',allowedLabels:[],policyVersion:'missing'});}}
export class InMemoryReplayStore implements ReplayStore{readonly #events:PlatformEvent[]=[];public append(event:PlatformEvent):void{if(!this.#events.some(value=>value.eventId===event.eventId))this.#events.push(event);}public query(request:ReplayRequest):readonly PlatformEvent[]{const start=Date.parse(request.from),end=Date.parse(request.to);return freeze(this.#events.filter(event=>event.scope.tenantId===request.scope.tenantId&&(request.scope.workspaceId===undefined||event.scope.workspaceId===request.scope.workspaceId)&&(request.scope.projectId===undefined||event.scope.projectId===request.scope.projectId)&&(request.eventTypes.length===0||request.eventTypes.includes(event.type))&&(request.correlationIds.length===0||request.correlationIds.includes(event.correlationId))&&Date.parse(event.occurredAt)>=start&&Date.parse(event.occurredAt)<=end));}public expire(at:string):number{const before=this.#events.length,time=Date.parse(at);for(let index=this.#events.length-1;index>=0;index--){const event=this.#events[index];if(event!==undefined&&event.retention.expiresAt!==undefined&&Date.parse(event.retention.expiresAt)<=time&&event.retention.category!=='permanent')this.#events.splice(index,1);}return before-this.#events.length;}}
export class InMemoryDeadLetterStore implements DeadLetterStore{readonly #values:DeadLetterRecord[]=[];public record(value:DeadLetterRecord):void{this.#values.push(value);}public list(subscriptionId?:string):readonly DeadLetterRecord[]{return freeze(this.#values.filter(value=>subscriptionId===undefined||value.subscriptionId===subscriptionId));}}
export class InMemoryDeliveryJournal implements DeliveryJournal{readonly #values:DeliveryRecord[]=[];public record(value:DeliveryRecord):void{this.#values.push(value);}public list(eventId?:string):readonly DeliveryRecord[]{return freeze(this.#values.filter(value=>eventId===undefined||value.eventId===eventId));}}
export class InMemoryEventBusDiagnostics implements EventBusDiagnostics{readonly #values:EventBusDiagnostic[]=[];public record(value:EventBusDiagnostic):void{this.#values.push(freeze({...value}));}public list():readonly EventBusDiagnostic[]{return freeze([...this.#values]);}}
export class InMemoryEventBusTelemetry implements EventBusTelemetry{readonly counters=new Map<string,number>();public published(type:string):void{this.#add(`published:${type}`);}public delivery(status:DeliveryRecord['status'],_durationMs:number):void{this.#add(`delivery:${status}`);}public replayed(count:number):void{this.#add('replayed',count);}public deadLettered():void{this.#add('dead-lettered');}public backpressure(subscriptionId:string):void{this.#add(`backpressure:${subscriptionId}`);}public outbox(status:'published'|'pending'):void{this.#add(`outbox:${status}`);}#add(key:string,value=1):void{this.counters.set(key,(this.counters.get(key)??0)+value);}}
export class InMemoryReplayAudit implements ReplayAudit{readonly records:Readonly<{request:ReplayRequest;result:Readonly<{delivered:number;filtered:number;rejected:number}>}>[]=[];public async record(request:ReplayRequest,result:Readonly<{delivered:number;filtered:number;rejected:number}>):Promise<void>{this.records.push(freeze({request,result}));}}
export class IdempotentSubscriber implements EventSubscriber{readonly deliveries:string[]=[];public constructor(public readonly id:string,private readonly inbox:SubscriberInbox,private readonly handler:(event:PlatformEvent)=>Promise<void>=async()=>{}){}public async handle(delivery:EventDelivery):Promise<'acknowledged'>{if(!this.inbox.has(delivery.event.eventId)){await this.handler(delivery.event);this.inbox.mark(delivery.event.eventId);this.deliveries.push(delivery.deliveryId);}return'acknowledged';}}
export class InMemorySubscriberInbox implements SubscriberInbox{readonly #ids=new Set<string>();public has(eventId:string):boolean{return this.#ids.has(eventId);}public mark(eventId:string):void{this.#ids.add(eventId);}}
export class InMemoryPublicationIntentStore implements PublicationIntentStore{readonly #values=new Map<string,PublicationIntent>();public add(value:PublicationIntent):void{this.#values.set(value.id,freeze({...value}));}public pending():readonly PublicationIntent[]{return freeze([...this.#values.values()].filter(value=>value.committed&&value.publishedAt===undefined));}public markPublished(id:string,at:string):void{const value=this.#values.get(id);if(value!==undefined)this.#values.set(id,freeze({...value,publishedAt:at,attempts:value.attempts+1}));}public markFailed(id:string,code:EventBusErrorCode):void{const value=this.#values.get(id);if(value!==undefined)this.#values.set(id,freeze({...value,errorCode:code,attempts:value.attempts+1}));}public get(id:string):PublicationIntent|undefined{return this.#values.get(id);}}

function matchesType(type:string,patterns:readonly string[]):boolean{return patterns.includes(type)||patterns.some(value=>value.endsWith('*')&&type.startsWith(value.slice(0,-1)));}
function matchesFilter(event:PlatformEvent,filter:EventFilter):boolean{return(filter.producers===undefined||filter.producers.includes(event.producer))&&(filter.correlationIds===undefined||filter.correlationIds.includes(event.correlationId))&&(filter.classifications===undefined||filter.classifications.includes(event.security.classification))&&(filter.labels===undefined||filter.labels.every(value=>event.security.labels.includes(value)));}
function scopeMatches(event:PlatformEvent,subscription:EventSubscription):boolean{return event.scope.tenantId===subscription.scope.tenantId&&(subscription.scope.workspaceId===undefined||event.scope.workspaceId===subscription.scope.workspaceId)&&(subscription.scope.projectId===undefined||event.scope.projectId===subscription.scope.projectId);}

export { InProcessEventTransport } from './reference/in-process-event-transport.js';
