export const AGENTPRODREADY_PLUGIN_MANAGER = Symbol('AGENTPRODREADY_PLUGIN_MANAGER');
export const AGENTPRODREADY_PLUGIN_DISCOVERY = Symbol('AGENTPRODREADY_PLUGIN_DISCOVERY');
export const AGENTPRODREADY_PLUGIN_PERMISSION_AUTHORIZER = Symbol('AGENTPRODREADY_PLUGIN_PERMISSION_AUTHORIZER');
export const AGENTPRODREADY_IMPLEMENTATION_ACTIVATOR = Symbol('AGENTPRODREADY_IMPLEMENTATION_ACTIVATOR');
