export const AGENTFORGE_PLUGIN_MANAGER = Symbol('AGENTFORGE_PLUGIN_MANAGER');
export const AGENTFORGE_PLUGIN_DISCOVERY = Symbol('AGENTFORGE_PLUGIN_DISCOVERY');
export const AGENTFORGE_PLUGIN_PERMISSION_AUTHORIZER = Symbol('AGENTFORGE_PLUGIN_PERMISSION_AUTHORIZER');
export const AGENTFORGE_IMPLEMENTATION_ACTIVATOR = Symbol('AGENTFORGE_IMPLEMENTATION_ACTIVATOR');
