import type { CapabilityPlanner,CapabilityRequirement,ExecutionStrategy,Goal,GoalAnalyzer,Intent,IntentAnalyzer,OptimizationMetadata,PlanOptimizer,PlanValidator,PlannedTask,PlanningEventPublisher,PlanningFact,PlanningTelemetry,StrategySelector,TaskDecomposer,WorkflowCatalog,WorkflowDefinition,WorkflowPlanner } from '../contracts/planning.js';
import { PlanningError } from '../errors/planning-error.js';

export class ObjectiveGoalAnalyzer implements GoalAnalyzer {public analyze(objective:string):Goal{return Object.freeze({statement:objective});}}
export class ObjectiveIntentAnalyzer implements IntentAnalyzer {public analyze(objective:string):Intent{return Object.freeze({name:'fulfill-objective',outcome:objective});}}
export class SequentialTaskDecomposer implements TaskDecomposer {public decompose(objective:string):readonly PlannedTask[]{const parts=objective.split(/\s+then\s+/iu).map(x=>x.trim()).filter(Boolean);return Object.freeze(parts.map((description,index)=>Object.freeze({id:`task-${String(index+1)}`,description,capability:normalizeCapability(description),dependencies:Object.freeze(index===0?[]:[`task-${String(index)}`]),optional:false})));}}
export class TaskCapabilityPlanner implements CapabilityPlanner {public identify(tasks:readonly PlannedTask[]):readonly CapabilityRequirement[]{return Object.freeze([...new Set(tasks.map(x=>x.capability))].sort().map(capability=>Object.freeze({capability,constraints:Object.freeze({})})));}}
export class TaskStrategySelector implements StrategySelector {public select(tasks:readonly PlannedTask[]):ExecutionStrategy{return tasks.length===1?'single-step':'sequential';}}
export class InMemoryWorkflowCatalog implements WorkflowCatalog {public constructor(private readonly definitions:readonly {readonly objective:string;readonly workflow:WorkflowDefinition}[]=[]){}public find(objective:string):WorkflowDefinition|undefined{return this.definitions.find(x=>x.objective===objective)?.workflow;}}
export class CatalogOrGeneratedWorkflowPlanner implements WorkflowPlanner {public async plan(objective:string,tasks:readonly PlannedTask[],catalog:WorkflowCatalog):Promise<WorkflowDefinition>{const found=await catalog.find(objective,tasks);return found??Object.freeze({id:`generated:${stableId(objective)}`,source:'generated',taskIds:Object.freeze(tasks.map(x=>x.id))});}}
export class DeduplicatingPlanOptimizer implements PlanOptimizer {public optimize(tasks:readonly PlannedTask[]):{readonly tasks:readonly PlannedTask[];readonly metadata:OptimizationMetadata}{const seen=new Set<string>();const kept:PlannedTask[]=[];const removed:string[]=[];for(const task of tasks){const key=`${task.description}\u0000${task.capability}`;if(seen.has(key))removed.push(task.id);else{seen.add(key);kept.push(task);}}return Object.freeze({tasks:Object.freeze(kept),metadata:Object.freeze({removedTaskIds:Object.freeze(removed),originalTaskCount:tasks.length,optimizedTaskCount:kept.length})});}}
export class StrictPlanValidator implements PlanValidator {public validate(plan:Parameters<PlanValidator['validate']>[0]):void{if(plan.goal.statement.trim()===''||plan.intent.outcome!==plan.objective||plan.tasks.length===0||plan.requiredCapabilities.length===0)throw new PlanningError('PLANNING_INVALID_PLAN','Plan is incomplete');const ids=new Set(plan.tasks.map(x=>x.id));if(ids.size!==plan.tasks.length||plan.workflow.taskIds.some(id=>!ids.has(id)))throw new PlanningError('PLANNING_INVALID_PLAN','Plan references invalid tasks');if(JSON.stringify(plan).toLowerCase().includes('providerid'))throw new PlanningError('PLANNING_PROVIDER_LEAKAGE','Plan contains provider ownership');const visiting=new Set<string>();const visited=new Set<string>();const byId=new Map(plan.tasks.map(x=>[x.id,x]));const visit=(id:string):void=>{if(visiting.has(id))throw new PlanningError('PLANNING_DEPENDENCY_CYCLE',`Cycle at ${id}`);if(visited.has(id))return;visiting.add(id);const task=byId.get(id);if(task===undefined)throw new PlanningError('PLANNING_INVALID_PLAN',`Missing task ${id}`);for(const dependency of task.dependencies)visit(dependency);visiting.delete(id);visited.add(id);};for(const id of ids)visit(id);}}
export class InMemoryPlanningEventPublisher implements PlanningEventPublisher {readonly #facts:PlanningFact[]=[];public async publish(fact:PlanningFact):Promise<void>{this.#facts.push(fact);}public facts():readonly PlanningFact[]{return Object.freeze([...this.#facts]);}}
export class NoopPlanningTelemetry implements PlanningTelemetry {public started(_id:string):void{}public completed(_id:string,_duration:number,_tasks:number):void{}public failed(_id:string,_code:string):void{}}
function normalizeCapability(value:string):string{return value.toLowerCase().replace(/[^a-z0-9]+/gu,'.').replace(/^\.|\.$/gu,'')||'general';}
function stableId(value:string):string{let hash=2166136261;for(const character of value){hash^=character.codePointAt(0)??0;hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16);}

