import type {AgentLifecycleState} from '@agentprodready/agent-framework';
import type {AuthorityState} from '@agentprodready/security';

export interface CollaborationScope{readonly tenantId:string;readonly workspaceId?:string;readonly projectId?:string;}
export type CollaborationRole='coordinator'|'planner'|'specialist'|'executor'|'reviewer'|'evaluator'|'approver'|'observer';
export type CoordinationStrategy='sequential'|'parallel'|'supervisory'|'hierarchical'|'consensus'|'debate-review'|'dynamic-assignment';
export interface ParticipantDefinition{readonly id:string;readonly agentId:string;readonly agentVersion:string;readonly agentPrincipalId:string;readonly role:CollaborationRole;readonly responsibilities:readonly string[];readonly allowedCommunicationTargets:readonly string[];readonly delegationRequirementReferences:readonly string[];readonly toolRestrictions:readonly string[];readonly knowledgeScopes:readonly string[];readonly memoryScopes:Readonly<{private:readonly string[];shared:readonly string[]}>;readonly requiredOutputs:readonly string[];readonly participationConditions:readonly string[];}
export interface CollaborationDefinition{readonly id:string;readonly version:string;readonly sharedObjective:string;readonly scope:CollaborationScope;readonly participants:readonly ParticipantDefinition[];readonly strategy:CoordinationStrategy;readonly delegationPolicyReference:string;readonly communicationPolicyReference:string;readonly sharedContextPolicyReference:string;readonly sharedMemoryPolicyReference:string;readonly aggregationPolicy:Readonly<{type:'all-results'|'majority'|'weighted'|'coordinator'|'evaluator';version:string;quorum:number}>;readonly conflictPolicy:Readonly<{type:'coordinator'|'majority'|'weighted'|'independent-evaluator'|'human-escalation'|'explicit-failure'|'additional-evidence';version:string}>;readonly evaluationRequirementReferences:readonly string[];readonly securityRequirementReferences:readonly string[];readonly constraints:Readonly<{maximumParticipants:number;maximumMessages:number;maximumChainDepth:number;allowedClassifications:readonly Classification[]}>;readonly governance:Readonly<{owner:string;policyVersion:string;classification:Classification}>;readonly provenance:Readonly<{definitionReference:string;createdBy:string;createdAt:string;builderVersion:string}>;}
export type Classification='public'|'internal'|'confidential'|'restricted';
export interface RegisteredAgentVersion{readonly agentId:string;readonly version:string;readonly principalReference:string;readonly scope:CollaborationScope;readonly lifecycleState:AgentLifecycleState;readonly compatible:boolean;}
export interface AgentVersionInspector{resolve(agentId:string,version:string,scope:CollaborationScope):RegisteredAgentVersion|undefined;}
export interface CollaborationValidationResult{readonly id:string;readonly valid:boolean;readonly findings:readonly Readonly<{code:string;participantId?:string;blocking:boolean;message:string}>[];readonly policyVersions:readonly string[];readonly diagnosticsReference:string;}
export interface ParticipantAuthority{readonly decisionId:string;readonly participantId:string;readonly principalId:string;readonly authorized:boolean;readonly state:AuthorityState;readonly scope:CollaborationScope;readonly allowedActions:readonly string[];readonly allowedCommunicationTargets:readonly string[];readonly allowedContextReferences:readonly string[];readonly allowedKnowledgeScopes:readonly string[];readonly allowedMemoryScopes:readonly string[];readonly allowedTools:readonly string[];readonly allowedProviders:readonly string[];readonly delegationReferences:readonly string[];readonly policyVersion:string;}
export interface AgentTaskAssignment{readonly id:string;readonly collaborationId:string;readonly participantId:string;readonly objective:string;readonly requiredCapabilities:readonly string[];readonly inputReferences:readonly string[];readonly outputContractReference:string;readonly dependencyAssignmentIds:readonly string[];readonly constraints:Readonly<Record<string,string|number|boolean>>;readonly authorityDecisionId:string;readonly correlationId:string;readonly causationId:string|null;}
export type AssignmentStatus='pending'|'logically-eligible'|'accepted'|'result-submitted'|'failed'|'cancelled';
export interface CoordinationInput{readonly definition:CollaborationDefinition;readonly assignments:readonly AgentTaskAssignment[];readonly statuses:Readonly<Record<string,AssignmentStatus>>;}
export interface CoordinationDecision{readonly strategy:CoordinationStrategy;readonly eligibleAssignmentIds:readonly string[];readonly blockedAssignmentIds:readonly string[];readonly reviewRequired:boolean;readonly policyReference:string;readonly schedulingPerformed:false;}
export interface CoordinationPolicy{decide(input:CoordinationInput):CoordinationDecision;}
export interface CollaborationMessage{readonly id:string;readonly collaborationId:string;readonly senderParticipantId:string;readonly recipientParticipantId:string;readonly type:'information'|'request'|'response'|'review'|'decision'|'conflict'|'status';readonly contentReference:string;readonly contextReferences:readonly string[];readonly memoryScope:'participant-private'|'collaboration-shared'|'none';readonly classification:Classification;readonly correlationId:string;readonly causationId:string|null;readonly sentAt:string;}
export interface CollaborationMessageStore{accept(message:CollaborationMessage):boolean;list(collaborationId:string):readonly CollaborationMessage[];}
export interface ParticipantResult{readonly id:string;readonly assignmentId:string;readonly participantId:string;readonly agentId:string;readonly agentVersion:string;readonly outcome:'succeeded'|'failed'|'partial'|'inconclusive'|'cancelled';readonly outputReference?:string;readonly evidenceReferences:readonly string[];readonly evaluationReferences:readonly string[];readonly uncertainty:readonly string[];readonly submittedAt:string;}
export interface CollaborationConflict{readonly id:string;readonly type:'contradictory-output'|'assignment-overlap'|'failed-consensus'|'incompatible-evidence'|'authority-limitation'|'policy-disagreement';readonly participantIds:readonly string[];readonly evidenceReferences:readonly string[];readonly status:'detected'|'resolved'|'unresolved'|'human-review';readonly policyVersion:string;readonly resolution?:string;}
export interface ConsensusDecision{readonly status:'reached'|'failed'|'tie'|'insufficient-quorum';readonly selectedReference?:string;readonly votes:Readonly<Record<string,string>>;readonly agreeingParticipantIds:readonly string[];readonly dissentingParticipantIds:readonly string[];readonly unanimous:boolean;readonly policyVersion:string;}
export interface CollaborationResult{readonly id:string;readonly collaborationId:string;readonly definitionVersion:string;readonly sharedObjective:string;readonly participantResults:readonly ParticipantResult[];readonly outcome:'successful'|'partial'|'inconclusive'|'failed'|'cancelled'|'awaiting-human-decision';readonly aggregatedReference?:string;readonly conflicts:readonly CollaborationConflict[];readonly consensus?:ConsensusDecision;readonly decisions:readonly string[];readonly evaluationReferences:readonly string[];readonly evidenceReferences:readonly string[];readonly diagnosticsReference:string;readonly correlationId:string;readonly completedAt:string;}
export type CollaborationExecutionStatus='requested'|'authorized'|'started'|'coordinating'|'aggregating'|'completed'|'partial'|'failed'|'cancelled'|'awaiting-human-decision';
export interface CollaborationExecutionState{readonly collaborationId:string;readonly definitionVersion:string;readonly status:CollaborationExecutionStatus;readonly participantStatuses:Readonly<Record<string,'pending'|'participating'|'completed'|'failed'|'cancelled'>>;readonly assignmentStatuses:Readonly<Record<string,AssignmentStatus>>;readonly submittedResultIds:readonly string[];readonly pendingReviewIds:readonly string[];readonly consensusStatus?:ConsensusDecision['status'];readonly conflictIds:readonly string[];readonly aggregationStatus:'pending'|'ready'|'completed'|'failed';readonly version:number;readonly updatedAt:string;}
export interface CollaborationLifecycleRecord{readonly id:string;readonly collaborationId:string;readonly from:CollaborationExecutionStatus;readonly to:CollaborationExecutionStatus;readonly reason:string;readonly authorizationDecisionId:string;readonly occurredAt:string;readonly correlationId:string;readonly version:number;}
export interface CollaborationStateStore{append(record:CollaborationLifecycleRecord,state:CollaborationExecutionState):void;state(id:string):CollaborationExecutionState|undefined;records(id:string):readonly CollaborationLifecycleRecord[];}
export interface ResultAggregator{aggregate(definition:CollaborationDefinition,results:readonly ParticipantResult[],conflicts:readonly CollaborationConflict[],consensus:ConsensusDecision|undefined,correlationId:string,at:string):CollaborationResult;}
export interface HumanEscalationPort{request(value:Readonly<{id:string;collaborationId:string;conflictIds:readonly string[];participantIds:readonly string[];reason:string;correlationId:string}>):Promise<Readonly<{interactionReference:string}>>;}
export interface CollaborationEvents{publish(value:CollaborationFact):Promise<void>;}
export interface CollaborationFact{readonly type:'collaboration.validated'|'collaboration.started'|'participant.assigned'|'participant.result.submitted'|'collaboration.conflict.detected'|'collaboration.human-review.requested'|'collaboration.completed'|'collaboration.cancelled';readonly collaborationId:string;readonly operationId:string;readonly tenantId:string;readonly correlationId:string;readonly causationId:string|null;readonly outcome:'completed'|'failed'|'partial';readonly diagnosticsReference:string;}
export interface CollaborationAudit{record(value:Readonly<{type:string;collaborationId:string;participantIds:readonly string[];authorityDecisionIds:readonly string[];evidenceReferences:readonly string[];operationId:string;correlationId:string}>):Promise<void>;}
export interface CollaborationDiagnostics{record(value:Readonly<{id:string;phase:string;outcome:'completed'|'failed';collaborationId:string;participantIds:readonly string[];policyVersions:readonly string[];errorCode?:CollaborationErrorCode}>):void;list():readonly unknown[];}
export type CollaborationErrorCode='COLLABORATION_DEFINITION_INVALID'|'COLLABORATION_PARTICIPANT_UNAVAILABLE'|'COLLABORATION_PARTICIPANT_UNAUTHORIZED'|'COLLABORATION_ASSIGNMENT_INVALID'|'COLLABORATION_DELEGATION_INVALID'|'COLLABORATION_COMMUNICATION_DENIED'|'COLLABORATION_SHARED_CONTEXT_DENIED'|'COLLABORATION_MEMORY_SCOPE_DENIED'|'COLLABORATION_CONSENSUS_FAILED'|'COLLABORATION_CONFLICT_UNRESOLVED'|'COLLABORATION_AGGREGATION_FAILED'|'COLLABORATION_INCOMPATIBLE'|'COLLABORATION_CANCELLED'|'COLLABORATION_STATE_INVALID'|'COLLABORATION_UNKNOWN';
export class CollaborationError extends Error{public constructor(public readonly code:CollaborationErrorCode,message:string,public readonly diagnosticId:string){super(message);this.name='CollaborationError';}}

export class CollaborationFramework{
 public constructor(private readonly agents:AgentVersionInspector,private readonly states:CollaborationStateStore,private readonly messages:CollaborationMessageStore,private readonly aggregator:ResultAggregator,private readonly events:CollaborationEvents,private readonly audit:CollaborationAudit,private readonly diagnostics:CollaborationDiagnostics){}
 public validate(definition:CollaborationDefinition):CollaborationValidationResult{const findings:Readonly<{code:string;participantId?:string;blocking:boolean;message:string}>[]=[];const mutable=[...findings];if(definition.id.trim()===''||definition.sharedObjective.trim()===''||definition.participants.length<2||definition.participants.length>definition.constraints.maximumParticipants)mutable.push({code:'COLLABORATION_STRUCTURE',blocking:true,message:'Collaboration structure invalid'});if(new Set(definition.participants.map(value=>value.id)).size!==definition.participants.length)mutable.push({code:'COLLABORATION_PARTICIPANT_DUPLICATE',blocking:true,message:'Participant identifiers must be unique'});for(const participant of definition.participants){const agent=this.agents.resolve(participant.agentId,participant.agentVersion,definition.scope);if(agent===undefined||agent.lifecycleState!=='active'||!agent.compatible)mutable.push({code:'COLLABORATION_AGENT_INELIGIBLE',participantId:participant.id,blocking:true,message:'Registered active compatible Agent Version required'});else if(agent.principalReference!==participant.agentPrincipalId)mutable.push({code:'COLLABORATION_PRINCIPAL_MISMATCH',participantId:participant.id,blocking:true,message:'Independent Agent Principal mismatch'});for(const target of participant.allowedCommunicationTargets)if(!definition.participants.some(value=>value.id===target))mutable.push({code:'COLLABORATION_TARGET_INVALID',participantId:participant.id,blocking:true,message:'Communication target unavailable'});}const result=freeze({id:`collaboration-validation:${definition.id}:${definition.version}`,valid:!mutable.some(value=>value.blocking),findings:mutable,policyVersions:[definition.governance.policyVersion,definition.conflictPolicy.version,definition.aggregationPolicy.version],diagnosticsReference:`collaboration:validation:${definition.id}`});this.diagnostics.record({id:result.diagnosticsReference,phase:'validation',outcome:result.valid?'completed':'failed',collaborationId:definition.id,participantIds:definition.participants.map(value=>value.id),policyVersions:result.policyVersions,...(result.valid?{}:{errorCode:'COLLABORATION_DEFINITION_INVALID'})});return result;}
 public initialize(definition:CollaborationDefinition,authorities:readonly ParticipantAuthority[],at:string,correlationId:string):CollaborationExecutionState{const validation=this.validate(definition);if(!validation.valid)throw new CollaborationError('COLLABORATION_DEFINITION_INVALID','Collaboration Definition is invalid',validation.diagnosticsReference);for(const participant of definition.participants)enforceAuthority(participant,authorities,definition.scope);const state:CollaborationExecutionState=freeze({collaborationId:definition.id,definitionVersion:definition.version,status:'authorized',participantStatuses:Object.fromEntries(definition.participants.map(value=>[value.id,'pending'])),assignmentStatuses:{},submittedResultIds:[],pendingReviewIds:[],conflictIds:[],aggregationStatus:'pending',version:1,updatedAt:at});this.states.append(freeze({id:`collaboration-lifecycle:${definition.id}:authorized`,collaborationId:definition.id,from:'requested',to:'authorized',reason:'participants-authorized',authorizationDecisionId:authorities.map(value=>value.decisionId).sort().join(','),occurredAt:at,correlationId,version:1}),state);return state;}
 public coordinate(definition:CollaborationDefinition,assignments:readonly AgentTaskAssignment[],statuses:Readonly<Record<string,AssignmentStatus>>,strategy:CoordinationPolicy):CoordinationDecision{for(const assignment of assignments)if(!definition.participants.some(value=>value.id===assignment.participantId)||assignment.collaborationId!==definition.id)throw new CollaborationError('COLLABORATION_ASSIGNMENT_INVALID','Assignment participant or collaboration invalid',`collaboration:assignment:${assignment.id}`);return strategy.decide(freeze({definition,assignments,statuses}));}
 public communicate(definition:CollaborationDefinition,message:CollaborationMessage,authorities:readonly ParticipantAuthority[]):boolean{const sender=requiredParticipant(definition,message.senderParticipantId),recipient=requiredParticipant(definition,message.recipientParticipantId);const authority=requiredAuthority(sender.id,authorities);if(!authority.authorized||authority.state!=='active'||!sender.allowedCommunicationTargets.includes(recipient.id)||!authority.allowedCommunicationTargets.includes(recipient.id))throw new CollaborationError('COLLABORATION_COMMUNICATION_DENIED','Participant communication denied',`collaboration:message:${message.id}`);if(message.contextReferences.some(value=>!authority.allowedContextReferences.includes(value)))throw new CollaborationError('COLLABORATION_SHARED_CONTEXT_DENIED','Shared Context reference denied',`collaboration:message:${message.id}`);if(message.memoryScope==='collaboration-shared'&&!sender.memoryScopes.shared.every(value=>authority.allowedMemoryScopes.includes(value)))throw new CollaborationError('COLLABORATION_MEMORY_SCOPE_DENIED','Shared Memory scope denied',`collaboration:message:${message.id}`);return this.messages.accept(freeze(copy(message)));}
 public aggregate(definition:CollaborationDefinition,results:readonly ParticipantResult[],conflicts:readonly CollaborationConflict[],consensus:ConsensusDecision|undefined,correlationId:string,at:string):CollaborationResult{for(const result of results){const participant=requiredParticipant(definition,result.participantId);if(result.agentId!==participant.agentId||result.agentVersion!==participant.agentVersion)throw new CollaborationError('COLLABORATION_AGGREGATION_FAILED','Participant provenance mismatch',`collaboration:result:${result.id}`);}return this.aggregator.aggregate(definition,results,conflicts,consensus,correlationId,at);}
 public async publishResult(definition:CollaborationDefinition,result:CollaborationResult,authorities:readonly ParticipantAuthority[]):Promise<void>{await this.events.publish({type:'collaboration.completed',collaborationId:definition.id,operationId:result.id,tenantId:definition.scope.tenantId,correlationId:result.correlationId,causationId:null,outcome:result.outcome==='successful'?'completed':result.outcome==='partial'?'partial':'failed',diagnosticsReference:result.diagnosticsReference});await this.audit.record({type:'collaboration-result',collaborationId:definition.id,participantIds:result.participantResults.map(value=>value.participantId),authorityDecisionIds:authorities.map(value=>value.decisionId),evidenceReferences:result.evidenceReferences,operationId:result.id,correlationId:result.correlationId});}
 public cancel(id:string,authorizationDecisionId:string,at:string,correlationId:string):CollaborationExecutionState{const current=this.states.state(id);if(current===undefined)throw new CollaborationError('COLLABORATION_STATE_INVALID','Collaboration state unavailable',`collaboration:cancel:${id}`);const state:CollaborationExecutionState=freeze({...current,status:'cancelled',participantStatuses:Object.fromEntries(Object.keys(current.participantStatuses).map(key=>[key,current.participantStatuses[key]==='completed'?'completed':'cancelled'])),assignmentStatuses:Object.fromEntries(Object.keys(current.assignmentStatuses).map(key=>[key,current.assignmentStatuses[key]==='result-submitted'?'result-submitted':'cancelled'])),version:current.version+1,updatedAt:at});this.states.append(freeze({id:`collaboration-lifecycle:${id}:cancelled:${String(state.version)}`,collaborationId:id,from:current.status,to:'cancelled',reason:'runtime-cancellation-cooperation',authorizationDecisionId,occurredAt:at,correlationId,version:state.version}),state);return state;}
}

function enforceAuthority(participant:ParticipantDefinition,authorities:readonly ParticipantAuthority[],scope:CollaborationScope):void{const value=requiredAuthority(participant.id,authorities);if(!value.authorized||value.state!=='active'||value.principalId!==participant.agentPrincipalId||value.scope.tenantId!==scope.tenantId||scope.workspaceId!==undefined&&value.scope.workspaceId!==scope.workspaceId||scope.projectId!==undefined&&value.scope.projectId!==scope.projectId||participant.delegationRequirementReferences.some(reference=>!value.delegationReferences.includes(reference)))throw new CollaborationError('COLLABORATION_PARTICIPANT_UNAUTHORIZED','Participant authority is invalid',`collaboration:participant:${participant.id}`);}
function requiredAuthority(id:string,values:readonly ParticipantAuthority[]):ParticipantAuthority{const value=values.find(item=>item.participantId===id);if(value===undefined)throw new CollaborationError('COLLABORATION_PARTICIPANT_UNAUTHORIZED','Participant authority is missing',`collaboration:participant:${id}`);return value;}
function requiredParticipant(definition:CollaborationDefinition,id:string):ParticipantDefinition{const value=definition.participants.find(item=>item.id===id);if(value===undefined)throw new CollaborationError('COLLABORATION_PARTICIPANT_UNAVAILABLE','Participant unavailable',`collaboration:participant:${id}`);return value;}
function copy<T>(value:T):T{return JSON.parse(JSON.stringify(value)) as T;}
export function freeze<T>(value:T):T{if(typeof value==='object'&&value!==null&&!Object.isFrozen(value)){for(const child of Object.values(value))freeze(child);Object.freeze(value);}return value;}

export * from './reference.js';

