import {describe,expect,it} from 'vitest';
import {CollaborationError,CollaborationFramework,freeze,type CollaborationDefinition,type CollaborationMessage,type ParticipantAuthority,type ParticipantResult} from './index.js';
import {detectConflicts,DeterministicResultAggregator,InMemoryCollaborationAudit,InMemoryCollaborationDiagnostics,InMemoryCollaborationEvents,InMemoryCollaborationMessages,InMemoryCollaborationStates,MajorityConsensus,ParallelEligibilityCoordination,SequentialCoordination,StaticAgentVersionInspector,SupervisoryCoordination} from './reference.js';

const scope={tenantId:'tenant-1',workspaceId:'workspace-1',projectId:'project-1'} as const;
function definition(overrides:Partial<CollaborationDefinition>={}):CollaborationDefinition{return freeze({id:'collaboration-1',version:'1.0.0',sharedObjective:'Produce a reviewed answer',scope,participants:[{id:'researcher',agentId:'research-agent',agentVersion:'1.0.0',agentPrincipalId:'principal:research',role:'specialist',responsibilities:['research'],allowedCommunicationTargets:['reviewer'],delegationRequirementReferences:['delegation:research'],toolRestrictions:[],knowledgeScopes:['knowledge:shared'],memoryScopes:{private:['memory:research'],shared:['memory:collaboration']},requiredOutputs:['research-result'],participationConditions:[]},{id:'reviewer',agentId:'review-agent',agentVersion:'2.0.0',agentPrincipalId:'principal:review',role:'reviewer',responsibilities:['review'],allowedCommunicationTargets:['researcher'],delegationRequirementReferences:['delegation:review'],toolRestrictions:[],knowledgeScopes:['knowledge:shared'],memoryScopes:{private:['memory:review'],shared:['memory:collaboration']},requiredOutputs:['review-result'],participationConditions:[]}],strategy:'sequential',delegationPolicyReference:'delegation-policy',communicationPolicyReference:'communication-policy',sharedContextPolicyReference:'context-policy',sharedMemoryPolicyReference:'memory-policy',aggregationPolicy:{type:'majority',version:'1',quorum:2},conflictPolicy:{type:'human-escalation',version:'1'},evaluationRequirementReferences:['evaluation-profile'],securityRequirementReferences:['security-policy'],constraints:{maximumParticipants:5,maximumMessages:100,maximumChainDepth:10,allowedClassifications:['internal','confidential']},governance:{owner:'team',policyVersion:'governance-1',classification:'confidential'},provenance:{definitionReference:'definition-source',createdBy:'admin',createdAt:'2026-08-06T00:00:00.000Z',builderVersion:'1'},...overrides});}
function authorities(overrides:Partial<ParticipantAuthority>={}):readonly ParticipantAuthority[]{return definition().participants.map(participant=>freeze({decisionId:`decision:${participant.id}`,participantId:participant.id,principalId:participant.agentPrincipalId,authorized:true,state:'active',scope,allowedActions:['participate'],allowedCommunicationTargets:[...participant.allowedCommunicationTargets],allowedContextReferences:['context:shared'],allowedKnowledgeScopes:['knowledge:shared'],allowedMemoryScopes:['memory:collaboration'],allowedTools:[],allowedProviders:[],delegationReferences:[...participant.delegationRequirementReferences],policyVersion:'security-1',...overrides}));}
function fixture():Readonly<{framework:CollaborationFramework;states:InMemoryCollaborationStates;messages:InMemoryCollaborationMessages;events:InMemoryCollaborationEvents;audit:InMemoryCollaborationAudit;diagnostics:InMemoryCollaborationDiagnostics}>{const states=new InMemoryCollaborationStates(),messages=new InMemoryCollaborationMessages(),events=new InMemoryCollaborationEvents(),audit=new InMemoryCollaborationAudit(),diagnostics=new InMemoryCollaborationDiagnostics();const agents=new StaticAgentVersionInspector([{agentId:'research-agent',version:'1.0.0',principalReference:'principal:research',scope,lifecycleState:'active',compatible:true},{agentId:'review-agent',version:'2.0.0',principalReference:'principal:review',scope,lifecycleState:'active',compatible:true}]);return{framework:new CollaborationFramework(agents,states,messages,new DeterministicResultAggregator(),events,audit,diagnostics),states,messages,events,audit,diagnostics};}
const assignments=[{id:'a1',collaborationId:'collaboration-1',participantId:'researcher',objective:'Research',requiredCapabilities:['research'],inputReferences:[],outputContractReference:'output:research',dependencyAssignmentIds:[],constraints:{},authorityDecisionId:'decision:researcher',correlationId:'correlation-1',causationId:null},{id:'a2',collaborationId:'collaboration-1',participantId:'reviewer',objective:'Review',requiredCapabilities:['review'],inputReferences:['output:research'],outputContractReference:'output:review',dependencyAssignmentIds:['a1'],constraints:{},authorityDecisionId:'decision:reviewer',correlationId:'correlation-1',causationId:'a1'}] as const;
function result(id:string,participantId:string,agentId:string,version:string,output:string,outcome:ParticipantResult['outcome']='succeeded'):ParticipantResult{return freeze({id,assignmentId:id==='r1'?'a1':'a2',participantId,agentId,agentVersion:version,outcome,outputReference:output,evidenceReferences:[`evidence:${id}`],evaluationReferences:[`evaluation:${id}`],uncertainty:outcome==='inconclusive'?['insufficient evidence']:[],submittedAt:'2026-08-06T01:00:00.000Z'});}

describe('definitions, participants, and authority',()=>{
 it('defines collaboration through deeply immutable provider-independent contracts',()=>{const value=definition();expect(Object.isFrozen(value)).toBe(true);expect(Object.isFrozen(value.participants[0])).toBe(true);expect(JSON.stringify(value)).not.toMatch(/kafka|openai|executionContext|retryState/i);});
 it('requires registered active compatible Agent Versions and matching principals',()=>{const value=fixture();expect(value.framework.validate(definition()).valid).toBe(true);const invalid=definition({participants:definition().participants.map((participant,index)=>index===0?{...participant,agentVersion:'9.0.0'}:participant)});expect(value.framework.validate(invalid).findings[0]?.code).toBe('COLLABORATION_AGENT_INELIGIBLE');});
 it('does not bypass lifecycle or independently inherit coordinator authority',()=>{const value=fixture();const unauthorized=authorities().map(item=>item.participantId==='reviewer'?{...item,principalId:'principal:research'}:item);expect(()=>value.framework.initialize(definition(),unauthorized,'2026-08-06T00:00:00.000Z','correlation-1')).toThrowError(/authority/);});
 it('enforces delegation and cross-tenant scope independently per participant',()=>{const value=fixture();expect(()=>value.framework.initialize(definition(),authorities({delegationReferences:[]}), '2026-08-06T00:00:00.000Z','c')).toThrowError(CollaborationError);expect(()=>value.framework.initialize(definition(),authorities({scope:{tenantId:'other'}}),'2026-08-06T00:00:00.000Z','c')).toThrow();});
});

describe('logical coordination without scheduling',()=>{
 it('supports sequential logical eligibility',()=>{const decision=fixture().framework.coordinate(definition(),assignments,{a1:'pending',a2:'pending'},new SequentialCoordination());expect(decision.eligibleAssignmentIds).toEqual(['a1']);expect(decision.schedulingPerformed).toBe(false);});
 it('supports parallel eligibility based only on declared dependencies',()=>{const decision=fixture().framework.coordinate(definition({strategy:'parallel'}),assignments,{a1:'result-submitted',a2:'pending'},new ParallelEligibilityCoordination());expect(decision.eligibleAssignmentIds).toEqual(['a2']);expect(decision.schedulingPerformed).toBe(false);});
 it('supports supervisory review semantics without executing work',()=>{const decision=fixture().framework.coordinate(definition({strategy:'supervisory'}),assignments,{a1:'pending',a2:'pending'},new SupervisoryCoordination());expect(decision.reviewRequired).toBe(true);expect(decision.eligibleAssignmentIds).toEqual(['a2']);});
});

describe('communication, shared context, and memory isolation',()=>{
 const message:CollaborationMessage={id:'message-1',collaborationId:'collaboration-1',senderParticipantId:'researcher',recipientParticipantId:'reviewer',type:'information',contentReference:'content:1',contextReferences:['context:shared'],memoryScope:'collaboration-shared',classification:'confidential',correlationId:'correlation-1',causationId:'a1',sentAt:'2026-08-06T00:30:00.000Z'};
 it('accepts authorized reference-only communication and deduplicates messages',()=>{const value=fixture();expect(value.framework.communicate(definition(),message,authorities())).toBe(true);expect(value.framework.communicate(definition(),message,authorities())).toBe(false);expect(value.messages.list('collaboration-1')).toHaveLength(1);});
 it('denies unauthorized shared Context and communication targets',()=>{const value=fixture();expect(()=>value.framework.communicate(definition(),{...message,contextReferences:['context:private']},authorities())).toThrowError(/Context/);expect(()=>value.framework.communicate(definition(),{...message,recipientParticipantId:'researcher'},authorities())).toThrowError(/communication/);});
 it('keeps participant-private and collaboration-shared Memory distinct',()=>{const value=fixture();expect(()=>value.framework.communicate(definition(),{...message,memoryScope:'collaboration-shared'},authorities({allowedMemoryScopes:[]}))).toThrowError(/Memory/);expect(definition().participants[0]?.memoryScopes.private).not.toEqual(definition().participants[1]?.memoryScopes.private);});
});

describe('conflict, consensus, aggregation, lifecycle, and accountability',()=>{
 it('detects contradictory outputs and preserves explicit conflict evidence',()=>{const results=[result('r1','researcher','research-agent','1.0.0','answer:A'),result('r2','reviewer','review-agent','2.0.0','answer:B')];const conflicts=detectConflicts(results,'conflict-1');expect(conflicts[0]).toMatchObject({type:'contradictory-output',status:'detected'});expect(conflicts[0]?.evidenceReferences).toHaveLength(2);});
 it('represents majority, tie, quorum, dissent, and unanimity explicitly',()=>{const consensus=new MajorityConsensus();expect(consensus.decide({researcher:'A',reviewer:'A'},2,'1')).toMatchObject({status:'reached',unanimous:true});expect(consensus.decide({researcher:'A',reviewer:'B'},2,'1')).toMatchObject({status:'tie',unanimous:false});expect(consensus.decide({researcher:'A'},2,'1').status).toBe('insufficient-quorum');});
 it('aggregates immutable normalized partial results with participant provenance and uncertainty',()=>{const value=fixture(),results=[result('r1','researcher','research-agent','1.0.0','answer:A'),result('r2','reviewer','review-agent','2.0.0','answer:A','inconclusive')];const consensus=new MajorityConsensus().decide({researcher:'answer:A',reviewer:'answer:A'},2,'1');const aggregated=value.framework.aggregate(definition(),results,[],consensus,'correlation-1','2026-08-06T02:00:00.000Z');expect(aggregated.outcome).toBe('partial');expect(aggregated.participantResults.map(item=>item.agentVersion)).toEqual(['1.0.0','2.0.0']);expect(Object.isFrozen(aggregated)).toBe(true);});
 it('uses human escalation semantics for unresolved ties without implementing interaction',()=>{const value=fixture(),results=[result('r1','researcher','research-agent','1.0.0','A'),result('r2','reviewer','review-agent','2.0.0','B')],consensus=new MajorityConsensus().decide({researcher:'A',reviewer:'B'},2,'1');expect(value.framework.aggregate(definition(),results,[],consensus,'c','2026-08-06T00:00:00.000Z').outcome).toBe('awaiting-human-decision');});
 it('publishes correlated events, diagnostics, and accountable audit facts',async()=>{const value=fixture();value.framework.initialize(definition(),authorities(),'2026-08-06T00:00:00.000Z','correlation-1');const results=[result('r1','researcher','research-agent','1.0.0','A'),result('r2','reviewer','review-agent','2.0.0','A')],aggregated=value.framework.aggregate(definition(),results,[],undefined,'correlation-1','2026-08-06T02:00:00.000Z');await value.framework.publishResult(definition(),aggregated,authorities());expect(value.events.values[0]).toMatchObject({correlationId:'correlation-1',collaborationId:'collaboration-1'});expect(value.audit.values).toHaveLength(1);expect(value.diagnostics.list()).not.toHaveLength(0);});
 it('cooperates with Runtime cancellation without scheduling, retry, or Workflow state',()=>{const value=fixture();value.framework.initialize(definition(),authorities(),'2026-08-06T00:00:00.000Z','correlation-1');const cancelled=value.framework.cancel('collaboration-1','decision:cancel','2026-08-06T03:00:00.000Z','correlation-1');expect(cancelled.status).toBe('cancelled');expect(cancelled).not.toHaveProperty('retryState');expect(cancelled).not.toHaveProperty('currentWorkflowNode');});
});
