import type {AgentTaskAssignment,CollaborationAudit,CollaborationConflict,CollaborationDefinition,CollaborationDiagnostics,CollaborationEvents,CollaborationExecutionState,CollaborationFact,CollaborationLifecycleRecord,CollaborationMessage,CollaborationMessageStore,CollaborationResult,CollaborationScope,CollaborationStateStore,ConsensusDecision,CoordinationDecision,CoordinationInput,CoordinationPolicy,ParticipantResult,RegisteredAgentVersion,ResultAggregator} from './index.js';
import {freeze} from './index.js';

export class SequentialCoordination implements CoordinationPolicy{public decide(input:CoordinationInput):CoordinationDecision{const eligible:AgentTaskAssignment[]=[];for(const assignment of input.assignments){const dependenciesComplete=assignment.dependencyAssignmentIds.every(id=>input.statuses[id]==='result-submitted');if((input.statuses[assignment.id]??'pending')==='pending'&&dependenciesComplete){eligible.push(assignment);break;}}return freeze({strategy:'sequential',eligibleAssignmentIds:eligible.map(value=>value.id),blockedAssignmentIds:input.assignments.filter(value=>!eligible.includes(value)).map(value=>value.id),reviewRequired:false,policyReference:'sequential-1',schedulingPerformed:false});}}
export class ParallelEligibilityCoordination implements CoordinationPolicy{public decide(input:CoordinationInput):CoordinationDecision{const eligible=input.assignments.filter(assignment=>(input.statuses[assignment.id]??'pending')==='pending'&&assignment.dependencyAssignmentIds.every(id=>input.statuses[id]==='result-submitted'));return freeze({strategy:'parallel',eligibleAssignmentIds:eligible.map(value=>value.id).sort(),blockedAssignmentIds:input.assignments.filter(value=>!eligible.includes(value)).map(value=>value.id).sort(),reviewRequired:false,policyReference:'parallel-eligibility-1',schedulingPerformed:false});}}
export class SupervisoryCoordination implements CoordinationPolicy{public decide(input:CoordinationInput):CoordinationDecision{const supervisors=new Set(input.definition.participants.filter(value=>value.role==='coordinator'||value.role==='reviewer').map(value=>value.id));const eligible=input.assignments.filter(value=>supervisors.has(value.participantId)&&(input.statuses[value.id]??'pending')==='pending');return freeze({strategy:'supervisory',eligibleAssignmentIds:eligible.map(value=>value.id),blockedAssignmentIds:input.assignments.filter(value=>!eligible.includes(value)).map(value=>value.id),reviewRequired:true,policyReference:'supervisory-1',schedulingPerformed:false});}}
export class MajorityConsensus{public decide(votes:Readonly<Record<string,string>>,quorum:number,policyVersion:string):ConsensusDecision{const entries=Object.entries(votes),counts=new Map<string,number>();for(const[,vote]of entries)counts.set(vote,(counts.get(vote)??0)+1);const ranked=[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));const first=ranked[0],second=ranked[1];const status=entries.length<quorum?'insufficient-quorum':first===undefined?'failed':second!==undefined&&second[1]===first[1]?'tie':'reached';const selected=status==='reached'?first?.[0]:undefined;return freeze({status,...(selected===undefined?{}:{selectedReference:selected}),votes:{...votes},agreeingParticipantIds:selected===undefined?[]:entries.filter(([,value])=>value===selected).map(([id])=>id),dissentingParticipantIds:selected===undefined?entries.map(([id])=>id):entries.filter(([,value])=>value!==selected).map(([id])=>id),unanimous:selected!==undefined&&entries.every(([,value])=>value===selected),policyVersion});}}
export class DeterministicResultAggregator implements ResultAggregator{public aggregate(definition:CollaborationDefinition,results:readonly ParticipantResult[],conflicts:readonly CollaborationConflict[],consensus:ConsensusDecision|undefined,correlationId:string,at:string):CollaborationResult{const unresolved=conflicts.some(value=>value.status==='unresolved'),human=conflicts.some(value=>value.status==='human-review')||consensus?.status==='tie',succeeded=results.filter(value=>value.outcome==='succeeded').length,failed=results.filter(value=>value.outcome==='failed').length;const outcome=human?'awaiting-human-decision':unresolved?'inconclusive':results.length===0||failed===results.length?'failed':succeeded===results.length?'successful':'partial';return freeze({id:`collaboration-result:${definition.id}:${definition.version}`,collaborationId:definition.id,definitionVersion:definition.version,sharedObjective:definition.sharedObjective,participantResults:results.map(clone),outcome,...(consensus?.selectedReference===undefined?{}:{aggregatedReference:consensus.selectedReference}),conflicts:conflicts.map(clone),...(consensus===undefined?{}:{consensus:clone(consensus)}),decisions:conflicts.flatMap(value=>value.resolution===undefined?[]:[value.resolution]),evaluationReferences:[...new Set(results.flatMap(value=>value.evaluationReferences))],evidenceReferences:[...new Set([...results.flatMap(value=>value.evidenceReferences),...conflicts.flatMap(value=>value.evidenceReferences)])],diagnosticsReference:`collaboration:result:${definition.id}`,correlationId,completedAt:at});}}
export class InMemoryCollaborationMessages implements CollaborationMessageStore{readonly #values=new Map<string,CollaborationMessage>();public accept(message:CollaborationMessage):boolean{if(this.#values.has(message.id))return false;this.#values.set(message.id,message);return true;}public list(id:string):readonly CollaborationMessage[]{return freeze([...this.#values.values()].filter(value=>value.collaborationId===id));}}
export class InMemoryCollaborationStates implements CollaborationStateStore{readonly #states=new Map<string,CollaborationExecutionState>();readonly #records=new Map<string,CollaborationLifecycleRecord[]>();public append(record:CollaborationLifecycleRecord,state:CollaborationExecutionState):void{const records=this.#records.get(record.collaborationId)??[];if(!records.some(value=>value.id===record.id))records.push(record);this.#records.set(record.collaborationId,records);this.#states.set(record.collaborationId,state);}public state(id:string):CollaborationExecutionState|undefined{return this.#states.get(id);}public records(id:string):readonly CollaborationLifecycleRecord[]{return freeze([...(this.#records.get(id)??[])]);}}
export class InMemoryCollaborationEvents implements CollaborationEvents{readonly values:CollaborationFact[]=[];public async publish(value:CollaborationFact):Promise<void>{this.values.push(value);}}
export class InMemoryCollaborationAudit implements CollaborationAudit{readonly values:unknown[]=[];public async record(value:Readonly<{type:string;collaborationId:string;participantIds:readonly string[];authorityDecisionIds:readonly string[];evidenceReferences:readonly string[];operationId:string;correlationId:string}>):Promise<void>{this.values.push(freeze({...value}));}}
export class InMemoryCollaborationDiagnostics implements CollaborationDiagnostics{readonly values:unknown[]=[];public record(value:unknown):void{this.values.push(freeze(value));}public list():readonly unknown[]{return freeze([...this.values]);}}
export class StaticAgentVersionInspector{public constructor(private readonly values:readonly RegisteredAgentVersion[]){}public resolve(agentId:string,version:string,scope:CollaborationScope):RegisteredAgentVersion|undefined{return this.values.find(value=>value.agentId===agentId&&value.version===version&&value.scope.tenantId===scope.tenantId&&value.scope.workspaceId===scope.workspaceId&&value.scope.projectId===scope.projectId);}}
export function detectConflicts(results:readonly ParticipantResult[],policyVersion:string):readonly CollaborationConflict[]{const outputs=new Set(results.map(value=>value.outputReference).filter((value):value is string=>value!==undefined));if(outputs.size<=1)return[];return[freeze({id:`conflict:${results.map(value=>value.id).sort().join(':')}`,type:'contradictory-output',participantIds:results.map(value=>value.participantId).sort(),evidenceReferences:results.flatMap(value=>value.evidenceReferences),status:'detected',policyVersion})];}
function clone<T>(value:T):T{return JSON.parse(JSON.stringify(value)) as T;}
