import {describe,expect,it} from 'vitest';
import {AgentError,AgentFramework,buildAgentDefinition,freeze,stable,type AgentAuthorizationOutcome,type AgentDefinition,type AgentInvocationRequest,type AgentManifest,type AgentRuntimePort,type RuntimeAgentInvocation,type ValidationCatalog} from './index.js';
import {DeterministicAgentValidator,DeterministicPackageVerifier,InMemoryAgentAudit,InMemoryAgentDiagnostics,InMemoryAgentFacts,InMemoryAgentLifecycleStore,InMemoryAgentRegistry} from './reference.js';

const scope={tenantId:'tenant-1',workspaceId:'workspace-1',projectId:'project-1'} as const;
function manifest(overrides:Partial<AgentManifest>={}):AgentManifest{return freeze({manifestId:'manifest-1',schemaVersion:'1',agentId:'support-agent',version:'1.0.0',name:'Support Agent',description:'Handles support',purpose:'Resolve bounded support requests',type:'task',principalReference:'agent-principal:support',scope,capabilities:[{capability:'text-generation',contractVersion:'1',requirement:'required'}],tools:[{id:'ticket.read',operations:['read'],scopes:['tickets'],authorizationRequired:true}],knowledge:[{id:'support-docs',operations:['retrieve'],scopes:['workspace-1'],authorizationRequired:true}],memory:[{id:'agent-memory',operations:['retrieve'],scopes:['agent'],authorizationRequired:true}],planning:{enabled:true,strategies:['bounded'],policyReference:'planning-policy'},workflows:['support-workflow'],contextPolicyReferences:['context-policy'],promptPolicyReferences:['prompt-policy'],evaluationPolicyReferences:['evaluation-policy'],securityPermissionDeclarations:['invoke'],delegationRequirementReferences:['delegation-policy'],constraints:{maximumDurationMs:60000,maximumCost:10,maximumToolInvocations:5,maximumPlanningDepth:3,maximumWorkflowIterations:10,prohibitedOperations:['delete'],requiredApprovals:['payment'],dataResidencies:['PK']},configuration:{tone:'helpful'},policyReferences:['agent-policy'],pluginDependencies:[{id:'support-plugin',version:'1.0.0'}],compatibility:{platformRange:'^1.0.0',contractVersions:{runtime:'1'}},governance:{owner:'support-team',reviewStatus:'approved',classification:'confidential',policyVersion:'governance-1'},packageReference:'package:support@1.0.0',packageIntegrityReference:'digest:1',publisherReference:'publisher-1',sourceConfigurationVersions:['config-1'],createdAt:'2026-08-06T00:00:00.000Z',createdBy:'admin-1',parentAgentReferences:[],appliedOverrides:[],...overrides});}
const catalog:ValidationCatalog={capabilities:new Map([['text-generation',['1']]]),plugins:new Map([['support-plugin','1.0.0']]),workflows:new Set(['support-workflow']),policies:new Set(['planning-policy','context-policy','prompt-policy','evaluation-policy','agent-policy']),packages:new Set(['package:support@1.0.0']),platformVersion:'1.0.0'};
function auth(operation:AgentAuthorizationOutcome['operation'],overrides:Partial<AgentAuthorizationOutcome>={}):AgentAuthorizationOutcome{return freeze({decisionId:`decision:${operation}`,authorized:true,state:'active',operation,principalId:'admin-1',agentPrincipalId:'agent-principal:support',scope,allowedCapabilities:['text-generation'],allowedTools:['ticket.read'],allowedKnowledgeScopes:['support-docs'],allowedMemoryScopes:['agent-memory'],restrictions:['no-delete'],obligations:['audit'],policyVersion:'security-1',...overrides});}
interface Fixture{readonly framework:AgentFramework;readonly registry:InMemoryAgentRegistry;readonly lifecycle:InMemoryAgentLifecycleStore;readonly runtime:AgentRuntimePort;readonly runtimeCalls:RuntimeAgentInvocation[];readonly facts:InMemoryAgentFacts;readonly audit:InMemoryAgentAudit;}
function fixture():Fixture{const registry=new InMemoryAgentRegistry(),lifecycle=new InMemoryAgentLifecycleStore(),runtimeCalls:RuntimeAgentInvocation[]=[],runtime:AgentRuntimePort={accept:async(request):Promise<Readonly<{executionReference:string}>>=>{runtimeCalls.push(request);return{executionReference:'execution-1'};}},facts=new InMemoryAgentFacts(),audit=new InMemoryAgentAudit();return{framework:new AgentFramework(registry,lifecycle,new DeterministicAgentValidator(),runtime,facts,audit,new InMemoryAgentDiagnostics(),()=>new Date('2026-08-06T00:00:00.000Z')),registry,lifecycle,runtime,runtimeCalls,facts,audit};}
async function active(value:Fixture,definition:AgentDefinition=buildAgentDefinition(manifest(),['validation-1'])):Promise<AgentDefinition>{const validation=value.framework.validate(definition,catalog);await value.framework.register(definition,validation,auth('register'),'admin-1','2026-08-06T00:00:00.000Z');await value.framework.transition(definition.agentId,definition.version,definition.scope,'approved',auth('lifecycle'),'approved','2026-08-06T00:01:00.000Z');await value.framework.transition(definition.agentId,definition.version,definition.scope,'active',auth('lifecycle'),'activated','2026-08-06T00:02:00.000Z',{approvalReference:'approval-1',evaluationReference:'evaluation-1',compatibilityReference:'compatibility-1'});return definition;}
function invocation(overrides:Partial<AgentInvocationRequest>={}):AgentInvocationRequest{return freeze({id:'invocation-1',agentId:'support-agent',objective:'Resolve ticket',initiatingPrincipalId:'user-1',agentPrincipalId:'agent-principal:support',scope,inputs:{ticketId:'T-1'},constraints:{maximumCost:5,maximumToolInvocations:2},delegationReferences:['delegation-1'],securityContextReference:'security-context-1',authorization:auth('invoke'),correlationId:'correlation-1',causationId:null,requestedAt:'2026-08-06T00:03:00.000Z',versionPolicyVersion:'version-policy-1',...overrides});}

describe('Agent definitions and validation',()=>{
 it('normalizes deterministic immutable provider-independent definitions with provenance',()=>{const first=buildAgentDefinition(manifest(),['validation-1']),second=buildAgentDefinition(manifest(),['validation-1']);expect(first).toEqual(second);expect(Object.isFrozen(first)).toBe(true);expect(first.agentId).toBe('support-agent');expect(first.version).toBe('1.0.0');expect(first.publisherReference).toBe('publisher-1');expect(JSON.stringify(first)).not.toMatch(/executionContext|runtimeState|openai|prisma/i);});
 it('rejects missing fields, identifiers, versions, secrets, SDK content, and mutable execution state',()=>{expect(()=>buildAgentDefinition(manifest({agentId:'X'}),[])).toThrowError(AgentError);expect(()=>buildAgentDefinition(manifest({version:'latest'}),[])).toThrowError(AgentError);for(const configuration of [{accessToken:'x'},{providerSdk:'x'},{currentNode:'x'}])expect(()=>buildAgentDefinition(manifest({configuration}),[])).toThrowError(/forbidden/);});
 it('produces immutable explicit six-category validation without approval or authorization',()=>{const value=fixture();const definition=buildAgentDefinition(manifest({governance:{...manifest().governance,reviewStatus:'draft'},schemaVersion:'',constraints:{...manifest().constraints,maximumDurationMs:0},securityPermissionDeclarations:[],workflows:['missing'],pluginDependencies:[{id:'missing',version:'1'}],compatibility:{...manifest().compatibility,platformRange:'2.0.0'}}),['validation-1']);const result=value.framework.validate(definition,{...catalog,capabilities:new Map()});expect(new Set(result.findings.map(item=>item.category))).toEqual(new Set(['structural','compatibility','dependency','constraint','security-requirement','governance']));expect(result.status).toBe('invalid');expect(result.impliesApproval).toBe(false);expect(result.impliesAuthorization).toBe(false);expect(result.impliesActivation).toBe(false);expect(Object.isFrozen(result)).toBe(true);});
 it('prevents registration with blocking findings',async()=>{const value=fixture(),definition=buildAgentDefinition(manifest(),['1']),validation=value.framework.validate(definition,{...catalog,capabilities:new Map()});await expect(value.framework.register(definition,validation,auth('register'),'admin','2026-08-06T00:00:00.000Z')).rejects.toMatchObject({code:'AGENT_VALIDATION_FAILED'});});
});

describe('registry, discovery, and lifecycle',()=>{
 it('registers idempotently and allows immutable versions to coexist',async()=>{const value=fixture(),one=buildAgentDefinition(manifest(),['1']),two=buildAgentDefinition(manifest({manifestId:'manifest-2',version:'2.0.0'}),['1']);const valid1=value.framework.validate(one,catalog),valid2=value.framework.validate(two,catalog);const first=await value.framework.register(one,valid1,auth('register'),'admin','2026-08-06T00:00:00.000Z');expect(await value.framework.register(one,valid1,auth('register'),'admin','2026-08-06T00:00:00.000Z')).toBe(first);await value.framework.register(two,valid2,auth('register'),'admin','2026-08-06T00:00:00.000Z');expect(value.registry.versions('support-agent',scope)).toHaveLength(2);});
 it('scopes discovery authorization and never implies invocation permission',async()=>{const value=fixture();await active(value);const result=value.framework.discover({id:'discover-1',authorization:auth('discover'),scope,agentIds:[],types:[],capabilities:['text-generation'],states:['active'],limit:10});expect(result.agents[0]?.invocationAuthorized).toBe(false);expect(result.invocationPermissionImplied).toBe(false);expect(()=>value.framework.discover({id:'d',authorization:auth('discover',{scope:{tenantId:'other'}}),scope,agentIds:[],types:[],capabilities:[],states:[],limit:1})).toThrowError(/Cross-tenant/);});
 it('enforces explicit lifecycle transitions and activation requirements',async()=>{const value=fixture(),definition=buildAgentDefinition(manifest(),['1']),validation=value.framework.validate(definition,catalog);await value.framework.register(definition,validation,auth('register'),'admin','2026-08-06T00:00:00.000Z');await expect(value.framework.transition(definition.agentId,definition.version,scope,'active',auth('lifecycle'),'skip','2026-08-06T00:01:00.000Z')).rejects.toMatchObject({code:'AGENT_LIFECYCLE_INVALID'});await value.framework.transition(definition.agentId,definition.version,scope,'approved',auth('lifecycle'),'approved','2026-08-06T00:01:00.000Z');await expect(value.framework.transition(definition.agentId,definition.version,scope,'active',auth('lifecycle'),'activate','2026-08-06T00:02:00.000Z')).rejects.toMatchObject({code:'AGENT_LIFECYCLE_INVALID'});});
 it('supports deactivation, suspension, quarantine, deprecation, and retirement without mutating definitions',async()=>{const value=fixture(),definition=await active(value);await value.framework.transition(definition.agentId,definition.version,scope,'suspended',auth('lifecycle'),'incident','2026-08-06T01:00:00.000Z');await value.framework.transition(definition.agentId,definition.version,scope,'quarantined',auth('lifecycle'),'security','2026-08-06T01:01:00.000Z');await value.framework.transition(definition.agentId,definition.version,scope,'retired',auth('lifecycle'),'retire','2026-08-06T01:02:00.000Z');expect(value.registry.definition(definition.agentId,definition.version,scope)).toBe(definition);expect(value.lifecycle.current(`registration:${definition.agentId}:${definition.version}:${scope.tenantId}`)).toBe('retired');});
 it('keeps lifecycle events and audit facts consistent with durable records',async()=>{const value=fixture();await active(value);expect(value.facts.values.map(item=>item.type)).toContain('agent.lifecycle.changed');expect(value.audit.values).toHaveLength(value.facts.values.length);expect(value.facts.values.every(item=>item.chainDepth===0)).toBe(true);});
});

describe('versioning, security, effective definitions, and Runtime handoff',()=>{
 it('resolves versions deterministically and preserves policy diagnostics',async()=>{const value=fixture();await active(value,buildAgentDefinition(manifest(),['1']));await active(value,buildAgentDefinition(manifest({manifestId:'m2',version:'2.0.0'}),['1']));const result=value.framework.resolveVersion({id:'v1',agentId:'support-agent',scope,policyVersion:'policy-1',platformVersion:'1.0.0'});expect(result.selectedVersion).toBe('2.0.0');expect(result.candidates).toEqual(['2.0.0','1.0.0']);expect(result.appliedPolicy).toBe('latest-compatible-active');expect(result.diagnosticsReference).toBe('agent:version:v1');});
 it('creates an effective definition that only narrows permissions and limits',()=>{const value=fixture(),definition=buildAgentDefinition(manifest(),['1']),request=invocation({authorization:auth('invoke',{allowedTools:[],allowedMemoryScopes:[]})});const effective=value.framework.effective(definition,request.authorization,request);expect(effective.tools).toEqual([]);expect(effective.memory).toEqual([]);expect(effective.constraints.maximumCost).toBe(5);expect(effective.constraints.maximumToolInvocations).toBe(2);expect(effective).not.toHaveProperty('executionId');});
 it('requires explicit Agent Security Principal and denies declarations as authority',async()=>{const value=fixture();await active(value);await expect(value.framework.invoke(invocation({agentPrincipalId:'self-declared'}))).rejects.toMatchObject({code:'AGENT_AUTHORIZATION_DENIED'});await expect(value.framework.invoke(invocation({authorization:auth('invoke',{authorized:false})}))).rejects.toMatchObject({code:'AGENT_AUTHORIZATION_DENIED'});});
 it('hands accepted invocation to Runtime and returns acceptance rather than final outcome',async()=>{const value=fixture();await active(value);const result=await value.framework.invoke(invocation());expect(value.runtimeCalls).toHaveLength(1);expect(result).toMatchObject({accepted:true,runtimeExecutionReference:'execution-1',finalExecutionOutcomeIncluded:false,agentVersion:'1.0.0'});const handoff=value.runtimeCalls[0];expect(handoff).not.toHaveProperty('executionContext');expect(handoff?.effectiveAgentDefinition.version).toBe('1.0.0');});
 it('prevents inactive versions from invocation and preserves new-version pinning',async()=>{const value=fixture(),definition=buildAgentDefinition(manifest(),['1']),validation=value.framework.validate(definition,catalog);await value.framework.register(definition,validation,auth('register'),'admin','2026-08-06T00:00:00.000Z');await expect(value.framework.invoke(invocation())).rejects.toMatchObject({code:'AGENT_VERSION_RESOLUTION_FAILED'});});
 it('creates explicit migration and rollback proposals without replacing active executions',async()=>{const value=fixture(),one=await active(value),two=buildAgentDefinition(manifest({manifestId:'m2',version:'2.0.0'}),['1']);await value.framework.register(two,value.framework.validate(two,catalog),auth('register'),'admin','2026-08-06T00:00:00.000Z');const migration=value.framework.migration({id:'migration-1',agentId:one.agentId,fromVersion:'1.0.0',toVersion:'2.0.0',scope,authorization:auth('migration'),policyVersion:'migration-policy-1',rollback:false,reason:'upgrade'});expect(migration).toMatchObject({status:'proposed',fromVersion:'1.0.0',toVersion:'2.0.0'});});
});

describe('packages, evaluation, certification, and self-improvement boundaries',()=>{
 it('validates package integrity without implying authorization, safety, registration, or activation',()=>{const verifier=new DeterministicPackageVerifier(),value=manifest(),digest=localHash(stable(value));const result=verifier.verify({id:'package-1',version:'1.0.0',manifest:value,dependencies:[],contentDigest:digest,signatureReference:'signature-1',publisherReference:'publisher-1',schemaVersion:'1'});expect(result).toMatchObject({verified:true,authorizationImplied:false,safetyImplied:false,descriptiveOnly:true});});
 it('treats revoked signatures as integrity/trust failure, not an authorization decision',()=>{const value=manifest(),result=new DeterministicPackageVerifier().verify({id:'p',version:'1',manifest:value,dependencies:[],contentDigest:localHash(stable(value)),signatureReference:'revoked',publisherReference:'publisher',schemaVersion:'1'},new Set(['revoked']));expect(result).toMatchObject({verified:false,signatureStatus:'revoked',authorizationImplied:false});});
 it('keeps evaluation descriptive, certification scoped/expirable, and change proposals non-mutating',()=>{const certification=freeze({id:'cert-1',agentId:'support-agent',version:'1.0.0',profile:'safe-agent',evaluationReferences:['evaluation-1'],descriptiveEvaluationResults:true as const,securityReviewReference:'security-review-1',scope,certifiedAt:'2026-08-06T00:00:00.000Z',expiresAt:'2026-09-06T00:00:00.000Z',authorityReference:'authority-1',policyVersions:['cert-policy-1'],limitations:['scope-limited']});const proposal=freeze({id:'proposal-1',agentId:'support-agent',sourceVersion:'1.0.0',proposedManifestReference:'manifest-2',reasons:['evaluation finding'],evaluationReferences:['evaluation-1'],automaticMutation:false as const,status:'proposed' as const});expect(certification.expiresAt).toBeTruthy();expect(proposal.automaticMutation).toBe(false);});
});

function localHash(value:string):string{let result=2166136261;for(const character of value){result^=character.codePointAt(0)??0;result=Math.imul(result,16777619);}return(result>>>0).toString(16);}

