import type {AuthorityState} from '@agentprodready/security';

export interface AgentScope{readonly tenantId:string;readonly workspaceId?:string;readonly projectId?:string;}
export type AgentType='task'|'conversational'|'workflow'|'specialist'|'supervisory'|'reactive'|'human-assisted'|'long-running'|'composite';
export interface AgentCapabilityDeclaration{readonly capability:string;readonly contractVersion:string;readonly requirement:'required'|'optional'|'conditional'|'fallback-eligible';}
export interface AgentResourceRequirement{readonly id:string;readonly operations:readonly string[];readonly scopes:readonly string[];readonly authorizationRequired:true;}
export interface AgentConstraint{readonly maximumDurationMs:number;readonly maximumCost:number;readonly maximumToolInvocations:number;readonly maximumPlanningDepth:number;readonly maximumWorkflowIterations:number;readonly prohibitedOperations:readonly string[];readonly requiredApprovals:readonly string[];readonly dataResidencies:readonly string[];}
export interface AgentManifest{readonly manifestId:string;readonly schemaVersion:string;readonly agentId:string;readonly version:string;readonly name:string;readonly description:string;readonly purpose:string;readonly type:AgentType;readonly principalReference:string;readonly scope:AgentScope;readonly capabilities:readonly AgentCapabilityDeclaration[];readonly tools:readonly AgentResourceRequirement[];readonly knowledge:readonly AgentResourceRequirement[];readonly memory:readonly AgentResourceRequirement[];readonly planning:Readonly<{enabled:boolean;strategies:readonly string[];policyReference:string}>;readonly workflows:readonly string[];readonly contextPolicyReferences:readonly string[];readonly promptPolicyReferences:readonly string[];readonly evaluationPolicyReferences:readonly string[];readonly securityPermissionDeclarations:readonly string[];readonly delegationRequirementReferences:readonly string[];readonly constraints:AgentConstraint;readonly configuration:Readonly<Record<string,string|number|boolean|readonly string[]>>;readonly policyReferences:readonly string[];readonly pluginDependencies:readonly Readonly<{id:string;version:string}>[];readonly compatibility:Readonly<{platformRange:string;contractVersions:Readonly<Record<string,string>>}>;readonly governance:Readonly<{owner:string;reviewStatus:'draft'|'reviewed'|'approved';classification:'public'|'internal'|'confidential'|'restricted';policyVersion:string}>;readonly packageReference?:string;readonly packageIntegrityReference?:string;readonly publisherReference:string;readonly sourceConfigurationVersions:readonly string[];readonly createdAt:string;readonly createdBy:string;readonly parentAgentReferences:readonly string[];readonly appliedOverrides:readonly string[];}
export interface AgentDefinition extends AgentManifest{readonly definitionId:string;readonly builderVersion:string;readonly validationPolicyVersions:readonly string[];readonly immutable:true;}
export type ValidationCategory='structural'|'compatibility'|'dependency'|'constraint'|'security-requirement'|'governance';
export interface AgentValidationFinding{readonly code:string;readonly category:ValidationCategory;readonly severity:'warning'|'blocking';readonly message:string;readonly reference?:string;}
export interface AgentValidationResult{readonly id:string;readonly agentId:string;readonly version:string;readonly status:'valid'|'invalid'|'valid-with-warnings';readonly findings:readonly AgentValidationFinding[];readonly validatorVersions:readonly string[];readonly policyVersions:readonly string[];readonly diagnosticsReference:string;readonly validatedAt:string;readonly impliesApproval:false;readonly impliesAuthorization:false;readonly impliesActivation:false;}
export interface ValidationCatalog{readonly capabilities:ReadonlyMap<string,readonly string[]>;readonly plugins:ReadonlyMap<string,string>;readonly workflows:ReadonlySet<string>;readonly policies:ReadonlySet<string>;readonly packages:ReadonlySet<string>;readonly platformVersion:string;}
export interface AgentValidator{validate(definition:AgentDefinition,catalog:ValidationCatalog):AgentValidationResult;}
export type AgentLifecycleState='draft'|'validated'|'registered'|'approved'|'active'|'deprecated'|'deactivated'|'suspended'|'quarantined'|'retired'|'rejected'|'incompatible';
export interface AgentRegistration{readonly id:string;readonly agentId:string;readonly version:string;readonly scope:AgentScope;readonly definitionId:string;readonly validationResultId:string;readonly registeredBy:string;readonly registeredAt:string;readonly immutable:true;}
export interface AgentLifecycleRecord{readonly id:string;readonly registrationId:string;readonly from:AgentLifecycleState;readonly to:AgentLifecycleState;readonly reason:string;readonly changedBy:string;readonly authorizationDecisionId:string;readonly occurredAt:string;readonly policyVersion:string;readonly correlationId:string;readonly approvalReference?:string;readonly evaluationReference?:string;readonly compatibilityReference?:string;readonly expiration?:string;readonly activeExecutionPolicy?:string;}
export interface AgentRegistryProvider{register(definition:AgentDefinition,registration:AgentRegistration):void;definition(agentId:string,version:string,scope:AgentScope):AgentDefinition|undefined;registration(agentId:string,version:string,scope:AgentScope):AgentRegistration|undefined;versions(agentId:string,scope:AgentScope):readonly AgentDefinition[];all(scope:AgentScope):readonly AgentDefinition[];}
export interface AgentLifecycleStore{append(record:AgentLifecycleRecord):void;records(registrationId:string):readonly AgentLifecycleRecord[];current(registrationId:string):AgentLifecycleState;}
export interface AgentAuthorizationOutcome{readonly decisionId:string;readonly authorized:boolean;readonly state:AuthorityState;readonly operation:'register'|'discover'|'lifecycle'|'invoke'|'package-install'|'migration'|'rollback';readonly principalId:string;readonly agentPrincipalId?:string;readonly scope:AgentScope;readonly allowedCapabilities:readonly string[];readonly allowedTools:readonly string[];readonly allowedKnowledgeScopes:readonly string[];readonly allowedMemoryScopes:readonly string[];readonly restrictions:readonly string[];readonly obligations:readonly string[];readonly policyVersion:string;}
export interface AgentDiscoveryRequest{readonly id:string;readonly authorization:AgentAuthorizationOutcome;readonly scope:AgentScope;readonly agentIds:readonly string[];readonly types:readonly AgentType[];readonly capabilities:readonly string[];readonly states:readonly AgentLifecycleState[];readonly limit:number;readonly cursor?:string;}
export interface AgentSummary{readonly agentId:string;readonly version:string;readonly name:string;readonly type:AgentType;readonly purpose:string;readonly state:AgentLifecycleState;readonly capabilities:readonly string[];readonly scope:AgentScope;readonly invocationAuthorized:false;}
export interface AgentDiscoveryResult{readonly id:string;readonly agents:readonly AgentSummary[];readonly nextCursor?:string;readonly diagnosticsReference:string;readonly invocationPermissionImplied:false;}
export interface AgentVersionResolutionRequest{readonly id:string;readonly agentId:string;readonly scope:AgentScope;readonly explicitVersion?:string;readonly pinnedVersion?:string;readonly rolloutVersion?:string;readonly policyVersion:string;readonly platformVersion:string;}
export interface AgentVersionResolutionResult{readonly requestId:string;readonly selectedVersion:string;readonly candidates:readonly string[];readonly appliedPolicy:'explicit'|'pinned'|'rollout'|'latest-compatible-active';readonly policyVersion:string;readonly diagnosticsReference:string;readonly resolvedAt:string;}
export interface EffectiveAgentDefinition{readonly id:string;readonly definitionId:string;readonly agentId:string;readonly version:string;readonly purpose:string;readonly principalReference:string;readonly scope:AgentScope;readonly capabilities:readonly AgentCapabilityDeclaration[];readonly tools:readonly AgentResourceRequirement[];readonly knowledge:readonly AgentResourceRequirement[];readonly memory:readonly AgentResourceRequirement[];readonly constraints:AgentConstraint;readonly policyReferences:readonly string[];readonly appliedRestrictionReferences:readonly string[];readonly rejectedOverrides:readonly string[];readonly sourceReferences:readonly string[];readonly policyVersions:readonly string[];readonly immutable:true;}
export interface AgentInvocationRequest{readonly id:string;readonly agentId:string;readonly version?:string;readonly objective:string;readonly initiatingPrincipalId:string;readonly agentPrincipalId:string;readonly scope:AgentScope;readonly inputs:Readonly<Record<string,string>>;readonly constraints:Partial<AgentConstraint>;readonly delegationReferences:readonly string[];readonly securityContextReference:string;readonly authorization:AgentAuthorizationOutcome;readonly correlationId:string;readonly causationId:string|null;readonly requestedAt:string;readonly versionPolicyVersion:string;}
export interface RuntimeAgentInvocation{readonly invocationId:string;readonly agentId:string;readonly agentVersion:string;readonly effectiveAgentDefinition:EffectiveAgentDefinition;readonly objective:string;readonly inputs:Readonly<Record<string,string>>;readonly securityContextReference:string;readonly correlationId:string;readonly causationId:string|null;}
export interface AgentRuntimePort{
 accept(request:RuntimeAgentInvocation):Promise<Readonly<{executionReference:string}>>;
 acceptStream(request:RuntimeAgentInvocation):Promise<Readonly<{executionReference:string}>>;
}
export interface AgentInvocationAcceptance{readonly invocationId:string;readonly accepted:true;readonly agentId:string;readonly agentVersion:string;readonly effectiveDefinitionId:string;readonly authorizationDecisionId:string;readonly runtimeExecutionReference:string;readonly correlationId:string;readonly versionResolutionReference:string;readonly finalExecutionOutcomeIncluded:false;}
export interface AgentPackage{readonly id:string;readonly version:string;readonly manifest:AgentManifest;readonly dependencies:readonly Readonly<{id:string;version:string}>[];readonly contentDigest:string;readonly signatureReference?:string;readonly publisherReference:string;readonly schemaVersion:string;}
export interface AgentPackageIntegrityResult{readonly packageId:string;readonly verified:boolean;readonly digestMatches:boolean;readonly signatureStatus:'valid'|'invalid'|'unavailable'|'revoked';readonly publisherReference:string;readonly descriptiveOnly:true;readonly authorizationImplied:false;readonly safetyImplied:false;}
export interface AgentPackageProvider{save(value:AgentPackage):void;get(id:string,version:string):AgentPackage|undefined;}
export interface AgentCertification{readonly id:string;readonly agentId:string;readonly version:string;readonly profile:string;readonly evaluationReferences:readonly string[];readonly descriptiveEvaluationResults:true;readonly securityReviewReference:string;readonly scope:AgentScope;readonly certifiedAt:string;readonly expiresAt:string;readonly authorityReference:string;readonly policyVersions:readonly string[];readonly limitations:readonly string[];}
export interface AgentChangeProposal{readonly id:string;readonly agentId:string;readonly sourceVersion:string;readonly proposedManifestReference:string;readonly reasons:readonly string[];readonly evaluationReferences:readonly string[];readonly automaticMutation:false;readonly status:'proposed';}
export interface AgentMigrationRequest{readonly id:string;readonly agentId:string;readonly fromVersion:string;readonly toVersion:string;readonly scope:AgentScope;readonly authorization:AgentAuthorizationOutcome;readonly policyVersion:string;readonly rollback:boolean;readonly reason:string;}
export interface AgentPinnedExecution{readonly executionReference:string;readonly agentId:string;readonly version:string;readonly effectiveDefinitionId:string;readonly pinnedAt:string;}
export interface AgentEvents{publish(value:AgentFact):Promise<void>;}
export interface AgentFact{readonly type:'agent.registered'|'agent.lifecycle.changed'|'agent.invocation.accepted'|'agent.package.installed'|'agent.migration.requested';readonly agentId:string;readonly version:string;readonly operationId:string;readonly tenantId:string;readonly correlationId:string;readonly outcome:'completed'|'rejected';readonly diagnosticsReference:string;readonly chainDepth:number;}
export interface AgentAudit{record(value:Readonly<{type:string;agentId:string;version:string;principalId:string;authorizationDecisionId:string;operationId:string;correlationId:string}>):Promise<void>;}
export interface AgentDiagnostics{record(value:Readonly<{id:string;phase:string;outcome:'completed'|'failed';agentId:string;version?:string;policyVersions:readonly string[];errorCode?:AgentErrorCode}>):void;list():readonly unknown[];}
export interface AgentTelemetry{record(metric:string,value:number):void;}
export type AgentErrorCode='AGENT_MANIFEST_INVALID'|'AGENT_FORBIDDEN_CONTENT'|'AGENT_VALIDATION_FAILED'|'AGENT_DEPENDENCY_MISSING'|'AGENT_INCOMPATIBLE'|'AGENT_REGISTRATION_CONFLICT'|'AGENT_NOT_REGISTERED'|'AGENT_LIFECYCLE_INVALID'|'AGENT_NOT_ACTIVE'|'AGENT_SUSPENDED'|'AGENT_QUARANTINED'|'AGENT_RETIRED'|'AGENT_AUTHORIZATION_DENIED'|'AGENT_CROSS_TENANT_DENIED'|'AGENT_PACKAGE_INVALID'|'AGENT_PACKAGE_INTEGRITY_FAILED'|'AGENT_VERSION_RESOLUTION_FAILED'|'AGENT_EFFECTIVE_DEFINITION_CONFLICT'|'AGENT_RUNTIME_HANDOFF_FAILED'|'AGENT_UNKNOWN';
export class AgentError extends Error{public constructor(public readonly code:AgentErrorCode,message:string,public readonly diagnosticId:string,options?:ErrorOptions){super(message,options);this.name='AgentError';}}

export function buildAgentDefinition(manifest:AgentManifest,validationPolicyVersions:readonly string[],builderVersion='1'):AgentDefinition{validateManifest(manifest);return freeze({...copy(manifest),definitionId:`agent-definition:${manifest.agentId}:${manifest.version}:${hash(stable(manifest))}`,builderVersion,validationPolicyVersions:[...validationPolicyVersions],immutable:true});}

export class AgentFramework{
 public constructor(private readonly registry:AgentRegistryProvider,private readonly lifecycle:AgentLifecycleStore,private readonly validator:AgentValidator,private readonly runtime:AgentRuntimePort,private readonly events:AgentEvents,private readonly audit:AgentAudit,private readonly diagnostics:AgentDiagnostics,private readonly now:()=>Date=()=>new Date()){}
 public validate(definition:AgentDefinition,catalog:ValidationCatalog):AgentValidationResult{return this.validator.validate(definition,catalog);}
 public async register(definition:AgentDefinition,validation:AgentValidationResult,authorization:AgentAuthorizationOutcome,principalId:string,at:string):Promise<AgentRegistration>{enforce(authorization,'register',definition.scope,`agent:register:${definition.definitionId}`);if(validation.status==='invalid'||validation.findings.some(value=>value.severity==='blocking'))throw new AgentError('AGENT_VALIDATION_FAILED','Blocking validation findings prevent registration',validation.diagnosticsReference);const existing=this.registry.registration(definition.agentId,definition.version,definition.scope);if(existing!==undefined)return existing;const registration=freeze({id:`registration:${definition.agentId}:${definition.version}:${definition.scope.tenantId}`,agentId:definition.agentId,version:definition.version,scope:copy(definition.scope),definitionId:definition.definitionId,validationResultId:validation.id,registeredBy:principalId,registeredAt:at,immutable:true as const});this.registry.register(definition,registration);this.lifecycle.append(freeze({id:`lifecycle:${registration.id}:registered`,registrationId:registration.id,from:'validated',to:'registered',reason:'registration-approved',changedBy:principalId,authorizationDecisionId:authorization.decisionId,occurredAt:at,policyVersion:authorization.policyVersion,correlationId:registration.id}));await this.#fact('agent.registered',definition,registration.id,authorization,registration.id);return registration;}
 public discover(request:AgentDiscoveryRequest):AgentDiscoveryResult{enforce(request.authorization,'discover',request.scope,`agent:discover:${request.id}`);if(request.limit<1)throw new AgentError('AGENT_MANIFEST_INVALID','Discovery limit is invalid',`agent:discover:${request.id}`);const values=this.registry.all(request.scope).filter(definition=>{const registration=this.registry.registration(definition.agentId,definition.version,definition.scope);const state=registration===undefined?'draft':this.lifecycle.current(registration.id);return(request.agentIds.length===0||request.agentIds.includes(definition.agentId))&&(request.types.length===0||request.types.includes(definition.type))&&(request.capabilities.length===0||request.capabilities.every(value=>definition.capabilities.some(capability=>capability.capability===value)))&&(request.states.length===0||request.states.includes(state));}).sort((a,b)=>a.agentId.localeCompare(b.agentId)||a.version.localeCompare(b.version));const offset=Number.parseInt(request.cursor??'0',10),selected=values.slice(offset,offset+request.limit),next=offset+selected.length<values.length?String(offset+selected.length):undefined;return freeze({id:request.id,agents:selected.map(definition=>{const registration=this.registry.registration(definition.agentId,definition.version,definition.scope);return{agentId:definition.agentId,version:definition.version,name:definition.name,type:definition.type,purpose:definition.purpose,state:registration===undefined?'draft':this.lifecycle.current(registration.id),capabilities:definition.capabilities.map(value=>value.capability),scope:copy(definition.scope),invocationAuthorized:false};}),...optional('nextCursor',next),diagnosticsReference:`agent:discover:${request.id}`,invocationPermissionImplied:false});}
 public async transition(agentId:string,version:string,scope:AgentScope,to:AgentLifecycleState,authorization:AgentAuthorizationOutcome,reason:string,at:string,options:Readonly<{approvalReference?:string;evaluationReference?:string;compatibilityReference?:string;expiration?:string}>= {}):Promise<AgentLifecycleRecord>{enforce(authorization,'lifecycle',scope,`agent:lifecycle:${agentId}:${version}`);const registration=this.registry.registration(agentId,version,scope);if(registration===undefined)throw new AgentError('AGENT_NOT_REGISTERED','Agent Version is not registered',`agent:lifecycle:${agentId}:${version}`);const from=this.lifecycle.current(registration.id);if(from===to){const existing=this.lifecycle.records(registration.id).at(-1);if(existing!==undefined)return existing;}if(!allowedTransitions[from].includes(to)||to==='active'&&(options.approvalReference===undefined||options.evaluationReference===undefined||options.compatibilityReference===undefined))throw new AgentError('AGENT_LIFECYCLE_INVALID',`${from} cannot transition to ${to}`,`agent:lifecycle:${registration.id}`);const record:AgentLifecycleRecord=freeze({id:`lifecycle:${registration.id}:${to}:${at}`,registrationId:registration.id,from,to,reason,changedBy:authorization.principalId,authorizationDecisionId:authorization.decisionId,occurredAt:at,policyVersion:authorization.policyVersion,correlationId:registration.id,...copy(options)});this.lifecycle.append(record);const definition=this.registry.definition(agentId,version,scope);if(definition===undefined)throw new AgentError('AGENT_NOT_REGISTERED','Agent Definition is unavailable',`agent:lifecycle:${agentId}:${version}`);await this.#fact('agent.lifecycle.changed',definition,record.id,authorization,registration.id);return record;}
 public resolveVersion(request:AgentVersionResolutionRequest):AgentVersionResolutionResult{const candidates=this.registry.versions(request.agentId,request.scope).filter(value=>compatible(value.compatibility.platformRange,request.platformVersion)).filter(value=>{const registration=this.registry.registration(value.agentId,value.version,value.scope);return registration!==undefined&&this.lifecycle.current(registration.id)==='active';}).map(value=>value.version).sort(compareVersions).reverse();const selected=request.explicitVersion??request.pinnedVersion??request.rolloutVersion??candidates[0];if(selected===undefined||!candidates.includes(selected))throw new AgentError('AGENT_VERSION_RESOLUTION_FAILED','No eligible Agent Version is available',`agent:version:${request.id}`);return freeze({requestId:request.id,selectedVersion:selected,candidates,appliedPolicy:request.explicitVersion!==undefined?'explicit':request.pinnedVersion!==undefined?'pinned':request.rolloutVersion!==undefined?'rollout':'latest-compatible-active',policyVersion:request.policyVersion,diagnosticsReference:`agent:version:${request.id}`,resolvedAt:this.now().toISOString()});}
 public effective(definition:AgentDefinition,authorization:AgentAuthorizationOutcome,invocation:AgentInvocationRequest):EffectiveAgentDefinition{const capabilities=definition.capabilities.filter(value=>authorization.allowedCapabilities.includes(value.capability));const tools=narrowResources(definition.tools,authorization.allowedTools);const knowledge=narrowResources(definition.knowledge,authorization.allowedKnowledgeScopes);const memory=narrowResources(definition.memory,authorization.allowedMemoryScopes);const constraints=narrowConstraints(definition.constraints,invocation.constraints);return freeze({id:`effective:${invocation.id}:${definition.definitionId}`,definitionId:definition.definitionId,agentId:definition.agentId,version:definition.version,purpose:definition.purpose,principalReference:definition.principalReference,scope:copy(definition.scope),capabilities,tools,knowledge,memory,constraints,policyReferences:[...definition.policyReferences],appliedRestrictionReferences:[...authorization.restrictions],rejectedOverrides:definition.capabilities.filter(value=>!authorization.allowedCapabilities.includes(value.capability)).map(value=>value.capability),sourceReferences:[definition.definitionId,invocation.id,authorization.decisionId],policyVersions:[authorization.policyVersion,invocation.versionPolicyVersion,definition.governance.policyVersion],immutable:true});}
 public async invoke(request:AgentInvocationRequest):Promise<AgentInvocationAcceptance>{return this.#invokeWithHandoff(request,'accept');}
 public async invokeStream(request:AgentInvocationRequest):Promise<AgentInvocationAcceptance>{return this.#invokeWithHandoff(request,'acceptStream');}
 async #invokeWithHandoff(request:AgentInvocationRequest,mode:'accept'|'acceptStream'):Promise<AgentInvocationAcceptance>{enforce(request.authorization,'invoke',request.scope,`agent:invoke:${request.id}`);if(request.agentPrincipalId!==request.authorization.agentPrincipalId||request.objective.trim()==='')throw new AgentError('AGENT_AUTHORIZATION_DENIED','Agent Principal or objective is invalid',`agent:invoke:${request.id}`);const resolution=this.resolveVersion({id:`version:${request.id}`,agentId:request.agentId,scope:request.scope,...optional('explicitVersion',request.version),policyVersion:request.versionPolicyVersion,platformVersion:'1.0.0'});const definition=this.registry.definition(request.agentId,resolution.selectedVersion,request.scope);if(definition===undefined)throw new AgentError('AGENT_NOT_REGISTERED','Agent Definition is unavailable',`agent:invoke:${request.id}`);const registration=this.registry.registration(definition.agentId,definition.version,definition.scope);if(registration===undefined||this.lifecycle.current(registration.id)!=='active')throw new AgentError('AGENT_NOT_ACTIVE','Agent Version is not active',`agent:invoke:${request.id}`);const effective=this.effective(definition,request.authorization,request);const handoffRequest=freeze({invocationId:request.id,agentId:definition.agentId,agentVersion:definition.version,effectiveAgentDefinition:effective,objective:request.objective,inputs:copy(request.inputs),securityContextReference:request.securityContextReference,correlationId:request.correlationId,causationId:request.causationId});let handoff:Readonly<{executionReference:string}>;try{handoff=mode==='accept'?await this.runtime.accept(handoffRequest):await this.runtime.acceptStream(handoffRequest);}catch(error){throw new AgentError('AGENT_RUNTIME_HANDOFF_FAILED','Runtime rejected Agent invocation handoff',`agent:invoke:${request.id}`,{cause:error});}await this.#fact('agent.invocation.accepted',definition,request.id,request.authorization,request.correlationId);return freeze({invocationId:request.id,accepted:true,agentId:definition.agentId,agentVersion:definition.version,effectiveDefinitionId:effective.id,authorizationDecisionId:request.authorization.decisionId,runtimeExecutionReference:handoff.executionReference,correlationId:request.correlationId,versionResolutionReference:resolution.diagnosticsReference,finalExecutionOutcomeIncluded:false});}
 public migration(request:AgentMigrationRequest):Readonly<{id:string;status:'proposed';fromVersion:string;toVersion:string;rollback:boolean;policyVersion:string}>{enforce(request.authorization,request.rollback?'rollback':'migration',request.scope,`agent:migration:${request.id}`);if(this.registry.definition(request.agentId,request.toVersion,request.scope)===undefined)throw new AgentError('AGENT_VERSION_RESOLUTION_FAILED','Migration target is unavailable',`agent:migration:${request.id}`);return freeze({id:request.id,status:'proposed',fromVersion:request.fromVersion,toVersion:request.toVersion,rollback:request.rollback,policyVersion:request.policyVersion});}
 async #fact(type:AgentFact['type'],definition:AgentDefinition,operationId:string,authorization:AgentAuthorizationOutcome,correlationId:string):Promise<void>{const diagnostic=`agent:${operationId}`;await this.events.publish(freeze({type,agentId:definition.agentId,version:definition.version,operationId,tenantId:definition.scope.tenantId,correlationId,outcome:'completed',diagnosticsReference:diagnostic,chainDepth:0}));await this.audit.record({type,agentId:definition.agentId,version:definition.version,principalId:authorization.principalId,authorizationDecisionId:authorization.decisionId,operationId,correlationId});}
}

const allowedTransitions:Record<AgentLifecycleState,readonly AgentLifecycleState[]>={draft:['validated','rejected'],validated:['registered','rejected'],registered:['approved','incompatible','retired'],approved:['active','rejected','retired'],active:['deactivated','suspended','quarantined','deprecated','retired'],deprecated:['deactivated','retired'],deactivated:['active','retired'],suspended:['active','quarantined','retired'],quarantined:['suspended','retired'],retired:[],rejected:[],incompatible:['registered','retired']};
function validateManifest(value:AgentManifest):void{if(!/^[a-z][a-z0-9-]{2,63}$/.test(value.agentId)||!/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(value.version)||value.name.trim()===''||value.purpose.trim()===''||value.principalReference.trim()===''||value.scope.tenantId.trim()==='')throw new AgentError('AGENT_MANIFEST_INVALID','Agent Manifest structure is invalid',`agent:manifest:${value.manifestId}`);const serialized=stable(value);if(/password|secretValue|accessToken|privateKey|runtimeState|executionContext|currentNode|retryState|providerSdk|databaseConnection/i.test(serialized))throw new AgentError('AGENT_FORBIDDEN_CONTENT','Agent Manifest contains forbidden content',`agent:manifest:${value.manifestId}`);if(value.capabilities.some(item=>item.capability.trim()===''||item.contractVersion.trim()===''))throw new AgentError('AGENT_MANIFEST_INVALID','Capability declaration is invalid',`agent:manifest:${value.manifestId}`);}
function enforce(value:AgentAuthorizationOutcome,operation:AgentAuthorizationOutcome['operation'],scope:AgentScope,id:string):void{if(!value.authorized||value.state!=='active'||value.operation!==operation)throw new AgentError('AGENT_AUTHORIZATION_DENIED','Agent operation is not authorized',id);if(value.scope.tenantId!==scope.tenantId)throw new AgentError('AGENT_CROSS_TENANT_DENIED','Cross-tenant Agent access denied',id);if(scope.workspaceId!==undefined&&value.scope.workspaceId!==scope.workspaceId||scope.projectId!==undefined&&value.scope.projectId!==scope.projectId)throw new AgentError('AGENT_AUTHORIZATION_DENIED','Agent operation scope denied',id);}
function narrowResources(values:readonly AgentResourceRequirement[],allowed:readonly string[]):readonly AgentResourceRequirement[]{return values.filter(value=>allowed.includes(value.id)).map(copy);}
function narrowConstraints(base:AgentConstraint,override:Partial<AgentConstraint>):AgentConstraint{return freeze({...copy(base),maximumDurationMs:Math.min(base.maximumDurationMs,override.maximumDurationMs??base.maximumDurationMs),maximumCost:Math.min(base.maximumCost,override.maximumCost??base.maximumCost),maximumToolInvocations:Math.min(base.maximumToolInvocations,override.maximumToolInvocations??base.maximumToolInvocations),maximumPlanningDepth:Math.min(base.maximumPlanningDepth,override.maximumPlanningDepth??base.maximumPlanningDepth),maximumWorkflowIterations:Math.min(base.maximumWorkflowIterations,override.maximumWorkflowIterations??base.maximumWorkflowIterations),prohibitedOperations:[...new Set([...base.prohibitedOperations,...(override.prohibitedOperations??[])])],requiredApprovals:[...new Set([...base.requiredApprovals,...(override.requiredApprovals??[])])],dataResidencies:(override.dataResidencies??base.dataResidencies).filter(value=>base.dataResidencies.includes(value))});}
function compatible(range:string,platform:string):boolean{return range==='*'||range===platform||range.startsWith('^')&&range.slice(1).split('.')[0]===platform.split('.')[0];}
function compareVersions(a:string,b:string):number{const left=a.split('.').map(Number),right=b.split('.').map(Number);for(let index=0;index<3;index++){const difference=(left[index]??0)-(right[index]??0);if(difference!==0)return difference;}return 0;}
export function stable(value:unknown):string{return JSON.stringify(sort(value));}
function sort(value:unknown):unknown{if(Array.isArray(value))return value.map(sort);if(typeof value==='object'&&value!==null)return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,sort(item)]));return value;}
function hash(value:string):string{let result=2166136261;for(const character of value){result^=character.codePointAt(0)??0;result=Math.imul(result,16777619);}return(result>>>0).toString(16);}
function optional<K extends string,V>(key:K,value:V|undefined):Partial<Record<K,V>>{return value===undefined?{}:{[key]:value} as Record<K,V>;}
function copy<T>(value:T):T{return JSON.parse(JSON.stringify(value)) as T;}
export function freeze<T>(value:T):T{if(typeof value==='object'&&value!==null&&!Object.isFrozen(value)){for(const child of Object.values(value))freeze(child);Object.freeze(value);}return value;}

export * from './reference.js';
export {
  createAgent,
  inMemory,
  openai,
  reference,
  tool,
  SimpleAgentError,
  type Agent,
  type AgentMemoryDiagnostics,
  type AgentModel,
  type AgentResult,
  type AgentStreamEvent,
  type AgentToolStreamStatus,
  type AgentUsage,
  type CreateAgentOptions,
  type SimpleAgentErrorCode,
  type SimpleMemory,
  type SimpleTool,
  type SimpleToolDefinition,
} from './simple/index.js';
