import type {AgentDefinition,AgentFact,AgentLifecycleRecord,AgentLifecycleState,AgentPackage,AgentPackageIntegrityResult,AgentPackageProvider,AgentRegistration,AgentRegistryProvider,AgentScope,AgentValidationFinding,AgentValidationResult,AgentValidator,ValidationCatalog} from './index.js';
import {freeze,stable} from './index.js';

export class DeterministicAgentValidator implements AgentValidator{public validate(definition:AgentDefinition,catalog:ValidationCatalog):AgentValidationResult{const findings:AgentValidationFinding[]=[];if(definition.name.trim()===''||definition.purpose.trim()===''||definition.schemaVersion.trim()==='')findings.push(finding('AGENT_STRUCTURE','structural','blocking','Required definition field missing'));if(!compatible(definition.compatibility.platformRange,catalog.platformVersion))findings.push(finding('AGENT_PLATFORM_INCOMPATIBLE','compatibility','blocking','Platform version incompatible'));for(const capability of definition.capabilities){const versions=catalog.capabilities.get(capability.capability);if(versions===undefined||!versions.includes(capability.contractVersion))findings.push(finding('AGENT_CAPABILITY_MISSING','dependency',capability.requirement==='required'?'blocking':'warning','Capability unavailable',capability.capability));}for(const plugin of definition.pluginDependencies)if(catalog.plugins.get(plugin.id)!==plugin.version)findings.push(finding('AGENT_PLUGIN_MISSING','dependency','blocking','Plugin dependency unavailable',plugin.id));for(const workflow of definition.workflows)if(!catalog.workflows.has(workflow))findings.push(finding('AGENT_WORKFLOW_INVALID','dependency','blocking','Workflow unavailable',workflow));for(const policy of [...definition.policyReferences,definition.planning.policyReference,...definition.contextPolicyReferences,...definition.promptPolicyReferences,...definition.evaluationPolicyReferences])if(!catalog.policies.has(policy))findings.push(finding('AGENT_POLICY_INVALID','governance','blocking','Policy unavailable',policy));if(definition.constraints.maximumDurationMs<=0||definition.constraints.maximumCost<0||definition.constraints.maximumToolInvocations<0)findings.push(finding('AGENT_CONSTRAINT_INVALID','constraint','blocking','Constraints are inconsistent'));if(definition.principalReference.trim()===''||definition.securityPermissionDeclarations.length===0)findings.push(finding('AGENT_SECURITY_REQUIREMENT','security-requirement','blocking','Security requirements incomplete'));if(definition.governance.owner.trim()===''||definition.governance.reviewStatus==='draft')findings.push(finding('AGENT_GOVERNANCE_INCOMPLETE','governance','blocking','Governance review incomplete'));const blocking=findings.some(value=>value.severity==='blocking');return freeze({id:`validation:${definition.definitionId}:${hash(stable(findings))}`,agentId:definition.agentId,version:definition.version,status:blocking?'invalid':findings.length>0?'valid-with-warnings':'valid',findings,validatorVersions:['deterministic-validator-1'],policyVersions:[...definition.validationPolicyVersions],diagnosticsReference:`agent:validation:${definition.definitionId}`,validatedAt:'2026-08-06T00:00:00.000Z',impliesApproval:false,impliesAuthorization:false,impliesActivation:false});}}
export class InMemoryAgentRegistry implements AgentRegistryProvider{readonly #definitions=new Map<string,AgentDefinition>();readonly #registrations=new Map<string,AgentRegistration>();public register(definition:AgentDefinition,registration:AgentRegistration):void{const key=registryKey(definition.agentId,definition.version,definition.scope);const existing=this.#definitions.get(key);if(existing!==undefined&&existing.definitionId!==definition.definitionId)throw new Error('Agent version conflict');this.#definitions.set(key,definition);this.#registrations.set(key,registration);}public definition(agentId:string,version:string,scope:AgentScope):AgentDefinition|undefined{return this.#definitions.get(registryKey(agentId,version,scope));}public registration(agentId:string,version:string,scope:AgentScope):AgentRegistration|undefined{return this.#registrations.get(registryKey(agentId,version,scope));}public versions(agentId:string,scope:AgentScope):readonly AgentDefinition[]{return freeze([...this.#definitions.values()].filter(value=>value.agentId===agentId&&sameScope(value.scope,scope)).sort((a,b)=>a.version.localeCompare(b.version)));}public all(scope:AgentScope):readonly AgentDefinition[]{return freeze([...this.#definitions.values()].filter(value=>sameScope(value.scope,scope)));}}
export class InMemoryAgentLifecycleStore{readonly #values=new Map<string,AgentLifecycleRecord[]>();public append(record:AgentLifecycleRecord):void{const values=this.#values.get(record.registrationId)??[];if(!values.some(value=>value.id===record.id)){values.push(record);this.#values.set(record.registrationId,values);}}public records(registrationId:string):readonly AgentLifecycleRecord[]{return freeze([...(this.#values.get(registrationId)??[])]);}public current(registrationId:string):AgentLifecycleState{return this.#values.get(registrationId)?.at(-1)?.to??'draft';}}
export class InMemoryAgentPackages implements AgentPackageProvider{readonly #values=new Map<string,AgentPackage>();public save(value:AgentPackage):void{this.#values.set(`${value.id}@${value.version}`,value);}public get(id:string,version:string):AgentPackage|undefined{return this.#values.get(`${id}@${version}`);}}
export class DeterministicPackageVerifier{public verify(value:AgentPackage,revokedSignatures:ReadonlySet<string>=new Set()):AgentPackageIntegrityResult{const digestMatches=value.contentDigest===hash(stable(value.manifest));const signatureStatus=value.signatureReference===undefined?'unavailable':revokedSignatures.has(value.signatureReference)?'revoked':'valid';return freeze({packageId:value.id,verified:digestMatches&&signatureStatus!=='revoked',digestMatches,signatureStatus,publisherReference:value.publisherReference,descriptiveOnly:true,authorizationImplied:false,safetyImplied:false});}}
export class InMemoryAgentFacts{readonly values:AgentFact[]=[];public async publish(value:AgentFact):Promise<void>{this.values.push(value);}}
export class InMemoryAgentAudit{readonly values:Readonly<{type:string;agentId:string;version:string;principalId:string;authorizationDecisionId:string;operationId:string;correlationId:string}>[]=[];public async record(value:Readonly<{type:string;agentId:string;version:string;principalId:string;authorizationDecisionId:string;operationId:string;correlationId:string}>):Promise<void>{this.values.push(freeze({...value}));}}
export class InMemoryAgentDiagnostics{readonly values:unknown[]=[];public record(value:unknown):void{this.values.push(freeze(value));}public list():readonly unknown[]{return freeze([...this.values]);}}
export class InMemoryAgentTelemetry{readonly values=new Map<string,number>();public record(metric:string,value:number):void{this.values.set(metric,(this.values.get(metric)??0)+value);}}

function finding(code:string,category:AgentValidationFinding['category'],severity:AgentValidationFinding['severity'],message:string,reference?:string):AgentValidationFinding{return freeze({code,category,severity,message,...(reference===undefined?{}:{reference})});}
function registryKey(id:string,version:string,scope:AgentScope):string{return`${scope.tenantId}:${scope.workspaceId??''}:${scope.projectId??''}:${id}@${version}`;}
function sameScope(a:AgentScope,b:AgentScope):boolean{return a.tenantId===b.tenantId&&a.workspaceId===b.workspaceId&&a.projectId===b.projectId;}
function compatible(range:string,platform:string):boolean{return range==='*'||range===platform||range.startsWith('^')&&range.slice(1).split('.')[0]===platform.split('.')[0];}
function hash(value:string):string{let result=2166136261;for(const character of value){result^=character.codePointAt(0)??0;result=Math.imul(result,16777619);}return(result>>>0).toString(16);}

