/* eslint-disable @typescript-eslint/explicit-function-return-type, @typescript-eslint/no-unsafe-assignment */
import type { CapabilityBinding } from '@agentprodready/capability-resolution';
import type { ExecutionContext } from '@agentprodready/foundation';
import { describe,expect,it,vi } from 'vitest';
import { AiToolCallHandoff,ExternalToolError,FactoryToolAdapterResolver,InMemoryToolDiagnostics,InMemoryToolEvents,NormalizedToolError,PluginToolRegistrationAdapter,ReferenceToolAdapter,ToolInvocationCoordinator,ToolRegistry,ToolValidator,type ToolAdapter,type ToolContract,type ToolExecutionRequest } from '../index.js';

const binding:CapabilityBinding=Object.freeze({bindingId:'b',requestId:'r',capability:'external.lookup',capabilityContractVersion:'1',implementationId:'lookup',implementationVersion:'1',provider:Object.freeze({id:'external',pluginId:'plugin',contributionId:'lookup'}),source:'default',diagnosticId:'resolution:r'});
const context:ExecutionContext=Object.freeze({executionId:'e',correlationId:'c',startedAt:'x',configurationVersion:'v',securityContextId:'s',attributes:Object.freeze({})});
const contract:ToolContract=Object.freeze({id:'lookup',capability:'external.lookup',version:'1',inputSchema:Object.freeze({type:'object',required:Object.freeze(['query'])}),outputSchema:Object.freeze({type:'object'}),sideEffect:'read-only',idempotency:'idempotent',metadata:Object.freeze({}),pluginId:'plugin',contributionId:'lookup'});
const request:ToolExecutionRequest=Object.freeze({requestId:'t1',binding,node:Object.freeze({workflowId:'w',nodeId:'n',kind:'capability',capability:'external.lookup'}),context,parameters:Object.freeze({query:'value'}),authorization:Object.freeze({authorized:true,decisionId:'decision'}),metadata:Object.freeze({}),validation:Object.freeze({schemaVersion:'1'}),constraints:Object.freeze({})});
function fixture(adapter:ToolAdapter=new ReferenceToolAdapter(),registered:ToolContract=contract){const registry=new ToolRegistry();registry.register(registered);const resolver=new FactoryToolAdapterResolver();const factory=vi.fn(async()=>adapter);resolver.bind('lookup',factory);const diagnostics=new InMemoryToolDiagnostics();const events=new InMemoryToolEvents();const telemetry={completed:vi.fn(),failed:vi.fn()};return{coordinator:new ToolInvocationCoordinator(registry,resolver,new ToolValidator(),diagnostics,events,telemetry),registry,factory,diagnostics,events,telemetry};}

describe('Tool Framework',()=>{
 it('validates before a single standardized adapter invocation and normalizes the result',async()=>{const f=fixture();const result=await f.coordinator.invoke(request);expect(result.status).toBe('completed');expect(result.data).toEqual({query:'value'});expect(Object.isFrozen(result)).toBe(true);expect(f.factory).toHaveBeenCalledOnce();expect(f.events.facts[0]).toMatchObject({type:'tool.completed',sideEffect:'read-only',idempotency:'idempotent'});expect(f.telemetry.completed).toHaveBeenCalledOnce();});
 it('rejects missing parameters before adapter resolution',async()=>{const f=fixture();await expect(f.coordinator.invoke({...request,parameters:{}})).rejects.toMatchObject({code:'TOOL_VALIDATION'});expect(f.factory).not.toHaveBeenCalled();});
 it('enforces declared side-effect and idempotency metadata without retrying',async()=>{const mutating={...contract,sideEffect:'external-side-effect' as const,idempotency:'non-idempotent' as const};const f=fixture(new ReferenceToolAdapter(),mutating);await expect(f.coordinator.invoke(request)).rejects.toMatchObject({code:'TOOL_VALIDATION'});expect((await f.coordinator.invoke({...request,idempotencyKey:'key-1'})).tool).toMatchObject({sideEffect:'external-side-effect',idempotency:'non-idempotent'});expect(f.factory).toHaveBeenCalledOnce();});
 it.each([['authentication','TOOL_AUTHENTICATION'],['authorization','TOOL_AUTHORIZATION'],['validation','TOOL_VALIDATION'],['rate-limit','TOOL_RATE_LIMITED'],['connection','TOOL_CONNECTION'],['unavailable','TOOL_UNAVAILABLE'],['not-found','TOOL_NOT_FOUND'],['conflict','TOOL_CONFLICT'],['timeout','TOOL_TIMEOUT'],['rejected','TOOL_REJECTED'],['unknown','TOOL_UNKNOWN']] as const)('normalizes %s external errors',async(kind,code)=>{const adapter:ToolAdapter={id:'failure',invoke:async()=>{throw new ExternalToolError(kind,'normalized',kind==='rate-limit'||kind==='unavailable');},health:async()=>({name:'failure',status:'unhealthy'})};const f=fixture(adapter);await expect(f.coordinator.invoke(request)).rejects.toMatchObject({code,retryable:expect.any(Boolean)});expect(f.diagnostics.get('tool:t1')).toMatchObject({outcome:'failed',errorCode:code});expect(f.telemetry.failed).toHaveBeenCalledOnce();});
 it('keeps registration passive and plugin-compatible',()=>{const registry=new ToolRegistry();new PluginToolRegistrationAdapter().register('p',{kind:'tool',id:'plugin-tool',version:'1',metadata:{capability:'plugin.work',inputSchema:{type:'object'},outputSchema:{type:'object'},sideEffect:'mutating',idempotency:'idempotent'}},registry);expect(registry.list()[0]).toMatchObject({id:'plugin-tool',pluginId:'p',sideEffect:'mutating'});});
 it('hands normalized AI tool calls to Runtime-owned tool invocation',()=>{const handoff=new AiToolCallHandoff();const result=handoff.create({id:'call',name:'lookup',arguments:{query:'ai'}},{binding,node:request.node,context,authorization:request.authorization,metadata:{},validation:{schemaVersion:'1'},constraints:{}});expect(result).toMatchObject({requestId:'e:call',parameters:{query:'ai'}});expect(Object.isFrozen(result)).toBe(true);});
 it('rejects external-specific fields and non-JSON parameters',async()=>{await expect(fixture().coordinator.invoke({...request,constraints:{apiKey:'secret'}})).rejects.toBeInstanceOf(NormalizedToolError);await expect(fixture().coordinator.invoke({...request,parameters:{query:()=>true}})).rejects.toMatchObject({code:'TOOL_VALIDATION'});});
});
