import type { ExecutionContext,HealthResult } from '@agentforge/foundation';
import type { NodeExecutionContract } from '@agentforge/workflow';
import { ExternalMemoryError, NormalizedMemoryError, type MemoryErrorCode } from './memory-errors.js';
import { isCanonicalMemoryIdSegment } from './memory-id.js';

export type MemoryCategory='session'|'working'|'episodic'|'semantic'|'user'|'agent'|'organizational';
export type MemoryImportance='low'|'normal'|'high'|'critical';
export type MemoryLifetime='temporary'|'session'|'persistent'|'permanent';
export type MemoryVisibility='private'|'agent'|'user'|'workspace'|'tenant'|'organization';
export type MemoryState='captured'|'classified'|'organized'|'indexed'|'available'|'archived'|'expired'|'deleted';
export interface ExecutionReference {readonly executionId:string;readonly correlationId:string;readonly parentExecutionId?:string;}
export interface MemoryOwnership {readonly tenantId:string;readonly workspaceId?:string;readonly userId?:string;readonly agentId?:string;}
export interface MemoryAuthorization {readonly authorized:true;readonly decisionId:string;readonly allowedLabels:readonly string[];readonly allowedVisibilities:readonly MemoryVisibility[];}
export interface MemoryClassification {readonly category:MemoryCategory;readonly importance:MemoryImportance;readonly lifetime:MemoryLifetime;readonly visibility:MemoryVisibility;}
export interface MemoryRetention {readonly policyId:string;readonly category:'session-only'|'time-based'|'usage-based'|'policy-based'|'permanent'|'compliance-controlled';readonly expiresAt?:string;}
export interface MemoryCaptureRequest {readonly requestId:string;readonly sourceEventId:string;readonly producer:string;readonly execution:ExecutionReference;readonly context:ExecutionContext;readonly ownership:MemoryOwnership;readonly authorization:MemoryAuthorization;readonly content:unknown;readonly metadata:Readonly<Record<string,string>>;readonly securityLabels:readonly string[];readonly classification:MemoryClassification;readonly retention:MemoryRetention;readonly version:string;readonly occurredAt:string;readonly semantics:Readonly<{sideEffect:'state-producing';idempotency:'idempotent'}>;}
export interface MemoryRecord {readonly id:string;readonly sourceEventId:string;readonly producer:string;readonly execution:ExecutionReference;readonly ownership:MemoryOwnership;readonly content:unknown;readonly metadata:Readonly<Record<string,string>>;readonly securityLabels:readonly string[];readonly classification:MemoryClassification;readonly retention:MemoryRetention;readonly version:string;readonly occurredAt:string;readonly state:MemoryState;readonly lifecycleVersion:number;}
export type MemoryLifecycleAction='classify'|'organize'|'index'|'make-available'|'archive'|'expire'|'delete';
export interface MemoryLifecycleRequest {readonly requestId:string;readonly memoryId:string;readonly expectedLifecycleVersion:number;readonly action:MemoryLifecycleAction;readonly authorization:MemoryAuthorization;readonly context:ExecutionContext;readonly semantics:Readonly<{sideEffect:'mutating';idempotency:'idempotent'|'conditionally-idempotent'}>;}
export interface MemoryStorageProvider {save(record:MemoryRecord):Promise<void>;get(id:string):Promise<MemoryRecord|undefined>;replace(record:MemoryRecord,expectedLifecycleVersion:number):Promise<void>;health():Promise<HealthResult>;}
export type MemorySearchStrategy='keyword'|'semantic'|'temporal'|'metadata'|'relationship'|'hybrid';
export interface MemoryRetrievalRequest {readonly requestId:string;readonly query:string;readonly node:NodeExecutionContract;readonly context:ExecutionContext;readonly authorization:MemoryAuthorization;readonly categories:readonly MemoryCategory[];readonly strategy:MemorySearchStrategy;readonly ownership:Readonly<{userId?:string;agentId?:string}>;readonly from?:string;readonly to?:string;readonly maximumResults:number;readonly ranking:Readonly<{relevanceWeight:number;importanceWeight:number;recencyWeight:number;policyVersion:string;aiAssisted?:boolean}>;readonly metadata:Readonly<Record<string,string>>;}
export interface MemoryCandidate {readonly record:MemoryRecord;readonly relevance:number;readonly frequency:number;readonly searchStrategy:MemorySearchStrategy;}
export interface MemorySearchProvider {search(request:MemoryRetrievalRequest):Promise<Readonly<{candidates:readonly MemoryCandidate[];partialReasons:readonly string[]}>>;health():Promise<HealthResult>;}
export interface MemoryRankingStrategy {rank(candidates:readonly MemoryCandidate[],request:MemoryRetrievalRequest):readonly MemoryCandidate[];}
export interface RecalledMemory {readonly id:string;readonly category:MemoryCategory;readonly producer:string;readonly occurredAt:string;readonly content:unknown;readonly metadata:Readonly<Record<string,string>>;readonly securityLabels:readonly string[];readonly importance:MemoryImportance;readonly version:string;readonly score:number;readonly rank:number;readonly execution:ExecutionReference;}
export interface MemoryRetrievalResult {readonly requestId:string;readonly status:'complete'|'empty'|'partial';readonly memories:readonly RecalledMemory[];readonly strategy:MemorySearchStrategy;readonly rankingPolicyVersion:string;readonly securityScope:Readonly<{tenantId:string;workspaceId?:string;decisionId:string}>;readonly partialReasons:readonly string[];readonly diagnosticId:string;}
export interface NormalizedMemoryAiPort {enrich(record:MemoryRecord,context:ExecutionContext):Promise<Readonly<Record<string,string>>>;consolidate(records:readonly MemoryRecord[],context:ExecutionContext):Promise<unknown>;rerank(candidates:readonly MemoryCandidate[],query:string,context:ExecutionContext):Promise<readonly string[]>;}
export interface MemoryConsolidationRequest {readonly requestId:string;readonly recordIds:readonly string[];readonly context:ExecutionContext;readonly authorization:MemoryAuthorization;readonly policyVersion:string;}
export type { MemoryErrorCode };
export { ExternalMemoryError, NormalizedMemoryError };
export interface MemoryDiagnostic {readonly id:string;readonly operation:'capture'|'lifecycle'|'retrieval'|'consolidation';readonly outcome:'completed'|'failed';readonly counts:Readonly<Record<string,number>>;readonly errorCode?:MemoryErrorCode;}
export interface MemoryDiagnostics {record(value:MemoryDiagnostic):void;list():readonly MemoryDiagnostic[];}
export interface MemoryFact {readonly type:string;readonly requestId:string;readonly executionId:string;readonly diagnosticId:string;}
export interface MemoryEvents {publish(value:MemoryFact):Promise<void>;}
export interface MemoryTelemetry {captured(category:MemoryCategory):void;transitioned(state:MemoryState):void;retrieved(candidates:number,authorized:number,results:number):void;failed(code:MemoryErrorCode):void;}

const lifecycle:Readonly<Record<MemoryState,Partial<Record<MemoryLifecycleAction,MemoryState>>>>={captured:{classify:'classified'},classified:{organize:'organized'},organized:{index:'indexed'},indexed:{'make-available':'available'},available:{archive:'archived',expire:'expired',delete:'deleted'},archived:{expire:'expired',delete:'deleted'},expired:{delete:'deleted'},deleted:{}};
export class MemoryEngine {
 public constructor(private readonly storage:MemoryStorageProvider,private readonly search:MemorySearchProvider,private readonly ranking:MemoryRankingStrategy,private readonly ai:NormalizedMemoryAiPort,private readonly diagnostics:MemoryDiagnostics,private readonly events:MemoryEvents,private readonly telemetry:MemoryTelemetry,private readonly now:()=>Date=()=>new Date()){}
 public async capture(request:MemoryCaptureRequest):Promise<MemoryRecord>{const diagnosticId=`memory:capture:${request.requestId}`;try{validateCapture(request);const record:MemoryRecord=deepFreeze({id:`memory:${request.ownership.tenantId}:${request.sourceEventId}`,sourceEventId:request.sourceEventId,producer:request.producer,execution:{...request.execution},ownership:{...request.ownership},content:cloneJson(request.content),metadata:{...request.metadata},securityLabels:[...request.securityLabels],classification:{...request.classification},retention:{...request.retention},version:request.version,occurredAt:request.occurredAt,state:'captured',lifecycleVersion:0});if(await this.storage.get(record.id)!==undefined)throw new ExternalMemoryError('duplicate','Memory already captured');await this.storage.save(record);this.diagnostics.record({id:diagnosticId,operation:'capture',outcome:'completed',counts:{records:1}});await this.events.publish({type:'memory.captured',requestId:request.requestId,executionId:request.context.executionId,diagnosticId});this.telemetry.captured(record.classification.category);return record;}catch(error){throw this.#failure(error,diagnosticId,'capture');}}
 public async transition(request:MemoryLifecycleRequest):Promise<MemoryRecord>{const diagnosticId=`memory:lifecycle:${request.requestId}`;try{const current=await this.storage.get(request.memoryId);if(current===undefined)throw new ExternalMemoryError('unavailable','Memory not found');assertAuthorized(current,request.context,request.authorization);const next=lifecycle[current.state][request.action];if(next===undefined)throw new ExternalMemoryError('version-conflict','Invalid lifecycle transition');if(request.action==='expire'&&current.retention.category==='permanent')throw new ExternalMemoryError('retention-failure','Permanent memory cannot expire');const updated=deepFreeze({...current,state:next,lifecycleVersion:current.lifecycleVersion+1});await this.storage.replace(updated,request.expectedLifecycleVersion);this.diagnostics.record({id:diagnosticId,operation:'lifecycle',outcome:'completed',counts:{records:1}});await this.events.publish({type:`memory.${next}`,requestId:request.requestId,executionId:request.context.executionId,diagnosticId});this.telemetry.transitioned(next);return updated;}catch(error){throw this.#failure(error,diagnosticId,'lifecycle');}}
 public async retrieve(request:MemoryRetrievalRequest):Promise<MemoryRetrievalResult>{const diagnosticId=`memory:retrieve:${request.requestId}`;try{validateRetrieval(request);const response=await this.search.search(deepFreeze(copyRetrieval(request)));const instant=this.now();const scoped=response.candidates.filter(candidate=>candidate.record.state==='available'&&!isExpired(candidate.record,instant)&&authorized(candidate.record,request));const unique=deduplicate(scoped);let ranked=this.ranking.rank(unique,request);if(request.ranking.aiAssisted===true){const order=await this.ai.rerank(ranked,request.query,request.context);const positions=new Map(order.map((id,index)=>[id,index]));ranked=[...ranked].sort((a,b)=>(positions.get(a.record.id)??Number.MAX_SAFE_INTEGER)-(positions.get(b.record.id)??Number.MAX_SAFE_INTEGER));}ranked=ranked.slice(0,request.maximumResults);const memories=ranked.map((candidate,index)=>deepFreeze({id:candidate.record.id,category:candidate.record.classification.category,producer:candidate.record.producer,occurredAt:candidate.record.occurredAt,content:cloneJson(candidate.record.content),metadata:{...candidate.record.metadata},securityLabels:[...candidate.record.securityLabels],importance:candidate.record.classification.importance,version:candidate.record.version,score:candidate.relevance,rank:index+1,execution:{...candidate.record.execution}}));const status=response.partialReasons.length>0?'partial':memories.length===0?'empty':'complete';const securityScope={tenantId:request.context.tenantId??'',...(request.context.workspaceId===undefined?{}:{workspaceId:request.context.workspaceId}),decisionId:request.authorization.decisionId};const result:MemoryRetrievalResult=deepFreeze({requestId:request.requestId,status,memories,strategy:request.strategy,rankingPolicyVersion:request.ranking.policyVersion,securityScope,partialReasons:[...response.partialReasons],diagnosticId});this.diagnostics.record({id:diagnosticId,operation:'retrieval',outcome:'completed',counts:{candidates:response.candidates.length,authorized:scoped.length,results:memories.length}});await this.events.publish({type:`memory.retrieval.${status}`,requestId:request.requestId,executionId:request.context.executionId,diagnosticId});this.telemetry.retrieved(response.candidates.length,scoped.length,memories.length);return result;}catch(error){throw this.#failure(error,diagnosticId,'retrieval');}}
 public async enrich(id:string,context:ExecutionContext,authorization:MemoryAuthorization):Promise<MemoryRecord>{const record=await this.storage.get(id);if(record===undefined)throw new NormalizedMemoryError('MEMORY_UNAVAILABLE','Memory not found',`memory:enrich:${id}`);assertAuthorized(record,context,authorization);try{const metadata=await this.ai.enrich(record,context);const updated=deepFreeze({...record,metadata:{...record.metadata,...metadata},lifecycleVersion:record.lifecycleVersion+1});await this.storage.replace(updated,record.lifecycleVersion);return updated;}catch(error){throw this.#failure(error,`memory:enrich:${id}`,'lifecycle');}}
 public async consolidate(request:MemoryConsolidationRequest):Promise<unknown>{const diagnosticId=`memory:consolidate:${request.requestId}`;try{const records:MemoryRecord[]=[];for(const id of request.recordIds){const record=await this.storage.get(id);if(record===undefined)throw new ExternalMemoryError('unavailable','Memory not found');assertAuthorized(record,request.context,request.authorization);records.push(record);}if(!sameScope(records))throw new ExternalMemoryError('consolidation-failure','Incompatible memory scopes');const content=await this.ai.consolidate(Object.freeze(records),request.context);this.diagnostics.record({id:diagnosticId,operation:'consolidation',outcome:'completed',counts:{records:records.length}});return cloneJson(content);}catch(error){throw this.#failure(error,diagnosticId,'consolidation');}}
 #failure(error:unknown,id:string,operation:MemoryDiagnostic['operation']):NormalizedMemoryError{const normalized=normalizeError(error,id);this.diagnostics.record({id,operation,outcome:'failed',counts:{},errorCode:normalized.code});this.telemetry.failed(normalized.code);return normalized;}
}

export class WeightedMemoryRanking implements MemoryRankingStrategy {public rank(candidates:readonly MemoryCandidate[],request:MemoryRetrievalRequest):readonly MemoryCandidate[]{const importance={low:.1,normal:.5,high:.8,critical:1};const now=Date.parse(request.context.startedAt);return Object.freeze([...candidates].sort((a,b)=>score(b)-score(a)||a.record.id.localeCompare(b.record.id)));function score(value:MemoryCandidate):number{const age=Math.max(0,now-Date.parse(value.record.occurredAt));const recency=1/(1+age/86400000);return value.relevance*request.ranking.relevanceWeight+importance[value.record.classification.importance]*request.ranking.importanceWeight+recency*request.ranking.recencyWeight;}}}
function validateCapture(value:MemoryCaptureRequest):void{if(value.requestId.trim()===''||value.sourceEventId.trim()===''||value.producer.trim()===''||value.context.tenantId!==value.ownership.tenantId||value.authorization.decisionId.trim()===''||!isJson(value.content)||!value.securityLabels.every(label=>value.authorization.allowedLabels.includes(label))||!isCanonicalMemoryIdSegment(value.ownership.tenantId)||!isCanonicalMemoryIdSegment(value.sourceEventId))throw new NormalizedMemoryError('MEMORY_VALIDATION','Invalid memory capture',`memory:capture:${value.requestId}`);}
function validateRetrieval(value:MemoryRetrievalRequest):void{if(value.requestId.trim()===''||value.query.trim()===''||value.maximumResults<1||value.context.tenantId===undefined||value.authorization.decisionId.trim()==='')throw new NormalizedMemoryError('MEMORY_VALIDATION','Invalid memory retrieval',`memory:retrieve:${value.requestId}`);}
function isExpired(record:MemoryRecord,now:Date):boolean{const expiresAt=record.retention.expiresAt;if(expiresAt===undefined)return false;const deadline=Date.parse(expiresAt);return Number.isFinite(deadline)&&now.getTime()>=deadline;}
function authorized(record:MemoryRecord,request:MemoryRetrievalRequest):boolean{return record.ownership.tenantId===request.context.tenantId&&(!request.context.workspaceId||record.ownership.workspaceId===request.context.workspaceId)&&(!request.ownership.userId||record.ownership.userId===request.ownership.userId)&&(!request.ownership.agentId||record.ownership.agentId===request.ownership.agentId)&&request.categories.includes(record.classification.category)&&request.authorization.allowedVisibilities.includes(record.classification.visibility)&&record.securityLabels.every(label=>request.authorization.allowedLabels.includes(label))&&(!request.from||record.occurredAt>=request.from)&&(!request.to||record.occurredAt<=request.to);}
function assertAuthorized(record:MemoryRecord,context:ExecutionContext,authorization:MemoryAuthorization):void{if(record.ownership.tenantId!==context.tenantId||(!context.workspaceId?false:record.ownership.workspaceId!==context.workspaceId)||!authorization.allowedVisibilities.includes(record.classification.visibility)||!record.securityLabels.every(label=>authorization.allowedLabels.includes(label)))throw new NormalizedMemoryError('MEMORY_VALIDATION','Memory security scope rejected',`memory:security:${record.id}`);}
function sameScope(records:readonly MemoryRecord[]):boolean{return records.length>0&&records.every(record=>JSON.stringify(record.ownership)===JSON.stringify(records[0]?.ownership)&&JSON.stringify(record.securityLabels)===JSON.stringify(records[0]?.securityLabels));}
function deduplicate(values:readonly MemoryCandidate[]):readonly MemoryCandidate[]{const map=new Map<string,MemoryCandidate>();for(const value of values){const current=map.get(value.record.id);if(current===undefined||value.relevance>current.relevance)map.set(value.record.id,value);}return [...map.values()];}
function normalizeError(error:unknown,id:string):NormalizedMemoryError{if(error instanceof NormalizedMemoryError)return error;const kind=error instanceof ExternalMemoryError?error.kind:'unknown';const code=({duplicate:'MEMORY_DUPLICATE','version-conflict':'MEMORY_VERSION_CONFLICT','storage-unavailable':'MEMORY_STORAGE_UNAVAILABLE','retrieval-failure':'MEMORY_RETRIEVAL_FAILURE','index-unavailable':'MEMORY_INDEX_UNAVAILABLE','consolidation-failure':'MEMORY_CONSOLIDATION_FAILURE','enrichment-failure':'MEMORY_ENRICHMENT_FAILURE','serialization-failure':'MEMORY_SERIALIZATION_FAILURE','retention-failure':'MEMORY_RETENTION_FAILURE','archive-failure':'MEMORY_ARCHIVE_FAILURE','deletion-failure':'MEMORY_DELETION_FAILURE',throttled:'MEMORY_THROTTLED',timeout:'MEMORY_TIMEOUT',unavailable:'MEMORY_UNAVAILABLE',unknown:'MEMORY_UNKNOWN'} as const)[kind];return new NormalizedMemoryError(code,error instanceof Error?error.message:'Memory operation failed',id);}
function copyRetrieval(value:MemoryRetrievalRequest):MemoryRetrievalRequest{return{...value,authorization:{...value.authorization,allowedLabels:[...value.authorization.allowedLabels],allowedVisibilities:[...value.authorization.allowedVisibilities]},categories:[...value.categories],ownership:{...value.ownership},ranking:{...value.ranking},metadata:{...value.metadata}};}
function cloneJson(value:unknown):unknown{return JSON.parse(JSON.stringify(value)) as unknown;}
function isJson(value:unknown):boolean{try{JSON.stringify(value);return value!==undefined;}catch{return false;}}
function deepFreeze<T>(value:T):T{if(typeof value==='object'&&value!==null&&!Object.isFrozen(value)){for(const child of Object.values(value))deepFreeze(child);Object.freeze(value);}return value;}
export * from './reference.js';
export * from './memory-id.js';
export { PersistenceBackedMemoryProvider } from './persistence-backed-memory-provider.js';

