/* eslint-disable @typescript-eslint/explicit-function-return-type */
import type { ExecutionContext } from '@agentforge/foundation';
import { describe,expect,it,vi } from 'vitest';
import { ExternalMemoryError,InMemoryMemoryDiagnostics,InMemoryMemoryEvents,InMemoryMemoryProvider,MemoryEngine,NoopMemoryAiPort,WeightedMemoryRanking,type MemoryAuthorization,type MemoryCaptureRequest,type MemoryRankingStrategy,type MemoryRecord,type MemoryRetrievalRequest,type MemorySearchProvider,type MemoryTelemetry } from './index.js';

const context:ExecutionContext=Object.freeze({executionId:'e',correlationId:'c',tenantId:'tenant',workspaceId:'workspace',startedAt:'2026-08-06T00:00:00.000Z',configurationVersion:'v',securityContextId:'s',attributes:Object.freeze({})});
const authorization:MemoryAuthorization=Object.freeze<MemoryAuthorization>({authorized:true,decisionId:'d',allowedLabels:Object.freeze(['public']),allowedVisibilities:Object.freeze(['private','user','workspace'])});
const capture=(event='event-1',overrides:Partial<MemoryCaptureRequest>={}):MemoryCaptureRequest=>({requestId:`capture-${event}`,sourceEventId:event,producer:'runtime',execution:{executionId:'e',correlationId:'c'},context,ownership:{tenantId:'tenant',workspaceId:'workspace',userId:'user'},authorization,content:{observation:`remember ${event}`},metadata:{topic:'test'},securityLabels:['public'],classification:{category:'episodic',importance:'normal',lifetime:'persistent',visibility:'user'},retention:{policyId:'retain',category:'time-based',expiresAt:'2027-01-01T00:00:00.000Z'},version:'1',occurredAt:'2026-08-05T00:00:00.000Z',semantics:{sideEffect:'state-producing',idempotency:'idempotent'},...overrides});
function fixture(provider:InMemoryMemoryProvider=new InMemoryMemoryProvider(),ranking:MemoryRankingStrategy=new WeightedMemoryRanking(),ai=new NoopMemoryAiPort()){const diagnostics=new InMemoryMemoryDiagnostics();const events=new InMemoryMemoryEvents();const captured=vi.fn();const transitioned=vi.fn();const retrieved=vi.fn();const telemetry:MemoryTelemetry={captured,transitioned,retrieved,failed:vi.fn()};return{engine:new MemoryEngine(provider,provider,ranking,ai,diagnostics,events,telemetry),provider,diagnostics,events,telemetry,captured,transitioned,retrieved};}
async function available(f:ReturnType<typeof fixture>,request:MemoryCaptureRequest):Promise<MemoryRecord>{let record=await f.engine.capture(request);for(const action of ['classify','organize','index','make-available'] as const)record=await f.engine.transition({requestId:`${request.requestId}-${action}`,memoryId:record.id,expectedLifecycleVersion:record.lifecycleVersion,action,authorization:request.authorization,context,semantics:{sideEffect:'mutating',idempotency:'idempotent'}});return record;}
const retrieval=(overrides:Partial<MemoryRetrievalRequest>={}):MemoryRetrievalRequest=>({requestId:'retrieve',query:'remember',node:{workflowId:'w',nodeId:'n',kind:'capability',capability:'memory.retrieve'},context,authorization,categories:['episodic'],strategy:'keyword',ownership:{userId:'user'},maximumResults:10,ranking:{relevanceWeight:1,importanceWeight:1,recencyWeight:1,policyVersion:'rank-1'},metadata:{},...overrides});

describe('Memory Engine',()=>{
 it('captures standardized immutable execution-derived records with stable identity',async()=>{const f=fixture();const record=await f.engine.capture(capture());expect(record).toMatchObject({id:'memory:tenant:event-1',state:'captured',producer:'runtime',execution:{executionId:'e'}});expect(record).not.toHaveProperty('context');expect(Object.isFrozen(record)).toBe(true);expect(f.events.facts[0]?.type).toBe('memory.captured');expect(f.captured).toHaveBeenCalledWith('episodic');});
 it('keeps lifecycle and retention semantics independent of replaceable storage',async()=>{const f=fixture();const record=await available(f,capture());const archived=await f.engine.transition({requestId:'archive',memoryId:record.id,expectedLifecycleVersion:record.lifecycleVersion,action:'archive',authorization,context,semantics:{sideEffect:'mutating',idempotency:'conditionally-idempotent'}});expect(archived.state).toBe('archived');expect(f.transitioned).toHaveBeenCalled();});
 it('prevents duplicate capture and version conflicts through normalized failures',async()=>{const f=fixture();await f.engine.capture(capture());await expect(f.engine.capture(capture())).rejects.toMatchObject({code:'MEMORY_DUPLICATE'});await expect(f.engine.transition({requestId:'bad',memoryId:'memory:tenant:event-1',expectedLifecycleVersion:9,action:'classify',authorization,context,semantics:{sideEffect:'mutating',idempotency:'idempotent'}})).rejects.toMatchObject({code:'MEMORY_VERSION_CONFLICT'});});
 it('retrieves only through requests, mandatorily filters security, deduplicates, and freezes results',async()=>{const f=fixture();await available(f,capture('public'));await available(f,capture('secret',{securityLabels:['secret'],authorization:{...authorization,allowedLabels:['public','secret']}}));const result=await f.engine.retrieve(retrieval());expect(result.status).toBe('complete');expect(result.memories).toHaveLength(1);expect(result.memories[0]?.id).toBe('memory:tenant:public');expect(Object.isFrozen(result)).toBe(true);expect(f.retrieved).toHaveBeenCalledWith(2,1,1);});
 it('supports configurable provider-independent ranking and explicit empty/partial results',async()=>{const reverse:MemoryRankingStrategy={rank:candidates=>[...candidates].reverse()};const f=fixture(new InMemoryMemoryProvider(),reverse);await available(f,capture('a'));await available(f,capture('b'));expect((await f.engine.retrieve(retrieval())).memories.map(x=>x.id)).toEqual(['memory:tenant:b','memory:tenant:a']);const partialProvider:MemorySearchProvider={search:async()=>({candidates:[],partialReasons:['provider-unavailable']}),health:async()=>({name:'p',status:'degraded'})};const emptyFixture=fixture();const engine=new MemoryEngine(emptyFixture.provider,partialProvider,reverse,new NoopMemoryAiPort(),emptyFixture.diagnostics,emptyFixture.events,emptyFixture.telemetry);expect(await engine.retrieve(retrieval({requestId:'partial'}))).toMatchObject({status:'partial',memories:[],partialReasons:['provider-unavailable']});});
 it('routes enrichment, consolidation, and reranking through a normalized AI boundary',async()=>{const ai={enrich:vi.fn(async()=>({sentiment:'positive'})),consolidate:vi.fn(async(records:readonly MemoryRecord[])=>({count:records.length})),rerank:vi.fn(async()=>['memory:tenant:b','memory:tenant:a'])};const f=fixture(new InMemoryMemoryProvider(),new WeightedMemoryRanking(),ai);const first=await available(f,capture('a'));const second=await available(f,capture('b'));expect((await f.engine.enrich(first.id,context,authorization)).metadata.sentiment).toBe('positive');expect(await f.engine.consolidate({requestId:'consolidate',recordIds:[first.id,second.id],context,authorization,policyVersion:'1'})).toEqual({count:2});expect((await f.engine.retrieve(retrieval({ranking:{relevanceWeight:1,importanceWeight:1,recencyWeight:1,policyVersion:'ai-rank-1',aiAssisted:true}}))).memories.map(memory=>memory.id)).toEqual(['memory:tenant:b','memory:tenant:a']);expect(ai.consolidate).toHaveBeenCalledOnce();expect(ai.rerank).toHaveBeenCalledOnce();});
 it('rejects consolidation across incompatible ownership/security scopes',async()=>{const f=fixture();const first=await available(f,capture('a'));const other=await available(f,capture('b',{ownership:{tenantId:'tenant',workspaceId:'workspace',userId:'other'}}));await expect(f.engine.consolidate({requestId:'bad-scope',recordIds:[first.id,other.id],context,authorization,policyVersion:'1'})).rejects.toMatchObject({code:'MEMORY_CONSOLIDATION_FAILURE'});});
 it('normalizes technology failures and exposes provider health without technology models',async()=>{class FailingProvider extends InMemoryMemoryProvider {public override async search():Promise<never>{throw new ExternalMemoryError('retrieval-failure','database detail hidden');}}const provider=new FailingProvider();const f=fixture(provider);await expect(f.engine.retrieve(retrieval())).rejects.toMatchObject({code:'MEMORY_RETRIEVAL_FAILURE'});expect(await provider.health()).toEqual({name:'in-memory-memory-provider',status:'healthy'});expect(JSON.stringify(f.diagnostics.list())).not.toMatch(/database detail|sdk|sql/iu);});
});


