import type { HealthResult } from '@agentprodready/foundation';
import { ExternalMemoryError } from './memory-errors.js';
import type { MemoryCandidate,MemoryDiagnostic,MemoryDiagnostics,MemoryEvents,MemoryFact,MemoryRecord,MemoryRetrievalRequest,MemorySearchProvider,MemoryStorageProvider,MemoryTelemetry,NormalizedMemoryAiPort } from './index.js';
export class InMemoryMemoryProvider implements MemoryStorageProvider,MemorySearchProvider {readonly #items=new Map<string,MemoryRecord>();public async save(record:MemoryRecord):Promise<void>{if(this.#items.has(record.id))throw new ExternalMemoryError('duplicate','Memory already exists');this.#items.set(record.id,record);}public async get(id:string):Promise<MemoryRecord|undefined>{return this.#items.get(id);}public async replace(record:MemoryRecord,expected:number):Promise<void>{const current=this.#items.get(record.id);if(current?.lifecycleVersion!==expected)throw new ExternalMemoryError('version-conflict','Memory version conflict');this.#items.set(record.id,record);}public async search(request:MemoryRetrievalRequest):Promise<Readonly<{candidates:readonly MemoryCandidate[];partialReasons:readonly string[]}>>{const terms=request.query.toLowerCase().split(/\s+/gu);const candidates=[...this.#items.values()].map(record=>{const text=JSON.stringify(record.content).toLowerCase();const relevance=terms.filter(term=>text.includes(term)).length/terms.length;return Object.freeze({record,relevance,frequency:1,searchStrategy:request.strategy});});return Object.freeze({candidates:Object.freeze(candidates),partialReasons:Object.freeze([])});}public async health():Promise<HealthResult>{return{name:'in-memory-memory-provider',status:'healthy'};}public list():readonly MemoryRecord[]{return Object.freeze([...this.#items.values()]);}}
export class NoopMemoryAiPort implements NormalizedMemoryAiPort {public async enrich():Promise<Readonly<Record<string,string>>>{return Object.freeze({});}public async consolidate(records:readonly MemoryRecord[]):Promise<unknown>{return records.map(record=>record.content);}public async rerank(candidates:readonly MemoryCandidate[]):Promise<readonly string[]>{return candidates.map(candidate=>candidate.record.id);}}
export class InMemoryMemoryDiagnostics implements MemoryDiagnostics {readonly items:MemoryDiagnostic[]=[];public record(value:MemoryDiagnostic):void{this.items.push(value);}public list():readonly MemoryDiagnostic[]{return Object.freeze([...this.items]);}}
export class InMemoryMemoryEvents implements MemoryEvents {readonly facts:MemoryFact[]=[];public async publish(value:MemoryFact):Promise<void>{this.facts.push(value);}}
export class NoopMemoryTelemetry implements MemoryTelemetry {public captured(_category:Parameters<MemoryTelemetry['captured']>[0]):void{}public transitioned(_state:Parameters<MemoryTelemetry['transitioned']>[0]):void{}public retrieved(_candidates:number,_authorized:number,_results:number):void{}public failed(_code:Parameters<MemoryTelemetry['failed']>[0]):void{}}

