import type { CapabilityBinding } from '@agentforge/capability-resolution';
import type { ExecutionContext,HealthResult } from '@agentforge/foundation';
import type { NodeExecutionContract } from '@agentforge/workflow';

export interface KnowledgeSource {readonly id:string;readonly category:string;readonly tenantId:string;readonly workspaceId?:string;readonly connectorId:string;readonly metadata:Readonly<Record<string,string>>;}
export interface KnowledgeAuthorization {readonly authorized:true;readonly decisionId:string;readonly allowedLabels:readonly string[];}
export type IngestionMode='full'|'incremental'|'targeted'|'reindex'|'deletion-sync';
export interface KnowledgeIngestionRequest {readonly requestId:string;readonly source:KnowledgeSource;readonly context:ExecutionContext;readonly mode:IngestionMode;readonly authorization:KnowledgeAuthorization;readonly processingVersion:string;readonly chunkingVersion:string;readonly indexVersion:string;readonly sinceVersion?:string;readonly targetRecordIds?:readonly string[];readonly metadata:Readonly<Record<string,string>>;readonly semantics:Readonly<{sideEffect:'state-producing'|'mutating';idempotency:'idempotent'|'conditionally-idempotent'}>;}
export interface RawKnowledgeRecord {readonly sourceId:string;readonly recordId:string;readonly content:string;readonly contentType:string;readonly metadata:Readonly<Record<string,string>>;readonly sourceVersion:string;readonly sourceTimestamp:string;readonly securityLabels:readonly string[];readonly sourceReference:string;}
export interface KnowledgeDocument {readonly id:string;readonly sourceId:string;readonly content:string;readonly contentType:string;readonly metadata:Readonly<Record<string,string>>;readonly securityLabels:readonly string[];readonly sourceReference:string;readonly sourceVersion:string;readonly processingVersion:string;}
export interface KnowledgeChunk {readonly id:string;readonly documentId:string;readonly sourceId:string;readonly content:string;readonly position:number;readonly structuralPath:readonly string[];readonly metadata:Readonly<Record<string,string>>;readonly securityLabels:readonly string[];readonly sourceReference:string;readonly sourceVersion:string;readonly processingVersion:string;readonly chunkingVersion:string;}
export interface KnowledgeIndexRecord {readonly id:string;readonly chunkId:string;readonly content:string;readonly metadata:Readonly<Record<string,string>>;readonly securityLabels:readonly string[];readonly sourceReference:string;readonly sourceVersion:string;readonly processingVersion:string;readonly chunkingVersion:string;readonly indexVersion:string;}
export interface KnowledgeConnector {readonly id:string;acquire(request:KnowledgeIngestionRequest):Promise<readonly RawKnowledgeRecord[]>;health():Promise<HealthResult>;}
export interface KnowledgeConnectorResolver {resolve(id:string):Promise<KnowledgeConnector>;}
export interface DocumentNormalizer {normalize(record:RawKnowledgeRecord,request:KnowledgeIngestionRequest):KnowledgeDocument;}
export interface ChunkingStrategy {readonly id:string;chunk(document:KnowledgeDocument,request:KnowledgeIngestionRequest):readonly KnowledgeChunk[];}
export interface KnowledgeEnricher {enrich(chunk:KnowledgeChunk,context:ExecutionContext):Promise<KnowledgeChunk>;}
export interface KnowledgeIndexProvider {write(records:readonly KnowledgeIndexRecord[]):Promise<void>;search(query:NormalizedKnowledgeQuery):Promise<readonly KnowledgeCandidate[]>;health():Promise<HealthResult>;}
export interface IngestionCheckpointStore {get(sourceId:string):string|undefined;set(sourceId:string,version:string):void;}
export interface KnowledgeIngestionResult {readonly requestId:string;readonly sourceId:string;readonly status:'completed';readonly processedRecords:number;readonly createdDocuments:number;readonly createdChunks:number;readonly skippedRecords:number;readonly indexVersion:string;readonly processingVersion:string;readonly diagnosticId:string;readonly semantics:KnowledgeIngestionRequest['semantics'];}

export type RetrievalStrategy='keyword'|'vector'|'hybrid'|'metadata'|'graph'|'federated'|'source-specific';
export interface KnowledgeRetrievalRequest {readonly requestId:string;readonly query:string;readonly binding:CapabilityBinding;readonly node:NodeExecutionContract;readonly context:ExecutionContext;readonly sourceIds:readonly string[];readonly strategy:RetrievalStrategy;readonly filters:Readonly<Record<string,string|readonly string[]>>;readonly authorization:KnowledgeAuthorization;readonly maximumResults:number;readonly minimumScore:number;readonly metadata:Readonly<Record<string,string>>;}
export interface NormalizedKnowledgeQuery {readonly text:string;readonly terms:readonly string[];readonly sourceIds:readonly string[];readonly strategy:RetrievalStrategy;readonly filters:Readonly<Record<string,string|readonly string[]>>;readonly tenantId?:string;readonly workspaceId?:string;}
export interface KnowledgeCandidate {readonly chunkId:string;readonly documentId:string;readonly sourceId:string;readonly content:string;readonly sourceReference:string;readonly metadata:Readonly<Record<string,string>>;readonly securityLabels:readonly string[];readonly score:number;readonly strategy:RetrievalStrategy;readonly indexVersion:string;readonly sourceVersion:string;}
export interface RetrievedKnowledgeItem extends KnowledgeCandidate {readonly rank:number;readonly citation:Readonly<{sourceReference:string;documentId:string;chunkId:string;version:string}>;}
export type EmptyReason='no-matches'|'security-trimmed'|'below-quality';
export interface KnowledgeRetrievalResult {readonly requestId:string;readonly status:'complete'|'empty'|'partial';readonly querySummary:string;readonly items:readonly RetrievedKnowledgeItem[];readonly strategies:readonly RetrievalStrategy[];readonly securityScope:Readonly<{tenantId?:string;workspaceId?:string;decisionId:string}>;readonly emptyReason?:EmptyReason;readonly partialReasons:readonly string[];readonly diagnosticId:string;readonly metadata:Readonly<Record<string,string>>;}
export interface RetrievalStrategyProvider {retrieve(query:NormalizedKnowledgeQuery):Promise<Readonly<{candidates:readonly KnowledgeCandidate[];partialReasons:readonly string[]}>>;health():Promise<HealthResult>;}
export interface RetrievalProviderResolver {resolve(strategy:RetrievalStrategy):Promise<RetrievalStrategyProvider>;}
export type KnowledgeErrorCode='KNOWLEDGE_INVALID_REQUEST'|'KNOWLEDGE_SOURCE_UNAVAILABLE'|'KNOWLEDGE_AUTHENTICATION'|'KNOWLEDGE_AUTHORIZATION'|'KNOWLEDGE_UNSUPPORTED_CONTENT'|'KNOWLEDGE_PROCESSING'|'KNOWLEDGE_INDEX_FAILURE'|'KNOWLEDGE_VERSION_CONFLICT'|'KNOWLEDGE_RETRIEVAL_FAILURE'|'KNOWLEDGE_TIMEOUT'|'KNOWLEDGE_UNKNOWN';
export class ExternalKnowledgeError extends Error {public constructor(public readonly kind:'source-unavailable'|'authentication'|'authorization'|'unsupported-content'|'processing'|'index-failure'|'version-conflict'|'retrieval-failure'|'timeout'|'unknown',message:string){super(message);this.name='ExternalKnowledgeError';}}
export class NormalizedKnowledgeError extends Error {public constructor(public readonly code:KnowledgeErrorCode,message:string,public readonly diagnosticId:string){super(message);this.name='NormalizedKnowledgeError';}}
export interface KnowledgeDiagnostic {readonly id:string;readonly operation:'ingestion'|'retrieval';readonly outcome:'completed'|'failed';readonly counts:Readonly<Record<string,number>>;readonly versions:readonly string[];readonly errorCode?:KnowledgeErrorCode;}
export interface KnowledgeDiagnostics {record(value:KnowledgeDiagnostic):void;list():readonly KnowledgeDiagnostic[];}
export interface KnowledgeFact {readonly type:string;readonly requestId:string;readonly executionId:string;readonly diagnosticId:string;}
export interface KnowledgeEvents {publish(value:KnowledgeFact):Promise<void>;}
export interface KnowledgeTelemetry {ingested(records:number,chunks:number):void;retrieved(candidates:number,authorized:number,results:number):void;failed(code:KnowledgeErrorCode):void;}

export class KnowledgeIngestionCoordinator {
 public constructor(private readonly connectors:KnowledgeConnectorResolver,private readonly normalizer:DocumentNormalizer,private readonly chunker:ChunkingStrategy,private readonly enricher:KnowledgeEnricher,private readonly index:KnowledgeIndexProvider,private readonly checkpoints:IngestionCheckpointStore,private readonly diagnostics:KnowledgeDiagnostics,private readonly events:KnowledgeEvents,private readonly telemetry:KnowledgeTelemetry){}
 public async ingest(request:KnowledgeIngestionRequest):Promise<KnowledgeIngestionResult>{validateIngestion(request);const diagnosticId=`knowledge:ingest:${request.requestId}`;try{const connector=await this.connectors.resolve(request.source.connectorId);const records=await connector.acquire(deepFreeze(copyIngestion(request)));const previous=request.mode==='incremental'?(request.sinceVersion??this.checkpoints.get(request.source.id)):undefined;const applicable=records.filter(record=>previous===undefined||record.sourceVersion>previous);const documents=applicable.map(record=>this.normalizer.normalize(record,request));const chunks:KnowledgeChunk[]=[];for(const document of documents)for(const chunk of this.chunker.chunk(document,request))chunks.push(await this.enricher.enrich(chunk,request.context));const indexRecords=chunks.map(chunk=>toIndexRecord(chunk,request.indexVersion));await this.index.write(Object.freeze(indexRecords));const maximum=applicable.map(record=>record.sourceVersion).sort().at(-1);if(maximum!==undefined)this.checkpoints.set(request.source.id,maximum);const result:KnowledgeIngestionResult=deepFreeze({requestId:request.requestId,sourceId:request.source.id,status:'completed',processedRecords:applicable.length,createdDocuments:documents.length,createdChunks:chunks.length,skippedRecords:records.length-applicable.length,indexVersion:request.indexVersion,processingVersion:request.processingVersion,diagnosticId,semantics:{...request.semantics}});this.diagnostics.record(deepFreeze({id:diagnosticId,operation:'ingestion',outcome:'completed',counts:{records:applicable.length,chunks:chunks.length},versions:[request.processingVersion,request.chunkingVersion,request.indexVersion]}));await this.events.publish({type:'knowledge.ingestion.completed',requestId:request.requestId,executionId:request.context.executionId,diagnosticId});this.telemetry.ingested(applicable.length,chunks.length);return result;}catch(error){const normalized=normalizeError(error,diagnosticId);this.diagnostics.record(deepFreeze({id:diagnosticId,operation:'ingestion',outcome:'failed',counts:{},versions:[request.indexVersion],errorCode:normalized.code}));this.telemetry.failed(normalized.code);throw normalized;}}
}

export class KnowledgeRetrievalCoordinator {
 public constructor(private readonly providers:RetrievalProviderResolver,private readonly diagnostics:KnowledgeDiagnostics,private readonly events:KnowledgeEvents,private readonly telemetry:KnowledgeTelemetry){}
 public async retrieve(request:KnowledgeRetrievalRequest):Promise<KnowledgeRetrievalResult>{validateRetrieval(request);const diagnosticId=`knowledge:retrieve:${request.requestId}`;try{const query=normalizeQuery(request);const response=await (await this.providers.resolve(request.strategy)).retrieve(query);const scoped=response.candidates.filter(candidate=>candidate.metadata.tenantId===request.context.tenantId&&labelsAllowed(candidate.securityLabels,request.authorization.allowedLabels)&&(!request.context.workspaceId||candidate.metadata.workspaceId===request.context.workspaceId));const deduplicated=deduplicate(scoped);const ranked=[...deduplicated].sort((a,b)=>b.score-a.score||a.chunkId.localeCompare(b.chunkId));const quality=ranked.filter(item=>item.score>=request.minimumScore).slice(0,request.maximumResults);const items=quality.map((item,index)=>deepFreeze({...item,rank:index+1,citation:{sourceReference:item.sourceReference,documentId:item.documentId,chunkId:item.chunkId,version:item.sourceVersion}}));const emptyReason:EmptyReason|undefined=items.length===0?(response.candidates.length===0?'no-matches':scoped.length===0?'security-trimmed':'below-quality'):undefined;const status=response.partialReasons.length>0?'partial':items.length===0?'empty':'complete';const securityScope={...(request.context.tenantId===undefined?{}:{tenantId:request.context.tenantId}),...(request.context.workspaceId===undefined?{}:{workspaceId:request.context.workspaceId}),decisionId:request.authorization.decisionId};const result:KnowledgeRetrievalResult=deepFreeze({requestId:request.requestId,status,querySummary:query.text,items,strategies:[request.strategy],securityScope,...(emptyReason===undefined?{}:{emptyReason}),partialReasons:[...response.partialReasons],diagnosticId,metadata:{...request.metadata}});this.diagnostics.record(deepFreeze({id:diagnosticId,operation:'retrieval',outcome:'completed',counts:{candidates:response.candidates.length,authorized:scoped.length,results:items.length},versions:[...new Set(items.map(item=>item.indexVersion))]}));await this.events.publish({type:`knowledge.retrieval.${status}`,requestId:request.requestId,executionId:request.context.executionId,diagnosticId});this.telemetry.retrieved(response.candidates.length,scoped.length,items.length);return result;}catch(error){const normalized=normalizeError(error,diagnosticId);this.diagnostics.record(deepFreeze({id:diagnosticId,operation:'retrieval',outcome:'failed',counts:{},versions:[],errorCode:normalized.code}));this.telemetry.failed(normalized.code);throw normalized;}}
}

function validateIngestion(value:KnowledgeIngestionRequest):void{if(value.requestId.trim()===''||value.source.id.trim()===''||value.source.tenantId!==value.context.tenantId||value.authorization.decisionId.trim()===''||value.processingVersion.trim()===''||value.indexVersion.trim()==='')throw new NormalizedKnowledgeError('KNOWLEDGE_INVALID_REQUEST','Invalid ingestion request',`knowledge:ingest:${value.requestId}`);}
function validateRetrieval(value:KnowledgeRetrievalRequest):void{if(value.requestId.trim()===''||value.query.trim()===''||value.maximumResults<1||value.minimumScore<0||value.node.capability!==value.binding.capability||value.authorization.decisionId.trim()===''||containsForbidden(value.filters))throw new NormalizedKnowledgeError('KNOWLEDGE_INVALID_REQUEST','Invalid retrieval request',`knowledge:retrieve:${value.requestId}`);}
function normalizeQuery(request:KnowledgeRetrievalRequest):NormalizedKnowledgeQuery{const text=request.query.trim().replace(/\s+/gu,' ').toLowerCase();return deepFreeze({text,terms:Object.freeze([...new Set(text.split(' '))]),sourceIds:[...request.sourceIds],strategy:request.strategy,filters:{...request.filters},...(request.context.tenantId===undefined?{}:{tenantId:request.context.tenantId}),...(request.context.workspaceId===undefined?{}:{workspaceId:request.context.workspaceId})});}
function toIndexRecord(chunk:KnowledgeChunk,indexVersion:string):KnowledgeIndexRecord{return deepFreeze({id:`${chunk.id}:${indexVersion}`,chunkId:chunk.id,content:chunk.content,metadata:{...chunk.metadata},securityLabels:[...chunk.securityLabels],sourceReference:chunk.sourceReference,sourceVersion:chunk.sourceVersion,processingVersion:chunk.processingVersion,chunkingVersion:chunk.chunkingVersion,indexVersion});}
function labelsAllowed(labels:readonly string[],allowed:readonly string[]):boolean{return labels.every(label=>allowed.includes(label));}
function deduplicate(values:readonly KnowledgeCandidate[]):readonly KnowledgeCandidate[]{const map=new Map<string,KnowledgeCandidate>();for(const value of values){const key=`${value.chunkId}:${value.sourceVersion}`;const current=map.get(key);if(current===undefined||value.score>current.score)map.set(key,value);}return [...map.values()];}
function normalizeError(error:unknown,id:string):NormalizedKnowledgeError{if(error instanceof NormalizedKnowledgeError)return error;const kind=error instanceof ExternalKnowledgeError?error.kind:'unknown';const code=({ 'source-unavailable':'KNOWLEDGE_SOURCE_UNAVAILABLE',authentication:'KNOWLEDGE_AUTHENTICATION',authorization:'KNOWLEDGE_AUTHORIZATION','unsupported-content':'KNOWLEDGE_UNSUPPORTED_CONTENT',processing:'KNOWLEDGE_PROCESSING','index-failure':'KNOWLEDGE_INDEX_FAILURE','version-conflict':'KNOWLEDGE_VERSION_CONFLICT','retrieval-failure':'KNOWLEDGE_RETRIEVAL_FAILURE',timeout:'KNOWLEDGE_TIMEOUT',unknown:'KNOWLEDGE_UNKNOWN'} as const)[kind];return new NormalizedKnowledgeError(code,error instanceof Error?error.message:'Knowledge operation failed',id);}
function copyIngestion(value:KnowledgeIngestionRequest):KnowledgeIngestionRequest{return{...value,source:{...value.source,metadata:{...value.source.metadata}},authorization:{...value.authorization,allowedLabels:[...value.authorization.allowedLabels]},metadata:{...value.metadata},semantics:{...value.semantics},...(value.targetRecordIds===undefined?{}:{targetRecordIds:[...value.targetRecordIds]})};}
function containsForbidden(value:unknown):boolean{if(typeof value!=='object'||value===null)return false;return Object.entries(value).some(([key,child])=>/vendor|index.?name|query.?syntax|sdk/iu.test(key)||containsForbidden(child));}
function deepFreeze<T>(value:T):T{if(typeof value==='object'&&value!==null&&!Object.isFrozen(value)){for(const child of Object.values(value))deepFreeze(child);Object.freeze(value);}return value;}
export * from './reference.js';
