/* eslint-disable @typescript-eslint/explicit-function-return-type */
import type { CapabilityBinding } from '@agentforge/capability-resolution';
import type { ExecutionContext } from '@agentforge/foundation';
import { describe,expect,it,vi } from 'vitest';
import { AiAssistedKnowledgeEnricher,ExternalKnowledgeError,FactoryKnowledgeConnectorResolver,FixedSizeChunkingStrategy,InMemoryIngestionCheckpoints,InMemoryKnowledgeConnector,InMemoryKnowledgeDiagnostics,InMemoryKnowledgeEvents,InMemoryKnowledgeIndex,KnowledgeIngestionCoordinator,KnowledgeRetrievalCoordinator,NoopKnowledgeEnricher,PlainTextDocumentNormalizer,StaticRetrievalProviderResolver,type KnowledgeCandidate,type KnowledgeEnricher,type KnowledgeIngestionRequest,type KnowledgeRetrievalRequest,type KnowledgeTelemetry,type RawKnowledgeRecord,type RetrievalStrategyProvider } from './index.js';

const context:ExecutionContext=Object.freeze({executionId:'e',correlationId:'c',tenantId:'tenant',workspaceId:'workspace',startedAt:'x',configurationVersion:'v',securityContextId:'s',attributes:Object.freeze({})});
const source=Object.freeze({id:'source',category:'document',tenantId:'tenant',workspaceId:'workspace',connectorId:'connector',metadata:Object.freeze({})});
const records:readonly RawKnowledgeRecord[]=[{sourceId:'source',recordId:'1',content:'Alpha knowledge text',contentType:'text/plain',metadata:{title:'A'},sourceVersion:'001',sourceTimestamp:'x',securityLabels:['public'],sourceReference:'source://1'},{sourceId:'source',recordId:'2',content:'Beta secret text',contentType:'text/plain',metadata:{title:'B'},sourceVersion:'002',sourceTimestamp:'x',securityLabels:['secret'],sourceReference:'source://2'}];
const ingestion:KnowledgeIngestionRequest=Object.freeze({requestId:'i',source,context,mode:'full',authorization:Object.freeze({authorized:true,decisionId:'d',allowedLabels:Object.freeze(['public','secret'])}),processingVersion:'p1',chunkingVersion:'c1',indexVersion:'idx1',metadata:Object.freeze({}),semantics:Object.freeze({sideEffect:'state-producing',idempotency:'idempotent'})});
const binding:CapabilityBinding=Object.freeze({bindingId:'b',requestId:'r',capability:'knowledge.retrieve',capabilityContractVersion:'1',implementationId:'knowledge',implementationVersion:'1',provider:{id:'p',pluginId:'plugin',contributionId:'knowledge'},source:'default',diagnosticId:'r'});
function setup(enricher:KnowledgeEnricher=new NoopKnowledgeEnricher()){const connector=new InMemoryKnowledgeConnector('connector',records);const connectors=new FactoryKnowledgeConnectorResolver();const connectorFactory=vi.fn(async()=>connector);connectors.bind('connector',connectorFactory);const index=new InMemoryKnowledgeIndex();const checkpoints=new InMemoryIngestionCheckpoints();const diagnostics=new InMemoryKnowledgeDiagnostics();const events=new InMemoryKnowledgeEvents();const telemetry:KnowledgeTelemetry={ingested:vi.fn(),retrieved:vi.fn(),failed:vi.fn()};const ingester=new KnowledgeIngestionCoordinator(connectors,new PlainTextDocumentNormalizer(),new FixedSizeChunkingStrategy(8),enricher,index,checkpoints,diagnostics,events,telemetry);const retrieval=new KnowledgeRetrievalCoordinator(new StaticRetrievalProviderResolver({},index),diagnostics,events,telemetry);return{ingester,retrieval,index,checkpoints,diagnostics,events,telemetry,connectorFactory};}
const retrievalRequest=(overrides:Partial<KnowledgeRetrievalRequest>={}):KnowledgeRetrievalRequest=>({requestId:'q',query:' alpha   knowledge ',binding,node:{workflowId:'w',nodeId:'n',kind:'capability',capability:'knowledge.retrieve'},context,sourceIds:['source'],strategy:'keyword',filters:{},authorization:{authorized:true,decisionId:'d',allowedLabels:['public']},maximumResults:10,minimumScore:0,metadata:{},...overrides});

describe('Knowledge Engine',()=>{
 it('accesses normalized connector records and deterministically ingests preserved metadata into versioned chunks',async()=>{const f=setup();const result=await f.ingester.ingest(ingestion);expect(result).toMatchObject({processedRecords:2,createdDocuments:2,indexVersion:'idx1',processingVersion:'p1'});expect(f.connectorFactory).toHaveBeenCalledOnce();const indexed=f.index.records();expect(indexed[0]).toMatchObject({processingVersion:'p1',chunkingVersion:'c1',indexVersion:'idx1',sourceReference:'source://1',securityLabels:['public']});expect(indexed.map(x=>x.id)).toEqual([...indexed.map(x=>x.id)].sort());expect(f.events.facts.at(-1)?.type).toBe('knowledge.ingestion.completed');});
 it('supports incremental ingestion checkpoints without duplicate processing',async()=>{const f=setup();await f.ingester.ingest(ingestion);const result=await f.ingester.ingest({...ingestion,requestId:'i2',mode:'incremental'});expect(result.processedRecords).toBe(0);expect(result.skippedRecords).toBe(2);expect(f.checkpoints.get('source')).toBe('002');});
 it('routes AI-assisted enrichment through a normalized capability port',async()=>{const ai={enrich:vi.fn(async()=>({topic:'assisted'}))};const f=setup(new AiAssistedKnowledgeEnricher(ai));await f.ingester.ingest(ingestion);expect(ai.enrich).toHaveBeenCalledWith(expect.any(String),'knowledge.enrichment',context);expect(f.index.records()[0]?.metadata.topic).toBe('assisted');});
 it('normalizes queries, security-trims before ranking, deduplicates, and returns immutable citations',async()=>{const f=setup();await f.ingester.ingest(ingestion);const result=await f.retrieval.retrieve(retrievalRequest());expect(result.status).toBe('complete');expect(result.items.every(item=>item.securityLabels.includes('public'))).toBe(true);expect(result.items[0]?.citation.sourceReference).toBe('source://1');expect(result.items.map(x=>x.rank)).toEqual(result.items.map((_x,i)=>i+1));expect(Object.isFrozen(result)).toBe(true);expect(result.querySummary).toBe('alpha knowledge');});
 it('enforces cross-tenant isolation and explicit empty reasons',async()=>{const candidate:KnowledgeCandidate={chunkId:'c',documentId:'d',sourceId:'s',content:'x',sourceReference:'x',metadata:{tenantId:'other',workspaceId:'workspace'},securityLabels:['public'],score:1,strategy:'vector',indexVersion:'1',sourceVersion:'1'};const provider:RetrievalStrategyProvider={retrieve:async()=>({candidates:[candidate],partialReasons:[]}),health:async()=>({name:'p',status:'healthy'})};const f=setup();const coordinator=new KnowledgeRetrievalCoordinator(new StaticRetrievalProviderResolver({vector:provider},provider),f.diagnostics,f.events,f.telemetry);const result=await coordinator.retrieve(retrievalRequest({strategy:'vector'}));expect(result).toMatchObject({status:'empty',emptyReason:'security-trimmed',items:[]});});
 it('represents empty, quality-filtered, and partial retrieval explicitly',async()=>{const emptyProvider:RetrievalStrategyProvider={retrieve:async()=>({candidates:[],partialReasons:['source-unavailable']}),health:async()=>({name:'p',status:'degraded'})};const f=setup();const coordinator=new KnowledgeRetrievalCoordinator(new StaticRetrievalProviderResolver({},emptyProvider),f.diagnostics,f.events,f.telemetry);const partial=await coordinator.retrieve(retrievalRequest());expect(partial).toMatchObject({status:'partial',emptyReason:'no-matches',partialReasons:['source-unavailable']});});
 it('supports every retrieval strategy category through replaceable contracts',async()=>{const provider:RetrievalStrategyProvider={retrieve:vi.fn(async()=>({candidates:[],partialReasons:[]})),health:async()=>({name:'p',status:'healthy'})};for(const strategy of ['keyword','vector','hybrid','metadata','graph','federated','source-specific'] as const){const f=setup();const result=await new KnowledgeRetrievalCoordinator(new StaticRetrievalProviderResolver({[strategy]:provider},provider),f.diagnostics,f.events,f.telemetry).retrieve(retrievalRequest({requestId:strategy,strategy}));expect(result.strategies).toEqual([strategy]);}});
 it('normalizes technology failures and exposes provider-neutral health',async()=>{const provider:RetrievalStrategyProvider={retrieve:async()=>{throw new ExternalKnowledgeError('retrieval-failure','search failed');},health:async()=>({name:'p',status:'unhealthy'})};const f=setup();await expect(new KnowledgeRetrievalCoordinator(new StaticRetrievalProviderResolver({},provider),f.diagnostics,f.events,f.telemetry).retrieve(retrievalRequest())).rejects.toMatchObject({code:'KNOWLEDGE_RETRIEVAL_FAILURE'});expect(await f.index.health()).toEqual({name:'in-memory-knowledge-index',status:'healthy'});expect(JSON.stringify(f.diagnostics.list())).not.toMatch(/secret text|sdk|vectorHit/iu);});
});

