import type { HealthResult } from '@agentforge/foundation';
import type { KnowledgeIndexRecord,ChunkingStrategy,DocumentNormalizer,IngestionCheckpointStore,KnowledgeCandidate,KnowledgeChunk,KnowledgeConnector,KnowledgeConnectorResolver,KnowledgeDiagnostic,KnowledgeDiagnostics,KnowledgeDocument,KnowledgeEnricher,KnowledgeEvents,KnowledgeFact,KnowledgeIndexProvider,KnowledgeIngestionRequest,KnowledgeTelemetry,NormalizedKnowledgeQuery,RawKnowledgeRecord,RetrievalProviderResolver,RetrievalStrategy,RetrievalStrategyProvider } from './index.js';

export class PlainTextDocumentNormalizer implements DocumentNormalizer {public normalize(record:RawKnowledgeRecord,request:KnowledgeIngestionRequest):KnowledgeDocument{return deepFreeze({id:`${record.sourceId}:${record.recordId}`,sourceId:record.sourceId,content:record.content.replace(/\r\n?/gu,'\n').normalize('NFC'),contentType:'text/plain',metadata:{...record.metadata,sourceId:record.sourceId,documentId:`${record.sourceId}:${record.recordId}`,tenantId:request.source.tenantId,...(request.source.workspaceId===undefined?{}:{workspaceId:request.source.workspaceId})},securityLabels:[...record.securityLabels],sourceReference:record.sourceReference,sourceVersion:record.sourceVersion,processingVersion:request.processingVersion});}}
export class FixedSizeChunkingStrategy implements ChunkingStrategy {public readonly id='fixed-size';public constructor(private readonly size:number=100){}public chunk(document:KnowledgeDocument,request:KnowledgeIngestionRequest):readonly KnowledgeChunk[]{if(this.size<1)throw new TypeError('Chunk size must be positive');const chunks:KnowledgeChunk[]=[];for(let offset=0,position=0;offset<document.content.length;offset+=this.size,position++)chunks.push(deepFreeze({id:`${document.id}:chunk:${String(position)}:${request.chunkingVersion}`,documentId:document.id,sourceId:document.sourceId,content:document.content.slice(offset,offset+this.size),position,structuralPath:[],metadata:{...document.metadata},securityLabels:[...document.securityLabels],sourceReference:document.sourceReference,sourceVersion:document.sourceVersion,processingVersion:document.processingVersion,chunkingVersion:request.chunkingVersion}));return Object.freeze(chunks);}}
export class NoopKnowledgeEnricher implements KnowledgeEnricher {public async enrich(chunk:KnowledgeChunk):Promise<KnowledgeChunk>{return chunk;}}
export interface NormalizedKnowledgeAiPort {enrich(content:string,capability:'knowledge.enrichment',context:Parameters<KnowledgeEnricher['enrich']>[1]):Promise<Readonly<Record<string,string>>>;}
export class AiAssistedKnowledgeEnricher implements KnowledgeEnricher {public constructor(private readonly ai:NormalizedKnowledgeAiPort){}public async enrich(chunk:KnowledgeChunk,context:Parameters<KnowledgeEnricher['enrich']>[1]):Promise<KnowledgeChunk>{const metadata=await this.ai.enrich(chunk.content,'knowledge.enrichment',context);return deepFreeze({...chunk,metadata:{...chunk.metadata,...metadata}});}}
export class InMemoryKnowledgeConnector implements KnowledgeConnector {public constructor(public readonly id:string,private readonly records:readonly RawKnowledgeRecord[]){}public async acquire(request:KnowledgeIngestionRequest):Promise<readonly RawKnowledgeRecord[]>{return Object.freeze(this.records.filter(record=>record.sourceId===request.source.id&&(request.targetRecordIds===undefined||request.targetRecordIds.includes(record.recordId))).map(record=>deepFreeze({...record,metadata:{...record.metadata},securityLabels:[...record.securityLabels]})));}public async health():Promise<HealthResult>{return{name:this.id,status:'healthy'};}}
export class FactoryKnowledgeConnectorResolver implements KnowledgeConnectorResolver {readonly #items=new Map<string,()=>Promise<KnowledgeConnector>>();public bind(id:string,factory:()=>Promise<KnowledgeConnector>):void{this.#items.set(id,factory);}public async resolve(id:string):Promise<KnowledgeConnector>{const factory=this.#items.get(id);if(factory===undefined)throw new TypeError(`No connector binding ${id}`);return await factory();}}
export class InMemoryKnowledgeIndex implements KnowledgeIndexProvider,RetrievalStrategyProvider {readonly #items=new Map<string,KnowledgeIndexRecord>();public async write(records:readonly KnowledgeIndexRecord[]):Promise<void>{for(const record of records)this.#items.set(record.id,record);}public async search(query:NormalizedKnowledgeQuery):Promise<readonly KnowledgeCandidate[]>{return this.#search(query);}public async retrieve(query:NormalizedKnowledgeQuery):Promise<Readonly<{candidates:readonly KnowledgeCandidate[];partialReasons:readonly string[]}>>{return{candidates:this.#search(query),partialReasons:Object.freeze([])};}public async health():Promise<HealthResult>{return{name:'in-memory-knowledge-index',status:'healthy'};}public records():readonly KnowledgeIndexRecord[]{return Object.freeze([...this.#items.values()]);}#search(query:NormalizedKnowledgeQuery):readonly KnowledgeCandidate[]{return Object.freeze([...this.#items.values()].filter(record=>query.sourceIds.length===0||query.sourceIds.includes(record.metadata.sourceId??record.chunkId.split(':')[0]??'')).map(record=>{const matches=query.terms.filter(term=>record.content.toLowerCase().includes(term)).length;return deepFreeze({chunkId:record.chunkId,documentId:record.chunkId.split(':chunk:')[0]??record.chunkId,sourceId:record.metadata.sourceId??record.chunkId.split(':')[0]??'',content:record.content,sourceReference:record.sourceReference,metadata:{...record.metadata},securityLabels:[...record.securityLabels],score:query.terms.length===0?0:matches/query.terms.length,strategy:query.strategy,indexVersion:record.indexVersion,sourceVersion:record.sourceVersion});}));}}
export class StaticRetrievalProviderResolver implements RetrievalProviderResolver {public constructor(private readonly providers:Partial<Record<RetrievalStrategy,RetrievalStrategyProvider>>,private readonly fallback:RetrievalStrategyProvider){}public async resolve(strategy:RetrievalStrategy):Promise<RetrievalStrategyProvider>{return this.providers[strategy]??this.fallback;}}
export class InMemoryIngestionCheckpoints implements IngestionCheckpointStore {readonly #items=new Map<string,string>();public get(id:string):string|undefined{return this.#items.get(id);}public set(id:string,value:string):void{this.#items.set(id,value);}}
export class InMemoryKnowledgeDiagnostics implements KnowledgeDiagnostics {readonly items:KnowledgeDiagnostic[]=[];public record(value:KnowledgeDiagnostic):void{this.items.push(value);}public list():readonly KnowledgeDiagnostic[]{return Object.freeze([...this.items]);}}
export class InMemoryKnowledgeEvents implements KnowledgeEvents {readonly facts:KnowledgeFact[]=[];public async publish(value:KnowledgeFact):Promise<void>{this.facts.push(value);}}
export class NoopKnowledgeTelemetry implements KnowledgeTelemetry {public ingested(_records:number,_chunks:number):void{}public retrieved(_candidates:number,_authorized:number,_results:number):void{}public failed(_code:Parameters<KnowledgeTelemetry['failed']>[0]):void{}}
function deepFreeze<T>(value:T):T{if(typeof value==='object'&&value!==null&&!Object.isFrozen(value)){for(const child of Object.values(value))deepFreeze(child);Object.freeze(value);}return value;}



