/* eslint-disable @typescript-eslint/explicit-function-return-type */
import type { ExecutionContext } from '@agentforge/foundation';
import { describe,expect,it,vi } from 'vitest';
import { CapabilityRegistry,CapabilityResolver,DeterministicResolutionPolicy,InMemoryResolutionDiagnostics,InMemoryResolutionEvents,ProviderRegistry,ResolutionError,RuntimeCapabilityResolutionAdapter,StaticResolutionConfiguration,type CapabilityRequest,type ImplementationDescriptor } from '../index.js';

const context:ExecutionContext=Object.freeze({executionId:'e1',correlationId:'c1',startedAt:'x',configurationVersion:'v',securityContextId:'s',tenantId:'t',workspaceId:'w',attributes:Object.freeze({})});
const node=Object.freeze({workflowId:'w1',nodeId:'n1',kind:'capability' as const,capability:'chat'});
const implementation=(id:string,overrides:Partial<ImplementationDescriptor>={}):ImplementationDescriptor=>({id,capabilityId:'chat',providerId:`provider-${id}`,pluginId:`plugin-${id}`,contributionId:id,contractVersions:['1'],implementationVersion:'2.0.0',enabled:true,health:'healthy',priority:0,attributes:Object.freeze({locality:'us'}),...overrides});
function fixture(configuration={} as ConstructorParameters<typeof StaticResolutionConfiguration>[0]){const capabilities=new CapabilityRegistry();capabilities.register({id:'chat',contractVersions:['1'],defaultImplementationId:'default',metadata:{}});const providers=new ProviderRegistry();providers.register(implementation('default'));providers.register(implementation('tenant'));const diagnostics=new InMemoryResolutionDiagnostics();const events=new InMemoryResolutionEvents();const telemetry={resolved:vi.fn(),failed:vi.fn()};return{resolver:new CapabilityResolver(capabilities,providers,new DeterministicResolutionPolicy(),new StaticResolutionConfiguration(configuration),diagnostics,events,telemetry),capabilities,providers,diagnostics,events,telemetry};}
const request:CapabilityRequest=Object.freeze({requestId:'r1',capability:'chat',contractVersion:'1',context,node,constraints:Object.freeze({locality:'us'})});

describe('Capability Resolution',()=>{
 it('resolves exclusively through the resolver into an immutable default binding',async()=>{const f=fixture();const binding=await f.resolver.resolve(request);expect(binding.implementationId).toBe('default');expect(binding.source).toBe('default');expect(Object.isFrozen(binding)).toBe(true);expect(Object.isFrozen(binding.provider)).toBe(true);expect(f.events.facts).toHaveLength(1);expect(f.telemetry.resolved).toHaveBeenCalledOnce();});
 it('uses deterministic tenant, workspace, project, global, default precedence',async()=>{const tenant=fixture({tenant:{chat:'tenant'},workspace:{chat:'default'}});expect((await tenant.resolver.resolve(request)).source).toBe('tenant');const global=fixture({global:{chat:'tenant'}});expect((await global.resolver.resolve(request)).implementationId).toBe('tenant');});
 it('treats registries as deterministic passive stores',()=>{const f=fixture();expect(f.capabilities.list().map(x=>x.id)).toEqual(['chat']);expect(f.providers.forCapability('chat').map(x=>x.id)).toEqual(['default','tenant']);expect(()=>{ f.providers.register(implementation('default')); }).toThrow();});
 it('fails explicitly for an invalid configured choice with structured diagnostics',async()=>{const f=fixture({tenant:{chat:'missing'}});await expect(f.resolver.resolve(request)).rejects.toMatchObject({code:'RESOLUTION_CONFIGURED_IMPLEMENTATION_INVALID'});expect(f.diagnostics.list()[0]).toMatchObject({outcome:'failed',errorCode:'RESOLUTION_CONFIGURED_IMPLEMENTATION_INVALID'});expect(f.events.facts[0]?.type).toBe('capability.failed');});
 it('validates contract compatibility and provider-independent requests',async()=>{const f=fixture();await expect(f.resolver.resolve({...request,contractVersion:'9'})).rejects.toMatchObject({code:'RESOLUTION_INCOMPATIBLE_VERSION'});await expect(f.resolver.resolve({...request,requestId:'r2',constraints:{preferences:{providerId:'x'}}})).rejects.toBeInstanceOf(ResolutionError);});
 it('keeps policy independent and filters execution-scoped constraints',()=>{const policy=new DeterministicResolutionPolicy();const capability={id:'chat',contractVersions:['1'],defaultImplementationId:'default',metadata:{}};expect(()=>policy.select({request:{...request,constraints:{locality:'eu'}},capability,candidates:[implementation('default')],configuration:{}})).toThrowError(ResolutionError);});
 it('lets Runtime consume bindings without activating or executing providers',async()=>{const f=fixture();const adapter=new RuntimeCapabilityResolutionAdapter(f.resolver);const result=await adapter.invoke({eligible:[node]},context,new AbortController().signal);expect(result).toHaveLength(1);expect(result[0]?.implementationId).toBe('default');expect(result[0]).not.toHaveProperty('instance');});
});
