/* eslint-disable @typescript-eslint/explicit-function-return-type, @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-member-access */
import { describe,expect,it,vi } from 'vitest';
import { CompositionRoot } from '@agentforge/composition';
import { InMemoryExecutionSnapshotPort,InMemoryRuntimeEventPublisher,RuntimeError,RuntimeOrchestrator,StaticRuntimePolicyProvider } from '../index.js';

const context={executionId:'e1',correlationId:'c1',configurationVersion:'v1',securityContextId:'s1'};
function fixture(overrides:Record<string,unknown>={}){const root=new CompositionRoot();root.build();const events=new InMemoryRuntimeEventPublisher();const snapshots=new InMemoryExecutionSnapshotPort();const telemetry={transition:vi.fn(),completed:vi.fn(),failed:vi.fn()};const planning={plan:vi.fn(async(input)=>({input}))};const workflow={execute:vi.fn(async plan=>plan)};const capabilities={invoke:vi.fn(async work=>work)};const dependencies={scopes:root,policies:new StaticRuntimePolicyProvider({timeoutMs:100,maxAttempts:2,maxConcurrency:1,isRetryable:()=>false}),planning,workflow,capabilities,security:{authorize:vi.fn(async ctx=>({authorized:ctx.securityContextId==='s1',decisionId:'d1'}))},events,telemetry,snapshots,...overrides};return{runtime:new RuntimeOrchestrator(dependencies),root,events,snapshots,telemetry,planning,workflow,capabilities};}

describe('RuntimeOrchestrator',()=>{
 it('owns the complete delegated lifecycle and disposes its factory-created scope',async()=>{const f=fixture();const result=await f.runtime.execute({context,input:'hello'});expect(result.state).toBe('completed');expect(result.history.map(x=>x.state)).toEqual(['created','initializing','planning','executing','completing','completed']);expect(f.planning.plan).toHaveBeenCalledWith('hello',expect.objectContaining({executionId:'e1'}),expect.any(AbortSignal));expect(f.events.facts().map(x=>x.state)).toEqual(result.history.slice(1).map(x=>x.state));expect(f.snapshots.load('e1')?.at(-1)?.state).toBe('completed');expect(f.telemetry.completed).toHaveBeenCalledOnce();expect(f.runtime.diagnostics()).toEqual({active:0,completed:1,failed:0,cancelled:0});});
 it('coordinates recovery and retry centrally',async()=>{let calls=0;const f=fixture({policies:new StaticRuntimePolicyProvider({timeoutMs:100,maxAttempts:2,maxConcurrency:1,isRetryable:()=>true}),capabilities:{invoke:vi.fn(async value=>{if(++calls===1)throw new Error('transient');return value;})}});const result=await f.runtime.execute({context,input:1});expect(result.attempts).toBe(2);expect(result.history.map(x=>x.state)).toContain('recovering');});
 it('enforces timeout and reports every failure',async()=>{const f=fixture({policies:new StaticRuntimePolicyProvider({timeoutMs:5,maxAttempts:1,maxConcurrency:1,isRetryable:()=>false}),planning:{plan:vi.fn(async()=>await new Promise(resolve=>setTimeout(()=>{ resolve('late'); },30)))}});await expect(f.runtime.execute({context,input:1})).rejects.toMatchObject({code:'RUNTIME_TIMEOUT'});expect(f.events.facts().at(-1)?.state).toBe('failed');expect(f.telemetry.failed).toHaveBeenCalledOnce();});
 it('propagates cancellation and reaches cancelled',async()=>{const controller=new AbortController();const f=fixture({planning:{plan:vi.fn(async(_i,_c,signal:AbortSignal)=>await new Promise((_r,reject)=>{ signal.addEventListener('abort',()=>{ reject(new RuntimeError('RUNTIME_CANCELLED','cancelled')); }); }))}});const pending=f.runtime.execute({context,input:1,signal:controller.signal});controller.abort();await expect(pending).rejects.toMatchObject({code:'RUNTIME_CANCELLED'});expect(f.events.facts().slice(-2).map(x=>x.state)).toEqual(['cancelling','cancelled']);});
 it('rejects unauthorized execution before delegated work',async()=>{const f=fixture();await expect(f.runtime.execute({context:{...context,securityContextId:'bad'},input:1})).rejects.toMatchObject({code:'RUNTIME_UNAUTHORIZED'});expect(f.planning.plan).not.toHaveBeenCalled();});
 it('centralizes concurrency and exposes health',async()=>{let release!:()=>void;const blocked=new Promise<void>(resolve=>{release=resolve;});const f=fixture({planning:{plan:vi.fn(async()=>{await blocked;return 1;})}});const first=f.runtime.execute({context,input:1});await vi.waitFor(()=>{ expect(f.runtime.diagnostics().active).toBe(1); });await expect(f.runtime.execute({context:{...context,executionId:'e2'},input:2})).rejects.toMatchObject({code:'RUNTIME_CONCURRENCY_LIMIT'});release();await first;expect((await f.runtime.health()).status).toBe('healthy');});
});

