/* eslint-disable @typescript-eslint/explicit-function-return-type */
import type { ExecutionState, RuntimeDependencies, RuntimeDiagnostics, RuntimeFact, RuntimePolicy, RuntimeRequest, RuntimeResult, StateTransition } from '../contracts/runtime.js';
import { RuntimeError } from '../errors/runtime-error.js';

const transitions:Readonly<Record<ExecutionState,readonly ExecutionState[]>>={created:['initializing'],initializing:['planning','failed','cancelling'],planning:['executing','recovering','failed','cancelling'],executing:['completing','recovering','failed','cancelling'],waiting:['executing','cancelling','failed'],recovering:['planning','failed','cancelling'],cancelling:['cancelled'],completing:['completed','failed','cancelling'],completed:[],failed:[],cancelled:[]};

export class ExecutionStateManager {
  readonly #history:StateTransition[]=[]; #state:ExecutionState='created';
  public constructor(private readonly now:()=>Date=()=>new Date()){this.#history.push(Object.freeze({state:'created',occurredAt:this.now().toISOString()}));}
  public get state():ExecutionState{return this.#state;}
  public get history():readonly StateTransition[]{return Object.freeze([...this.#history]);}
  public transition(next:ExecutionState):StateTransition {if(!transitions[this.#state].includes(next))throw new RuntimeError('RUNTIME_INVALID_TRANSITION',`${this.#state} -> ${next}`);this.#state=next;const item=Object.freeze({state:next,occurredAt:this.now().toISOString()});this.#history.push(item);return item;}
}

export class ConcurrencyManager {#active=0; public get active():number{return this.#active;} public async run<T>(limit:number,work:()=>Promise<T>):Promise<T>{if(this.#active>=limit)throw new RuntimeError('RUNTIME_CONCURRENCY_LIMIT','Runtime concurrency limit reached');this.#active++;try{return await work();}finally{this.#active--;}}}
export class ExecutionScheduler {public constructor(private readonly concurrency=new ConcurrencyManager()){} public schedule<T>(policy:RuntimePolicy,work:()=>Promise<T>):Promise<T>{return this.concurrency.run(policy.maxConcurrency,work);} public get active():number{return this.concurrency.active;}}
export class TimeoutManager {public async run<T>(milliseconds:number,signal:AbortSignal,work:(signal:AbortSignal)=>Promise<T>):Promise<T>{const controller=new AbortController();const abort=()=>{ controller.abort(); };signal.addEventListener('abort',abort,{once:true});const timer=setTimeout(()=>{ controller.abort(); },milliseconds);try{return await Promise.race([work(controller.signal),new Promise<T>((_,reject)=>{ controller.signal.addEventListener('abort',()=>{ reject(new RuntimeError(signal.aborted?'RUNTIME_CANCELLED':'RUNTIME_TIMEOUT',signal.aborted?'Execution cancelled':'Execution timed out')); },{once:true}); })]);}finally{clearTimeout(timer);signal.removeEventListener('abort',abort);}}}
export class RetryManager {public async run<T>(policy:RuntimePolicy,work:(attempt:number)=>Promise<T>,recover:(error:unknown,attempt:number)=>Promise<void>):Promise<{value:T;attempts:number}>{let last:unknown;for(let attempt=1;attempt<=policy.maxAttempts;attempt++){try{return{value:await work(attempt),attempts:attempt};}catch(error){last=error;if(attempt>=policy.maxAttempts||!policy.isRetryable(error))throw error;await recover(error,attempt);}}throw last;}}

export class RuntimeOrchestrator {
  readonly #scheduler=new ExecutionScheduler(); readonly #timeout=new TimeoutManager(); readonly #retry=new RetryManager(); #completed=0;#failed=0;#cancelled=0;
  public constructor(private readonly dependencies:RuntimeDependencies){}
  public async execute<T=unknown>(request:RuntimeRequest):Promise<RuntimeResult<T>>{const started=Date.now();const scope=this.dependencies.scopes.createExecutionScope(request.context);const state=new ExecutionStateManager(this.dependencies.now);const controller=new AbortController();const forward=()=>{ controller.abort(); };request.signal?.addEventListener('abort',forward,{once:true});const context=scope.context;
    const publish=async(next:ExecutionState):Promise<void>=>{const item=state.transition(next);const fact:RuntimeFact=Object.freeze({type:`runtime.execution.${next}`,executionId:context.executionId,correlationId:context.correlationId,occurredAt:item.occurredAt,state:next});this.dependencies.telemetry.transition(fact);await this.dependencies.events.publish(fact);await this.dependencies.snapshots.store(context.executionId,state.history);};
    try{await publish('initializing');const decision=await this.dependencies.security.authorize(context);if(!decision.authorized)throw new RuntimeError('RUNTIME_UNAUTHORIZED',`Authorization denied: ${decision.decisionId}`);const policy=await this.dependencies.policies.get(context);const result=await this.#scheduler.schedule(policy,()=>this.#retry.run(policy,async()=>this.#timeout.run(policy.timeoutMs,controller.signal,async signal=>{await publish('planning');const plan=await this.dependencies.planning.plan(request.input,context,signal);await publish('executing');const work=await this.dependencies.workflow.execute(plan,context,signal);return await this.dependencies.capabilities.invoke(work,context,signal) as T;}),async()=>{await publish('recovering');}));await publish('completing');await publish('completed');this.#completed++;this.dependencies.telemetry.completed(context.executionId,Date.now()-started,result.attempts);return Object.freeze({executionId:context.executionId,state:'completed',output:result.value,attempts:result.attempts,history:state.history});
    }catch(error){const cancelled=error instanceof RuntimeError&&error.code==='RUNTIME_CANCELLED';try{await publish(cancelled?'cancelling':'failed');if(cancelled)await publish('cancelled');}catch{/* preserve original failure */}if(cancelled)this.#cancelled++;else this.#failed++;const normalized=error instanceof RuntimeError?error:new RuntimeError('RUNTIME_EXECUTION_FAILED','Runtime execution failed',{cause:error});this.dependencies.telemetry.failed(context.executionId,normalized.code,Date.now()-started);throw normalized;}finally{request.signal?.removeEventListener('abort',forward);await scope.dispose();}}
  public diagnostics():RuntimeDiagnostics{return Object.freeze({active:this.#scheduler.active,completed:this.#completed,failed:this.#failed,cancelled:this.#cancelled});}
  public async health(){const d=this.diagnostics();return Object.freeze({name:'runtime',status:d.active>=0?'healthy':'unhealthy',details:Object.freeze({active:String(d.active),completed:String(d.completed),failed:String(d.failed),cancelled:String(d.cancelled)})} as const);}
}
