/* eslint-disable @typescript-eslint/explicit-function-return-type */
import type { ExecutionContext } from '@agentforge/foundation';
import type { KnowledgeRetrievalResult } from '@agentforge/knowledge';
import type { MemoryRetrievalResult } from '@agentforge/memory';
import type { ExecutionPlan } from '@agentforge/planning';
import type { WorkflowSnapshot } from '@agentforge/workflow';
import { describe,expect,it,vi } from 'vitest';
import { ContextAssemblyEngine,DefaultContextPolicyEvaluator,ExternalContextError,InMemoryContextDiagnostics,InMemoryContextEvents,type ContextAssemblyPolicy,type ContextAssemblyRequest,type ContextPolicyEvaluator,type ContextTelemetry } from './index.js';

const context:ExecutionContext={executionId:'execution-1',correlationId:'correlation-1',tenantId:'tenant-1',workspaceId:'workspace-1',startedAt:'2026-08-06T00:00:00.000Z',configurationVersion:'configuration-1',securityContextId:'security-1',attributes:{locale:'en'}};
const plan:ExecutionPlan={planId:'plan-1',objective:'answer',goal:{statement:'answer'},intent:{name:'respond',outcome:'complete'},strategy:'workflow',requiredCapabilities:[{capability:'answer',constraints:{}}],tasks:[{id:'task-1',description:'answer',capability:'answer',dependencies:[],optional:false}],workflow:{id:'workflow-1',source:'generated',taskIds:['task-1']},decisionPoints:[],validation:{valid:true,checkedAt:'2026-08-06T00:00:00.000Z'},optimization:{removedTaskIds:[],originalTaskCount:1,optimizedTaskCount:1},metadata:{plannerVersion:'planner-1',createdAt:'2026-08-06T00:00:00.000Z',executionId:'execution-1',correlationId:'correlation-1'}};
const workflow:WorkflowSnapshot={workflowId:'workflow-1',status:'running',nodeStates:{'task-1':'executing'},branchOutcomes:{},loopIterations:{},history:['created','initialized','running']};
const knowledge:KnowledgeRetrievalResult={requestId:'knowledge-1',status:'complete',querySummary:'answer',items:[{chunkId:'chunk-1',documentId:'document-1',sourceId:'source-1',content:'knowledge',sourceReference:'source://one',metadata:{tenantId:'tenant-1',workspaceId:'workspace-1'},securityLabels:['public'],score:.9,strategy:'hybrid',indexVersion:'index-1',sourceVersion:'source-version-1',rank:1,citation:{sourceReference:'source://one',documentId:'document-1',chunkId:'chunk-1',version:'source-version-1'}}],strategies:['hybrid'],securityScope:{tenantId:'tenant-1',workspaceId:'workspace-1',decisionId:'decision-1'},partialReasons:[],diagnosticId:'knowledge-diagnostic',metadata:{}};
const memory:MemoryRetrievalResult={requestId:'memory-1',status:'complete',memories:[{id:'memory-1',category:'episodic',producer:'runtime',occurredAt:'2026-08-05T00:00:00.000Z',content:{observation:'memory'},metadata:{},securityLabels:['public'],importance:'normal',version:'memory-version-1',score:.8,rank:1,execution:{executionId:'execution-0',correlationId:'correlation-0'}}],strategy:'hybrid',rankingPolicyVersion:'memory-ranking-1',securityScope:{tenantId:'tenant-1',workspaceId:'workspace-1',decisionId:'decision-1'},partialReasons:[],diagnosticId:'memory-diagnostic'};
const priorities={execution:100,plan:90,workflow:80,knowledge:70,memory:60,runtime:50} as const;
const policy:ContextAssemblyPolicy={version:'policy-1',schemaVersion:'context-package-1',minimumPriority:0,maximumLogicalUnits:10,sourceBudgets:{},sourcePriorities:priorities,ordering:'priority'};
const request=(overrides:Partial<ContextAssemblyRequest>={}):ContextAssemblyRequest=>({requestId:'assembly-1',context,node:{workflowId:'workflow-1',nodeId:'task-1',kind:'capability',capability:'answer'},plan,workflow,knowledge,memory,runtime:{state:'running',cancellationRequested:false,resourceClass:'standard',diagnosticsReference:'runtime-diagnostic',version:'runtime-1',attributes:{}},authorization:{authorized:true,decisionId:'decision-1',allowedLabels:['public'],allowedSources:['execution','plan','workflow','knowledge','memory','runtime']},policy,platformVersion:'0.1.0',...overrides});
function fixture(evaluator:ContextPolicyEvaluator=new DefaultContextPolicyEvaluator()){const diagnostics=new InMemoryContextDiagnostics();const events=new InMemoryContextEvents();const completed=vi.fn();const failed=vi.fn();const telemetry:ContextTelemetry={completed,failed};return{engine:new ContextAssemblyEngine(evaluator,diagnostics,events,telemetry),diagnostics,events,completed,failed};}

describe('Context Assembly Engine',()=>{
  it('deterministically assembles only normalized contracts with source traceability',async()=>{const first=await fixture().engine.assemble(request());const second=await fixture().engine.assemble(request());expect(first).toEqual(second);expect(first.elements.map(item=>item.source)).toEqual(['execution','plan','workflow','knowledge','memory','runtime']);expect(first.elements.every(item=>item.sourceReference.length>0&&item.sourceVersion.length>0)).toBe(true);expect(first).not.toHaveProperty('prompt');expect(first).not.toHaveProperty('messages');});
  it('never modifies source information and returns a deeply immutable serializable package',async()=>{const input=request();const before=JSON.stringify(input);const result=await fixture().engine.assemble(input);expect(JSON.stringify(input)).toBe(before);expect(Object.isFrozen(result)).toBe(true);expect(Object.isFrozen(result.elements[0]?.content)).toBe(true);expect(()=>JSON.stringify(result)).not.toThrow();});
  it('evaluates configurable versioned filtering and ordering policies',async()=>{const custom={...policy,version:'policy-2',minimumPriority:60,ordering:'source' as const};const result=await fixture().engine.assemble(request({policy:custom}));expect(result.versions.policy).toBe('policy-2');expect(result.elements.map(item=>item.source)).toEqual(['execution','knowledge','memory','plan','workflow']);expect(result.sources.find(item=>item.source==='runtime')?.omitted).toBe(1);});
  it('enforces total and per-source logical budgets after prioritization',async()=>{const constrained={...policy,maximumLogicalUnits:3,sourceBudgets:{knowledge:0}};const result=await fixture().engine.assemble(request({policy:constrained}));expect(result.budget).toEqual({maximum:3,used:3});expect(result.elements.map(item=>item.source)).toEqual(['execution','plan','workflow']);expect(result.status).toBe('partial');});
  it('preserves supplied security boundaries without making authorization decisions',async()=>{const item=knowledge.items[0];if(item===undefined)throw new Error('Knowledge fixture is missing');const restrictedKnowledge={...knowledge,items:[{...item,securityLabels:['secret']}]};const result=await fixture().engine.assemble(request({knowledge:restrictedKnowledge}));expect(result.elements.some(element=>element.source==='knowledge')).toBe(false);expect(result.security).toEqual({decisionId:'decision-1',labels:['public']});expect(result.status).toBe('partial');});
  it('rejects incompatible normalized source security scopes',async()=>{const mismatched={...memory,securityScope:{...memory.securityScope,tenantId:'another-tenant'}};const f=fixture();await expect(f.engine.assemble(request({memory:mismatched}))).rejects.toMatchObject({code:'CONTEXT_SECURITY_SCOPE'});expect(f.failed).toHaveBeenCalledWith('CONTEXT_SECURITY_SCOPE');expect(f.events.facts.at(-1)?.type).toBe('context.assembly.failed');});
  it('represents empty context as a valid immutable outcome',async()=>{const result=await fixture().engine.assemble(request({policy:{...policy,maximumLogicalUnits:0}}));expect(result).toMatchObject({status:'empty',elements:[],budget:{maximum:0,used:0}});expect(Object.isFrozen(result.elements)).toBe(true);});
  it('preserves upstream partial reasons in a partial package',async()=>{const partialKnowledge={...knowledge,status:'partial' as const,partialReasons:['provider-degraded']};const result=await fixture().engine.assemble(request({knowledge:partialKnowledge}));expect(result.status).toBe('partial');expect(result.omissions).toContain('knowledge:provider-degraded');});
  it('publishes facts and exposes safe diagnostics and telemetry',async()=>{const f=fixture();const result=await f.engine.assemble(request());expect(f.events.facts.map(fact=>fact.type)).toEqual(['context.assembly.started','context.assembly.completed']);expect(f.diagnostics.list()[0]).toMatchObject({outcome:'completed',counts:{supplied:6,filtered:0,included:6},policyVersion:'policy-1'});expect(f.completed).toHaveBeenCalledWith(result.status,6,6);expect(JSON.stringify(f.diagnostics.list())).not.toMatch(/source:\/\/one|observation/iu);});
  it('normalizes replaceable policy failures without leaking technology types',async()=>{const evaluator:ContextPolicyEvaluator={evaluate:()=>{throw new ExternalContextError('policy','policy adapter failed');}};const f=fixture(evaluator);await expect(f.engine.assemble(request())).rejects.toMatchObject({code:'CONTEXT_POLICY_FAILURE',diagnosticId:'context:assembly:assembly-1'});expect(f.diagnostics.list()[0]?.errorCode).toBe('CONTEXT_POLICY_FAILURE');});
});
